// content/estructura.ts
// Fuente de verdad de la ruta de estudio. 4 bloques · 29 módulos.
// Los módulos arrancan en 'en-preparacion'; se pasan a 'completo' SOLO cuando
// tienen teoría + ≥12 tarjetas + ≥25 ítems que pasan el validador. Ver §23.
//
// Nota: §9.1 del blueprint muestra c5-umbrales-zonas ya en 'completo', pero
// §17 paso 8 (viñeta 5) es el que lo cambia. Aquí va en 'en-preparacion'
// porque su contenido no existe todavía. Ver ADR-004.

import type { Bloque, Modulo } from '@/lib/tipos';

export const BLOQUES: Bloque[] = [
  {
    id: 'A',
    numeroCartilla: 1,
    titulo: 'Ciencias Básicas',
    descripcion: 'Biología celular, anatomía, nutrición, sistemas energéticos y estadística aplicada al deporte.',
    pesoExamen: 0.2,
    color: 'a',
    modulos: [
      'a1-celula',
      'a2-terminologia-anatomica',
      'a3-tejidos-organos-sistemas',
      'a4-nutrientes',
      'a5-sistemas-energeticos-biomarcadores',
      'a6-estadistica',
    ],
  },
  {
    id: 'B',
    numeroCartilla: 2,
    titulo: 'Pedagogía y Didáctica',
    descripcion: 'Cómo se enseña el deporte: principios, modelos, estilos y estructura de la sesión.',
    pesoExamen: 0.22,
    color: 'b',
    modulos: [
      'b1-fundamentos-pedagogia',
      'b2-principios',
      'b3-modelos-pedagogicos',
      'b4-componentes-didacticos',
      'b5-estilos-ensenanza',
      'b6-aprendizaje-sesion',
    ],
  },
  {
    id: 'C',
    numeroCartilla: 3,
    titulo: 'Ciencias Aplicadas',
    descripcion: 'Fisiología del ejercicio, sistemas corporales, biomecánica, nutrición deportiva, psicología y dopaje.',
    pesoExamen: 0.33,
    color: 'c',
    modulos: [
      'c1-vias-energeticas',
      'c2-cardiovascular',
      'c3-respiratorio-vo2',
      'c4-nervioso-digestivo-osteomuscular',
      'c5-umbrales-zonas',
      'c6-biomecanica',
      'c7-nutricion-deportiva',
      'c8-psicologia-deporte',
      'c9-dopaje',
    ],
  },
  {
    id: 'D',
    numeroCartilla: 4,
    titulo: 'Entrenamiento Deportivo',
    descripcion: 'Metodología, carga, capacidades físicas y planificación del entrenamiento.',
    pesoExamen: 0.25,
    color: 'd',
    modulos: [
      'd1-conceptualizacion',
      'd2-carga',
      'd3-fuerza',
      'd4-resistencia',
      'd5-velocidad',
      'd6-flexibilidad',
      'd7-modelos-planificacion',
      'd8-estructuras',
    ],
  },
];

export const MODULOS: Modulo[] = [
  /* ══════════ BLOQUE A — Ciencias Básicas ══════════ */
  {
    slug: 'a1-celula',
    bloque: 'A',
    orden: 1,
    titulo: 'Célula: estructura, tipos y división',
    subtitulo: 'Eucariota vs procariota, orgánulos y las etapas de la mitosis.',
    minutosEstimados: 25,
    objetivos: [
      'Distinguir célula procariota de eucariota y saber qué organismos son cada una',
      'Identificar qué orgánulos tiene la célula vegetal y no la animal, y viceversa',
      'Nombrar la función de cada orgánulo',
      'Ordenar las etapas de la mitosis y diferenciarla de la meiosis',
    ],
    conceptosClave: ['Célula procariota', 'Célula eucariota', 'Mitosis', 'Meiosis', 'Orgánulo'],
    prerequisitos: [],
    estadoContenido: 'en-preparacion',
  },
  {
    slug: 'a2-terminologia-anatomica',
    bloque: 'A',
    orden: 2,
    titulo: 'Terminología anatómica y planos',
    subtitulo: 'El idioma con el que se describe el movimiento.',
    minutosEstimados: 25,
    objetivos: [
      'Describir los 3 planos anatómicos y qué divide cada uno',
      'Aplicar los 8 términos de posición sobre un caso concreto',
      'Diferenciar flexión, extensión, rotación, abducción y aducción',
    ],
    conceptosClave: ['Posición anatómica', 'Plano sagital', 'Plano frontal', 'Plano transversal', 'Abducción'],
    prerequisitos: [],
    estadoContenido: 'en-preparacion',
  },
  {
    slug: 'a3-tejidos-organos-sistemas',
    bloque: 'A',
    orden: 3,
    titulo: 'Tejidos, órganos y sistemas',
    subtitulo: 'De los 4 tejidos a los 11 sistemas del cuerpo.',
    minutosEstimados: 40,
    objetivos: [
      'Nombrar los 4 tejidos y su función',
      'Diferenciar osteoblasto, osteocito y osteoclasto',
      'Describir las estructuras de una articulación y su función',
      'Relacionar cada uno de los 11 sistemas con sus órganos',
    ],
    conceptosClave: ['Tejido óseo', 'Osteoblasto', 'Hueso esponjoso', 'Articulación sinovial', 'Hematopoyesis'],
    prerequisitos: ['a1-celula'],
    estadoContenido: 'en-preparacion',
  },
  {
    slug: 'a4-nutrientes',
    bloque: 'A',
    orden: 4,
    titulo: 'Macronutrientes y micronutrientes',
    subtitulo: 'Qué hace cada nutriente y de dónde sale.',
    minutosEstimados: 35,
    objetivos: [
      'Clasificar los carbohidratos en mono, di y polisacáridos con ejemplos',
      'Diferenciar proteína de alto y bajo valor biológico',
      'Distinguir grasas saturadas, monoinsaturadas, poliinsaturadas y trans por su efecto',
      'Relacionar vitaminas y minerales con su función',
    ],
    conceptosClave: ['Monosacárido', 'Valor biológico', 'Grasa trans', 'Micronutriente'],
    prerequisitos: [],
    estadoContenido: 'en-preparacion',
  },
  {
    slug: 'a5-sistemas-energeticos-biomarcadores',
    bloque: 'A',
    orden: 5,
    titulo: 'Sistemas aeróbico y anaeróbico · Biomarcadores',
    subtitulo: 'De dónde sale la energía y cómo se mide el estado del deportista.',
    minutosEstimados: 35,
    objetivos: [
      'Diferenciar el sistema anaeróbico aláctico del láctico por duración, sustrato y subproducto',
      'Comparar el metabolismo aeróbico con el anaeróbico',
      'Clasificar los biomarcadores en rendimiento, salud, estrés oxidativo y hormonales',
      'Reconocer los valores normales de los biomarcadores más preguntados',
    ],
    conceptosClave: ['Sistema aláctico', 'Sistema láctico', 'Biomarcador', 'Relación testosterona/cortisol'],
    prerequisitos: ['a1-celula'],
    estadoContenido: 'en-preparacion',
  },
  {
    slug: 'a6-estadistica',
    bloque: 'A',
    orden: 6,
    titulo: 'Estadística descriptiva y calidad de pruebas',
    subtitulo: 'Media, mediana, desviación y las tres propiedades de un test.',
    minutosEstimados: 45,
    objetivos: [
      'Calcular media, mediana, moda, rango, varianza y desviación estándar',
      'Explicar la ventaja y la desventaja de cada medida de tendencia central',
      'Diferenciar validez, fiabilidad y objetividad con ejemplos de campo',
      'Resolver problemas de regla de tres y porcentaje de aumento',
    ],
    conceptosClave: ['Media aritmética', 'Mediana', 'Desviación estándar', 'Validez', 'Fiabilidad', 'Objetividad'],
    prerequisitos: [],
    estadoContenido: 'en-preparacion',
  },

  /* ══════════ BLOQUE B — Pedagogía y Didáctica ══════════ */
  {
    slug: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    orden: 1,
    titulo: 'Fundamentos de la pedagogía del deporte',
    subtitulo: 'El vocabulario base: deporte, entrenamiento, entrenabilidad, competición.',
    minutosEstimados: 35,
    objetivos: [
      'Definir deporte, pedagogía, entrenamiento, entrenabilidad y competición',
      'Identificar las manifestaciones del deporte (vital, físico, táctico, técnico)',
      'Diferenciar las 3 clases de entrenador y su efecto en el deportista',
      'Nombrar los fundamentos específicos: carga, fatiga, recuperación, adaptación, forma deportiva',
    ],
    conceptosClave: ['Entrenabilidad', 'Forma deportiva', 'Capacidad motriz', 'Adaptación'],
    prerequisitos: [],
    estadoContenido: 'completo',
  },
  {
    slug: 'b2-principios',
    bloque: 'B',
    orden: 2,
    titulo: 'Principios pedagógicos, infanto-juveniles y biológicos',
    subtitulo: 'Los 12 principios biológicos son el corazón del bloque B.',
    minutosEstimados: 40,
    objetivos: [
      'Nombrar los 4 principios pedagógicos y aplicarlos a una sesión',
      'Enumerar los 8 principios para niños y jóvenes',
      'Diferenciar especificidad, especialización, sobrecarga y progresión',
      'Distinguir supercompensación, variabilidad, multilateralidad y retornos en disminución',
    ],
    conceptosClave: ['Multilateralidad', 'Especificidad', 'Sobrecarga', 'Supercompensación', 'Retornos en disminución'],
    prerequisitos: ['b1-fundamentos-pedagogia'],
    estadoContenido: 'completo',
  },
  {
    slug: 'b3-modelos-pedagogicos',
    bloque: 'B',
    orden: 3,
    titulo: 'Modelos pedagógicos del deporte',
    subtitulo: 'Del modelo tradicional al comprensivo, y quién propuso cada uno.',
    minutosEstimados: 35,
    objetivos: [
      'Diferenciar modelos básicos de modelos emergentes',
      'Describir los 6 modelos como estrategia de intervención',
      'Relacionar cada modelo por autor con su propuesta',
    ],
    conceptosClave: ['Modelo comprensivo', 'Modelo constructivista', 'Modelo integrado técnico-táctico'],
    prerequisitos: ['b1-fundamentos-pedagogia'],
    estadoContenido: 'completo',
  },
  {
    slug: 'b4-componentes-didacticos',
    bloque: 'B',
    orden: 4,
    titulo: 'Componentes didácticos y principios de enseñanza',
    subtitulo: 'Las 5 fases del entrenamiento y los elementos de la acción motora.',
    minutosEstimados: 35,
    objetivos: [
      'Diferenciar didáctica, metodología, método y objetivo',
      'Ordenar las 5 fases del entrenamiento',
      'Definir volumen, intensidad, frecuencia, duración y densidad como elementos de la acción motora',
      'Enumerar los 9 principios de enseñanza',
    ],
    conceptosClave: ['Didáctica', 'Método', 'Tarea deportiva', 'Programación'],
    prerequisitos: ['b1-fundamentos-pedagogia'],
    estadoContenido: 'completo',
  },
  {
    slug: 'b5-estilos-ensenanza',
    bloque: 'B',
    orden: 5,
    titulo: 'Estilos de enseñanza',
    subtitulo: 'Las 4 categorías y qué estilo pertenece a cada una.',
    minutosEstimados: 35,
    objetivos: [
      'Clasificar cada estilo en tradicional, participación, implicación cognitiva u organización',
      'Diferenciar asignación de tareas de los estilos de participación',
      'Elegir el estilo adecuado según el nivel y el objetivo de la sesión',
    ],
    conceptosClave: ['Mando directo', 'Microenseñanza', 'Descubrimiento guiado', 'Enseñanza modular'],
    prerequisitos: ['b4-componentes-didacticos'],
    estadoContenido: 'completo',
  },
  {
    slug: 'b6-aprendizaje-sesion',
    bloque: 'B',
    orden: 6,
    titulo: 'Fases del aprendizaje y sesión de entrenamiento',
    subtitulo: 'De la coordinación gruesa a la fina, y cómo cambia la sesión por nivel.',
    minutosEstimados: 35,
    objetivos: [
      'Ordenar las 4 fases del aprendizaje de la técnica',
      'Diferenciar las 3 fases del aprendizaje autorregulado',
      'Explicar qué son las fases sensibles y por qué importan',
      'Describir la estructura de la sesión en formación, perfeccionamiento y altos logros',
    ],
    conceptosClave: ['Coordinación gruesa', 'Coordinación fina', 'Fase sensible', 'Fase asociativa'],
    prerequisitos: ['b4-componentes-didacticos'],
    estadoContenido: 'completo',
  },

  /* ══════════ BLOQUE C — Ciencias Aplicadas ══════════ */
  {
    slug: 'c1-vias-energeticas',
    bloque: 'C',
    orden: 1,
    titulo: 'Vías energéticas y fisiología del ejercicio',
    subtitulo: 'Fosfocreatina, glucólisis y el ATP por molécula de glucosa.',
    minutosEstimados: 45,
    objetivos: [
      'Escribir la reacción de la fosfocreatina y nombrar su enzima',
      'Diferenciar glucólisis anaeróbica de aeróbica por producto y duración',
      'Ubicar dónde ocurre cada etapa de la glucólisis aeróbica',
      'Relacionar %1RM con vía energética, repeticiones y descanso',
    ],
    conceptosClave: ['Fosfocreatina', 'Creatina quinasa', 'Glucólisis', 'Ciclo de Krebs'],
    prerequisitos: ['a5-sistemas-energeticos-biomarcadores'],
    // Volteado en el paso 16 (ADR-004). El validador le exige teoría + ≥12
    // tarjetas + ≥28 ítems (bloque C, ADR-006) + sus conceptos clave en el glosario.
    estadoContenido: 'completo',
  },
  {
    slug: 'c2-cardiovascular',
    bloque: 'C',
    orden: 2,
    titulo: 'Sistema cardiovascular',
    subtitulo: 'Las 5 fórmulas de FCmáx con su autor y su población.',
    minutosEstimados: 40,
    objetivos: [
      'Convertir una toma de pulso a latidos por minuto',
      'Aplicar las 5 fórmulas de FCmáx e identificar la población de cada una',
      'Calcular frecuencia cardíaca de reserva y gasto cardíaco',
      'Diferenciar la adaptación por dilatación de la adaptación por hipertrofia',
    ],
    conceptosClave: ['Frecuencia cardíaca máxima', 'Frecuencia cardíaca de reserva', 'Gasto cardíaco', 'Volumen sistólico'],
    prerequisitos: ['a3-tejidos-organos-sistemas'],
    estadoContenido: 'completo',
  },
  {
    slug: 'c3-respiratorio-vo2',
    bloque: 'C',
    orden: 3,
    titulo: 'Sistema respiratorio y VO₂máx',
    subtitulo: '1 MET = 3,5 ml/kg/min. Ese número cae.',
    minutosEstimados: 40,
    objetivos: [
      'Describir los 3 procesos ventilatorios',
      'Calcular VO₂ a partir del gasto cardíaco y la diferencia arteriovenosa',
      'Convertir entre MET y ml/kg/min',
      'Ubicar un valor de VO₂máx en los baremos por sexo y edad',
    ],
    conceptosClave: ['VO₂máx', 'MET', 'Diferencia arteriovenosa', 'Ventilación'],
    prerequisitos: ['c2-cardiovascular'],
    estadoContenido: 'completo',
  },
  {
    slug: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    orden: 4,
    titulo: 'Sistemas nervioso, digestivo y osteomuscular',
    subtitulo: 'Propiocepción, tipos de contracción y los 7 pasos de la contracción muscular.',
    minutosEstimados: 45,
    objetivos: [
      'Relacionar husos musculares, órganos tendinosos de Golgi y corpúsculos de Pacini con lo que detecta cada uno',
      'Diferenciar contracción isotónica concéntrica, excéntrica e isométrica',
      'Ordenar los 7 pasos de la contracción muscular',
      'Comparar fibras tipo I y tipo II',
    ],
    conceptosClave: ['Propiocepción', 'Huso muscular', 'Contracción excéntrica', 'Fibra tipo II'],
    prerequisitos: ['a3-tejidos-organos-sistemas'],
    estadoContenido: 'completo',
  },
  {
    slug: 'c5-umbrales-zonas',
    bloque: 'C',
    orden: 5,
    titulo: 'Umbrales y zonas de entrenamiento',
    subtitulo: 'R0 a R3+, VT1 y VT2, MLSS y los 4 modelos de distribución de la carga.',
    minutosEstimados: 45,
    objetivos: [
      'Ubicar las zonas R0, R1, R2 y R3 por su porcentaje de FCmáx y de VO₂máx',
      'Explicar el objetivo fisiológico y las adaptaciones de cada zona',
      'Definir MLSS y situarlo respecto a VT1 y VT2',
      'Diferenciar los 4 modelos de distribución de la intensidad',
      'Prescribir la zona correcta a partir de un objetivo de entrenamiento',
    ],
    conceptosClave: [
      'Umbral aeróbico (VT1)',
      'Umbral anaeróbico (VT2)',
      'MLSS',
      'IMTG',
      'VAM',
      'Potencia aeróbica',
      'Entrenamiento polarizado',
      'HIIT',
      'SIT',
    ],
    prerequisitos: ['c1-vias-energeticas', 'c2-cardiovascular', 'c3-respiratorio-vo2'],
    // Volteado en el paso 8, cuando su contenido pasó a existir (ADR-004).
    // Con esto el validador le exige teoría + ≥12 tarjetas + ≥28 ítems (bloque C,
    // ADR-005 hueco 5 y ADR-006) + sus 9 conceptos clave en el glosario.
    estadoContenido: 'completo',
  },
  {
    slug: 'c6-biomecanica',
    bloque: 'C',
    orden: 6,
    titulo: 'Biomecánica',
    subtitulo: 'Palancas, centro de gravedad y eficiencia en la carrera.',
    minutosEstimados: 40,
    objetivos: [
      'Diferenciar cinética de cinemática',
      'Clasificar palancas y aplicarlas al cuerpo humano',
      'Relacionar centro de gravedad y base de sustentación con el equilibrio',
      'Explicar los factores de eficiencia en la carrera',
    ],
    conceptosClave: ['Cinética', 'Cinemática', 'Centro de gravedad', 'Cadena cinemática'],
    prerequisitos: ['a2-terminologia-anatomica'],
    estadoContenido: 'completo',
  },
  {
    slug: 'c7-nutricion-deportiva',
    bloque: 'C',
    orden: 7,
    titulo: 'Nutrición deportiva',
    subtitulo: 'Qué comer, cuánto y sobre todo cuándo.',
    minutosEstimados: 35,
    objetivos: [
      'Determinar el momento de consumo de CHO, grasas y proteínas antes, durante y después',
      'Aplicar la proporción CHO:proteína de recuperación',
      'Decidir la estrategia de hidratación según la duración del esfuerzo',
      'Calcular índices antropométricos básicos',
    ],
    conceptosClave: ['Índice glucémico', 'Ventana de recuperación', 'Bebida isotónica', 'Gasto energético total'],
    prerequisitos: ['a4-nutrientes'],
    estadoContenido: 'completo',
  },
  {
    slug: 'c8-psicologia-deporte',
    bloque: 'C',
    orden: 8,
    titulo: 'Psicología del deporte',
    subtitulo: 'Teorías del aprendizaje y qué aplicar en cada fase de la sesión.',
    minutosEstimados: 35,
    objetivos: [
      'Relacionar cada etapa del ciclo vital con lo que predomina en ella',
      'Asociar cada teoría del aprendizaje con su autor',
      'Elegir la técnica psicológica adecuada según la fase de la sesión',
    ],
    conceptosClave: ['Condicionamiento operante', 'Aprendizaje vicario', 'Refuerzo positivo', 'Activación mental'],
    prerequisitos: [],
    estadoContenido: 'completo',
  },
  {
    slug: 'c9-dopaje',
    bloque: 'C',
    orden: 9,
    titulo: 'Prevención y control del dopaje',
    subtitulo: 'Las 11 infracciones del Artículo 2 del Código Mundial Antidopaje.',
    minutosEstimados: 35,
    objetivos: [
      'Describir las 3 estrategias del programa antidopaje',
      'Identificar las 11 infracciones del Artículo 2',
      'Explicar el principio de responsabilidad estricta',
      'Resumir el Artículo 3: carga de la prueba, muestra B y TAD',
    ],
    conceptosClave: ['Responsabilidad estricta', 'AMA/WADA', 'Localización fallida', 'Asociación prohibida'],
    prerequisitos: [],
    estadoContenido: 'completo',
  },

  /* ══════════ BLOQUE D — Entrenamiento Deportivo ══════════ */
  {
    slug: 'd1-conceptualizacion',
    bloque: 'D',
    orden: 1,
    titulo: 'Conceptualización y metodología del entrenamiento',
    subtitulo: 'Los 5 componentes y los 3 niveles de la Ley 2210.',
    minutosEstimados: 25,
    objetivos: [
      'Definir entrenamiento deportivo y metodología del entrenamiento',
      'Nombrar los 5 componentes del entrenamiento',
      'Ordenar las fases del proceso: planificación, programación, ejecución, control y evaluación',
      'Relacionar los 3 niveles de la Ley 2210 con principiante, intermedio y avanzado',
    ],
    conceptosClave: ['Metodología del entrenamiento', 'Nivel de formación', 'Altos logros', 'Ley 2210 de 2022'],
    prerequisitos: [],
    estadoContenido: 'completo',
  },
  {
    slug: 'd2-carga',
    bloque: 'D',
    orden: 2,
    titulo: 'La carga y sus componentes',
    subtitulo: 'Volumen, intensidad, densidad y la relación inversa que lo explica todo.',
    minutosEstimados: 45,
    objetivos: [
      'Definir carga y sus cinco componentes',
      'Explicar la relación inversa entre volumen e intensidad',
      'Calcular la densidad de una sesión',
      'Diferenciar carga interna de carga externa y aplicar la escala de Borg',
    ],
    conceptosClave: ['Densidad', 'Carga interna', 'Carga externa', 'Escala de Borg (RPE)'],
    prerequisitos: ['d1-conceptualizacion'],
    estadoContenido: 'completo',
  },
  {
    slug: 'd3-fuerza',
    bloque: 'D',
    orden: 3,
    titulo: 'Capacidad física: fuerza',
    subtitulo: 'Clasificación, métodos y tests de fuerza.',
    minutosEstimados: 35,
    objetivos: [
      'Definir fuerza y clasificar sus manifestaciones',
      'Elegir el método de entrenamiento según el objetivo',
      'Aplicar los tests de fuerza más usados',
    ],
    conceptosClave: ['Fuerza máxima', 'Fuerza explosiva', 'Test de 1RM'],
    prerequisitos: ['d2-carga'],
    estadoContenido: 'completo',
  },
  {
    slug: 'd4-resistencia',
    bloque: 'D',
    orden: 4,
    titulo: 'Capacidad física: resistencia',
    subtitulo: 'Métodos continuos, fraccionados, de repeticiones y de competición.',
    minutosEstimados: 35,
    objetivos: [
      'Clasificar la resistencia por duración, metabolismo y masa muscular implicada',
      'Diferenciar los métodos continuos de los fraccionados',
      'Aplicar los tests de Cooper y Course Navette',
    ],
    conceptosClave: ['Resistencia aeróbica', 'Método interválico', 'Test de Cooper', 'Course Navette'],
    prerequisitos: ['d2-carga', 'c5-umbrales-zonas'],
    estadoContenido: 'completo',
  },
  {
    slug: 'd5-velocidad',
    bloque: 'D',
    orden: 5,
    titulo: 'Capacidad física: velocidad',
    subtitulo: 'Reacción, desplazamiento, gestual y resistencia a la velocidad.',
    minutosEstimados: 30,
    objetivos: [
      'Definir velocidad como frecuencia y amplitud por unidad de tiempo',
      'Clasificar los tipos de velocidad',
      'Seleccionar métodos y tests de velocidad',
    ],
    conceptosClave: ['Velocidad de reacción', 'Velocidad gestual', 'Resistencia a la velocidad'],
    prerequisitos: ['d2-carga'],
    estadoContenido: 'completo',
  },
  {
    slug: 'd6-flexibilidad',
    bloque: 'D',
    orden: 6,
    titulo: 'Capacidad física: flexibilidad',
    subtitulo: 'Movilidad, elasticidad y flexibilidad no son lo mismo.',
    minutosEstimados: 30,
    objetivos: [
      'Diferenciar movilidad, elasticidad y flexibilidad',
      'Comparar procedimientos estáticos y dinámicos',
      'Describir la facilitación neuromuscular propioceptiva',
      'Aplicar los tests de sit and reach y goniometría',
    ],
    conceptosClave: ['Movilidad articular', 'Elasticidad muscular', 'FNP', 'Sit and reach'],
    prerequisitos: ['d2-carga'],
    estadoContenido: 'completo',
  },
  {
    slug: 'd7-modelos-planificacion',
    bloque: 'D',
    orden: 7,
    titulo: 'Modelos de planificación',
    subtitulo: 'Tradicional, contemporáneo y cíclico: cuándo usar cada uno.',
    minutosEstimados: 35,
    objetivos: [
      'Describir las 4 características del modelo tradicional',
      'Diferenciar el modelo contemporáneo por flexibilidad, multifuncionalidad e individualización',
      'Elegir el modelo adecuado según el nivel del deportista y el calendario',
    ],
    conceptosClave: ['Modelo tradicional', 'Modelo contemporáneo', 'Pico de rendimiento'],
    prerequisitos: ['d1-conceptualizacion'],
    estadoContenido: 'completo',
  },
  {
    slug: 'd8-estructuras',
    bloque: 'D',
    orden: 8,
    titulo: 'Estructuras de la planificación',
    subtitulo: 'Macro, meso, micro y sesión: qué se define en cada nivel.',
    minutosEstimados: 35,
    objetivos: [
      'Diferenciar macroestructura, mesoestructura, microestructura y estructura de sesión',
      'Indicar la duración típica de cada nivel',
      'Describir las partes de una sesión de entrenamiento',
    ],
    conceptosClave: ['Macrociclo', 'Mesociclo', 'Microciclo', 'Vuelta a la calma'],
    prerequisitos: ['d7-modelos-planificacion'],
    estadoContenido: 'completo',
  },
];

/* ─── Helpers de consulta ─────────────────────────────────────────── */

export const MODULOS_POR_SLUG = new Map(MODULOS.map((m) => [m.slug, m]));
export const BLOQUES_POR_ID = new Map(BLOQUES.map((b) => [b.id, b]));

export function modulosDelBloque(bloqueId: string) {
  return MODULOS.filter((m) => m.bloque === bloqueId).sort((a, b) => a.orden - b.orden);
}

export function moduloSiguiente(slug: string) {
  const i = MODULOS.findIndex((m) => m.slug === slug);
  return i >= 0 && i < MODULOS.length - 1 ? MODULOS[i + 1] : null;
}
