// content/banco/a2-terminologia-anatomica.ts
// Bloque A · Módulo 2 — Terminología anatómica y planos.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   tipos      → 12 única · 3 emparejar · 3 múltiple · 3 caso · 2 ordenar · 2 V/F
//
// Sin ítems de cálculo: el módulo es vocabulario y no tiene magnitudes. El eje
// del banco es la correspondencia plano-movimiento-eje, donde el eje va
// PERPENDICULAR al plano, que es el error que más se cobra.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'A2-001',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿En qué divide el cuerpo el plano sagital?',
    opciones: [
      'En mitad derecha y mitad izquierda',
      'En parte anterior y parte posterior del cuerpo',
      'En parte superior y parte inferior del cuerpo',
      'En parte proximal y parte distal de cada miembro',
    ],
    correcta: 0,
    explicacion:
      'El plano sagital corta el cuerpo de delante a atrás y lo separa en mitad derecha e izquierda; en él ocurren la flexión y la extensión. El distractor más tentador es el segundo, que corresponde al plano frontal, porque los dos son planos verticales y se confunden al memorizarlos de corrido. El tercero es el transversal. Dato para recordar: sagital separa derecha e izquierda, frontal separa delante y detrás.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['plano sagital', 'planos anatómicos', 'definición'],
  },
  {
    id: 'A2-002',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué describe el término «abducción»?',
    opciones: [
      'El movimiento que aleja un segmento de la línea media del cuerpo, como separar los brazos',
      'El movimiento que acerca un segmento a la línea media del cuerpo',
      'El giro de un segmento sobre su propio eje longitudinal hacia dentro',
      'La disminución del ángulo formado entre dos segmentos contiguos',
    ],
    correcta: 0,
    explicacion:
      'La abducción aleja el segmento de la línea media y ocurre en el plano frontal: separar los brazos en cruz es abducción de hombro. El distractor más tentador es el segundo, la aducción, porque las dos palabras se diferencian en una sola letra. El truco que funciona es leer la d: a-d-ucción adiciona, suma, acerca al cuerpo. Dato para recordar: si acerca lleva d, la otra aleja.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['abducción', 'aducción', 'movimientos articulares'],
  },
  {
    id: 'A2-003',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se colocan las manos en la posición anatómica de referencia?',
    opciones: [
      'Brazos extendidos a los lados con las palmas hacia adelante',
      'Brazos extendidos a los lados con las palmas hacia los muslos',
      'Brazos cruzados sobre el pecho con las palmas hacia el cuerpo',
      'Brazos elevados por encima de la cabeza con las palmas enfrentadas',
    ],
    correcta: 0,
    explicacion:
      'En la posición anatómica las palmas miran hacia adelante, y ese detalle no es decorativo: con la palma hacia el muslo el radio y el cúbito quedan cruzados y los términos medial y lateral del antebrazo cambian de sitio. El distractor más tentador es el segundo, precisamente porque es la postura natural de pie. Dato para recordar: la posición anatómica es un convenio, no la postura cómoda.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['posición anatómica', 'referencia', 'terminología'],
  },
  {
    id: 'A2-004',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Relacione cada plano anatómico con lo que separa.',
    izquierda: ['Plano sagital', 'Plano frontal', 'Plano transversal', 'Posición anatómica'],
    derecha: [
      'Mitad derecha y mitad izquierda',
      'Parte anterior y parte posterior',
      'Parte superior y parte inferior',
      'La postura de referencia desde la que se definen los tres planos',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los dos planos verticales son los que se cruzan al memorizar: el sagital separa derecha e izquierda y el frontal separa delante y detrás. El transversal es el único horizontal, y por eso es el más fácil de retener. La posición anatómica aparece en la lista porque sin ella los tres planos no tienen dónde apoyarse: se definen sobre un cuerpo colocado de una forma concreta.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['planos anatómicos', 'posición anatómica', 'clasificación'],
  },
  {
    id: 'A2-005',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Los movimientos que ocurren en el plano sagital giran alrededor de un eje sagital.',
    correcta: false,
    explicacion:
      'Falso, y es el error más caro del módulo. El eje es siempre perpendicular al plano en que ocurre el movimiento: los movimientos del plano sagital giran sobre un eje transversal, los del frontal sobre un eje sagital y los del transversal sobre un eje longitudinal. Una flexión de codo dibuja el plano sagital y gira sobre un eje que atraviesa el codo de lado a lado. Dato para recordar: el eje es el clavo, y el clavo cruza el plano.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['ejes', 'plano sagital', 'planos anatómicos'],
  },
  {
    id: 'A2-006',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué significa que una estructura sea proximal respecto a otra?',
    opciones: [
      'Que está más cerca del punto donde el miembro se une al tronco',
      'Que está más cerca de la línea media que divide el cuerpo en dos mitades',
      'Que está situada por encima de la otra en el eje vertical del cuerpo',
      'Que se encuentra más próxima a la superficie de la piel que la otra',
    ],
    correcta: 0,
    explicacion:
      'Proximal significa más cercano al origen del miembro, es decir a su unión con el tronco: el codo es proximal respecto a la muñeca. El distractor más tentador es el segundo, que define «medial», porque los dos hablan de cercanía y se cruzan con facilidad. El tercero corresponde a superior y el cuarto a superficial. Dato para recordar: proximal y distal solo se usan en los miembros.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['proximal', 'distal', 'términos de posición'],
  },
  {
    id: 'A2-007',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué movimientos ocurren en el plano frontal?',
    opciones: [
      'Abducción, aducción y flexión lateral del tronco',
      'Flexión y extensión de las articulaciones de los miembros',
      'Rotación interna y rotación externa sobre el eje longitudinal',
      'Pronación y supinación del antebrazo sobre su eje mayor',
    ],
    correcta: 0,
    explicacion:
      'El plano frontal aloja los movimientos que separan o acercan el segmento respecto a la línea media, y por eso son suyas la abducción, la aducción y la flexión lateral. El distractor más tentador es el segundo, porque flexión y extensión son los movimientos más habituales y se asignan por defecto a cualquier plano: van en el sagital. Dato para recordar: si el segmento se abre hacia el lado, es plano frontal.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['plano frontal', 'abducción', 'movimientos articulares'],
  },
  {
    id: 'A2-008',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione los TRES pares de términos de posición correctamente formulados.',
    opciones: [
      'Superior y inferior, también llamados craneal y caudal',
      'Anterior y posterior, también llamados ventral y dorsal',
      'Medial y lateral, según la cercanía a la línea media del cuerpo',
      'Proximal y distal, según la cercanía a la superficie de la piel',
      'Sagital y frontal, según la orientación del segmento en el espacio',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Los tres primeros son pares de posición con sus sinónimos correctos. El cuarto mezcla dos pares distintos: proximal y distal se refieren a la distancia al tronco dentro de un miembro, y la cercanía a la piel corresponde a superficial y profundo. El quinto nombra planos y no términos de posición. Dato para recordar: cada par tiene su criterio, y confundir el criterio invierte la respuesta.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['términos de posición', 'medial', 'proximal', 'clasificación'],
  },
  {
    id: 'A2-009',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué es la circunducción?',
    opciones: [
      'La combinación encadenada de flexión, abducción, extensión y aducción',
      'El giro de un segmento sobre su eje longitudinal en ambos sentidos',
      'El movimiento simultáneo de dos articulaciones contiguas en el mismo plano',
      'La flexión máxima de una articulación seguida de su extensión completa',
    ],
    correcta: 0,
    explicacion:
      'La circunducción no es un movimiento simple sino la sucesión encadenada de cuatro, de modo que el extremo del segmento describe un cono: el brazo haciendo círculos es el ejemplo típico. El distractor más tentador es el segundo, porque describir un círculo y girar sobre el propio eje se parecen mucho vistos de lejos; el giro sobre el eje es rotación. Dato para recordar: la circunducción dibuja un cono, la rotación no se mueve del sitio.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['circunducción', 'rotación', 'movimientos articulares'],
  },
  {
    id: 'A2-010',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada plano con el eje sobre el que giran sus movimientos.',
    izquierda: ['Plano sagital', 'Plano frontal', 'Plano transversal', 'Movimiento de rotación'],
    derecha: [
      'Eje transversal o latero-lateral',
      'Eje sagital o anteroposterior',
      'Eje longitudinal o vertical',
      'Gira sobre el eje longitudinal, en el plano transversal',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'La regla que resuelve el emparejamiento completo es que el eje va perpendicular al plano, nunca con su mismo nombre: sagital con transversal, frontal con sagital y transversal con longitudinal. El error más frecuente es emparejar cada plano con el eje homónimo, que es exactamente lo contrario de lo correcto en dos de los tres casos. Dato para recordar: el eje es el clavo alrededor del cual gira el segmento.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['ejes', 'planos anatómicos', 'rotación', 'clasificación'],
  },
  {
    id: 'A2-011',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'En supinación del antebrazo, ¿hacia dónde mira la palma de la mano?',
    opciones: [
      'Hacia arriba',
      'Hacia abajo, con el dorso de la mano visible desde arriba',
      'Hacia la línea media del cuerpo, con el pulgar apuntando al frente',
      'Hacia fuera, con el pulgar orientado hacia la espalda del sujeto',
    ],
    correcta: 0,
    explicacion:
      'En supinación la palma mira hacia arriba y en pronación hacia abajo. El distractor más tentador es el segundo, porque los dos términos se aprenden juntos y se intercambian con facilidad. La regla mnemotécnica que funciona es la sopa: su-pinación es la mano que sostiene el plato de sopa, con la palma hacia arriba para que no se derrame. Dato para recordar: si el plato se cae, era pronación.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['supinación', 'pronación', 'antebrazo'],
  },
  {
    id: 'A2-012',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un deportista eleva el brazo lateralmente hasta la horizontal. ¿Qué movimiento realiza y en qué plano?',
    opciones: [
      'Abducción de hombro, en el plano frontal, porque el brazo se aleja lateralmente de la línea media',
      'Flexión de hombro, en el plano sagital, porque el brazo sube desde la posición anatómica',
      'Rotación externa de hombro, en el plano transversal',
      'Aducción de hombro, en el plano frontal, porque el brazo se separa del tronco',
    ],
    correcta: 0,
    explicacion:
      'Subir el brazo por el lado aleja el segmento de la línea media, y eso es abducción, que ocurre en el plano frontal. El distractor más tentador es el segundo, porque «elevar el brazo» describe también la flexión: la diferencia está en la trayectoria, por delante en la flexión y por el lado en la abducción. El cuarto acierta el plano y se equivoca de término, porque separar es abducción. Dato para recordar: la instrucción «sube el brazo» es ambigua y el plano la desambigua.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['abducción', 'plano frontal', 'hombro'],
  },
  {
    id: 'A2-013',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Una flexión de codo ocurre en el plano sagital. ¿Sobre qué eje gira el antebrazo?',
    opciones: [
      'Sobre un eje transversal, que atraviesa el codo de lado a lado',
      'Sobre un eje sagital, que atraviesa el codo de delante hacia atrás',
      'Sobre un eje longitudinal, que recorre el antebrazo en toda su longitud',
      'Sobre ningún eje, porque la flexión es un desplazamiento y no un giro',
    ],
    correcta: 0,
    explicacion:
      'El eje es perpendicular al plano del movimiento, así que un gesto que se dibuja en el plano sagital gira sobre un eje transversal. El distractor más tentador es el segundo, porque emparejar plano sagital con eje sagital es el reflejo automático y es justamente lo contrario. El tercero describe el eje de las rotaciones y de la pronosupinación. Dato para recordar: si el codo gira, hay un clavo cruzándolo de derecha a izquierda.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['ejes', 'flexión', 'plano sagital'],
  },
  {
    id: 'A2-014',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre los términos proximal y distal.',
    opciones: [
      'Se emplean en los miembros y toman como referencia su unión con el tronco',
      'Son relativos: el codo es proximal a la muñeca y distal al hombro',
      'Equivalen respectivamente a superficial y profundo respecto a la piel',
      'Son absolutos: una estructura es proximal o distal con independencia de la comparación',
      'Se aplican también al tronco, donde el ombligo es distal respecto al esternón',
    ],
    correctas: [0, 1],
    explicacion:
      'Las dos primeras recogen lo esencial: el par se usa en los miembros y siempre exige un segundo término con el que comparar. La tercera confunde con superficial y profundo, la cuarta niega el carácter relativo que la segunda afirma, y la quinta extiende los términos al tronco, donde no se emplean. Dato para recordar: una pregunta que diga «el codo es distal» sin decir respecto a qué está mal formulada.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['proximal', 'distal', 'términos de posición'],
  },
  {
    id: 'A2-015',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'vf',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Al ponerse de puntillas, el tobillo realiza una flexión dorsal.',
    correcta: false,
    explicacion:
      'Falso. Ponerse de puntillas aleja la punta del pie de la tibia, y eso es flexión plantar. La flexión dorsal es el movimiento contrario: sube la punta del pie hacia la tibia, como cuando se camina apoyando el talón. Los nombres despistan porque «dorsal» en el resto del cuerpo significa hacia la espalda, y en el pie se refiere al dorso, que es su cara superior. Dato para recordar: dorso del pie es empeine, y la dorsiflexión lo acerca a la tibia.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['flexión plantar', 'flexión dorsal', 'tobillo'],
  },
  {
    id: 'A2-016',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el radio y el cúbito quedan cruzados si se describe el antebrazo con la palma hacia el muslo?',
    opciones: [
      'Porque esa postura corresponde a una pronación y no a la posición anatómica',
      'Porque el codo se encuentra en flexión parcial y desplaza los dos huesos',
      'Porque el hombro está en rotación externa y arrastra al antebrazo consigo',
      'Porque la muñeca queda en desviación cubital y modifica la alineación',
    ],
    correcta: 0,
    explicacion:
      'Con la palma hacia el muslo el antebrazo está pronado, y en pronación el radio cruza por encima del cúbito: por eso la posición anatómica exige la palma hacia adelante, que corresponde a la supinación y deja los dos huesos paralelos. El distractor más tentador es el tercero, porque el hombro sí influye en la orientación del brazo; lo que cruza los huesos es el giro del antebrazo, no el del hombro. Dato para recordar: la posición anatómica lleva el antebrazo supinado.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['posición anatómica', 'pronación', 'antebrazo'],
  },
  {
    id: 'A2-017',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador anota en la ficha de un jugador: «dolor al elevar el brazo por delante hasta la altura del hombro; sin dolor al separarlo lateralmente». El fisioterapeuta necesita saber exactamente qué movimiento reproduce el síntoma.',
    enunciado: '¿Cómo debe describirse el gesto doloroso?',
    opciones: [
      'Flexión de hombro, en el plano sagital sobre el eje transversal',
      'Abducción de hombro, en el plano frontal sobre el eje sagital',
      'Rotación externa de hombro, en el plano transversal sobre el eje longitudinal',
      'Aducción de hombro, en el plano frontal sobre el eje anteroposterior',
    ],
    correcta: 0,
    explicacion:
      'Elevar el brazo por delante es flexión de hombro, un movimiento del plano sagital que gira sobre un eje transversal. El distractor más tentador es el segundo, porque describe el otro gesto de la ficha, el que no duele: separar lateralmente es abducción. Distinguirlos por escrito es exactamente lo que permite prescribir y derivar sin estar delante. Dato para recordar: por delante es flexión, por el lado es abducción, y no son el mismo ejercicio.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['flexión', 'abducción', 'hombro', 'descripción del gesto'],
  },
  {
    id: 'A2-018',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'emparejar',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Relacione cada gesto con el movimiento articular que lo describe.',
    izquierda: [
      'Llevar la rodilla al pecho desde la bipedestación',
      'Separar las piernas en un salto de tijera',
      'Girar el pie de modo que la planta mire hacia dentro',
      'Volver el hombro a su posición tras haber girado el brazo hacia dentro',
    ],
    derecha: [
      'Flexión de cadera',
      'Abducción de cadera',
      'Inversión del pie',
      'Rotación externa de hombro',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los dos primeros gestos son de cadera y se separan por el plano: la rodilla al pecho es flexión, en el plano sagital, y separar las piernas es abducción, en el frontal. Los dos últimos comprueban vocabulario específico: la inversión mira la planta hacia dentro, y deshacer una rotación interna es una rotación externa. Dato para recordar: el plano del gesto decide el nombre, no la articulación implicada.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['movimientos articulares', 'inversión', 'rotación', 'clasificación'],
  },
  {
    id: 'A2-019',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Al describir un gesto se afirma que ocurre en el plano transversal. ¿Qué tipo de movimiento cabe esperar?',
    opciones: [
      'Una rotación sobre el eje longitudinal del segmento',
      'Una flexión o una extensión sobre el eje transversal del segmento',
      'Una abducción o una aducción sobre el eje anteroposterior',
      'Una flexión lateral del tronco sobre el eje sagital del cuerpo',
    ],
    correcta: 0,
    explicacion:
      'El plano transversal es el horizontal, y los movimientos que se dibujan en él son las rotaciones, que giran sobre el eje longitudinal. Los tres distractores asignan correctamente eje y movimiento entre sí, pero a los otros dos planos: flexión y extensión al sagital, y abducción, aducción y flexión lateral al frontal. Dato para recordar: si el segmento gira sin desplazarse, el plano es transversal.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['plano transversal', 'rotación', 'ejes'],
  },
  {
    id: 'A2-020',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Una entrenadora escribe en el plan: «tres series de elevaciones de brazo». Al llegar a la sesión, la mitad del grupo las hace por delante y la otra mitad por el lado, y las sensaciones que reportan son muy distintas.',
    enunciado: '¿Cómo debió redactarse la tarea para que no hubiera ambigüedad?',
    opciones: [
      'Especificando el movimiento y el plano: elevaciones en abducción, en el plano frontal',
      'Especificando el número de repeticiones y la carga empleada en cada serie',
      'Especificando el eje longitudinal sobre el que debe girar la articulación',
      'Especificando la posición anatómica de partida, sin necesidad de nombrar el plano',
    ],
    correcta: 0,
    explicacion:
      'Nombrar el movimiento y el plano elimina la ambigüedad de golpe: por delante es flexión en el plano sagital y por el lado es abducción en el frontal, y son ejercicios distintos con músculos distintos. El distractor más tentador es el último, porque la posición de partida sí es necesaria; partiendo de la misma posición anatómica se pueden hacer los dos gestos. Dato para recordar: la terminología existe para prescribir sin estar delante.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['abducción', 'flexión', 'prescripción', 'aplicación'],
  },
  {
    id: 'A2-021',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado: 'Ordene las estructuras del miembro superior de proximal a distal.',
    elementos: ['Hombro', 'Brazo', 'Codo', 'Antebrazo', 'Muñeca'],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'El criterio es la distancia al punto donde el miembro se une al tronco, y por eso la secuencia empieza en el hombro y termina en la muñeca. El error habitual es ordenar por tamaño o por importancia funcional en lugar de por posición. Conviene recordar que los términos son relativos: el codo es distal respecto al hombro y proximal respecto a la muñeca, y ambas afirmaciones son ciertas a la vez.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['proximal', 'distal', 'miembro superior', 'secuencia'],
  },
  {
    id: 'A2-022',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un entrenador quiere trabajar la musculatura que estabiliza el tronco frente a giros. Diseña un ejercicio en el que el deportista, con los pies fijos, debe resistir un tirón elástico que intenta hacerle girar el tronco.',
    enunciado: '¿En qué plano se produce la fuerza que el deportista debe resistir?',
    opciones: [
      'En el plano transversal, porque el tirón intenta provocar una rotación del tronco',
      'En el plano sagital, porque el deportista permanece de pie y con los pies fijos',
      'En el plano frontal, porque el elástico tira desde un lateral del cuerpo',
      'En ninguno, porque al resistir sin moverse no se produce movimiento articular',
    ],
    correcta: 0,
    explicacion:
      'Lo que define el plano es la dirección del movimiento que se intenta producir, y aquí el elástico busca una rotación del tronco, que es un movimiento del plano transversal. El distractor más tentador es el tercero, porque el elástico está colocado en un lateral; la posición del anclaje no determina el plano, lo determina el giro que provoca. Dato para recordar: el trabajo antirrotación es trabajo del plano transversal.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['plano transversal', 'rotación', 'core', 'aplicación'],
  },
  {
    id: 'A2-023',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un informe describe una lesión «en la cara medial de la rodilla derecha». ¿Dónde está localizada?',
    opciones: [
      'En la cara interna, la que mira hacia la otra rodilla',
      'En la cara externa, la que mira hacia el exterior de la pierna',
      'En la cara anterior, sobre la rótula y el tendón rotuliano',
      'En la cara posterior, en el hueco poplíteo detrás de la articulación',
    ],
    correcta: 0,
    explicacion:
      'Medial significa más cerca de la línea media del cuerpo, así que la cara medial de la rodilla derecha es la interna, la que mira hacia la izquierda del sujeto. El distractor más tentador es el segundo, porque lateral y medial se cruzan con facilidad al leer deprisa, y en una derivación clínica ese cruce manda al lado equivocado. Dato para recordar: medial es hacia la línea media, sea cual sea el lado del cuerpo.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.1 — Posición anatómica y términos de posición',
    etiquetas: ['medial', 'lateral', 'localización', 'aplicación'],
  },
  {
    id: 'A2-024',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Ordene los movimientos que componen una circunducción completa de hombro, empezando desde la posición anatómica.',
    elementos: [
      'Flexión: el brazo sube por delante del cuerpo',
      'Abducción: el brazo se desplaza hacia el lateral por arriba',
      'Extensión: el brazo desciende por detrás del cuerpo',
      'Aducción: el brazo regresa al costado, junto a la línea media',
    ],
    ordenCorrecto: [0, 1, 2, 3],
    explicacion:
      'La circunducción no es un movimiento simple sino el encadenamiento de cuatro que hace que el extremo del segmento describa un cono. Ordenarlos obliga a comprobar que cada uno pertenece a su plano: flexión y extensión al sagital, abducción y aducción al frontal. El error frecuente es tratarla como una rotación, que gira sobre el eje sin desplazar el segmento del sitio. Dato para recordar: la circunducción dibuja un cono, la rotación no.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.3 — Movimientos articulares',
    etiquetas: ['circunducción', 'hombro', 'movimientos articulares', 'secuencia'],
  },
  {
    id: 'A2-025',
    modulo: 'a2-terminologia-anatomica',
    bloque: 'A',
    tipo: 'multiple',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador quiere cubrir los tres planos en una misma sesión de movilidad. Seleccione las DOS tareas que faltan si ya ha programado flexiones y extensiones de cadera.',
    opciones: [
      'Aperturas laterales de pierna, que trabajan la abducción en el plano frontal',
      'Giros de tronco controlados, que trabajan la rotación en el plano transversal',
      'Elevaciones frontales de brazo, que trabajan la flexión en el plano sagital',
      'Flexiones de codo con carga ligera, que trabajan el plano sagital del miembro superior',
      'Movilizaciones del tobillo en flexión dorsal y plantar, que trabajan el plano sagital',
    ],
    correctas: [0, 1],
    explicacion:
      'Con flexiones y extensiones de cadera el plano sagital ya está cubierto, así que faltan el frontal y el transversal: las aperturas laterales aportan la abducción y los giros de tronco, la rotación. Los tres distractores son tareas válidas que repiten el plano sagital con otra articulación, y ese es justamente el descuido más común al planificar movilidad. Dato para recordar: cambiar de articulación no equivale a cambiar de plano.',
    referencia: 'Cartilla 1, Tema 2, Subtema 2.2 — Planos y ejes',
    etiquetas: ['planos anatómicos', 'movilidad', 'programación', 'aplicación'],
  },
];
