// content/banco/a6-estadistica.ts
// Bloque A · Módulo 6 — Estadística descriptiva y calidad de pruebas.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   tipos      → 10 única · 5 cálculo · 3 emparejar · 3 múltiple · 2 caso · 2 V/F
//
// Es el módulo con más ítems de cálculo de los doce del paso 17, y no es
// forzado: el objetivo del módulo es literalmente calcular media, mediana,
// moda, rango, varianza, desviación estándar y porcentajes.
//
// ADR-014 · el punto verificado: el porcentaje de aumento de 50 a 75 es del
// 50 %, no del 150 %. El nuevo valor ES el 150 % del viejo, que es otra
// pregunta. Y la mediana con n par exige ordenar la lista primero.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'A6-001',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se calcula la media aritmética de un conjunto de datos?',
    opciones: [
      'Sumando todos los valores y dividiendo el total entre el número de datos',
      'Ordenando los datos de menor a mayor y tomando el valor que ocupa la posición central',
      'Identificando el valor que aparece con mayor frecuencia en el conjunto',
      'Restando el valor mínimo del valor máximo del conjunto de datos',
    ],
    correcta: 0,
    explicacion:
      'La media es la suma de todos los valores dividida entre cuántos son, y su virtud es que utiliza toda la información disponible. Los tres distractores definen mediana, moda y rango respectivamente. El más tentador es el segundo, porque media y mediana se confunden por el parecido de sus nombres y por describir las dos el centro del conjunto. Dato para recordar: la media suma todo, la mediana solo mira la posición central.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['media aritmética', 'tendencia central', 'estadística'],
  },
  {
    id: 'A6-002',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué medida de tendencia central es la única aplicable a variables cualitativas?',
    opciones: [
      'La moda',
      'La mediana, porque solo necesita ordenar los valores del conjunto',
      'La media aritmética, siempre que se asigne un número a cada categoría',
      'El rango, porque identifica los dos extremos de la distribución',
    ],
    correcta: 0,
    explicacion:
      'La moda es el valor que más se repite, y eso puede determinarse aunque los datos no sean números: la posición más frecuente de un equipo, el color de camiseta más elegido. El distractor más tentador es el segundo, porque ordenar parece posible con categorías; ordenar exige un criterio de magnitud que las cualitativas no tienen. Y el rango, además, es una medida de dispersión, no de tendencia central.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['moda', 'tendencia central', 'variables cualitativas'],
  },
  {
    id: 'A6-003',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se obtiene la desviación estándar?',
    opciones: [
      'Calculando la raíz cuadrada de la varianza',
      'Elevando la varianza al cuadrado para amplificar las diferencias',
      'Restando la media al valor máximo del conjunto de datos',
      'Dividiendo el rango entre el número total de datos del conjunto',
    ],
    correcta: 0,
    explicacion:
      'La desviación estándar es la raíz cuadrada de la varianza, y esa raíz existe por un motivo práctico: devuelve el resultado a las unidades originales, mientras que la varianza queda en unidades al cuadrado y es difícil de interpretar. El distractor más tentador es el segundo, porque invoca correctamente la relación entre las dos medidas y la aplica al revés. Dato para recordar: la varianza se calcula, la desviación estándar se lee.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['desviación estándar', 'varianza', 'dispersión'],
  },
  {
    id: 'A6-004',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Para calcular la mediana basta con tomar el valor central de la lista tal como fue registrada.',
    correcta: false,
    explicacion:
      'Falso. La mediana es el valor central de la lista ORDENADA, y ordenar es precisamente el paso que más se olvida. La mediana de 12, 30, 15 y 9 no se obtiene mirando el centro de esa secuencia: se ordena a 9, 12, 15, 30 y se promedian las dos posiciones centrales, lo que da 13,5. Dato para recordar: sin ordenar, el número que sale no significa nada.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['mediana', 'tendencia central', 'procedimiento'],
  },
  {
    id: 'A6-005',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'calculo',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'Cinco jugadores registran estos saltos verticales: 38, 42, 45, 40 y 45 cm. Calcule la media.',
    respuesta: 42,
    tolerancia: 0.5,
    unidad: 'cm',
    pasos: [
      'Sumar todos los valores: 38 + 42 + 45 + 40 + 45 = 210',
      'Contar los datos: n = 5',
      'Media = 210 / 5 = 42 cm',
    ],
    explicacion:
      'La media exige sumar todo y dividir entre el número de datos, sin ordenar ni descartar nada. El error más común en un conjunto pequeño es olvidar un valor al sumar, sobre todo cuando hay repetidos como los dos 45. Conviene comprobar el resultado con criterio: 42 cae dentro del rango 38–45, y una media fuera de ese rango indicaría un fallo de cálculo. Dato para recordar: la media siempre queda entre el mínimo y el máximo.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['media aritmética', 'cálculo', 'tendencia central'],
  },
  {
    id: 'A6-006',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Relacione cada medida con lo que calcula.',
    izquierda: ['Media aritmética', 'Mediana', 'Moda', 'Rango'],
    derecha: [
      'Suma de los valores dividida entre el número de datos',
      'Valor central de la lista una vez ordenada',
      'Valor que aparece con mayor frecuencia',
      'Diferencia entre el valor máximo y el mínimo',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Las tres primeras son medidas de tendencia central y la cuarta es de dispersión, distinción que conviene tener presente porque el examen las lista juntas. El par que más se falla es media con mediana, por el parecido del nombre. Y el rango se cuela a veces entre las de tendencia central pese a que no describe el centro sino la amplitud del conjunto.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['tendencia central', 'dispersión', 'clasificación'],
  },
  {
    id: 'A6-007',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es la principal desventaja de la media aritmética?',
    opciones: [
      'Que resulta muy sensible a los valores extremos del conjunto de datos',
      'Que no puede calcularse si el número de datos del conjunto es par',
      'Que exige ordenar previamente todos los valores antes de operar',
      'Que solo utiliza dos de los valores de todo el conjunto analizado',
    ],
    correcta: 0,
    explicacion:
      'La media utiliza todos los datos, y eso mismo la hace vulnerable: un solo valor muy alejado la desplaza. El distractor más tentador es el tercero, porque ordenar es un requisito real de la estadística descriptiva, solo que de la mediana y no de la media. El cuarto describe el defecto del rango, que efectivamente solo mira el máximo y el mínimo. Dato para recordar: la media lo usa todo, y por eso lo sufre todo.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['media aritmética', 'valores extremos', 'tendencia central'],
  },
  {
    id: 'A6-008',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'calculo',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      'Se registran estos tiempos, en segundos: 12,4 · 11,8 · 13,2 · 12,0. Calcule la mediana.',
    respuesta: 12.2,
    tolerancia: 0.05,
    unidad: 's',
    pasos: [
      'Ordenar la lista: 11,8 · 12,0 · 12,4 · 13,2',
      'Como n = 4 es par, se promedian las posiciones N/2 y (N/2)+1, es decir la 2.ª y la 3.ª',
      'Esos valores son 12,0 y 12,4',
      'Mediana = (12,0 + 12,4) / 2 = 12,2 s',
    ],
    explicacion:
      'El paso decisivo es el primero: sin ordenar, las posiciones centrales de la lista original serían 11,8 y 13,2 y darían 12,5, que es incorrecto. El segundo error frecuente es tomar un solo valor central cuando n es par, y con cuatro datos no existe una única posición central. Dato para recordar: ordenar primero, y con n par promediar las dos del medio.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['mediana', 'cálculo', 'tendencia central'],
  },
  {
    id: 'A6-009',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué garantiza la fiabilidad de una prueba?',
    opciones: [
      'Que repetida en las mismas condiciones arroje resultados equivalentes',
      'Que la prueba mida efectivamente el atributo que dice estar midiendo en el deportista',
      'Que el resultado obtenido no dependa de quién realice la evaluación',
      'Que el resultado pueda compararse con baremos de población general',
    ],
    correcta: 0,
    explicacion:
      'La fiabilidad es consistencia: mismas condiciones, resultados equivalentes. Los distractores segundo y tercero definen validez y objetividad, que son las otras dos propiedades del trío y se confunden constantemente. El más tentador es el segundo, porque en el habla corriente «fiable» se usa como sinónimo de «correcto». Dato para recordar: una prueba puede ser fiable y estar midiendo mal.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.4 — Validez, fiabilidad y objetividad',
    etiquetas: ['fiabilidad', 'validez', 'calidad de pruebas'],
  },
  {
    id: 'A6-010',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las TRES medidas de dispersión.',
    opciones: [
      'El rango',
      'La varianza',
      'La desviación estándar',
      'La mediana de la distribución',
      'La moda',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Rango, varianza y desviación estándar describen cuánto se separan los datos entre sí; mediana y moda describen por dónde están, así que son de tendencia central. La distinción importa porque dos grupos pueden tener la misma media y no parecerse en nada: es la dispersión la que los separa. Dato para recordar: la tendencia central dice dónde y la dispersión dice cuánto se abren.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['dispersión', 'varianza', 'clasificación'],
  },
  {
    id: 'A6-011',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Por qué la varianza eleva al cuadrado las diferencias respecto a la media?',
    opciones: [
      'Para que las diferencias negativas no cancelen a las positivas al sumarlas',
      'Para amplificar la influencia de los valores más próximos a la media',
      'Para expresar el resultado en las mismas unidades que los datos originales',
      'Para que el resultado pueda dividirse entre el número de datos del conjunto',
    ],
    correcta: 0,
    explicacion:
      'Sin elevar al cuadrado, la suma de las diferencias respecto a la media sería siempre cero y no informaría de nada, porque las que quedan por encima compensan exactamente a las que quedan por debajo. El distractor más tentador es el tercero, porque dice justo lo contrario de lo que ocurre: el cuadrado saca el resultado de las unidades originales, y es la raíz de la desviación estándar la que lo devuelve. Dato para recordar: se eleva para no perder información y se saca raíz para volver a leerla.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['varianza', 'desviación estándar', 'dispersión'],
  },
  {
    id: 'A6-012',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'calculo',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un jugador pasa de levantar 50 kg a levantar 75 kg en press de banca. ¿Cuál es el porcentaje de aumento?',
    respuesta: 50,
    tolerancia: 1,
    unidad: '%',
    pasos: [
      'Porcentaje de aumento = ((nuevo − viejo) / viejo) × 100',
      'Diferencia = 75 − 50 = 25 kg',
      'Porcentaje = (25 / 50) × 100 = 50 %',
    ],
    explicacion:
      'El aumento es del 50 %, y el fallo típico es responder 150 %: esa cifra es correcta para otra pregunta, porque el valor nuevo ES el 150 % del viejo, pero el aumento es la diferencia respecto al punto de partida. El otro error es dividir entre 75 en lugar de entre 50, lo que daría 33 % y no responde a nada. Dato para recordar: el denominador siempre es el valor de partida, y la palabra aumento pide la diferencia.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.5 — Proporcionalidad y porcentajes',
    etiquetas: ['porcentaje de aumento', 'cálculo', 'proporcionalidad'],
  },
  {
    id: 'A6-013',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'En un grupo de diez corredores, nueve tardan 40 minutos y uno tarda 90. ¿Qué medida describe mejor al grupo y por qué?',
    opciones: [
      'La mediana, porque los valores extremos no la desplazan',
      'La media, porque incorpora toda la información disponible del grupo',
      'La moda, porque coincide con el valor que más veces se repite en el grupo',
      'El rango, porque muestra la distancia entre el mejor y el peor tiempo',
    ],
    correcta: 0,
    explicacion:
      'Un solo valor muy alejado dispara la media y deja de representar a la mayoría, mientras que la mediana se mantiene en 40 minutos y describe lo que le pasa al grupo. El distractor más tentador es el tercero, porque la moda también daría 40 y parece igual de buena: la moda solo cuenta repeticiones y falla en cuanto los tiempos no coinciden exactamente. Dato para recordar: con un dato atípico, la mediana es la medida honesta.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.2 — Tendencia central',
    etiquetas: ['mediana', 'media aritmética', 'valores extremos'],
  },
  {
    id: 'A6-014',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'calculo',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Calcule la desviación estándar poblacional de estos cuatro registros: 4, 6, 8 y 10.',
    respuesta: 2.24,
    tolerancia: 0.05,
    unidad: 'unidades',
    pasos: [
      'Media = (4 + 6 + 8 + 10) / 4 = 7',
      'Diferencias respecto a la media: −3, −1, 1 y 3',
      'Cuadrados de esas diferencias: 9, 1, 1 y 9; suma = 20',
      'Varianza poblacional = 20 / 4 = 5',
      'Desviación estándar = √5 = 2,24',
    ],
    explicacion:
      'El procedimiento tiene cinco pasos y el error más frecuente es quedarse en el cuarto, dando 5 como respuesta: eso es la varianza, que está en unidades al cuadrado. El otro fallo habitual es sumar las diferencias sin elevarlas, lo que daría cero. Y conviene fijarse en que se pide la poblacional, dividida entre n: la muestral se dividiría entre n − 1 y daría 2,58. Dato para recordar: la raíz final es lo que hace legible el resultado.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['desviación estándar', 'varianza', 'cálculo'],
  },
  {
    id: 'A6-015',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'vf',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Una prueba válida puede no ser fiable.',
    correcta: false,
    explicacion:
      'Falso. La relación entre las dos propiedades va en una sola dirección: una prueba puede ser fiable sin ser válida, pero no puede ser válida sin ser fiable. Si el resultado baila cada vez que se repite, la prueba no puede estar midiendo bien nada. El caso contrario sí existe y es el ejemplo clásico: una báscula descalibrada que siempre marca tres kilos de más repite el resultado y no mide el peso real.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.4 — Validez, fiabilidad y objetividad',
    etiquetas: ['validez', 'fiabilidad', 'calidad de pruebas'],
  },
  {
    id: 'A6-016',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'emparejar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Relacione cada situación con la propiedad de la prueba que está fallando.',
    izquierda: [
      'Se mide el salto vertical para estimar la resistencia aeróbica del grupo',
      'El mismo test da 30 cm hoy y 42 cm mañana, sin que nada haya cambiado',
      'Dos evaluadores puntúan de forma distinta la misma ejecución técnica',
      'Los tres problemas anteriores aparecen a la vez en el mismo protocolo',
    ],
    derecha: [
      'Validez',
      'Fiabilidad',
      'Objetividad',
      'Validez, fiabilidad y objetividad al mismo tiempo',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada propiedad falla de una forma reconocible: la validez cuando el instrumento no mide el atributo pretendido, la fiabilidad cuando el resultado no se repite, y la objetividad cuando depende de quién evalúa. La confusión más habitual es entre fiabilidad y objetividad, porque las dos producen resultados inconsistentes: en una varía entre repeticiones y en la otra varía entre evaluadores.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.4 — Validez, fiabilidad y objetividad',
    etiquetas: ['validez', 'fiabilidad', 'objetividad', 'clasificación'],
  },
  {
    id: 'A6-017',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre la varianza.',
    opciones: [
      'Se divide entre n cuando los datos son toda la población que interesa',
      'Se divide entre n − 1 cuando los datos son una muestra de un grupo mayor',
      'Se expresa en las mismas unidades que los datos originales del conjunto',
      'Su valor puede ser negativo si la mayoría de los datos están por debajo de la media',
      'Coincide siempre con la desviación estándar cuando el conjunto tiene pocos datos',
    ],
    correctas: [0, 1],
    explicacion:
      'Las dos primeras recogen la distinción entre varianza poblacional y muestral, que con muestras pequeñas cambia el resultado de forma apreciable. La tercera es falsa porque la varianza queda en unidades al cuadrado, y de ahí que se use la desviación estándar. La cuarta también, porque al elevar al cuadrado ningún término puede ser negativo. Y la quinta solo se cumpliría por casualidad si el valor fuese 1. Dato para recordar: varianza al cuadrado, desviación en unidades reales.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['varianza', 'muestra', 'población', 'dispersión'],
  },
  {
    id: 'A6-018',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador mide la flexibilidad de su grupo con un cajón de sit and reach cuyo tope está desplazado tres centímetros. Repite la medición tres días seguidos y obtiene siempre el mismo valor para cada deportista, con diferencias de milímetros.',
    enunciado: '¿Qué propiedades cumple y cuáles no ese procedimiento?',
    opciones: [
      'Es fiable pero no válido, porque repite el resultado y no mide el valor real',
      'Es válido pero no fiable, porque el instrumento es adecuado y el resultado varía',
      'No es fiable ni válido, porque el desplazamiento del tope invalida ambas propiedades',
      'Es válido y fiable, porque el error afecta por igual a todos los deportistas medidos',
    ],
    correcta: 0,
    explicacion:
      'La consistencia entre repeticiones es fiabilidad, y el procedimiento la tiene: repite el resultado con diferencias de milímetros. Lo que no tiene es validez, porque el tope desplazado hace que todos los valores estén sesgados tres centímetros respecto al real. Es exactamente el caso de la báscula descalibrada. El distractor más tentador es el cuarto, porque un sesgo constante permite comparar entre deportistas y sigue sin medir bien. Dato para recordar: fiable sin válida sí; válida sin fiable, nunca.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.4 — Validez, fiabilidad y objetividad',
    etiquetas: ['fiabilidad', 'validez', 'sit and reach', 'calidad de pruebas'],
  },
  {
    id: 'A6-019',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Dos grupos de corredores tienen exactamente la misma media de 40 minutos, pero el primero tiene una desviación estándar de 1 minuto y el segundo de 12. ¿Qué significa?',
    opciones: [
      'Que el segundo grupo es mucho más heterogéneo, con marcas mucho más dispersas',
      'Que el segundo grupo ha cometido errores de medición en la toma de tiempos',
      'Que el primer grupo tiene un nivel medio superior al del segundo grupo',
      'Que el segundo grupo tiene más corredores que el primero, y por eso se dispersa',
    ],
    correcta: 0,
    explicacion:
      'La desviación estándar describe cuánto se separan los datos entre sí, así que con la misma media un grupo puede ser muy homogéneo y otro muy disperso: eso es exactamente lo que la tendencia central no puede decir. El distractor más tentador es el tercero, porque asocia dispersión con nivel; las dos medias son idénticas, de modo que el nivel medio es el mismo. Dato para recordar: la media dice dónde y la desviación dice cuánto se abren.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['desviación estándar', 'dispersión', 'interpretación'],
  },
  {
    id: 'A6-020',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Si 4 series de un ejercicio ocupan 20 minutos de sesión, ¿cuánto tiempo ocuparán 7 series al mismo ritmo?',
    respuesta: 35,
    tolerancia: 0.5,
    unidad: 'min',
    pasos: [
      'Planteamiento por regla de tres: 4 series equivalen a 20 minutos',
      'Multiplicar en cruz: 7 series × 20 minutos = 140',
      'Dividir por el término que queda: 140 / 4 = 35 minutos',
    ],
    explicacion:
      'La regla de tres se resuelve multiplicando en cruz y dividiendo por el término restante, y el error habitual es invertir la operación, dividiendo 4 entre 7 antes de multiplicar. Conviene además comprobar el resultado con sentido común: 7 series son casi el doble que 4, así que el tiempo tiene que quedar cerca del doble de 20. Dato para recordar: si el resultado no encaja con la proporción esperada, la operación se planteó al revés.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.5 — Proporcionalidad y porcentajes',
    etiquetas: ['regla de tres', 'proporcionalidad', 'cálculo', 'aplicación'],
  },
  {
    id: 'A6-021',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Una nadadora baja su marca de 64 s a 58 s. Calcule el porcentaje de mejora respecto a su marca anterior.',
    respuesta: 9.4,
    tolerancia: 0.3,
    unidad: '%',
    pasos: [
      'Diferencia = 64 − 58 = 6 s',
      'Porcentaje de variación = (diferencia / valor de partida) × 100',
      'Porcentaje = (6 / 64) × 100 = 9,375 %',
      'Redondeado: 9,4 %',
    ],
    explicacion:
      'La fórmula es la misma que la del porcentaje de aumento, con el valor de partida en el denominador; lo único que cambia es que aquí el descenso de la cifra significa mejora, porque se trata de un tiempo. El error habitual es dividir entre 58, el valor nuevo, lo que daría 10,3 %. Dato para recordar: el denominador es siempre el punto de partida, se esté midiendo una subida o una bajada.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.5 — Proporcionalidad y porcentajes',
    etiquetas: ['porcentaje', 'cálculo', 'proporcionalidad', 'aplicación'],
  },
  {
    id: 'A6-022',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un entrenador quiere que su test de velocidad no dependa de quién lo aplique. ¿Qué propiedad busca y cómo se garantiza?',
    opciones: [
      'La objetividad, con procedimientos e instrumentos estandarizados y medición instrumental',
      'La fiabilidad, repitiendo la prueba varias veces con el mismo grupo de deportistas',
      'La validez, comprobando que el test guarda relación con el rendimiento en competición',
      'La representatividad, ampliando el número de deportistas evaluados en cada tanda',
    ],
    correcta: 0,
    explicacion:
      'Que el resultado no dependa del evaluador es la definición de objetividad, y se garantiza estandarizando protocolo, material e instrucciones, y sustituyendo la apreciación visual por medición instrumental siempre que se pueda. El distractor más tentador es el segundo, porque repetir la prueba también reduce el error; repetir mide consistencia, que es fiabilidad, y no elimina el sesgo del evaluador. Dato para recordar: la fiabilidad varía entre repeticiones y la objetividad entre personas.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.4 — Validez, fiabilidad y objetividad',
    etiquetas: ['objetividad', 'estandarización', 'calidad de pruebas', 'aplicación'],
  },
  {
    id: 'A6-023',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un entrenador presenta a la dirección deportiva la mejora de su grupo en sentadilla: la media pasó de 80 a 120 kg. Al escribir el informe duda entre poner que la carga aumentó un 50 % o que aumentó un 150 %.',
    enunciado: '¿Qué cifra corresponde y por qué?',
    opciones: [
      'Un 50 %, porque el aumento se calcula sobre el valor de partida: (120 − 80) / 80',
      'Un 150 %, porque el valor final representa el 150 % del valor inicial del grupo',
      'Un 40 %, porque la diferencia de 40 kg se expresa directamente como porcentaje',
      'Un 33 %, porque la diferencia debe dividirse entre el valor final alcanzado',
    ],
    correcta: 0,
    explicacion:
      'El aumento es del 50 %, y el 150 % responde a otra pregunta: el valor final ES el 150 % del inicial, que no es lo mismo que haber aumentado un 150 %. La palabra que decide es aumento, y su fórmula divide la diferencia entre el valor de partida. Los otros dos distractores recogen los dos errores restantes: confundir la diferencia absoluta con un porcentaje y dividir entre el valor nuevo. Dato para recordar: 50 a 75 sube un 50 %, y 80 a 120 también.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.5 — Proporcionalidad y porcentajes',
    etiquetas: ['porcentaje de aumento', 'proporcionalidad', 'informe', 'aplicación'],
  },
  {
    id: 'A6-024',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'emparejar',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado: 'Relacione cada pregunta del entrenador con la medida que la responde.',
    izquierda: [
      '¿Cuál es el registro típico de mi grupo, sin que un dato raro lo distorsione?',
      '¿Cuánto se parecen entre sí los registros de mis deportistas?',
      '¿Qué distancia hay entre el mejor y el peor registro del grupo?',
      '¿Qué posición de juego eligen más mis jugadores cuando pueden elegir?',
    ],
    derecha: ['Mediana', 'Desviación estándar', 'Rango', 'Moda'],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada pregunta tiene una única medida que la responde bien, y el emparejamiento obliga a elegir por criterio y no por costumbre. El par que más se falla es el segundo con el tercero, porque los dos hablan de diferencias: el rango solo mira los dos extremos y la desviación estándar recoge cuánto se separa cada dato del conjunto. La cuarta pregunta es cualitativa, y ahí solo sirve la moda.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['mediana', 'desviación estándar', 'moda', 'clasificación'],
  },
  {
    id: 'A6-025',
    modulo: 'a6-estadistica',
    bloque: 'A',
    tipo: 'multiple',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador aplica un nuevo test de agilidad a su plantilla completa de doce jugadores. Seleccione las DOS decisiones correctas.',
    opciones: [
      'Calcular la varianza dividiendo entre n, porque los doce son toda la población de interés',
      'Estandarizar el protocolo y el material para que el resultado no dependa del evaluador',
      'Calcular la varianza dividiendo entre n − 1, porque doce datos son una muestra pequeña',
      'Usar la moda como medida principal, porque hay pocos datos y algunos se repetirán',
      'Prescindir de la desviación estándar, porque la media ya resume el rendimiento del grupo',
    ],
    correctas: [0, 1],
    explicacion:
      'Si los doce jugadores son todo el grupo que interesa, se trata de una población y la varianza se divide entre n; estandarizar protocolo y material es lo que garantiza la objetividad. La tercera opción confunde tamaño pequeño con muestra, que son cosas distintas. La cuarta elige una medida inadecuada para datos numéricos, y la quinta descarta la dispersión, que es justo lo que la media no puede decir. Dato para recordar: muestra o población no depende de cuántos son, sino de a quién se quiere representar.',
    referencia: 'Cartilla 1, Tema 5, Subtema 5.3 — Dispersión',
    etiquetas: ['varianza', 'objetividad', 'población', 'aplicación'],
  },
];
