// content/banco/b1-fundamentos-pedagogia.ts
// Bloque B · Módulo 1 — Fundamentos de la pedagogía del deporte.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   tipos      → 13 única · 3 caso · 3 emparejar · 2 ordenar · 2 múltiple · 2 V/F
//
// Sin ítems de cálculo: el módulo es un diccionario y no tiene magnitudes que
// calcular. Forzar uno daría aritmética disfrazada de fisiología, que es lo que
// c8 y c9 ya evitaron en el paso 16.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'B1-001',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué tres condiciones definen al deporte y lo separan de la actividad física?',
    opciones: [
      'Que esté reglado, institucionalizado y tenga carácter competitivo',
      'Que sea voluntario, saludable y produzca un gasto energético apreciable',
      'Que se practique en grupo, con horario fijo y bajo la dirección de un técnico',
      'Que exija esfuerzo físico, entrenamiento previo y un espacio reglamentario',
    ],
    correcta: 0,
    explicacion:
      'Las tres condiciones son reglamento, institución que lo sostiene y competición. El distractor más tentador es el segundo, porque describe con precisión la actividad física orientada a la salud: caminar una hora es actividad física completa y no es deporte, porque no hay regla ni confrontación. Dato para recordar: si falta el reglamento o falta la competición, hay movimiento pero no deporte.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.1 — Deporte y pedagogía',
    etiquetas: ['deporte', 'definición', 'fundamentos'],
  },
  {
    id: 'B1-002',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué expresa la entrenabilidad de un deportista?',
    opciones: [
      'El grado en que responde a un estímulo de entrenamiento',
      'El nivel de rendimiento que ha alcanzado hasta el momento actual',
      'La cantidad de horas semanales que su cuerpo tolera sin lesionarse',
      'La disposición psicológica con la que afronta las sesiones exigentes',
    ],
    correcta: 0,
    explicacion:
      'La entrenabilidad mide capacidad de respuesta, no nivel logrado. El distractor más tentador es el segundo, porque en el lenguaje corriente «está muy entrenable» suena a «está muy entrenado»: son lo contrario. El principiante desentrenado tiene poca capacidad y mucha entrenabilidad; el de élite, mucha capacidad y muy poca. Dato para recordar: entrenabilidad es cuánto te va a mejorar el estímulo, no cuánto vales hoy.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.2 — Entrenamiento y entrenabilidad',
    etiquetas: ['entrenabilidad', 'definición', 'fundamentos'],
  },
  {
    id: 'B1-003',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué caracteriza a la forma deportiva?',
    opciones: [
      'Es un estado temporal de disposición óptima para rendir, que se construye y se pierde',
      'Es el nivel máximo de condición física alcanzado en la carrera deportiva',
      'Es la adaptación permanente que deja un ciclo completo de entrenamiento',
      'Es la ausencia de fatiga acumulada tras un período largo de descanso',
    ],
    correcta: 0,
    explicacion:
      'La forma deportiva es un estado de disposición óptima y, sobre todo, es temporal: se construye, se alcanza y se pierde. El distractor más tentador es el tercero, que la confunde con la adaptación: la adaptación sí es un cambio estable, la forma no. Precisamente porque caduca existe la planificación, que decide cuándo debe aparecer el pico. Dato para recordar: si algo dura todo el año, no es forma deportiva.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.5 — Fundamentos específicos',
    etiquetas: ['forma deportiva', 'fundamentos específicos', 'definición'],
  },
  {
    id: 'B1-004',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'La aparición de fatiga tras una sesión indica que la carga fue mal dosificada y que el plan debe corregirse.',
    correcta: false,
    explicacion:
      'Falso. La fatiga es el descenso transitorio del rendimiento que provoca la carga, y es la prueba de que el estímulo llegó: una sesión que no fatiga en absoluto no ha aplicado carga suficiente para producir adaptación. Lo que sí es un problema es la fatiga que no se recupera antes de la siguiente sesión, que es otra cosa. Dato para recordar: sin fatiga no hay adaptación, pero sin recuperación tampoco.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.5 — Fundamentos específicos',
    etiquetas: ['fatiga', 'carga', 'adaptación'],
  },
  {
    id: 'B1-005',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿De qué sistema del organismo dependen principalmente las capacidades coordinativas?',
    opciones: [
      'Del sistema nervioso',
      'Del sistema muscular y su composición de fibras',
      'De los sistemas energéticos aeróbico y anaeróbico',
      'Del sistema osteoarticular y su rango de movimiento',
    ],
    correcta: 0,
    explicacion:
      'Las coordinativas —equilibrio, ritmo, orientación, reacción, diferenciación, acoplamiento y adaptación— dependen del sistema nervioso, que es lo que las separa de las condicionales. El distractor más tentador es el segundo, porque el movimiento coordinado se ve en el músculo: pero lo que se entrena ahí es la orden, no el motor. Dato para recordar: condicionales al músculo y al metabolismo, coordinativas al sistema nervioso.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['capacidades coordinativas', 'sistema nervioso', 'clasificación'],
  },
  {
    id: 'B1-006',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Relacione cada manifestación del deporte con lo que expresa.',
    izquierda: ['Vital', 'Físico', 'Técnico', 'Táctico'],
    derecha: [
      'El deporte como movimiento y juego, ligado a la salud y al desarrollo de la persona',
      'El deporte como condición: fuerza, resistencia, velocidad y flexibilidad',
      'El gesto: la ejecución eficiente del movimiento propio de cada deporte',
      'La decisión: qué hacer, cuándo y por qué, en función del adversario y del contexto',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es técnico con táctico, porque en la conversación de campo se usan casi como sinónimos. La regla que los separa cabe en dos palabras: la técnica responde a cómo se ejecuta y la táctica a qué se decide ejecutar. La manifestación vital también se confunde con la física: la vital es el movimiento por sí mismo, la física es la condición que lo sostiene. Dato para recordar: cada manifestación da lugar a un contenido de entrenamiento distinto.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['manifestaciones', 'técnica', 'táctica', 'clasificación'],
  },
  {
    id: 'B1-007',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué caracteriza la conducta del entrenador de estilo permisivo?',
    opciones: [
      'Deja hacer y apenas interviene ni corrige durante el trabajo',
      'Decide con el grupo, explica el porqué y admite propuestas de los deportistas',
      'Decide todo por su cuenta y no admite discusión sobre lo programado',
      'Alterna la exigencia y la cercanía según el momento de la temporada',
    ],
    correcta: 0,
    explicacion:
      'El permisivo se define por la ausencia de intervención: deja hacer, no corrige y no fija objetivos. El distractor más tentador es el segundo, porque el democrático también cede decisiones y a veces se confunde con «no dirigir»: la diferencia es que el democrático sí interviene, explica y corrige, solo que contando con el grupo. Dato para recordar: el permisivo no delega, se ausenta, y sin objetivos claros el progreso se detiene.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.4 — Clases de entrenador',
    etiquetas: ['clases de entrenador', 'estilo permisivo', 'dirección'],
  },
  {
    id: 'B1-008',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'ordenar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Ordene los cinco fundamentos específicos del entrenamiento según su secuencia.',
    elementos: [
      'Carga — el estímulo que se aplica, con su volumen, intensidad y densidad',
      'Fatiga — el descenso transitorio del rendimiento que provoca la carga',
      'Recuperación — el proceso de restablecimiento tras el esfuerzo',
      'Adaptación — el cambio estable del organismo ante cargas repetidas',
      'Forma deportiva — el estado de disposición óptima para rendir',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La secuencia es carga, fatiga, recuperación, adaptación y forma deportiva, y no es una lista sino una cadena causal: sin carga no hay estímulo y sin recuperación no hay adaptación. El error más frecuente es colocar la adaptación antes de la recuperación, porque se asume que el cuerpo mejora durante la sesión. Ocurre al revés: la sesión aplica el estímulo y la mejora se produce descansando. Dato para recordar: si se rompe un eslabón, no hay mejora.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.5 — Fundamentos específicos',
    etiquetas: ['fundamentos específicos', 'ciclo', 'adaptación'],
  },
  {
    id: 'B1-009',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Además de ser un fin en sí misma, ¿qué otras dos funciones cumple la competición?',
    opciones: [
      'Es un medio de entrenamiento y una herramienta de control del estado del deportista',
      'Es criterio de selección del equipo y fuente principal de financiación del club',
      'Es instrumento de motivación del grupo y ocasión de descanso activo programado',
      'Es prueba de la técnica adquirida y sustituto válido de la sesión de fuerza',
    ],
    correcta: 0,
    explicacion:
      'La competición aplica una carga que no se reproduce en sesión y a la vez mide el estado real del deportista frente a un adversario: por eso es medio y es control. El distractor más tentador es el tercero, porque competir sí motiva; pero la motivación es un efecto colateral y no una función metodológica, y desde luego no es descanso activo. Dato para recordar: la competición entrena y mide, no solo corona.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.1 — Deporte y pedagogía',
    etiquetas: ['competición', 'control', 'medio de entrenamiento'],
  },
  {
    id: 'B1-010',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione los TRES factores de los que depende la entrenabilidad.',
    opciones: [
      'La edad y el momento madurativo del deportista',
      'El nivel de partida y la experiencia previa de entrenamiento',
      'La carga genética heredada por el deportista',
      'El número de competiciones oficiales disputadas en la temporada anterior',
      'La categoría administrativa en la que el entrenador está acreditado',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Edad y maduración, nivel de partida y genética son los tres factores clásicos, a los que suele añadirse el estado de salud y descanso. Los dos distractores describen datos reales de la ficha del deportista que no predicen su respuesta al estímulo: haber competido mucho no significa responder mejor, y la acreditación del entrenador no es una propiedad del deportista. Dato para recordar: la entrenabilidad es del que entrena, no del que dirige.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.2 — Entrenamiento y entrenabilidad',
    etiquetas: ['entrenabilidad', 'factores', 'individualización'],
  },
  {
    id: 'B1-011',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿En qué fecha fue sancionada la Ley 2210, que regula la idoneidad del entrenador?',
    opciones: [
      'El 23 de mayo de 2022',
      'El 23 de mayo de 2021, un año antes de su entrada en vigor efectiva',
      'El 13 de marzo de 2022, junto con el decreto reglamentario del sector',
      'El 30 de noviembre de 2022, al cierre de la legislatura correspondiente',
    ],
    correcta: 0,
    explicacion:
      'La Ley 2210 se sancionó el 23 de mayo de 2022 y es la norma que exige la evaluación de idoneidad para ejercer como entrenador deportivo en Colombia. Los tres distractores son fechas próximas y verosímiles, y ese es justamente el problema del ítem: sin la fecha memorizada, las cuatro parecen igual de plausibles. Dato para recordar: 23 de mayo de 2022, ninguna otra fecha, y tres niveles de ejercicio.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.1 — Deporte y pedagogía',
    etiquetas: ['Ley 2210', 'marco legal', 'idoneidad'],
  },
  {
    id: 'B1-012',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un texto define un concepto como «la disciplina que estudia los métodos y medios con los que se dirige la preparación deportiva». ¿Qué está definiendo?',
    opciones: [
      'La metodología del entrenamiento',
      'El entrenamiento deportivo entendido como proceso planificado',
      'La pedagogía del deporte en su vertiente aplicada al alto rendimiento',
      'La didáctica, entendida como la organización concreta de la enseñanza',
    ],
    correcta: 0,
    explicacion:
      'La palabra que decide es «estudia»: lo que estudia métodos y medios es la metodología, no el proceso que ocurre en la cancha. El distractor más tentador es el segundo, porque los dos términos aparecen siempre juntos y se usan como sinónimos en el habla diaria. La regla es simple: si la definición habla de estudiar el cómo, es metodología; si habla de aplicar cargas, es entrenamiento. Dato para recordar: una es la disciplina, el otro es el proceso.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.2 — Entrenamiento y entrenabilidad',
    etiquetas: ['metodología', 'entrenamiento', 'definición'],
  },
  {
    id: 'B1-013',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un jugador ejecuta el pase con una mecánica impecable, pero elige casi siempre al compañero peor situado. ¿Qué manifestación del deporte tiene comprometida?',
    opciones: [
      'La táctica, porque el problema está en la decisión que toma y no en la ejecución del gesto',
      'La técnica, porque el resultado del pase acaba siendo defectuoso en el juego',
      'La física, porque la elección apresurada delata una falta de condición aeróbica',
      'La vital, porque el jugador no ha interiorizado el sentido del juego colectivo',
    ],
    correcta: 0,
    explicacion:
      'La técnica responde a cómo se ejecuta y la táctica a qué se decide: si la mecánica es impecable, el gesto está resuelto y lo que falla es la elección. El distractor más tentador es el segundo, porque el resultado en el campo es malo y se atribuye al pase; pero un mal resultado con buena ejecución señala decisión, no gesto. Dato para recordar: antes de mandar a un jugador a repetir técnica, comprueba si lo que falla es lo que decide.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['táctica', 'técnica', 'manifestaciones'],
  },
  {
    id: 'B1-014',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Relacione cada término del vocabulario base con lo que designa.',
    izquierda: ['Deporte', 'Pedagogía', 'Entrenamiento', 'Metodología del entrenamiento'],
    derecha: [
      'Actividad física reglada, institucionalizada y de carácter competitivo',
      'Ciencia que estudia la educación; aplicada al deporte, cómo se enseña',
      'Proceso planificado que aplica cargas para provocar adaptaciones',
      'Disciplina que estudia los métodos y medios con que se dirige la preparación',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es entrenamiento con metodología, porque los dos términos aparecen siempre juntos: uno es el proceso que ocurre en la cancha y el otro la disciplina que lo estudia. La palabra que decide es «estudia». Pedagogía y metodología también se cruzan: la pedagogía es la ciencia de la educación en general, y la metodología del entrenamiento se ocupa solo de los métodos y medios de la preparación deportiva. Dato para recordar: si la definición habla de estudiar, no está definiendo el proceso.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.2 — Entrenamiento y entrenabilidad',
    etiquetas: ['vocabulario', 'metodología', 'pedagogía', 'clasificación'],
  },
  {
    id: 'B1-015',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el trabajo de las capacidades coordinativas se concentra en la infancia y no en la adolescencia?',
    opciones: [
      'Porque dependen del sistema nervioso, que madura antes que la estructura muscular',
      'Porque el niño dispone de más tiempo libre y de menos exigencia competitiva',
      'Porque hasta la pubertad el músculo no tolera cargas de fuerza ni de resistencia',
      'Porque las coordinativas se pierden por completo si no se trabajan cada temporada',
    ],
    correcta: 0,
    explicacion:
      'La razón es madurativa: el sistema nervioso, del que dependen las coordinativas, alcanza su desarrollo antes que la estructura muscular y metabólica de la que dependen las condicionales. El distractor más tentador es el tercero, porque contiene una idea a medias cierta —el niño tolera menos carga— que no explica por qué precisamente lo coordinativo funciona tan bien a esa edad. Dato para recordar: lo que se coordina entre los 7 y los 12 años se conserva casi toda la vida.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['capacidades coordinativas', 'fases sensibles', 'infancia'],
  },
  {
    id: 'B1-016',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'vf',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Con una planificación bien construida, un deportista puede sostener su forma deportiva a lo largo de toda la temporada.',
    correcta: false,
    explicacion:
      'Falso. La forma deportiva es por definición un estado temporal: se construye, se alcanza y se pierde, y ninguna planificación la vuelve permanente. Lo que la planificación decide es cuándo debe aparecer el pico y cuántas veces al año puede repetirse, que es un problema distinto. Confundirla con la adaptación —esa sí estable— es el error de fondo. Dato para recordar: si alguien promete forma óptima nueve meses seguidos, no ha entendido el ciclo.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.5 — Fundamentos específicos',
    etiquetas: ['forma deportiva', 'planificación', 'adaptación'],
  },
  {
    id: 'B1-017',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Un adulto sedentario mejora su marca de 5 km con casi cualquier plan de carrera, mientras que un fondista formado apenas progresa con el mismo trabajo. ¿Qué lo explica?',
    opciones: [
      'La diferencia de entrenabilidad entre los dos, que es inversa a su nivel',
      'La diferencia de motivación, que en el principiante es más alta al empezar',
      'La diferencia de edad biológica, que condiciona la respuesta cardiovascular',
      'La diferencia de volumen semanal, que en el fondista ya resulta excesivo',
    ],
    correcta: 0,
    explicacion:
      'La entrenabilidad es alta cuando el margen de mejora es grande y baja cuando el deportista ya está cerca de su techo: el sedentario responde a cualquier estímulo porque casi todo es nuevo para él, y el fondista necesita cargas muy específicas para mover su marca. El distractor más tentador es la motivación, que sí influye en la adherencia pero no explica una diferencia de respuesta fisiológica. Dato para recordar: a más nivel, menos entrenabilidad y más especificidad hace falta.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.2 — Entrenamiento y entrenabilidad',
    etiquetas: ['entrenabilidad', 'nivel', 'especificidad'],
  },
  {
    id: 'B1-018',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre las capacidades condicionales.',
    opciones: [
      'Son la fuerza, la resistencia, la velocidad y la flexibilidad',
      'Dependen de los sistemas energéticos y de la estructura muscular del deportista',
      'Incluyen el equilibrio y la orientación espacial entre sus manifestaciones',
      'Se desarrollan de forma preferente antes de la pubertad, como las coordinativas',
      'La flexibilidad es la que más margen de mejora conserva en la edad adulta',
    ],
    correctas: [0, 1],
    explicacion:
      'Las condicionales son las cuatro clásicas y dependen del metabolismo y del músculo, que es lo que las separa de las coordinativas. La tercera opción cuela una coordinativa en la lista; la cuarta invierte el calendario madurativo, porque las condicionales rinden más desde la pubertad; y la quinta es falsa en el sentido contrario, ya que la flexibilidad es la única capacidad que empieza a involucionar en la infancia. Dato para recordar: cuatro condicionales, y el equilibrio no es una de ellas.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['capacidades condicionales', 'clasificación', 'flexibilidad'],
  },
  {
    id: 'B1-019',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador de categoría juvenil deja que el grupo elija cada día qué trabajar, no corrige la ejecución de los ejercicios y no ha fijado objetivos para el semestre. El ambiente es excelente y la asistencia es alta, pero al cabo de cuatro meses ningún jugador ha mejorado sus registros y varios repiten los mismos errores técnicos de septiembre.',
    enunciado: '¿Qué describe mejor lo que está ocurriendo?',
    opciones: [
      'Es un estilo permisivo: sin intervención ni objetivos, el buen clima no produce progreso',
      'Es un estilo democrático bien aplicado, y el problema está en la falta de talento del grupo',
      'Es un estilo autocrático encubierto, porque el entrenador impone la ausencia de correcciones',
      'Es un problema de entrenabilidad del grupo, que a esa edad responde poco a cualquier estímulo',
    ],
    correcta: 0,
    explicacion:
      'La ausencia de corrección, de objetivos y de dirección define el estilo permisivo, y el caso muestra su efecto característico: clima cómodo y progreso detenido. El distractor más tentador es el segundo, porque el democrático también cede decisiones al grupo; la diferencia es que el democrático interviene, explica y corrige. Y la entrenabilidad en categoría juvenil es alta, no baja. Dato para recordar: delegar no es ausentarse.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.4 — Clases de entrenador',
    etiquetas: ['estilo permisivo', 'clases de entrenador', 'dirección'],
  },
  {
    id: 'B1-020',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Durante una sesión de lanzamientos, un deportista se coloca en la zona de caída de los implementos mientras el resto sigue lanzando. El entrenador venía trabajando con un estilo participativo, consultando cada progresión con el grupo antes de aplicarla.',
    enunciado: '¿Cómo debe intervenir el entrenador en ese momento?',
    opciones: [
      'De forma autocrática e inmediata: detener el trabajo y reubicar al deportista sin discusión',
      'De forma democrática: detener el trabajo y abrir con el grupo cómo reorganizar la zona',
      'De forma permisiva: dejar que el propio grupo advierta el riesgo y se autorregule solo',
      'Sin intervenir en la sesión: anotar lo ocurrido y tratarlo en la reunión técnica semanal',
    ],
    correcta: 0,
    explicacion:
      'Ninguna clase de entrenador es correcta siempre, y el riesgo inmediato es justo el contexto donde el estilo autocrático es el adecuado: hay que sacar al deportista de la zona de caída antes de conversar nada. El distractor más tentador es el segundo, porque premia la coherencia con el estilo previo; pero coherencia no es rigidez, y deliberar mientras vuelan implementos es un error de criterio. Dato para recordar: el estilo se elige por la situación, no por costumbre.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.4 — Clases de entrenador',
    etiquetas: ['clases de entrenador', 'seguridad', 'toma de decisiones'],
  },
  {
    id: 'B1-021',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador quiere que sus jugadores de 9 años lleguen a la pubertad con buena base de equilibrio, ritmo y orientación. ¿Qué contenido debe priorizar en esta etapa?',
    opciones: [
      'Tareas variadas de coordinación en contextos cambiantes, con el juego como vehículo',
      'Circuitos de fuerza con cargas ligeras y control estricto de la ejecución técnica',
      'Trabajo continuo de resistencia aeróbica para construir la base del rendimiento',
      'Repetición sistemática del gesto técnico de su deporte hasta automatizarlo',
    ],
    correcta: 0,
    explicacion:
      'Equilibrio, ritmo y orientación son capacidades coordinativas y dependen del sistema nervioso, que madura antes: a los 9 años el estímulo rentable es la variedad de tareas motrices en contextos cambiantes, y el juego es su vehículo natural. El distractor más tentador es el último, porque suena a trabajo técnico serio; pero repetir un solo gesto empobrece precisamente la variabilidad que la coordinación necesita. Dato para recordar: a esa edad, variedad antes que especialización.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['capacidades coordinativas', 'infancia', 'prescripción'],
  },
  {
    id: 'B1-022',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Una deportista entrena seis días por semana con cargas altas y sin días de descanso programados. Las tres primeras semanas mejoró; desde entonces sus marcas bajan, llega a cada sesión con las piernas cargadas y duerme mal. El entrenador propone subir el volumen otro 10 % porque «se ha estancado».',
    enunciado: '¿Qué eslabón del ciclo de los fundamentos específicos está roto?',
    opciones: [
      'La recuperación, y sin ella la carga no llega a convertirse en adaptación',
      'La carga, que resulta insuficiente para seguir provocando un estímulo nuevo',
      'La forma deportiva, que ya alcanzó su pico y ahora entra en su declive natural',
      'La entrenabilidad, que en una deportista formada limita cualquier progreso adicional',
    ],
    correcta: 0,
    explicacion:
      'El cuadro descrito —caída del rendimiento, fatiga persistente y sueño alterado con cargas altas y sin descanso— señala que falta recuperación, que es donde ocurre la adaptación. El distractor más tentador es el segundo, porque es exactamente lo que propone el entrenador del caso: subir el volumen añade estímulo a un organismo que no ha asimilado el anterior y agrava el problema. Dato para recordar: si falta recuperación, más carga no es más adaptación.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.5 — Fundamentos específicos',
    etiquetas: ['recuperación', 'fatiga', 'sobrecarga', 'fundamentos específicos'],
  },
  {
    id: 'B1-023',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Dos deportistas siguen el mismo plan durante doce semanas y uno mejora el doble que el otro. ¿Cuál es la lectura correcta de esa diferencia?',
    opciones: [
      'Que su entrenabilidad es distinta, y por eso el plan debe individualizarse',
      'Que el plan está mal construido, porque uno bien hecho iguala las respuestas',
      'Que el segundo deportista no completó el trabajo prescrito en las sesiones',
      'Que la diferencia es de forma deportiva, y se corregirá sola en el siguiente ciclo',
    ],
    correcta: 0,
    explicacion:
      'La entrenabilidad depende de edad, nivel de partida, genética y estado de salud, y esos factores no los iguala ningún plan: dos personas con el mismo estímulo responden distinto, y esa es la base del principio de individualización. El distractor más tentador es el segundo, porque suena exigente con el entrenador; pero un plan bien hecho no iguala respuestas, las anticipa. Dato para recordar: la respuesta desigual es lo esperado, no la señal de un fallo.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.2 — Entrenamiento y entrenabilidad',
    etiquetas: ['entrenabilidad', 'individualización', 'planificación'],
  },
  {
    id: 'B1-024',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Ordene lo que ocurre en un microciclo bien construido, desde la sesión exigente hasta la competición.',
    elementos: [
      'El deportista completa una sesión de alta exigencia con cargas próximas a su máximo',
      'Aparece un descenso transitorio del rendimiento y sensación de piernas cargadas',
      'Se programan descanso, sueño suficiente y una sesión regenerativa de baja intensidad',
      'El organismo restablece y refuerza las estructuras solicitadas por encima del punto inicial',
      'El deportista llega a la competición con su disposición óptima para rendir',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La secuencia reproduce el ciclo carga, fatiga, recuperación, adaptación y forma deportiva sobre un caso concreto. El error habitual es colocar la sesión regenerativa después de la adaptación, como premio por haber mejorado, cuando es precisamente lo que permite que la mejora ocurra. Y la competición va al final porque exige la disposición óptima, no porque cierre el calendario. Dato para recordar: el descanso no viene después de la mejora, la produce.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.5 — Fundamentos específicos',
    etiquetas: ['microciclo', 'recuperación', 'adaptación', 'aplicación'],
  },
  {
    id: 'B1-025',
    modulo: 'b1-fundamentos-pedagogia',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado: 'Relacione cada situación de campo con la capacidad coordinativa que exige.',
    izquierda: [
      'Salir del taco al oír el disparo, lo antes posible',
      'Mantener la posición sobre una sola pierna al recibir un contacto',
      'Ajustar la carrera al ritmo de los apoyos en una serie de vallas',
      'Saber dónde está la portería sin mirarla, tras un giro completo',
    ],
    derecha: [
      'Capacidad de reacción',
      'Capacidad de equilibrio',
      'Capacidad de ritmo',
      'Capacidad de orientación espacial',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Las cuatro son capacidades coordinativas y todas dependen del sistema nervioso, que es lo que las agrupa. El par que más se falla es el de ritmo con el de reacción, porque los dos tienen que ver con el tiempo: la reacción mide la latencia hasta iniciar el movimiento y el ritmo, la organización temporal de una secuencia ya en marcha. Dato para recordar: reacción es cuándo empiezas, ritmo es cómo distribuyes lo que ya empezaste.',
    referencia: 'Cartilla 2, Tema 1, Subtema 1.3 — Manifestaciones del deporte',
    etiquetas: ['capacidades coordinativas', 'reacción', 'ritmo', 'aplicación'],
  },
];
