// content/banco/b3-modelos-pedagogicos.ts
// Bloque B · Módulo 3 — Modelos pedagógicos del deporte.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   tipos      → 12 única · 4 emparejar · 3 caso · 2 múltiple · 2 ordenar · 2 V/F
//
// Sin ítems de cálculo: el módulo es nominal y no tiene magnitudes. Se apoya en
// emparejar, que es lo que mejor rinde cuando lo que se pregunta es qué propone
// cada modelo y quién lo firma.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'B3-001',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿En qué orden enseña el modelo técnico o tradicional?',
    opciones: [
      'De la técnica a la táctica: primero el gesto aislado y después el juego',
      'De la táctica a la técnica: primero el problema y después el gesto que lo resuelve',
      'Simultáneamente, con cada tarea integrando un objetivo técnico y uno táctico',
      'Sin orden fijo, según lo que el grupo demande al comienzo de cada sesión',
    ],
    correcta: 0,
    explicacion:
      'El modelo tradicional va de la técnica a la táctica: se domina el gesto en un ejercicio analítico y descontextualizado y solo después se lleva al juego. El distractor más tentador es el segundo, que describe exactamente el orden contrario, el de los modelos emergentes: son las dos respuestas a la misma pregunta y por eso aparecen juntas. Dato para recordar: si empieza por el gesto aislado, es tradicional.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.1 — Modelos básicos y emergentes',
    etiquetas: ['modelo tradicional', 'modelo técnico', 'clasificación'],
  },
  {
    id: 'B3-002',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Quiénes son los autores de referencia del modelo comprensivo (TGfU)?',
    opciones: [
      'Bunker y Thorpe',
      'Siedentop, en el marco de su propuesta de educación deportiva',
      'Hellison, desde el modelo de responsabilidad personal y social',
      'Mosston, autor del espectro de estilos de enseñanza',
    ],
    correcta: 0,
    explicacion:
      'El modelo comprensivo, Teaching Games for Understanding, se atribuye a Bunker y Thorpe. Los tres distractores son autores reales del mismo campo, que es lo que hace el ítem exigente: Siedentop firma la educación deportiva, Hellison el modelo de responsabilidad personal y social, y Mosston el espectro de estilos de enseñanza del módulo B5. Dato para recordar: comprensivo y TGfU son el mismo modelo con dos nombres.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.3 — Modelos por autor',
    etiquetas: ['modelo comprensivo', 'TGfU', 'Bunker y Thorpe', 'autores'],
  },
  {
    id: 'B3-003',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué es un juego modificado?',
    opciones: [
      'Una versión simplificada del deporte que conserva su lógica táctica',
      'Un juego popular adaptado como calentamiento previo a la parte principal',
      'Una competición reducida en la que se puntúa la ejecución técnica del gesto',
      'Un ejercicio analítico al que se añade una regla para hacerlo más ameno',
    ],
    correcta: 0,
    explicacion:
      'El juego modificado es la herramienta del modelo comprensivo: simplifica la exigencia técnica cambiando espacio, número de jugadores, móvil o reglas, y mantiene intacto el problema táctico del deporte. El distractor más tentador es el cuarto, porque también parte de un ejercicio y añade reglas; la diferencia es que allí sigue sin haber problema táctico que resolver. Dato para recordar: se simplifica la ejecución, nunca la decisión.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['juego modificado', 'modelo comprensivo', 'definición'],
  },
  {
    id: 'B3-004',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Relacione cada categoría táctica de juego con sus deportes.',
    izquierda: ['Invasión', 'Cancha dividida', 'Bate y campo', 'Blanco o diana'],
    derecha: [
      'Fútbol, baloncesto y balonmano',
      'Voleibol, tenis y bádminton',
      'Béisbol, sóftbol y críquet',
      'Golf, bolos y tiro con arco',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Las cuatro categorías agrupan los deportes por el problema táctico que plantean, no por el material ni por el número de jugadores. El error más frecuente es meter el voleibol entre los de invasión porque es un deporte colectivo de equipo; lo decisivo es que los dos equipos nunca comparten el espacio de juego, y eso lo sitúa en cancha dividida. Dato para recordar: la transferencia táctica ocurre dentro de la categoría, no entre categorías.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['categorías de juego', 'invasión', 'transferencia', 'clasificación'],
  },
  {
    id: 'B3-005',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'El modelo ludotécnico se diseñó para enseñar la táctica de los deportes colectivos de invasión.',
    correcta: false,
    explicacion:
      'Falso. El ludotécnico está pensado para deportes individuales como el atletismo o la natación, donde no hay oposición ni problema táctico que comprender, y usa el juego como medio para aprender el gesto técnico. El modelo que se ocupa de la táctica en deportes de invasión es el comprensivo. Dato para recordar: los dos usan el juego, uno para la técnica y otro para la táctica.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo ludotécnico', 'modelo comprensivo', 'deportes individuales'],
  },
  {
    id: 'B3-006',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué papel tiene el error en el modelo constructivista?',
    opciones: [
      'Es información: indica qué hipótesis del deportista no funcionó',
      'Es un fallo de ejecución que el entrenador debe corregir de inmediato',
      'Es un indicador de que la tarea excede el nivel del grupo y hay que bajarla',
      'Es irrelevante mientras el resultado final de la jugada sea el buscado',
    ],
    correcta: 0,
    explicacion:
      'En el constructivista el conocimiento se construye probando, así que el error deja de ser un fallo y pasa a ser información sobre qué hipótesis no funcionó. El distractor más tentador es el segundo, porque describe la reacción instintiva de cualquier entrenador; corregir de inmediato impide justamente el aprendizaje que estaba a punto de producirse. Dato para recordar: primero se deja probar, después se pregunta, y solo entonces se corrige.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo constructivista', 'error', 'aprendizaje'],
  },
  {
    id: 'B3-007',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada modelo pedagógico con el núcleo de su propuesta.',
    izquierda: ['Comprensivo', 'Constructivista', 'Integrado técnico-táctico', 'Ludotécnico'],
    derecha: [
      'Del juego a la técnica, mediante juegos modificados que conservan la lógica táctica',
      'El aprendiz construye su conocimiento resolviendo los problemas que se le plantean',
      'Técnica y táctica trabajadas juntas, siempre dentro de situaciones de juego',
      'El juego como medio para aprender la técnica en deportes individuales',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es comprensivo con integrado, porque los dos llevan la técnica al juego: el comprensivo empieza por el problema táctico y deja que la técnica aparezca cuando haga falta, mientras que el integrado programa desde el inicio un objetivo táctico y un contenido técnico en cada tarea. Dato para recordar: en el comprensivo la técnica emerge, en el integrado está prevista.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelos pedagógicos', 'clasificación', 'intervención'],
  },
  {
    id: 'B3-008',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione los TRES rasgos propios del modelo de educación deportiva.',
    opciones: [
      'La afiliación estable de cada deportista a un equipo durante toda la temporada',
      'El reparto de roles: arbitrar, entrenar, llevar estadísticas o gestionar material',
      'La existencia de un evento culminante que cierra la temporada con carácter festivo',
      'La supresión de la competición formal para evitar la comparación entre deportistas',
      'La repetición analítica del gesto técnico antes de cualquier situación de juego',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Afiliación, roles y evento culminante son tres de los seis rasgos del modelo de Siedentop, junto con la temporada larga, la competición formal y el registro de resultados. Los dos distractores lo contradicen de frente: el modelo no suprime la competición, la formaliza con calendario y estadísticas, y no se apoya en la repetición analítica sino en la participación con sentido. Dato para recordar: el modelo reproduce la cultura del deporte, no la esconde.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.3 — Modelos por autor',
    etiquetas: ['educación deportiva', 'Siedentop', 'roles'],
  },
  {
    id: 'B3-009',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué propuesta pedagógica se atribuye a Siedentop?',
    opciones: [
      'El modelo de educación deportiva',
      'El modelo comprensivo, conocido por sus siglas inglesas TGfU',
      'El modelo ludotécnico, aplicado a la enseñanza del atletismo escolar',
      'El espectro de estilos de enseñanza, con sus cuatro grandes categorías',
    ],
    correcta: 0,
    explicacion:
      'Siedentop firma el modelo de educación deportiva, cuyo propósito es reproducir la cultura del deporte dentro de la sesión mediante temporada, equipo, roles y evento final. El distractor más tentador es el segundo, porque los dos modelos son emergentes y se citan juntos: el comprensivo es de Bunker y Thorpe. Dato para recordar: Siedentop organiza una temporada, Bunker y Thorpe organizan un juego.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.3 — Modelos por autor',
    etiquetas: ['Siedentop', 'educación deportiva', 'autores'],
  },
  {
    id: 'B3-010',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué caracteriza al modelo integrado técnico-táctico?',
    opciones: [
      'Trabaja técnica y táctica a la vez dentro de situaciones de juego con sentido',
      'Alterna sesiones íntegramente técnicas con sesiones íntegramente tácticas',
      'Reserva la táctica para el nivel avanzado y la técnica para el nivel inicial',
      'Integra en cada sesión contenidos de condición física y de técnica deportiva',
    ],
    correcta: 0,
    explicacion:
      'El integrado responde a la falsa disyuntiva entre empezar por la técnica o por la táctica: no elige, las trabaja juntas y siempre dentro del juego, con un objetivo táctico y un contenido técnico asociados en cada tarea. El distractor más tentador es el segundo, porque alternar suena a integrar; alternar mantiene los dos contenidos separados, que es justamente lo que el modelo evita. Dato para recordar: integrar es en la misma tarea, no en semanas alternas.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo integrado', 'técnica', 'táctica'],
  },
  {
    id: 'B3-011',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada autor con la propuesta que se le atribuye.',
    izquierda: ['Bunker y Thorpe', 'Siedentop', 'Hellison', 'Mosston'],
    derecha: [
      'Modelo comprensivo o Teaching Games for Understanding',
      'Modelo de educación deportiva',
      'Modelo de responsabilidad personal y social',
      'Espectro de estilos de enseñanza',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los cuatro pertenecen al mismo campo y se citan siempre juntos, que es lo que hace fácil cruzarlos. El par que más se falla es Hellison con Siedentop, porque los dos modelos trabajan valores y autonomía: el de Hellison se centra en la responsabilidad personal y social del alumno, y el de Siedentop en reproducir la cultura del deporte. Mosston no propone un modelo pedagógico sino un espectro de estilos, que es el contenido del módulo B5.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.3 — Modelos por autor',
    etiquetas: ['autores', 'modelos pedagógicos', 'Mosston', 'Hellison'],
  },
  {
    id: 'B3-012',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el modelo tradicional resulta especialmente limitado para enseñar deportes de invasión?',
    opciones: [
      'Porque el deportista aprende a ejecutar el gesto sin aprender cuándo aplicarlo',
      'Porque los gestos de esos deportes exigen más repeticiones de las que permite',
      'Porque el mando directo impide que el entrenador corrija durante el juego real',
      'Porque las sesiones analíticas exigen más material del que un club suele tener',
    ],
    correcta: 0,
    explicacion:
      'En los deportes de invasión la dificultad no está en el gesto sino en decidir cuál usar, cuándo y contra quién: un modelo que aísla el gesto del contexto deja al deportista con la ejecución resuelta y la decisión sin trabajar. El distractor más tentador es el segundo, porque suena a un problema real de volumen; el problema no es cuántas repeticiones, es que están descontextualizadas. Dato para recordar: en gestos cerrados sin oposición, el enfoque analítico sí es el correcto.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.1 — Modelos básicos y emergentes',
    etiquetas: ['modelo tradicional', 'invasión', 'táctica'],
  },
  {
    id: 'B3-013',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un entrenador reduce tanto el campo de un juego modificado que ya no hay espacio libre que buscar. ¿Qué ha ocurrido?',
    opciones: [
      'Ha simplificado la decisión y no solo la ejecución, así que el juego perdió su sentido',
      'Ha aplicado correctamente la modificación, porque el objetivo era rebajar la dificultad',
      'Ha convertido el juego modificado en un ejercicio del modelo integrado técnico-táctico',
      'Ha cambiado la categoría del juego, que pasa de invasión a cancha dividida',
    ],
    correcta: 0,
    explicacion:
      'La regla del juego modificado es que se simplifica la ejecución y nunca la decisión: si al reducir el campo desaparece el problema táctico que se quería enseñar, la modificación está mal hecha. El distractor más tentador es el segundo, porque rebajar la dificultad sí es parte de la idea; lo que no puede rebajarse es el problema, que es precisamente el contenido de la sesión. Dato para recordar: sin problema táctico, el juego modificado ya no enseña táctica.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['juego modificado', 'modelo comprensivo', 'diseño de tareas'],
  },
  {
    id: 'B3-014',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Según la clasificación por categorías tácticas, ¿entre qué pares de deportes cabe esperar transferencia del aprendizaje táctico?',
    opciones: [
      'Entre balonmano y baloncesto, porque ambos son deportes de invasión',
      'Entre voleibol y baloncesto, porque los dos se juegan en cancha con un balón',
      'Entre tenis y golf, porque en ambos se golpea un móvil con un implemento',
      'Entre béisbol y fútbol, porque los dos se disputan sobre un campo de hierba',
    ],
    correcta: 0,
    explicacion:
      'La transferencia táctica ocurre dentro de la categoría: balonmano y baloncesto plantean el mismo problema —ocupar el espacio del rival para llegar a su meta— aunque el gesto cambie por completo. Los tres distractores agrupan por rasgos superficiales: el material, la superficie o el implemento, que no dicen nada del problema que hay que resolver. Dato para recordar: la categoría la fija el problema táctico, no el balón ni el terreno.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['transferencia', 'categorías de juego', 'invasión'],
  },
  {
    id: 'B3-015',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre el modelo comprensivo.',
    opciones: [
      'Sostiene que la principal carencia del principiante es la comprensión táctica',
      'Emplea juegos modificados que rebajan la exigencia técnica sin tocar la táctica',
      'Prescinde por completo del trabajo técnico a lo largo de todo el proceso',
      'Fue formulado por Siedentop dentro del modelo de educación deportiva',
      'Se aplica sobre todo en deportes individuales sin oposición directa',
    ],
    correctas: [0, 1],
    explicacion:
      'Las dos primeras describen el núcleo del modelo: el problema es de comprensión y la herramienta son los juegos modificados. La tercera exagera hasta volverlo falso, porque el comprensivo no elimina la técnica sino que la coloca después del problema que la hace necesaria. La cuarta atribuye mal la autoría y la quinta describe el terreno del ludotécnico. Dato para recordar: la técnica no desaparece, cambia de sitio en la secuencia.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo comprensivo', 'juego modificado', 'técnica'],
  },
  {
    id: 'B3-016',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'vf',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Los modelos emergentes son pedagógicamente superiores al enfoque analítico en cualquier deporte y en cualquier contexto.',
    correcta: false,
    explicacion:
      'Falso. En gestos cerrados, sin oposición y con una única solución mecánicamente eficiente —un salto de trampolín, un lanzamiento de jabalina— el trabajo analítico es el adecuado, porque no hay problema táctico que comprender. Lo que el modelo tradicional hace mal es tratar los deportes de invasión como si fueran gestos cerrados. Dato para recordar: el modelo se elige por el tipo de deporte, el nivel y el objetivo, no por preferencia.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.1 — Modelos básicos y emergentes',
    etiquetas: ['modelos emergentes', 'modelo tradicional', 'criterio de elección'],
  },
  {
    id: 'B3-017',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Comprensivo y ludotécnico emplean ambos el juego como recurso. ¿Cuál es la diferencia de fondo entre los dos?',
    opciones: [
      'El comprensivo lo usa para que emerja el problema táctico y el ludotécnico para enseñar el gesto técnico',
      'El comprensivo se aplica en la etapa de formación y el ludotécnico en la de alto rendimiento',
      'El comprensivo emplea juegos reglados y el ludotécnico solo juegos libres sin reglamento',
      'El comprensivo trabaja en grupo y el ludotécnico exige siempre atención individualizada',
    ],
    correcta: 0,
    explicacion:
      'Los dos usan el juego, pero para problemas distintos: el comprensivo lo usa en deportes de oposición para que el deportista se tope con el problema táctico, y el ludotécnico en deportes individuales, donde no hay táctica que comprender, para hacer motivante el aprendizaje del gesto. El distractor más tentador es el primero de los tres falsos, porque introduce una diferencia de etapa que no existe. Dato para recordar: el criterio es el tipo de deporte, no la edad ni el nivel.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo comprensivo', 'modelo ludotécnico', 'comparación'],
  },
  {
    id: 'B3-018',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Una entrenadora plantea un juego reducido y pide a sus jugadoras que busquen cómo superar la presión de la defensa. En cuanto una de ellas prueba una solución distinta a la prevista, la detiene y le explica la respuesta correcta. Al cabo de un mes, el grupo espera la indicación antes de decidir cualquier cosa.',
    enunciado: '¿Qué está fallando en su intervención?',
    opciones: [
      'Corrige antes de dar tiempo a probar, y así impide la construcción que buscaba',
      'Ha elegido un modelo constructivista para un contenido que exige trabajo analítico',
      'El juego reducido no conserva la lógica táctica del deporte y no sirve como tarea',
      'Falta un evento culminante que dé sentido competitivo a la secuencia de sesiones',
    ],
    correcta: 0,
    explicacion:
      'El planteamiento es constructivista y correcto; lo que lo anula es la intervención inmediata, porque si el entrenador da la solución antes de que el deportista pruebe, no queda nada que construir. El resultado descrito —esperar la indicación antes de decidir— es exactamente lo que produce esa práctica. El distractor más tentador es el segundo, porque culpa a la elección del modelo cuando el problema es su ejecución. Dato para recordar: en el constructivista, las preguntas valen más que las correcciones.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo constructivista', 'intervención', 'error'],
  },
  {
    id: 'B3-019',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Relacione cada decisión del entrenador con el modelo que la inspira.',
    izquierda: [
      'Reparte roles de árbitro, anotador y capitán a lo largo de una temporada larga',
      'Plantea un cuatro contra cuatro en espacio reducido antes de enseñar el pase',
      'Convierte la serie de saltos en un circuito con reto y puntuación por equipos',
      'Ordena diez repeticiones del gesto de saque frente a la pared, sin oposición',
    ],
    derecha: [
      'Educación deportiva',
      'Comprensivo',
      'Ludotécnico',
      'Técnico o tradicional',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es el ludotécnico con el comprensivo, porque en los dos hay juego: la clave está en que el circuito de saltos no tiene oposición ni problema táctico, así que el juego solo aporta motivación para repetir el gesto. El reparto de roles con temporada larga es la firma inconfundible del modelo de Siedentop. Dato para recordar: hay juego en tres de los cuatro, y lo que los separa es para qué sirve.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelos pedagógicos', 'aplicación', 'clasificación'],
  },
  {
    id: 'B3-020',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador de atletismo debe enseñar la técnica de lanzamiento de jabalina a un grupo de iniciación. ¿Qué enfoque es el adecuado?',
    opciones: [
      'Trabajo analítico del gesto, apoyado en tareas lúdicas que motiven la repetición',
      'Juegos modificados que conserven el problema táctico del lanzamiento',
      'Situaciones de oposición reducida para que emerja la necesidad del gesto',
      'Reparto de roles y calendario de competición interna durante la temporada',
    ],
    correcta: 0,
    explicacion:
      'La jabalina es un gesto cerrado, sin oposición y con una única solución mecánicamente eficiente: ahí el trabajo analítico es lo correcto, y el modelo ludotécnico aporta la parte lúdica que sostiene la repetición. Los dos distractores centrales invocan herramientas del modelo comprensivo, que no tiene dónde agarrarse porque no hay problema táctico que resolver. Dato para recordar: sin oposición no hay táctica, y sin táctica el comprensivo no aplica.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo ludotécnico', 'gesto cerrado', 'prescripción'],
  },
  {
    id: 'B3-021',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un entrenador de baloncesto quiere que su grupo infantil aprenda a generar líneas de pase. Dispone de media pista, ocho jugadores y treinta minutos, y sabe que el bote todavía es muy inseguro en la mitad del grupo.',
    enunciado: '¿Qué tarea responde mejor al modelo comprensivo?',
    opciones: [
      'Un cuatro contra cuatro sin bote, en el que solo se puede avanzar pasando',
      'Una hilera de pases estáticos por parejas, aumentando la distancia cada minuto',
      'Un uno contra uno con bote libre para que ganen seguridad en el manejo',
      'Un partido a media pista con reglas completas, sin ninguna modificación',
    ],
    correcta: 0,
    explicacion:
      'Prohibir el bote elimina la dificultad técnica que el grupo no domina y a la vez obliga a resolver el problema táctico que se quiere enseñar, porque sin bote solo se avanza generando líneas de pase: eso es exactamente simplificar la ejecución sin tocar la decisión. El distractor más tentador es el último, porque también es juego real; sin modificación, el bote inseguro impedirá que aparezca el contenido de la sesión. Dato para recordar: el juego modificado se diseña desde el problema, no desde el nivel técnico.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['juego modificado', 'modelo comprensivo', 'diseño de tareas'],
  },
  {
    id: 'B3-022',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'En un club escolar la asistencia cae cada trimestre. Los chicos dicen que las sesiones son «siempre lo mismo» y que apenas juegan. El coordinador quiere un cambio de enfoque que aumente la implicación y dé continuidad al curso, más allá de cambiar los ejercicios de la semana.',
    enunciado: '¿Qué modelo responde mejor a lo que describe el caso?',
    opciones: [
      'El de educación deportiva, con temporada, equipos estables, roles y evento final',
      'El técnico o tradicional, con progresiones analíticas mejor secuenciadas que las actuales',
      'El ludotécnico, sustituyendo cada ejercicio por una versión con reto y puntuación',
      'El constructivista, planteando problemas abiertos en cada una de las sesiones',
    ],
    correcta: 0,
    explicacion:
      'El caso pide implicación y continuidad más allá de la sesión suelta, y eso es justo lo que estructura la educación deportiva: temporada larga, afiliación estable, competición formal, registro, festividad y evento culminante, con roles que dan a cada uno un lugar propio. El distractor más tentador es el ludotécnico, porque también ataca la motivación; lo hace tarea a tarea y no resuelve la falta de continuidad. Dato para recordar: el problema del caso es de estructura, no de ejercicio.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.3 — Modelos por autor',
    etiquetas: ['educación deportiva', 'Siedentop', 'motivación', 'aplicación'],
  },
  {
    id: 'B3-023',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Una entrenadora de balonmano quiere aprovechar que sus jugadoras vienen del baloncesto. ¿Qué contenido puede dar por parcialmente adquirido?',
    opciones: [
      'Los principios tácticos de ocupación de espacios, desmarque y apoyo al portador',
      'La técnica de lanzamiento en suspensión, por la similitud del gesto de brazo',
      'La lectura del saque y la colocación defensiva ante un envío desde el fondo',
      'La gestión del ritmo de juego, propia de los deportes de cancha dividida',
    ],
    correcta: 0,
    explicacion:
      'Baloncesto y balonmano son deportes de invasión, así que comparten el problema táctico y transfieren desmarque, apoyo y ocupación de espacios aunque el gesto cambie por completo. El distractor más tentador es el segundo, porque la similitud del movimiento de brazo es real y visible; la transferencia que la clasificación predice es táctica, no técnica. Dato para recordar: transfiere el problema, no el gesto.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['transferencia', 'invasión', 'categorías de juego', 'aplicación'],
  },
  {
    id: 'B3-024',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado: 'Ordene las fases de una sesión planteada según el modelo comprensivo.',
    elementos: [
      'Presentación del juego modificado, con sus reglas y su espacio',
      'Juego: las deportistas se topan con el problema táctico y ensayan soluciones',
      'Preguntas del entrenador sobre qué funcionó y por qué, sin dar la respuesta',
      'Trabajo del recurso técnico que el problema ha hecho necesario',
      'Vuelta al juego, ahora con el recurso técnico disponible',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La secuencia del modelo comprensivo va del juego al gesto y vuelve al juego: primero se plantea la situación, después se deja que aparezca el problema, se pregunta, se trabaja la técnica que el problema exige y se regresa a jugar para comprobar que sirve. El error más frecuente es colocar el trabajo técnico en primer lugar, que es precisamente el orden del modelo tradicional. Dato para recordar: la técnica va en el centro de la sesión, no al principio.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['modelo comprensivo', 'estructura de sesión', 'aplicación'],
  },
  {
    id: 'B3-025',
    modulo: 'b3-modelos-pedagogicos',
    bloque: 'B',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Ordene la progresión de un juego modificado desde la mayor simplificación hasta el juego real.',
    elementos: [
      'Tres contra dos en espacio muy reducido, con superioridad numérica del atacante',
      'Tres contra tres en el mismo espacio, ya en igualdad numérica',
      'Cuatro contra cuatro en medio campo, con las reglas propias del deporte',
      'Partido completo en campo entero y reglamento oficial',
    ],
    ordenCorrecto: [0, 1, 2, 3],
    explicacion:
      'La progresión retira las ayudas de una en una: primero desaparece la superioridad numérica, después se amplía el espacio y por último se recupera el reglamento completo. El error habitual es igualar el número de jugadores y ampliar el campo a la vez, con lo que la tarea se vuelve demasiado difícil de golpe y el problema táctico se diluye. Dato para recordar: un elemento nuevo por escalón, igual que en la sistematicidad del módulo B2.',
    referencia: 'Cartilla 2, Tema 3, Subtema 3.2 — Modelos de intervención',
    etiquetas: ['juego modificado', 'progresión', 'diseño de tareas'],
  },
];
