// content/banco/b5-estilos-ensenanza.ts
// Bloque B · Módulo 5 — Estilos de enseñanza.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   tipos      → 11 única · 4 emparejar · 4 caso · 2 múltiple · 2 ordenar · 2 V/F
//
// Sin ítems de cálculo: el módulo es una taxonomía y no tiene magnitudes.
// Emparejar y caso llevan el peso, que es lo que rinde cuando lo que se
// pregunta es a qué categoría pertenece cada estilo y cuál elegir.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'B5-001',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué caracteriza al estilo de mando directo?',
    opciones: [
      'El entrenador decide todo y la ejecución es simultánea a su señal',
      'El entrenador fija la tarea y el deportista decide cuándo y a qué ritmo la hace',
      'Un compañero observa la ejecución y corrige apoyado en una ficha de criterios',
      'El deportista avanza por módulos de contenido según su propio nivel',
    ],
    correcta: 0,
    explicacion:
      'El mando directo es el extremo de la escala: el entrenador decide qué, cómo, cuándo se empieza y cuándo se para, y todo el grupo ejecuta a la vez a su señal. Los tres distractores describen, en orden, la asignación de tareas, la enseñanza recíproca y la enseñanza modular. El más tentador es el segundo, porque los dos son estilos tradicionales y solo se separan por quién marca el ritmo. Dato para recordar: si la ejecución es simultánea y a la señal, es mando directo.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['mando directo', 'estilos tradicionales', 'definición'],
  },
  {
    id: 'B5-002',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿En qué consiste el descubrimiento guiado?',
    opciones: [
      'En conducir al deportista hacia una solución concreta mediante preguntas encadenadas',
      'En plantear un problema abierto y aceptar cualquier solución razonable que el grupo proponga',
      'En repartir roles de observador y ejecutante dentro de cada pareja de trabajo',
      'En dividir el contenido en módulos que el deportista supera a su propio ritmo',
    ],
    correcta: 0,
    explicacion:
      'En el descubrimiento guiado el entrenador nunca da la respuesta, pero la conoce de antemano y diseña la secuencia de preguntas para que el deportista llegue a ella. El distractor más tentador es el segundo, que describe la resolución de problemas: los dos son estilos de implicación cognitiva y solo se separan por si hay una respuesta buscada o varias válidas. Dato para recordar: guiado significa que hay destino.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.3 — Estilos de implicación cognitiva',
    etiquetas: ['descubrimiento guiado', 'implicación cognitiva', 'definición'],
  },
  {
    id: 'B5-003',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'Relacione cada estilo con la categoría a la que pertenece.',
    izquierda: ['Mando directo', 'Enseñanza recíproca', 'Resolución de problemas', 'Enseñanza modular'],
    derecha: [
      'Estilos tradicionales',
      'Estilos de participación',
      'Estilos de implicación cognitiva',
      'Estilos de organización',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada categoría se reconoce por lo que el entrenador cede: nada en los tradicionales, la evaluación en los de participación, la respuesta en los de implicación cognitiva y el ritmo en los de organización. El error más frecuente es colocar la enseñanza modular entre los de participación, porque el deportista trabaja con autonomía; lo que cede el estilo modular es el itinerario, no la corrección. Dato para recordar: la categoría la fija la decisión cedida.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['estilos de enseñanza', 'categorías', 'clasificación'],
  },
  {
    id: 'B5-004',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué define a la microenseñanza?',
    opciones: [
      'Que un grupo de alumnos-monitores recibe la información y cada uno enseña a su subgrupo',
      'Que el contenido se fragmenta en tareas muy breves de dos o tres minutos cada una',
      'Que el entrenador trabaja con grupos de tres o cuatro deportistas como máximo',
      'Que cada deportista dispone de un programa individual escrito para toda la temporada de competición',
    ],
    correcta: 0,
    explicacion:
      'La microenseñanza delega la enseñanza misma: el entrenador informa a unos pocos alumnos-monitores y son ellos quienes enseñan al resto. Es el estilo que más decisiones cede. El distractor más tentador es el segundo, porque el prefijo «micro» sugiere tareas cortas, cuando se refiere al tamaño del grupo que atiende cada monitor. Dato para recordar: en la recíproca se delega corregir, en la microenseñanza se delega enseñar.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['microenseñanza', 'estilos de participación', 'definición'],
  },
  {
    id: 'B5-005',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'La enseñanza modular pertenece a la categoría de los estilos tradicionales.',
    correcta: false,
    explicacion:
      'Falso. La enseñanza modular es un estilo de organización: divide el contenido en módulos con sus criterios de superación y permite que cada deportista avance según su nivel y su ritmo, en vez de según el calendario del grupo. Los tradicionales son el mando directo, el mando directo modificado y la asignación de tareas. Dato para recordar: los de organización ajustan el itinerario a la persona, no la persona al itinerario.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.4 — Estilos de organización',
    etiquetas: ['enseñanza modular', 'estilos de organización', 'clasificación'],
  },
  {
    id: 'B5-006',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'En la enseñanza recíproca, ¿a quién corrige el entrenador?',
    opciones: [
      'Al observador, que es quien debe aprender a mirar y a dar la información',
      'Al ejecutante, mientras el observador toma nota de lo que el entrenador señala',
      'A los dos por igual, alternando la atención entre ejecutante y observador',
      'A ninguno: el estilo se define porque el entrenador no interviene durante la tarea',
    ],
    correcta: 0,
    explicacion:
      'En la enseñanza recíproca el entrenador corrige al observador, no al ejecutante: la corrección del gesto se ha delegado en el compañero, y lo que el entrenador enseña es a observar bien. El distractor más tentador es el segundo, porque describe lo que casi todo el mundo hace la primera vez que aplica el estilo, y con ello lo convierte en mando directo con público. Dato para recordar: el entrenador enseña a corregir, no corrige.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['enseñanza recíproca', 'estilos de participación', 'feedback'],
  },
  {
    id: 'B5-007',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada categoría de estilos con la decisión que cede el entrenador.',
    izquierda: [
      'Estilos tradicionales',
      'Estilos de participación',
      'Estilos de implicación cognitiva',
      'Estilos de organización',
    ],
    derecha: [
      'Ninguna decisión relevante, o solo el ritmo de ejecución',
      'La evaluación: quien corrige la ejecución es un compañero',
      'La respuesta: el deportista tiene que buscarla por sí mismo',
      'El ritmo y el itinerario: cada uno avanza por donde le corresponde',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Este emparejamiento es la clave de todo el módulo, porque permite clasificar cualquier estilo sin memorizar listas: basta preguntarse qué ha dejado de decidir el entrenador. El par que más se falla es participación con organización, porque en los dos el deportista trabaja con autonomía aparente: en uno se cede corregir y en el otro se cede el recorrido. Dato para recordar: autonomía no es una sola cosa, y cada categoría cede una distinta.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['categorías', 'estilos de enseñanza', 'clasificación'],
  },
  {
    id: 'B5-008',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione los TRES estilos que pertenecen a la categoría de los tradicionales.',
    opciones: [
      'Mando directo',
      'Mando directo modificado',
      'Asignación de tareas',
      'Enseñanza recíproca por parejas',
      'Descubrimiento guiado',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Los tres tradicionales son el mando directo, su versión modificada y la asignación de tareas. La enseñanza recíproca es de participación y el descubrimiento guiado de implicación cognitiva. El error frecuente es sacar la asignación de tareas de esta familia porque el deportista ya decide su ritmo: sigue siendo tradicional, porque el feedback continúa viniendo del entrenador. Dato para recordar: ceder el ritmo no cambia de categoría.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['estilos tradicionales', 'asignación de tareas', 'clasificación'],
  },
  {
    id: 'B5-009',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué caracteriza al estilo de resolución de problemas?',
    opciones: [
      'Que el problema admite varias soluciones válidas y el entrenador no dirige la búsqueda',
      'Que el entrenador reorienta con nuevas preguntas cada vez que el deportista se desvía',
      'Que el deportista corrige a un compañero apoyándose en una lista de criterios',
      'Que el contenido se organiza en niveles que se superan uno detrás de otro',
    ],
    correcta: 0,
    explicacion:
      'En la resolución de problemas no hay destino único: varias respuestas pueden ser buenas y el entrenador acompaña en lugar de reorientar. El distractor más tentador es el segundo, que describe exactamente el descubrimiento guiado, su vecino de categoría: allí sí hay una solución concreta y las preguntas están diseñadas para alcanzarla. Dato para recordar: si el entrenador corrige el rumbo, es guiado; si lo deja abierto, es resolución de problemas.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.3 — Estilos de implicación cognitiva',
    etiquetas: ['resolución de problemas', 'implicación cognitiva', 'definición'],
  },
  {
    id: 'B5-010',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'En la asignación de tareas, ¿qué decide el deportista?',
    opciones: [
      'Cuándo empieza, a qué ritmo trabaja y cómo distribuye las repeticiones asignadas',
      'Qué contenido se trabaja en la sesión y con qué criterios de ejecución',
      'Cómo corrige a su compañero de pareja durante la ejecución de la tarea',
      'Por qué módulo del programa avanza y en qué orden supera los contenidos',
    ],
    correcta: 0,
    explicacion:
      'En la asignación de tareas el entrenador fija qué se hace y con qué criterios, y el deportista gestiona el cuándo, el ritmo y el reparto de repeticiones. Los tres distractores describen decisiones que este estilo no cede: el contenido sigue siendo del entrenador, corregir es de los estilos de participación y elegir itinerario es de los de organización. Dato para recordar: es la primera cesión real, y es solo de gestión del tiempo.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['asignación de tareas', 'estilos tradicionales', 'autonomía'],
  },
  {
    id: 'B5-011',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada estilo con su rasgo distintivo.',
    izquierda: [
      'Asignación de tareas',
      'Enseñanza recíproca',
      'Grupos reducidos',
      'Microenseñanza',
    ],
    derecha: [
      'El deportista gestiona su ritmo, pero el entrenador sigue corrigiendo',
      'Parejas: uno ejecuta y otro observa con una ficha de criterios',
      'Más roles repartidos: ejecutante, observador, anotador y material',
      'Alumnos-monitores que enseñan cada uno a su propio subgrupo',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los tres últimos ceden la evaluación al compañero y se ordenan por cuánto delegan: la recíproca reparte dos papeles, los grupos reducidos reparten varios y la microenseñanza llega a delegar la enseñanza entera. La asignación de tareas está aquí como frontera, porque es la que más se cuela entre los de participación: cede el ritmo y conserva la corrección, así que sigue siendo tradicional. Dato para recordar: la ficha de criterios marca el paso a participación.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['estilos de participación', 'microenseñanza', 'clasificación'],
  },
  {
    id: 'B5-012',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un entrenador entrega una hoja con cinco ejercicios, deja que cada deportista los haga en el orden y al ritmo que quiera, y va corrigiendo él uno por uno. ¿Qué estilo está usando?',
    opciones: [
      'Asignación de tareas, porque cede el ritmo pero conserva la corrección',
      'Enseñanza recíproca, porque los deportistas trabajan de forma autónoma',
      'Enseñanza modular, porque cada uno avanza por los ejercicios a su ritmo',
      'Descubrimiento guiado, porque no impone una única forma de resolver la sesión',
    ],
    correcta: 0,
    explicacion:
      'La prueba está en quién corrige: aquí lo hace el entrenador, así que sigue siendo un estilo tradicional, y como el deportista gestiona el orden y el ritmo, es asignación de tareas. El distractor más tentador es el tercero, porque hay autonomía de ritmo; la enseñanza modular exige módulos con criterios de superación y un itinerario propio, no una lista de ejercicios común. Dato para recordar: ceder el ritmo no es ceder la evaluación.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['asignación de tareas', 'estilos de participación', 'comparación'],
  },
  {
    id: 'B5-013',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Cuál es la diferencia de fondo entre el descubrimiento guiado y la resolución de problemas?',
    opciones: [
      'Que el guiado persigue una respuesta concreta que el entrenador ya conoce y el otro admite varias',
      'Que el guiado se aplica en deportes individuales y el otro en deportes colectivos',
      'Que el guiado exige más tiempo de sesión que la resolución de problemas',
      'Que el guiado se dirige a principiantes y la resolución de problemas a deportistas formados',
    ],
    correcta: 0,
    explicacion:
      'Los dos son estilos de implicación cognitiva y en los dos el deportista busca; lo que cambia es si hay destino. En el descubrimiento guiado el entrenador conoce la respuesta y encadena preguntas para llegar a ella, y si el deportista se desvía lo reorienta. En la resolución de problemas varias soluciones son válidas y no hay reorientación. Los otros tres distractores inventan criterios de deporte, tiempo o nivel que el estilo no contempla.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.3 — Estilos de implicación cognitiva',
    etiquetas: ['descubrimiento guiado', 'resolución de problemas', 'comparación'],
  },
  {
    id: 'B5-014',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 2,
    viñeta:
      'Una entrenadora organiza el trabajo por parejas para pulir el saque: uno saca y el otro mira. No entrega ningún material y pide a los observadores que «digan lo que vean». Al cabo de veinte minutos, la mayoría de los comentarios son «bien» o «vuelve a intentarlo».',
    enunciado: '¿Qué le falta a su planteamiento?',
    opciones: [
      'La ficha de criterios que indica al observador qué aspectos concretos debe mirar',
      'Un tiempo de demostración previa del gesto por parte de la propia entrenadora',
      'La rotación de las parejas cada cierto número de repeticiones del saque',
      'Un criterio de agrupamiento por nivel que empareje a deportistas equivalentes',
    ],
    correcta: 0,
    explicacion:
      'La enseñanza recíproca se sostiene sobre la ficha de criterios: sin ella el observador no sabe qué mirar y su corrección se reduce a una opinión, que es exactamente lo que describe el caso. El distractor más tentador es el segundo, porque la demostración también ayuda; con demostración y sin criterios el observador seguiría sin saber qué tres cosas comprobar. Dato para recordar: la ficha no es burocracia, es el estilo.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['enseñanza recíproca', 'ficha de criterios', 'estilos de participación'],
  },
  {
    id: 'B5-015',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'vf',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'El mando directo es un estilo superado que conviene evitar en cualquier contexto de entrenamiento actual.',
    correcta: false,
    explicacion:
      'Falso. El mando directo es el estilo indicado cuando un error de ejecución termina en lesión —trampolín, halterofilia, trabajo en agua— y también cuando el grupo es muy numeroso y el tiempo escaso, porque garantiza el control de la ejecución. El error no es usarlo, es usarlo siempre, incluido el día en que el objetivo era que el grupo comprendiera algo. Dato para recordar: ningún estilo es mejor que otro en abstracto.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['mando directo', 'seguridad', 'criterio de elección'],
  },
  {
    id: 'B5-016',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué problema resuelve específicamente la enseñanza modular?',
    opciones: [
      'Que no todo el grupo va al mismo ritmo ni necesita trabajar el mismo contenido',
      'Que el entrenador no dispone de tiempo suficiente para corregir a cada deportista',
      'Que los deportistas no saben observar ni dar información útil a sus compañeros',
      'Que el contenido de la sesión resulta poco motivante para el grupo de trabajo',
    ],
    correcta: 0,
    explicacion:
      'La enseñanza modular existe porque la heterogeneidad de nivel dentro de un grupo hace inútil un itinerario único: cada deportista avanza por los módulos que le corresponden y a su ritmo. El distractor más tentador es el segundo, porque también alivia la carga del entrenador; ese es el problema que resuelven los estilos de participación delegando la corrección. Dato para recordar: la modular ajusta el itinerario a la persona.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.4 — Estilos de organización',
    etiquetas: ['enseñanza modular', 'estilos de organización', 'heterogeneidad'],
  },
  {
    id: 'B5-017',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Por qué el mando directo es el estilo indicado en contenidos con riesgo de lesión?',
    opciones: [
      'Porque mantiene el control de la ejecución en manos del entrenador en todo momento',
      'Porque permite trabajar con grupos más numerosos de lo que admite cualquier otro estilo',
      'Porque el deportista aprende antes el gesto cuando no tiene que tomar decisiones',
      'Porque evita que los compañeros den información incorrecta durante la ejecución',
    ],
    correcta: 0,
    explicacion:
      'Cuando un error termina en lesión, lo primero es que nadie ejecute sin que el entrenador esté mirando y pueda detener la acción: el mando directo garantiza exactamente eso, porque decide cuándo se empieza y cuándo se para. El distractor más tentador es el cuarto, porque también apunta a un riesgo real; el problema del contenido peligroso no es la calidad del feedback, es el control de la acción. Dato para recordar: en riesgo, la seguridad manda sobre la autonomía.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['mando directo', 'seguridad', 'criterio de elección'],
  },
  {
    id: 'B5-018',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador de escuela municipal recibe 36 niños con un solo ayudante. Antes de la sesión reúne a seis de los mayores, les explica la tarea y los criterios de ejecución, y cada uno se hace cargo de un grupo de cinco durante la parte principal.',
    enunciado: '¿Qué estilo está aplicando y qué categoría le corresponde?',
    opciones: [
      'Microenseñanza, de la categoría de estilos de participación',
      'Grupos reducidos, de la categoría de estilos de organización',
      'Asignación de tareas, de la categoría de estilos tradicionales',
      'Enseñanza modular, de la categoría de estilos de organización',
    ],
    correcta: 0,
    explicacion:
      'Que unos alumnos reciban la información y enseñen cada uno a su subgrupo es la definición de microenseñanza, el estilo de participación que más decisiones cede porque delega la enseñanza y no solo la corrección. El distractor más tentador es el segundo, porque también hay subgrupos: en grupos reducidos los roles se reparten dentro del grupo y el entrenador sigue enseñando a todos. Dato para recordar: si hay alumno que enseña, es microenseñanza.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['microenseñanza', 'estilos de participación', 'grupos numerosos'],
  },
  {
    id: 'B5-019',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'emparejar',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Relacione cada situación de sesión con el estilo de enseñanza que la describe.',
    izquierda: [
      'Todos ejecutan el mismo ejercicio a la voz del entrenador, sin margen de ritmo',
      'Por parejas, uno ejecuta y el otro corrige con una lista de tres criterios',
      'El entrenador pregunta «¿dónde queda el defensor si sales por ese lado?» y espera',
      'Cada deportista trabaja en el módulo que le corresponde según su última evaluación',
    ],
    derecha: [
      'Mando directo',
      'Enseñanza recíproca',
      'Descubrimiento guiado',
      'Enseñanza modular',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada situación delata su estilo por una sola pista: la señal de ejecución conjunta, la ficha de criterios en manos del compañero, la pregunta que conduce sin dar la respuesta, y el itinerario propio marcado por una evaluación previa. La que más se falla es la tercera, porque una pregunta también puede ser resolución de problemas; aquí la pregunta apunta a una respuesta concreta, y eso la sitúa en el descubrimiento guiado.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.3 — Estilos de implicación cognitiva',
    etiquetas: ['estilos de enseñanza', 'aplicación', 'clasificación'],
  },
  {
    id: 'B5-020',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Una entrenadora inicia a un grupo de doce principiantes en los saltos desde trampolín de un metro. Ninguno ha saltado antes y la piscina solo permite tener un saltador en el agua a la vez.',
    enunciado: '¿Qué estilo corresponde emplear en esta sesión?',
    opciones: [
      'Mando directo, porque el riesgo exige controlar cuándo salta cada uno',
      'Resolución de problemas, para que cada saltador encuentre su propia entrada al agua',
      'Enseñanza recíproca, para que los compañeros se corrijan mientras esperan turno',
      'Enseñanza modular, para que cada uno avance por los saltos según su nivel',
    ],
    correcta: 0,
    explicacion:
      'Con principiantes, riesgo real y un solo saltador permitido en el agua, la prioridad es el control de la ejecución, y eso es exactamente lo que garantiza el mando directo al decidir cuándo se empieza y cuándo se para. El distractor más tentador es el tercero, porque aprovecha el tiempo de espera; pedir a doce principiantes que se corrijan un salto que ninguno domina genera información equivocada. Dato para recordar: en riesgo, primero seguridad, después autonomía.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.1 — Estilos tradicionales',
    etiquetas: ['mando directo', 'seguridad', 'iniciación', 'aplicación'],
  },
  {
    id: 'B5-021',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'multiple',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador quiere que su grupo entienda por qué conviene abrir el campo en ataque, no solo que lo ejecute. Seleccione los DOS estilos adecuados.',
    opciones: [
      'Descubrimiento guiado',
      'Resolución de problemas',
      'Mando directo',
      'Asignación de tareas',
      'Enseñanza modular',
    ],
    correctas: [0, 1],
    explicacion:
      'Cuando el objetivo es comprender y no ejecutar, corresponden los estilos de implicación cognitiva, que son el descubrimiento guiado y la resolución de problemas: los dos obligan al deportista a construir la explicación en vez de recibirla. Los tres distractores son estilos válidos para otros objetivos, pero ninguno pone al deportista a razonar: dos son tradicionales y el tercero organiza el itinerario. Dato para recordar: comprender exige buscar, y buscar exige que no le den la respuesta.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.3 — Estilos de implicación cognitiva',
    etiquetas: ['implicación cognitiva', 'criterio de elección', 'aplicación'],
  },
  {
    id: 'B5-022',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'En un grupo de veinte adultos conviven personas que corren maratones y personas que empiezan de cero. Con una sola tarea común, la mitad se aburre y la otra mitad no llega. El entrenador dispone de material suficiente y de una hora por sesión.',
    enunciado: '¿Qué estilo responde mejor a este problema?',
    opciones: [
      'Enseñanza modular, con módulos de contenido y criterios de superación por nivel',
      'Mando directo, para que todo el grupo trabaje unido y nadie quede descolgado',
      'Microenseñanza, con los maratonianos enseñando al grupo de principiantes',
      'Resolución de problemas, para que cada uno encuentre su propio nivel de exigencia',
    ],
    correcta: 0,
    explicacion:
      'El problema descrito es de heterogeneidad de nivel, y ese es exactamente el que resuelven los estilos de organización: la enseñanza modular da a cada deportista el itinerario que le corresponde con criterios claros de superación. El distractor más tentador es la microenseñanza, porque aprovecha a los avanzados; convierte a los maratonianos en monitores y deja de entrenarlos, que no era el objetivo. Dato para recordar: ajusta el itinerario a la persona, no la persona al itinerario.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.4 — Estilos de organización',
    etiquetas: ['enseñanza modular', 'heterogeneidad', 'estilos de organización', 'aplicación'],
  },
  {
    id: 'B5-023',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un entrenador aplica enseñanza recíproca, pero acaba corrigiendo él mismo a los ejecutantes cada vez que ve un fallo. ¿Qué corresponde ajustar?',
    opciones: [
      'Dirigir su intervención al observador, para que sea este quien traslade la corrección',
      'Retirar la ficha de criterios, que está limitando lo que el observador es capaz de ver',
      'Cambiar a grupos reducidos, repartiendo más roles entre los miembros de cada grupo',
      'Volver al mando directo, ya que el grupo todavía no está preparado para observar',
    ],
    correcta: 0,
    explicacion:
      'En la enseñanza recíproca el entrenador corrige al observador y no al ejecutante: cuando corrige directamente, vacía el estilo y lo convierte en mando directo con público. El ajuste es redirigir la intervención, no cambiar de estilo. El distractor más tentador es el último, porque describe una retirada razonable; el grupo no está fallando, lo está haciendo el entrenador. Dato para recordar: en este estilo se enseña a corregir, no se corrige.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['enseñanza recíproca', 'feedback', 'estilos de participación', 'aplicación'],
  },
  {
    id: 'B5-024',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Ordene los estilos según cuántas decisiones cede el entrenador, de menos a más.',
    elementos: [
      'Mando directo: el entrenador decide todo, incluida la señal de ejecución',
      'Asignación de tareas: el deportista gestiona su ritmo y sus repeticiones',
      'Enseñanza recíproca: un compañero asume la corrección de la ejecución',
      'Microenseñanza: un alumno-monitor asume la enseñanza de su subgrupo',
    ],
    ordenCorrecto: [0, 1, 2, 3],
    explicacion:
      'La escala de cesión ordena el módulo entero: primero se cede el ritmo, después la evaluación y por último la enseñanza. El error más frecuente es colocar la asignación de tareas por encima de la recíproca porque el deportista parece más libre; gestionar el propio ritmo es una cesión menor que hacerse cargo de corregir a otro. Dato para recordar: la pregunta no es cuánta libertad hay, sino qué decisión concreta cambió de manos.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.2 — Estilos de participación',
    etiquetas: ['estilos de enseñanza', 'autonomía', 'secuencia'],
  },
  {
    id: 'B5-025',
    modulo: 'b5-estilos-ensenanza',
    bloque: 'B',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado: 'Ordene los pasos de una intervención con descubrimiento guiado.',
    elementos: [
      'El entrenador decide de antemano la respuesta a la que quiere llegar',
      'Plantea una situación de juego en la que esa respuesta resulte pertinente',
      'Formula la primera pregunta, que acota el problema sin resolverlo',
      'Encadena nuevas preguntas y reorienta cuando la búsqueda se desvía',
      'El deportista enuncia la solución y la aplica en la misma situación',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'El descubrimiento guiado empieza antes de la sesión: el entrenador ya sabe a qué respuesta quiere llegar, y esa decisión previa es lo que le permite encadenar preguntas con sentido. El error más habitual es improvisar la secuencia sobre la marcha, con lo que las preguntas dejan de conducir a ninguna parte y el estilo se convierte en resolución de problemas sin quererlo. Dato para recordar: guiado significa que hay destino, y el destino se elige antes.',
    referencia: 'Cartilla 2, Tema 5, Subtema 5.3 — Estilos de implicación cognitiva',
    etiquetas: ['descubrimiento guiado', 'implicación cognitiva', 'secuencia'],
  },
];
