// content/banco/c3-respiratorio-vo2.ts
// C3 · Sistema respiratorio y VO₂máx. 28 ítems (bloque C, ADR-006).
//
// Reparto verificado contra verificarCuotas(cuotasDelBloque('C')):
//   Nivel      → 12 recuerdo (43 %) · 9 comprensión (32 %) · 7 aplicación (25 %)
//   Dificultad → 5 de nivel 1 · 18 de nivel 2 · 5 de nivel 3
//   Tipos      → 14 única · 4 cálculo · 3 múltiple · 3 caso · 2 emparejar
//                · 1 ordenar · 1 V/F
//
// ADR-014 — lo verificado que este módulo enseña:
//   · Test de Cooper: VO₂máx = (metros − 504,9) / 44,73. Las dos constantes van
//     juntas y la distancia entra EN METROS; en kilómetros el resultado sale
//     negativo.
//   · Course Navette: 20 m entre líneas, arranca en 8,5 km/h y sube 0,5 km/h
//     por palier de 1 min → velocidad = 8,5 + 0,5 × (palier − 1).
//   · La FCmáx no cambia con el entrenamiento; lo que sube es el VO₂máx por la
//     vía del gasto cardíaco máximo y de la extracción periférica.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 28 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'C3-001',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿A cuánto equivale 1 MET?',
    opciones: [
      '3,5 ml de O₂ por kilogramo de peso y por minuto',
      '5 ml de O₂ por cada 100 ml de sangre que atraviesa el tejido',
      '3,5 litros de O₂ por minuto en un adulto de tamaño medio',
      '1 litro de O₂ consumido por minuto durante el reposo absoluto',
    ],
    correcta: 0,
    explicacion:
      'Un MET equivale a 3,5 ml de oxígeno por kilogramo de peso y por minuto, que es aproximadamente el consumo en reposo. El distractor más tentador son los 5 ml por 100 ml de sangre, que es la diferencia arteriovenosa en reposo: los dos valores se estudian en el mismo tema y los dos hablan de oxígeno, pero uno mide consumo por unidad de peso y el otro extracción por unidad de sangre. Dato para recordar: el MET expresa la intensidad de una actividad como múltiplo del reposo.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['MET', 'VO₂', 'unidades'],
  },
  {
    id: 'C3-002',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se calcula el consumo de oxígeno según la ecuación de Fick?',
    opciones: [
      'VO₂ = gasto cardíaco × diferencia arteriovenosa',
      'VO₂ = frecuencia cardíaca × volumen sistólico del ventrículo izquierdo',
      'VO₂ = ventilación por minuto × frecuencia respiratoria del sujeto',
      'VO₂ = gasto cardíaco ÷ diferencia arteriovenosa de oxígeno medida',
    ],
    correcta: 0,
    explicacion:
      'El consumo de oxígeno es el producto de cuánta sangre se mueve por cuánto oxígeno se le extrae: gasto cardíaco por diferencia arteriovenosa. El distractor más tentador es FC × volumen sistólico, que es la fórmula del gasto cardíaco, es decir, uno de los dos factores de esta: se estudian seguidas y se sustituye la una por la otra. Dato para recordar: el gasto cardíaco es el transporte y la diferencia arteriovenosa es la extracción; el VO₂ necesita las dos.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂', 'ecuación de Fick', 'fórmula'],
  },
  {
    id: 'C3-003',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es la diferencia arteriovenosa de oxígeno en reposo?',
    opciones: [
      '5 ml de O₂ por cada 100 ml de sangre',
      '15–17 ml de O₂ por cada 100 ml de sangre en el adulto en reposo',
      '3,5 ml de O₂ por kilogramo de peso corporal y por minuto',
      '35–45 ml de O₂ por kilogramo de peso corporal y por minuto',
    ],
    correcta: 0,
    explicacion:
      'En reposo el tejido extrae unos 5 ml de oxígeno por cada 100 ml de sangre que lo atraviesa: una fracción pequeña de lo que la sangre transporta, porque las necesidades son bajas. El distractor más tentador son los 15–17 ml, que es el valor en ejercicio: la extracción se triplica cuando el músculo trabaja. Dato para recordar: la sangre siempre lleva oxígeno de sobra en reposo, y esa reserva es la que el ejercicio aprovecha.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['diferencia arteriovenosa', 'reposo', 'valores'],
  },
  {
    id: 'C3-004',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es la diferencia arteriovenosa de oxígeno durante el ejercicio intenso?',
    opciones: [
      '15–17 ml de O₂ por cada 100 ml de sangre',
      '5 ml de O₂ por cada 100 ml de sangre, igual que en situación de reposo',
      '30–40 ml de O₂ por cada 100 ml de sangre, según el nivel de entrenamiento',
      '3,5 ml de O₂ por kilogramo de peso, que es el equivalente de un MET',
    ],
    correcta: 0,
    explicacion:
      'Durante el ejercicio intenso la extracción sube a 15–17 ml por cada 100 ml de sangre, aproximadamente el triple que en reposo. El distractor más tentador son los 30–40 ml, que suena a la progresión lógica de un deportista muy entrenado, pero excede el contenido total de oxígeno que la sangre puede transportar: no se puede extraer más de lo que va dentro. Dato para recordar: la extracción se triplica, y ese es uno de los dos motores del aumento del VO₂ en ejercicio.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['diferencia arteriovenosa', 'ejercicio', 'valores'],
  },
  {
    id: 'C3-005',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué es el VO₂máx?',
    opciones: [
      'El máximo volumen de oxígeno que el organismo puede captar, transportar y utilizar por unidad de tiempo',
      'El volumen máximo de aire que los pulmones consiguen movilizar en una sola inspiración forzada',
      'La cantidad de oxígeno que queda en la sangre venosa tras atravesar el músculo en esfuerzo',
      'El máximo volumen de aire que se ventila por minuto durante una prueba de esfuerzo máxima',
    ],
    correcta: 0,
    explicacion:
      'El VO₂máx incluye los tres pasos: captar el oxígeno en el pulmón, transportarlo con la sangre y utilizarlo en la mitocondria. El distractor más tentador es el de la ventilación máxima por minuto, porque también es un techo respiratorio medible en la misma prueba: la diferencia es que ventilar aire no es lo mismo que consumir oxígeno, y en una persona sana la ventilación no es lo que pone el límite. Dato para recordar: el VO₂máx mide consumo, no respiración.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'definición', 'consumo'],
  },
  {
    id: 'C3-006',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      '¿Cuál es el rango orientativo de VO₂máx en hombres sedentarios de entre 20 y 40 años?',
    opciones: [
      '35–45 ml/kg/min',
      '30–40 ml/kg/min, que es el rango de las mujeres sedentarias de esa edad',
      '60–70 ml/kg/min, propio del deportista de resistencia de alto rendimiento',
      '15–20 ml/kg/min, que corresponde a una situación de reposo absoluto',
    ],
    correcta: 0,
    explicacion:
      'Un hombre sedentario de 20 a 40 años se mueve entre 35 y 45 ml/kg/min. El distractor más tentador son los 30–40, que es el rango de las mujeres sedentarias de la misma edad: los dos baremos se presentan en la misma tabla y se solapan en su parte central, así que se cruzan con facilidad. Dato para recordar: los valores femeninos van unos cinco puntos por debajo de los masculinos a igualdad de edad y nivel de actividad.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'baremos', 'valores'],
  },
  {
    id: 'C3-007',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuáles son los tres procesos que permiten que el oxígeno llegue a la mitocondria?',
    opciones: [
      'Ventilación pulmonar, difusión alveolo-capilar y transporte con utilización tisular',
      'Inspiración, espiración y apnea voluntaria durante el esfuerzo de alta intensidad',
      'Ventilación pulmonar, glucólisis anaeróbica y oxidación completa de los sustratos',
      'Difusión alveolo-capilar, filtración renal y transporte por el sistema linfático',
    ],
    correcta: 0,
    explicacion:
      'La cadena tiene tres eslabones: mover el aire hasta el alvéolo, pasar el oxígeno del alvéolo a la sangre y llevarlo hasta el tejido donde se consume. El distractor más tentador es el de inspiración y espiración, porque describe correctamente la mecánica de la ventilación: el problema es que esos son los dos tiempos de un solo proceso, no los tres procesos completos. Dato para recordar: ventilar, difundir y transportar. Si falla cualquiera de los tres, el oxígeno no llega.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.5 — Ventilación y mecánica respiratoria',
    etiquetas: ['ventilación', 'difusión', 'procesos'],
  },
  {
    id: 'C3-008',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Dónde ocurre el intercambio de gases entre el aire y la sangre?',
    opciones: [
      'En la membrana alveolo-capilar',
      'En los bronquios principales, justo antes de la entrada a cada pulmón',
      'En la tráquea, mientras el aire desciende hacia el árbol bronquial',
      'En las cavidades del corazón derecho, antes de salir hacia el pulmón',
    ],
    correcta: 0,
    explicacion:
      'El intercambio ocurre en la membrana alveolo-capilar, donde la pared del alvéolo y la del capilar quedan separadas por una distancia mínima que el oxígeno atraviesa por difusión. Los distractores nombran estructuras reales de la vía aérea, pero todas ellas son conducción: llevan el aire, no lo intercambian. Dato para recordar: la vía aérea transporta y el alvéolo intercambia, y por eso el volumen de las vías se llama espacio muerto.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.5 — Ventilación y mecánica respiratoria',
    etiquetas: ['alvéolo', 'difusión', 'anatomía'],
  },
  {
    id: 'C3-009',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada proceso respiratorio con lo que hace.',
    izquierda: ['Ventilación pulmonar', 'Difusión', 'Transporte', 'Utilización tisular'],
    derecha: [
      'Mueve el aire entre la atmósfera y el alvéolo',
      'Pasa el oxígeno del alvéolo a la sangre del capilar',
      'Lleva el oxígeno hasta el tejido unido a la hemoglobina',
      'Consume el oxígeno en la mitocondria de la fibra',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'La secuencia es mover, pasar, llevar y consumir. El par que más se falla es el de difusión con transporte: se asigna a la difusión el papel de llevar el oxígeno hasta el músculo, cuando la difusión solo cubre el salto del alvéolo al capilar y quien recorre la distancia es la hemoglobina. Dato para recordar: la difusión es un paso de milímetros y el transporte es un viaje de metros.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.5 — Ventilación y mecánica respiratoria',
    etiquetas: ['procesos respiratorios', 'clasificación', 'difusión'],
  },
  {
    id: 'C3-010',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada volumen pulmonar con su definición.',
    izquierda: [
      'Volumen corriente',
      'Volumen de reserva inspiratorio',
      'Volumen de reserva espiratorio',
      'Volumen residual',
    ],
    derecha: [
      'El aire que se moviliza en una respiración tranquila',
      'El aire extra que se puede inspirar tras una inspiración normal',
      'El aire extra que se puede espirar tras una espiración normal',
      'El aire que queda en el pulmón tras una espiración forzada',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los tres primeros son volúmenes movilizables y el residual no lo es: por mucho que se fuerce la espiración, siempre queda aire dentro, y eso impide que el pulmón se colapse. El par que más se falla es el residual con el de reserva espiratorio, porque los dos aparecen al final de la espiración: la diferencia es que uno se puede expulsar y el otro no. Dato para recordar: el volumen residual no se puede medir con un espirómetro corriente, precisamente porque nunca sale.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.5 — Ventilación y mecánica respiratoria',
    etiquetas: ['volúmenes pulmonares', 'espirometría', 'clasificación'],
  },
  {
    id: 'C3-011',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre el MET.',
    opciones: [
      'Equivale a 3,5 ml de O₂ por kilogramo y por minuto',
      'Expresa la intensidad de una actividad como múltiplo del consumo en reposo',
      'Es una unidad de potencia mecánica equivalente a un vatio por kilogramo',
      'Su valor cambia con la edad y el sexo de la persona que realiza la actividad',
      'Se emplea para medir la ventilación pulmonar en litros por minuto',
    ],
    correctas: [0, 1],
    explicacion:
      'El MET vale 3,5 ml/kg/min y sirve para expresar la intensidad como múltiplo del reposo: una actividad de 8 MET cuesta ocho veces el gasto basal. El distractor más tentador es el de que su valor cambia con la edad y el sexo, porque los baremos de VO₂máx sí lo hacen: el MET es una constante convenida, y lo que varía es cuántos MET puede sostener cada persona. Dato para recordar: el MET es la regla, no lo medido.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['MET', 'intensidad', 'unidades'],
  },
  {
    id: 'C3-012',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'El VO₂máx relativo se expresa en litros de oxígeno por minuto.',
    correcta: false,
    explicacion:
      'Falso. El VO₂máx relativo se expresa en mililitros por kilogramo de peso y por minuto, porque está dividido entre la masa corporal: eso es lo que significa relativo. En litros por minuto se expresa el VO₂máx absoluto, que no descuenta el peso. La confusión importa en la práctica: dos deportistas pueden tener el mismo valor absoluto y rendir muy distinto en carrera si pesan cosas distintas. Dato para recordar: relativo lleva kilogramos en el denominador.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'unidades', 'relativo'],
  },
  {
    id: 'C3-013',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Por qué el VO₂máx se expresa habitualmente en ml/kg/min y no en litros por minuto?',
    opciones: [
      'Porque dividir entre el peso permite comparar a deportistas de tamaños distintos en actividades donde hay que desplazar el propio cuerpo',
      'Porque el valor absoluto en litros por minuto no se puede medir con la instrumentación habitual',
      'Porque el consumo de oxígeno solo tiene sentido fisiológico cuando se relativiza por unidad de masa',
      'Porque las tablas de baremos internacionales únicamente recogen valores relativos al peso',
    ],
    correcta: 0,
    explicacion:
      'En carrera o en cualquier deporte donde se transporta el propio cuerpo, lo que rinde no es el oxígeno total sino el oxígeno por kilo: un deportista de 90 kg con 4,5 L/min y otro de 60 kg con 3,3 L/min tienen 50 y 55 ml/kg/min, y el segundo corre mejor pese a consumir menos en términos absolutos. El distractor más tentador dice que el absoluto no se puede medir, y es al revés: es lo que mide directamente el analizador. Dato para recordar: en remo o natación el absoluto pesa más de lo que parece.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'relativo', 'absoluto'],
  },
  {
    id: 'C3-014',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Según la ecuación de Fick, ¿por qué el VO₂ aumenta tanto al pasar del reposo al ejercicio máximo?',
    opciones: [
      'Porque suben sus dos factores a la vez: el gasto cardíaco y la extracción de oxígeno',
      'Porque el gasto cardíaco se multiplica mientras la extracción de oxígeno se mantiene fija',
      'Porque la extracción de oxígeno se triplica mientras el gasto cardíaco no llega a cambiar',
      'Porque aumenta la frecuencia respiratoria y con ella la cantidad de aire que entra al pulmón',
    ],
    correcta: 0,
    explicacion:
      'El VO₂ es un producto y los dos factores suben: el gasto cardíaco puede pasar de 5 a 25 L/min y la extracción de 5 a unos 16 ml por 100 ml. Al multiplicarse, el consumo se dispara. Los dos primeros distractores dejan uno de los factores quieto, que es el error de entender la ecuación como una suma de aportes independientes. Dato para recordar: se multiplican, y por eso el VO₂ puede crecer más de quince veces sobre el valor de reposo.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['ecuación de Fick', 'VO₂', 'ejercicio'],
  },
  {
    id: 'C3-015',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Por qué aumenta la diferencia arteriovenosa de oxígeno durante el ejercicio?',
    opciones: [
      'Porque el músculo activo extrae una fracción mucho mayor del oxígeno que le llega, y la sangre venosa vuelve más pobre',
      'Porque la sangre arterial llega al músculo cargada con más oxígeno del que transportaba en reposo',
      'Porque el número de glóbulos rojos aumenta de forma inmediata al comenzar el esfuerzo',
      'Porque la frecuencia respiratoria eleva la saturación arterial muy por encima de su valor de reposo',
    ],
    correcta: 0,
    explicacion:
      'La diferencia crece por el lado venoso: el músculo que trabaja consume mucho más y devuelve la sangre casi vacía de oxígeno. El distractor más tentador apunta al lado arterial, y es justo lo que no cambia: en una persona sana la sangre arterial ya sale del pulmón prácticamente saturada en reposo, así que no queda margen para cargar más. Dato para recordar: en ejercicio no entra más oxígeno en la sangre, se saca más de ella.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['diferencia arteriovenosa', 'ejercicio', 'extracción'],
  },
  {
    id: 'C3-016',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Cómo se estima el VO₂máx a partir del test de Cooper?',
    opciones: [
      'VO₂máx = (metros recorridos en 12 minutos − 504,9) / 44,73',
      'VO₂máx = (kilómetros recorridos en 12 minutos − 504,9) / 44,73',
      'VO₂máx = (metros recorridos en 6 minutos − 504,9) / 44,73',
      'VO₂máx = (metros recorridos en 12 minutos + 504,9) / 44,73',
    ],
    correcta: 0,
    explicacion:
      'El test de Cooper mide la distancia recorrida en 12 minutos y la convierte con esa fórmula, en la que las dos constantes van juntas y la distancia entra en metros. El distractor más tentador es el de los kilómetros, porque es la unidad en la que se suele hablar de la distancia: con 2,6 en lugar de 2600 el numerador se vuelve negativo y el resultado también, lo que delata el error si se comprueba. Dato para recordar: 12 minutos, metros, y restar antes de dividir.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['test de Cooper', 'VO₂máx', 'fórmula'],
  },
  {
    id: 'C3-017',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Cómo progresa la velocidad en el test de Course Navette?',
    opciones: [
      'Arranca en 8,5 km/h y sube 0,5 km/h en cada palier de un minuto',
      'Arranca en 8,5 km/h y sube 1 km/h en cada palier de un minuto de duración',
      'Arranca en 10 km/h y sube 0,5 km/h en cada palier de dos minutos de duración',
      'Arranca en 8,5 km/h y sube 0,5 km/h cada vez que se completa un tramo de 20 metros',
    ],
    correcta: 0,
    explicacion:
      'La Course Navette se corre entre dos líneas separadas 20 metros, arranca a 8,5 km/h y sube medio kilómetro por hora en cada palier de un minuto, de modo que la velocidad es 8,5 + 0,5 × (palier − 1). El distractor más tentador es el incremento de 1 km/h: parece un número más limpio y acortaría el test a la mitad de paliers, con lo que un mismo deportista aparecería en un nivel muy inferior. Dato para recordar: 20 metros, 8,5 de salida, medio en medio.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['Course Navette', 'test', 'protocolo'],
  },
  {
    id: 'C3-018',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre la ventilación durante el ejercicio.',
    opciones: [
      'La ventilación por minuto aumenta por la frecuencia y por el volumen corriente',
      'Al inicio del esfuerzo el volumen corriente sube antes que la frecuencia respiratoria',
      'En una persona sana la ventilación no es el factor que limita el VO₂máx',
      'La sangre arterial se dessatura de forma marcada en cuanto empieza el ejercicio moderado',
      'El volumen residual se expulsa por completo cuando la espiración es forzada',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'La ventilación crece por sus dos componentes, el volumen corriente responde primero, y en el sujeto sano el techo lo pone el transporte de oxígeno y no el pulmón. El distractor más tentador es el de la desaturación, porque parece coherente con el jadeo: en una persona sana la saturación arterial se mantiene casi intacta incluso en esfuerzo intenso. Y el residual, por definición, no sale nunca. Dato para recordar: el pulmón casi nunca es el cuello de botella.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.5 — Ventilación y mecánica respiratoria',
    etiquetas: ['ventilación', 'ejercicio', 'limitación'],
  },
  {
    id: 'C3-019',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene el recorrido del oxígeno desde el aire ambiente hasta la mitocondria.',
    elementos: [
      'Entra por las vías aéreas y llega al alvéolo',
      'Atraviesa por difusión la membrana alveolo-capilar',
      'Se une a la hemoglobina del glóbulo rojo',
      'Llega al capilar del músculo activo y se libera al tejido',
      'Se consume en la mitocondria de la fibra muscular',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La secuencia recorre los tres procesos en orden: ventilación, difusión y transporte con utilización final. El error más frecuente es colocar la unión a la hemoglobina antes de la difusión, porque se piensa en la hemoglobina como quien va a buscar el oxígeno: la hemoglobina está dentro del capilar y el oxígeno tiene que atravesar la membrana antes de encontrarla. Dato para recordar: primero cruza, después se engancha.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.5 — Ventilación y mecánica respiratoria',
    etiquetas: ['oxígeno', 'secuencia', 'transporte'],
  },
  {
    id: 'C3-020',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'En una persona sana, ¿qué factor limita principalmente el VO₂máx?',
    opciones: [
      'El transporte de oxígeno, es decir, el gasto cardíaco máximo alcanzable',
      'La capacidad del pulmón para ventilar aire suficiente durante el esfuerzo',
      'La superficie total disponible para la difusión en la membrana alveolo-capilar',
      'La frecuencia respiratoria máxima que el sujeto es capaz de sostener en la prueba',
    ],
    correcta: 0,
    explicacion:
      'El cuello de botella está en el transporte: cuánta sangre oxigenada puede entregar el corazón por minuto. Los tres distractores señalan al pulmón, que es lo que uno nota cuando jadea, y por eso resultan convincentes: en una persona sana el aparato respiratorio conserva reserva incluso en esfuerzo máximo y la saturación arterial apenas cae. Dato para recordar: se jadea por el pulmón y se limita por el corazón, y por eso el entrenamiento sube el VO₂máx elevando el gasto cardíaco máximo.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'limitación', 'gasto cardíaco'],
  },
  {
    id: 'C3-021',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre el VO₂máx.',
    opciones: [
      'Mejora con el entrenamiento, sobre todo por el aumento del gasto cardíaco máximo',
      'Se puede estimar de forma indirecta con pruebas de campo como Cooper o Course Navette',
      'Es idéntico en valor absoluto y en valor relativo cuando el sujeto pesa más de 70 kg',
      'Desciende de forma inmediata en cuanto el deportista deja de entrenar una sola semana',
      'Coincide numéricamente con la frecuencia cardíaca máxima estimada por la fórmula de Fox',
    ],
    correctas: [0, 1],
    explicacion:
      'El VO₂máx mejora con el entrenamiento, principalmente elevando el gasto cardíaco máximo, y se estima con pruebas de campo cuando no hay laboratorio. El distractor más tentador es el del desentrenamiento en una semana: la pérdida es real pero necesita semanas, y en siete días los cambios son mínimos. El de la coincidencia con la FCmáx mezcla dos magnitudes que ni siquiera comparten unidad. Dato para recordar: Cooper y Course Navette estiman, no miden.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'entrenamiento', 'tests'],
  },
  {
    id: 'C3-022',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Una actividad tiene una intensidad de 10 MET. ¿A cuántos ml/kg/min de consumo de oxígeno equivale?',
    respuesta: 35,
    tolerancia: 0.5,
    unidad: 'ml/kg/min',
    pasos: [
      '1 MET = 3,5 ml de O₂ por kilogramo y por minuto',
      'VO₂ = MET × 3,5',
      'VO₂ = 10 × 3,5',
      'VO₂ = 35 ml/kg/min',
    ],
    explicacion:
      'La conversión de MET a ml/kg/min es una multiplicación por 3,5, y la inversa es una división por el mismo número. El error más frecuente es dividir cuando toca multiplicar, lo que daría 2,86 ml/kg/min: un valor inferior al del reposo para una actividad diez veces más intensa, incoherencia que debería saltar a la vista. Dato para recordar: si vas de MET a mililitros, el número crece; si vas al revés, se reduce.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['MET', 'conversión', 'cálculo'],
  },
  {
    id: 'C3-023',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un deportista tiene un VO₂máx de 42 ml/kg/min. ¿A cuántos MET equivale ese valor? Responda con un decimal.',
    respuesta: 12,
    tolerancia: 0.3,
    unidad: 'MET',
    pasos: [
      '1 MET = 3,5 ml de O₂ por kilogramo y por minuto',
      'MET = VO₂ ÷ 3,5',
      'MET = 42 ÷ 3,5',
      'MET = 12 MET',
    ],
    explicacion:
      'Para pasar de ml/kg/min a MET se divide entre 3,5, y este deportista sostiene 12 veces su consumo de reposo. El error más frecuente es multiplicar, que daría 147 MET: un valor imposible, porque ni los mejores atletas de resistencia del mundo pasan de unos 25 MET. Dato para recordar: expresar el VO₂máx en MET ayuda a explicárselo al deportista, porque «doce veces lo que gastas sentado» se entiende mejor que un número en mililitros.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['MET', 'VO₂máx', 'cálculo'],
  },
  {
    id: 'C3-024',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Durante un esfuerzo máximo, un deportista alcanza un gasto cardíaco de 20 L/min con una diferencia arteriovenosa de 15 ml de O₂ por cada 100 ml de sangre. Calcule su VO₂ en litros por minuto.',
    respuesta: 3,
    tolerancia: 0.1,
    unidad: 'L/min',
    pasos: [
      'Ecuación de Fick: VO₂ = gasto cardíaco × diferencia arteriovenosa',
      'Expresar la diferencia arteriovenosa como fracción: 15 ml / 100 ml = 0,15',
      'VO₂ = 20 L/min × 0,15',
      'VO₂ = 3 L/min',
    ],
    explicacion:
      'El paso que decide el ítem es la conversión de la diferencia arteriovenosa: viene dada por cada 100 ml de sangre y hay que expresarla como fracción antes de multiplicar. Sin ese paso se responde 300, que es el resultado en unidades mezcladas. Un VO₂ de 3 L/min es coherente con un adulto entrenado de tamaño medio. Dato para recordar: si el enunciado da una cifra por cada 100 ml, divídela entre 100 antes de usarla.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['ecuación de Fick', 'VO₂', 'cálculo'],
  },
  {
    id: 'C3-025',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un deportista recorre 2600 metros en el test de Cooper. Estime su VO₂máx con un decimal.',
    respuesta: 46.8,
    tolerancia: 0.6,
    unidad: 'ml/kg/min',
    pasos: [
      'Test de Cooper: VO₂máx = (metros − 504,9) / 44,73',
      'Numerador = 2600 − 504,9 = 2095,1',
      'VO₂máx = 2095,1 / 44,73',
      'VO₂máx = 46,84 ≈ 46,8 ml/kg/min',
    ],
    explicacion:
      'La distancia entra en metros y hay que restar antes de dividir: 46,8 ml/kg/min sitúa a este deportista por encima del rango sedentario. El error más frecuente es meter la distancia en kilómetros, que da un numerador negativo y un resultado negativo, imposible para un consumo de oxígeno. El segundo error es dividir antes de restar. Dato para recordar: las dos constantes van juntas y en ese orden, y el resultado tiene que caer entre 20 y 80.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['test de Cooper', 'VO₂máx', 'cálculo'],
  },
  {
    id: 'C3-026',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Una mujer de 34 años, sedentaria desde hace años, hace el test de Cooper y obtiene un VO₂máx estimado de 33 ml/kg/min. Llega convencida de que ese resultado la descalifica para empezar a correr.',
    enunciado: '¿Qué corresponde interpretar y comunicarle?',
    opciones: [
      'Que su valor está dentro del rango esperable para una mujer sedentaria de su edad y sirve como punto de partida medido',
      'Que su valor está muy por encima de lo normal y puede empezar directamente con trabajo interválico intenso',
      'Que su valor es incompatible con la actividad física y conviene descartar cualquier programa de carrera',
      'Que el test no aporta información válida en personas sedentarias y hay que repetirlo en laboratorio',
    ],
    correcta: 0,
    explicacion:
      'El rango de mujeres sedentarias de 20 a 40 años es de 30 a 40 ml/kg/min, así que 33 es un valor esperable y perfectamente compatible con empezar a entrenar. El distractor más tentador es el de repetir en laboratorio: es cierto que Cooper estima y la ergoespirometría mide, pero eso no invalida la estimación ni justifica retrasar el inicio. Dato para recordar: el primer test no es un veredicto, es la línea de base contra la que se medirán los progresos.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'baremos', 'interpretación'],
  },
  {
    id: 'C3-027',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Dos deportistas hacen una ergoespirometría. El primero pesa 90 kg y alcanza 4,5 L/min de consumo máximo de oxígeno; el segundo pesa 60 kg y alcanza 3,3 L/min. Los dos compiten en media maratón.',
    enunciado: '¿Quién tiene mejor pronóstico en esa prueba y por qué?',
    opciones: [
      'El segundo, porque su valor relativo es de 55 ml/kg/min frente a los 50 del primero',
      'El primero, porque su consumo absoluto de 4,5 L/min es claramente el más alto de los dos',
      'Los dos por igual, porque el consumo de oxígeno absoluto y el relativo miden lo mismo',
      'No se puede saber, porque el VO₂máx no guarda ninguna relación con el rendimiento en carrera',
    ],
    correcta: 0,
    explicacion:
      '4500 ÷ 90 = 50 ml/kg/min y 3300 ÷ 60 = 55 ml/kg/min: en una prueba donde hay que desplazar el propio cuerpo, lo que manda es el valor relativo, y el segundo va por delante pese a consumir menos oxígeno en términos absolutos. El distractor más tentador es el primero, porque 4,5 L/min es un número mayor y en deportes sin transporte del peso corporal, como el remo, sí sería la referencia. Dato para recordar: si cargas con tu peso, divide entre tu peso.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['VO₂máx', 'relativo', 'absoluto', 'rendimiento'],
  },
  {
    id: 'C3-028',
    modulo: 'c3-respiratorio-vo2',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un entrenador aplica el test de Course Navette a un grupo de jugadores. Uno de ellos completa el palier 9 y abandona al principio del 10. El entrenador quiere anotar a qué velocidad iba corriendo cuando se retiró.',
    enunciado: '¿Qué velocidad corresponde al palier 9?',
    opciones: [
      '12,5 km/h, aplicando velocidad = 8,5 + 0,5 × (palier − 1)',
      '13 km/h, porque al palier inicial le corresponden ya los primeros 0,5 km/h',
      '17,5 km/h, aplicando un incremento de 1 km/h por cada palier completado',
      '9 km/h, porque cada palier añade 0,5 km/h sobre la velocidad del anterior',
    ],
    correcta: 0,
    explicacion:
      'La velocidad del palier 9 es 8,5 + 0,5 × 8 = 12,5 km/h: el primer palier ya se corre a 8,5, así que los incrementos se cuentan desde el segundo. El distractor más tentador son los 13 km/h, que salen de multiplicar por el número de palier en lugar de por los palieres transcurridos, y es el error de desfase clásico de este test. Dato para recordar: en el palier 1 la velocidad es la de salida, y el paréntesis de la fórmula está justamente para eso.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.7 — VO₂máx, MET y baremos',
    etiquetas: ['Course Navette', 'test', 'cálculo', 'protocolo'],
  },
];
