// content/banco/c4-nervioso-digestivo-osteomuscular.ts
// C4 · Sistemas nervioso, digestivo y osteomuscular. 28 ítems (bloque C, ADR-006).
//
// Reparto verificado contra verificarCuotas(cuotasDelBloque('C')):
//   Nivel      → 12 recuerdo (43 %) · 9 comprensión (32 %) · 7 aplicación (25 %)
//   Dificultad → 4 de nivel 1 · 18 de nivel 2 · 6 de nivel 3
//   Tipos      → 15 única · 3 múltiple · 3 caso · 2 emparejar · 2 ordenar
//                · 2 cálculo · 1 V/F
//
// ADR-014 — lo verificado que este módulo enseña:
//   · La célula muscular es la fibra muscular o miocito; el sarcómero es su
//     unidad contráctil, no una célula.
//   · El ATP se necesita para SOLTAR el puente cruzado, no para formarlo. Lo
//     demuestra el rigor mortis: sin ATP el puente queda enganchado.
//   · El dolor muscular tardío es daño mecánico de la fibra, sobre todo por
//     trabajo excéntrico. No lo causa el lactato, que se retira en horas.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 28 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'C4-001',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué detecta el huso muscular?',
    opciones: [
      'El estiramiento del músculo y la velocidad a la que se produce',
      'La tensión que soporta el tendón cuando el músculo se contrae con fuerza',
      'La presión profunda y las vibraciones rápidas que llegan a la articulación',
      'La posición articular mantenida durante un estiramiento sostenido y lento',
    ],
    correcta: 0,
    explicacion:
      'El huso muscular está dentro del vientre muscular y detecta cuánto y cuán rápido se estira el músculo: por eso dispara el reflejo miotático, que responde con una contracción protectora. El distractor más tentador es la tensión del tendón, que corresponde al órgano tendinoso de Golgi: los dos son propioceptores del mismo aparato y se estudian juntos. Dato para recordar: el huso vigila la longitud y el Golgi vigila la fuerza.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['huso muscular', 'propiocepción', 'reflejo miotático'],
  },
  {
    id: 'C4-002',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué detecta el órgano tendinoso de Golgi?',
    opciones: [
      'La tensión que se genera en el tendón',
      'El grado de estiramiento del vientre muscular y su velocidad de cambio',
      'La temperatura del tejido durante el esfuerzo prolongado en calor',
      'La posición relativa de los segmentos corporales en el espacio circundante',
    ],
    correcta: 0,
    explicacion:
      'El órgano tendinoso de Golgi se sitúa en la unión miotendinosa y mide tensión: cuando la fuerza es excesiva dispara el reflejo miotático inverso, que inhibe la contracción para proteger la estructura. El distractor más tentador es el estiramiento, que corresponde al huso muscular: la pareja huso-Golgi es la que más se cruza del módulo. Dato para recordar: el Golgi es un limitador de fuerza y el huso es un detector de longitud.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['órgano tendinoso de Golgi', 'propiocepción', 'tensión'],
  },
  {
    id: 'C4-003',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué detectan los corpúsculos de Pacini?',
    opciones: [
      'La presión profunda y las vibraciones rápidas',
      'La tensión que soporta el tendón durante una contracción máxima voluntaria',
      'El estiramiento del vientre muscular cuando la articulación llega a su tope',
      'La concentración de metabolitos acumulados en el tejido durante el esfuerzo',
    ],
    correcta: 0,
    explicacion:
      'Los corpúsculos de Pacini son receptores de adaptación rápida situados en piel, cápsulas articulares y tejido profundo, y responden a presión y vibración. Los distractores nombran las funciones de los otros dos propioceptores del tema, que es exactamente donde está la confusión: los tres se aprenden en la misma lista. Dato para recordar: Pacini detecta cambios bruscos de presión, y por eso se apaga enseguida cuando la presión se mantiene constante.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['corpúsculos de Pacini', 'propiocepción', 'presión'],
  },
  {
    id: 'C4-004',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué caracteriza a una contracción isotónica concéntrica?',
    opciones: [
      'El músculo se acorta mientras vence la resistencia',
      'El músculo se alarga mientras frena la resistencia que lo supera',
      'El músculo genera tensión sin que su longitud llegue a modificarse',
      'El músculo se acorta y se alarga de forma alternada en el mismo gesto',
    ],
    correcta: 0,
    explicacion:
      'En la concéntrica el músculo gana a la resistencia y se acorta: es la fase de subida en un curl de bíceps. El distractor más tentador es la excéntrica, en la que el músculo también trabaja pero se alarga porque la resistencia gana: las dos son isotónicas y se diferencian solo en el sentido del cambio de longitud. Dato para recordar: concéntrica acorta, excéntrica alarga, isométrica mantiene.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['contracción concéntrica', 'tipos de contracción'],
  },
  {
    id: 'C4-005',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué caracteriza a una contracción isométrica?',
    opciones: [
      'El músculo genera tensión sin cambiar de longitud',
      'El músculo se acorta venciendo una resistencia menor que su fuerza máxima',
      'El músculo se alarga de forma controlada mientras frena una carga elevada',
      'El músculo alterna acortamiento y alargamiento a velocidad constante',
    ],
    correcta: 0,
    explicacion:
      'En la isométrica hay tensión pero no hay movimiento: la longitud del músculo no cambia, como al sostener una plancha o empujar una pared. El distractor más tentador es la excéntrica, porque las dos se perciben como «aguantar»; la diferencia es que en la excéntrica la carga gana terreno y el músculo cede longitud, y en la isométrica el empate es perfecto. Dato para recordar: isométrica significa igual medida, es decir, misma longitud.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['contracción isométrica', 'tipos de contracción'],
  },
  {
    id: 'C4-006',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué caracteriza a las fibras musculares de tipo I?',
    opciones: [
      'Son lentas, oxidativas y muy resistentes a la fatiga',
      'Son rápidas, glucolíticas y capaces de generar mucha potencia en poco tiempo',
      'Son las que predominan en el músculo de un velocista de nivel internacional',
      'Son las que menos mitocondrias y menos capilares tienen de todo el músculo',
    ],
    correcta: 0,
    explicacion:
      'Las fibras tipo I son lentas y oxidativas: muchas mitocondrias, mucha mioglobina, muchos capilares y una resistencia a la fatiga que las hace dominantes en deportes de fondo. El distractor más tentador describe a las tipo II, que es la otra mitad de la clasificación y por eso el par se cruza con facilidad. Dato para recordar: tipo I son rojas, lentas y de fondo; tipo II son pálidas, rápidas y de potencia.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['fibra tipo I', 'clasificación', 'resistencia'],
  },
  {
    id: 'C4-007',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué caracteriza a las fibras musculares de tipo II?',
    opciones: [
      'Son rápidas, generan mucha fuerza y se fatigan pronto',
      'Son lentas, oxidativas y resisten muy bien los esfuerzos de larga duración',
      'Tienen más mitocondrias y más mioglobina que cualquier otro tipo de fibra',
      'Predominan en la musculatura postural que sostiene el tronco todo el día',
    ],
    correcta: 0,
    explicacion:
      'Las tipo II son rápidas y potentes, con predominio glucolítico y baja resistencia a la fatiga: son las del sprint y el salto. Los tres distractores describen a las tipo I, y el de la musculatura postural es el más tentador porque suena a especialización creíble: sostener el tronco todo el día es justamente el trabajo de las fibras resistentes. Dato para recordar: si el rasgo tiene que ver con aguantar, es tipo I; si tiene que ver con explotar, es tipo II.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['fibra tipo II', 'clasificación', 'potencia'],
  },
  {
    id: 'C4-008',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cómo se divide el sistema nervioso?',
    opciones: [
      'En central (encéfalo y médula espinal) y periférico (somático y autónomo)',
      'En somático y autónomo, y este último en encéfalo y en médula espinal',
      'En simpático y parasimpático, y cada uno de ellos en central y periférico',
      'En voluntario e involuntario, según el tipo de músculo al que dé la orden',
    ],
    correcta: 0,
    explicacion:
      'La división mayor es central frente a periférico: el central lo forman encéfalo y médula, y el periférico se subdivide en somático —voluntario— y autónomo, que a su vez es simpático y parasimpático. Los distractores invierten el orden de los niveles, que es el error clásico: colocar el simpático por encima del central o meter el encéfalo dentro del autónomo. Dato para recordar: la jerarquía va central-periférico, después somático-autónomo, y por último simpático-parasimpático.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['sistema nervioso', 'clasificación', 'anatomía'],
  },
  {
    id: 'C4-009',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada receptor con lo que detecta.',
    izquierda: [
      'Huso muscular',
      'Órgano tendinoso de Golgi',
      'Corpúsculos de Pacini',
      'Terminaciones de Ruffini',
    ],
    derecha: [
      'Estiramiento del músculo y velocidad del estiramiento',
      'Tensión generada en el tendón',
      'Presión profunda y vibración',
      'Posición articular y estiramiento sostenido',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es huso con Golgi, porque los dos viven en el mismo músculo y protegen del mismo tipo de lesión desde extremos opuestos: uno reacciona a que el músculo se alargue demasiado rápido y el otro a que la tensión suba demasiado. Pacini y Ruffini se cruzan por la vía contraria, la velocidad de adaptación: Pacini responde a lo brusco y Ruffini a lo sostenido. Dato para recordar: longitud, fuerza, vibración y posición.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['propioceptores', 'clasificación', 'propiocepción'],
  },
  {
    id: 'C4-010',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada estructura del aparato digestivo con su función principal.',
    izquierda: ['Estómago', 'Intestino delgado', 'Intestino grueso', 'Páncreas'],
    derecha: [
      'Digestión química por acción del jugo gástrico',
      'Absorción de la mayor parte de los nutrientes',
      'Absorción de agua y formación de las heces',
      'Vierte enzimas digestivas y regula la glucemia',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es el del estómago con el intestino delgado: se atribuye al estómago la absorción de nutrientes porque es donde uno imagina que «se procesa la comida», cuando su papel es digerir y la absorción ocurre casi entera en el intestino delgado, gracias a las vellosidades que multiplican su superficie. Dato para recordar: el estómago descompone, el delgado absorbe nutrientes y el grueso absorbe agua.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.10 — Sistema digestivo',
    etiquetas: ['sistema digestivo', 'absorción', 'clasificación'],
  },
  {
    id: 'C4-011',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre la unidad motora.',
    opciones: [
      'Está formada por una motoneurona y todas las fibras que inerva',
      'Todas las fibras de una misma unidad motora son del mismo tipo',
      'Está formada por una fibra muscular y todas las motoneuronas que llegan a ella',
      'Las unidades motoras de los músculos que hacen gestos finos son las más grandes',
      'Una unidad motora puede contraer solo una parte de las fibras que la componen',
    ],
    correctas: [0, 1],
    explicacion:
      'La unidad motora es una motoneurona más todas sus fibras, y esas fibras son siempre del mismo tipo, porque la neurona impone su carácter a todas. El distractor más tentador invierte los términos —una fibra con muchas neuronas—, que es imposible: cada fibra recibe una sola motoneurona. Y las unidades de los gestos finos son las más pequeñas, precisamente para poder graduar. Dato para recordar: la unidad motora es todo o nada, no se activa a medias.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['unidad motora', 'motoneurona', 'reclutamiento'],
  },
  {
    id: 'C4-012',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      'El ATP es necesario para que la cabeza de miosina se una a la actina y forme el puente cruzado.',
    correcta: false,
    explicacion:
      'Falso. El ATP hace falta para SOLTAR el puente cruzado, no para formarlo: la unión ocurre en cuanto el calcio deja libres los sitios de la actina. Lo demuestra el rigor mortis, en el que la ausencia de ATP deja los puentes enganchados y el músculo rígido. El ATP también se gasta después, en devolver el calcio al retículo sarcoplásmico. Dato para recordar: sin energía el músculo no se relaja; lo que no puede es soltarse.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['ATP', 'puente cruzado', 'contracción'],
  },
  {
    id: 'C4-013',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué la contracción excéntrica genera más tensión y más daño muscular que la concéntrica?',
    opciones: [
      'Porque el músculo frena una carga que lo supera, con menos fibras activas soportando más tensión cada una',
      'Porque en la fase excéntrica se recluta un número mucho mayor de unidades motoras que en la concéntrica',
      'Porque la acumulación de lactato es mucho más elevada durante el trabajo de frenado que en el de empuje',
      'Porque el músculo trabaja sin recibir ningún aporte de oxígeno mientras dura la fase de alargamiento',
    ],
    correcta: 0,
    explicacion:
      'En la excéntrica el músculo cede ante una carga superior y lo hace reclutando MENOS unidades motoras, así que cada fibra activa soporta más tensión: de ahí la mayor fuerza y el mayor daño estructural. El distractor más tentador dice justo lo contrario, que se reclutan más unidades, porque parece la explicación natural de «aquí se hace más fuerza». Dato para recordar: en excéntrico se puede frenar más peso del que se puede levantar, y esa es la clave del dolor tardío.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['contracción excéntrica', 'daño muscular', 'tensión'],
  },
  {
    id: 'C4-014',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué diferencia al reflejo miotático del reflejo miotático inverso?',
    opciones: [
      'El miotático contrae ante el estiramiento; el inverso relaja ante el exceso de tensión',
      'El miotático relaja ante el estiramiento; el inverso contrae ante el exceso de tensión',
      'El miotático depende del órgano de Golgi y el inverso depende del huso muscular',
      'El miotático solo aparece en reposo y el inverso solo durante el ejercicio intenso',
    ],
    correcta: 0,
    explicacion:
      'El miotático nace en el huso y responde al estiramiento contrayendo; el inverso nace en el órgano de Golgi y responde a la tensión excesiva relajando. El distractor más tentador es el que invierte las respuestas, porque conserva los conceptos correctos y solo cambia qué hace cada uno: es el fallo más frecuente del par. Dato para recordar: el miotático protege de que te estires demasiado y el inverso de que te rompas tirando.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['reflejo miotático', 'órgano tendinoso de Golgi', 'propiocepción'],
  },
  {
    id: 'C4-015',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Qué demuestra el rigor mortis sobre el papel del ATP en la contracción?',
    opciones: [
      'Que el ATP es necesario para soltar el puente cruzado, no para formarlo',
      'Que el ATP es necesario para que la miosina se una a la actina al inicio del ciclo',
      'Que el ATP interviene únicamente en el transporte del calcio hacia el retículo',
      'Que la contracción muscular puede producirse sin ningún gasto de energía previo',
    ],
    correcta: 0,
    explicacion:
      'Sin ATP los puentes cruzados quedan enganchados y el músculo se vuelve rígido: si el ATP hiciera falta para unir, un cuerpo sin ATP quedaría flácido, no rígido. Eso demuestra que la energía se gasta en soltar. El distractor del calcio es tentador porque señala un uso real del ATP —la bomba que lo devuelve al retículo—, pero no explica la rigidez. Dato para recordar: la contracción es espontánea si hay calcio; lo que cuesta energía es dejar de contraerse.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['ATP', 'rigor mortis', 'puente cruzado'],
  },
  {
    id: 'C4-016',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué papel cumple el calcio en la contracción muscular?',
    opciones: [
      'Se une a la troponina y desplaza la tropomiosina, dejando libres los sitios de unión de la actina',
      'Aporta la energía necesaria para que la cabeza de miosina ejecute el golpe de fuerza',
      'Transmite el impulso nervioso desde la motoneurona hasta la placa motora terminal',
      'Une físicamente los filamentos de actina y de miosina para que no se separen',
    ],
    correcta: 0,
    explicacion:
      'El calcio es el interruptor: al unirse a la troponina mueve la tropomiosina y descubre los puntos de la actina donde la miosina puede engancharse. El distractor más tentador le atribuye el aporte de energía, que es tarea del ATP: son las dos moléculas protagonistas del proceso y se intercambian sus papeles con facilidad. Dato para recordar: el calcio abre la puerta y el ATP paga el trabajo.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['calcio', 'troponina', 'contracción'],
  },
  {
    id: 'C4-017',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Según el principio del tamaño, ¿en qué orden se reclutan las unidades motoras al aumentar la exigencia?',
    opciones: [
      'Primero las pequeñas y lentas, y después las grandes y rápidas',
      'Primero las grandes y rápidas, porque son las que más fuerza aportan al gesto',
      'Todas al mismo tiempo, y lo que varía es la frecuencia de descarga de cada una',
      'En orden aleatorio, para repartir la fatiga entre todas las fibras del músculo',
    ],
    correcta: 0,
    explicacion:
      'Las unidades motoras se reclutan de menor a mayor umbral: primero las pequeñas y lentas, y solo cuando la exigencia sube entran las grandes y rápidas. El distractor más tentador es el orden inverso, que parece lógico si se piensa que a más peso hay que empezar por lo más potente. La consecuencia práctica es grande: para reclutar tipo II hay que ir a intensidad alta o a velocidad de ejecución alta. Dato para recordar: no hay atajo, las rápidas entran las últimas.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['principio del tamaño', 'reclutamiento', 'unidad motora'],
  },
  {
    id: 'C4-018',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre los tipos de fibra muscular.',
    opciones: [
      'Las tipo I tienen más mitocondrias y más capilares que las tipo II',
      'Las tipo II alcanzan mayor velocidad de contracción y mayor fuerza',
      'La proporción entre tipos tiene un componente genético importante',
      'Un programa de resistencia convierte todas las fibras tipo II en fibras tipo I',
      'Las fibras tipo I son las que se reclutan en último lugar dentro del gesto',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tipo I están mejor equipadas para oxidar, las tipo II para generar fuerza rápido, y el reparto entre ambas depende en buena medida de la genética. El distractor más tentador es la conversión total: el entrenamiento sí modifica subtipos dentro de las tipo II y cambia sus propiedades metabólicas, pero no transforma masivamente un tipo en otro. Y las tipo I se reclutan primero, no al final. Dato para recordar: el entrenamiento afina lo que hay, no reescribe el mapa.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['fibras musculares', 'genética', 'entrenamiento'],
  },
  {
    id: 'C4-019',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Ordene los siete pasos de la contracción muscular.',
    elementos: [
      'El impulso nervioso llega a la placa motora y se libera acetilcolina',
      'Se despolariza el sarcolema y el impulso viaja por los túbulos T',
      'El retículo sarcoplásmico libera calcio al interior de la fibra',
      'El calcio se une a la troponina y la tropomiosina descubre los sitios de la actina',
      'La cabeza de miosina se une a la actina y forma el puente cruzado',
      'Se produce el golpe de fuerza y los filamentos se deslizan entre sí',
      'Un nuevo ATP suelta el puente y el calcio vuelve al retículo sarcoplásmico',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4, 5, 6],
    explicacion:
      'La secuencia va del nervio al filamento: señal, despolarización, calcio, desbloqueo, unión, deslizamiento y relajación. Los pasos que más se cruzan son el cuarto y el quinto, porque se coloca la unión de la miosina antes de que el calcio despeje el sitio: si la tropomiosina sigue tapando la actina no hay dónde engancharse. Dato para recordar: el calcio siempre va antes que el puente, y el ATP del final es el que suelta, no el que une.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['contracción muscular', 'secuencia', 'calcio'],
  },
  {
    id: 'C4-020',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene el recorrido del alimento por el aparato digestivo.',
    elementos: [
      'Boca: masticación e inicio de la digestión de los almidones',
      'Esófago: transporte del bolo alimenticio por peristaltismo',
      'Estómago: digestión química por acción del jugo gástrico',
      'Intestino delgado: absorción de la mayoría de los nutrientes',
      'Intestino grueso: absorción de agua y formación de las heces',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'El recorrido es boca, esófago, estómago, intestino delgado e intestino grueso. El error más habitual no está en el orden sino en la función: se sitúa la absorción de nutrientes en el estómago, cuando el estómago digiere y quien absorbe es el intestino delgado, gracias a las vellosidades que multiplican su superficie. Dato para recordar: para un deportista, esto explica por qué lo que cuenta no es cuándo comes sino cuándo llega al intestino.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.10 — Sistema digestivo',
    etiquetas: ['sistema digestivo', 'secuencia', 'absorción'],
  },
  {
    id: 'C4-021',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre la propiocepción.',
    opciones: [
      'Informa de la posición y el movimiento del cuerpo sin necesidad de mirarlo',
      'El trabajo de equilibrio e inestabilidad la entrena y mejora su respuesta',
      'Depende exclusivamente de la información que aporta el sentido de la vista',
      'Es una capacidad fija que no se modifica con el entrenamiento específico',
      'Se localiza únicamente en la planta del pie y en la cápsula de la rodilla',
    ],
    correctas: [0, 1],
    explicacion:
      'La propiocepción informa de dónde está el cuerpo sin mirarlo, y es entrenable: el trabajo de equilibrio e inestabilidad mejora la respuesta refleja, que es la base de los programas de prevención de esguinces. El distractor más tentador es el de la vista, porque el equilibrio empeora al cerrar los ojos: eso demuestra que la vista contribuye, no que la propiocepción dependa de ella. Dato para recordar: si no fuera entrenable, la readaptación de tobillo no existiría.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['propiocepción', 'entrenamiento', 'equilibrio'],
  },
  {
    id: 'C4-022',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un músculo tiene 4800 fibras inervadas por 60 motoneuronas. ¿Cuántas fibras corresponden en promedio a cada unidad motora?',
    respuesta: 80,
    tolerancia: 1,
    unidad: 'fibras',
    pasos: [
      'Una unidad motora es una motoneurona con todas las fibras que inerva',
      'Fibras por unidad motora = número de fibras ÷ número de motoneuronas',
      'Fibras por unidad motora = 4800 ÷ 60',
      'Fibras por unidad motora = 80 fibras',
    ],
    explicacion:
      'El cociente da 80 fibras por motoneurona, una unidad motora grande, propia de músculos de fuerza como el cuádriceps. El error más frecuente es invertir la división y responder 0,0125, un valor sin sentido porque una motoneurona no puede inervar una fracción de fibra. Dato para recordar: la relación fibras por motoneurona mide la finura del control — en los músculos del ojo son unidades de menos de diez fibras, y por eso su movimiento es tan preciso.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['unidad motora', 'cálculo', 'reclutamiento'],
  },
  {
    id: 'C4-023',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'En una biopsia del vasto lateral se cuentan 250 fibras, de las cuales 160 son de tipo I. ¿Qué porcentaje de fibras tipo I tiene ese músculo?',
    respuesta: 64,
    tolerancia: 1,
    unidad: '%',
    pasos: [
      'Porcentaje = (fibras tipo I ÷ fibras totales) × 100',
      'Porcentaje = (160 ÷ 250) × 100',
      'Porcentaje = 0,64 × 100',
      'Porcentaje = 64 %',
    ],
    explicacion:
      'Un 64 % de fibras tipo I es un perfil orientado a la resistencia, coherente con un deportista de fondo. El error más frecuente es dividir entre las fibras tipo II en lugar de entre el total, lo que daría 178 %: cualquier porcentaje por encima de 100 delata el error. Dato para recordar: el reparto entre tipos tiene un componente genético importante, así que este dato orienta hacia qué modalidad rendirá mejor, no hacia cuánto ha entrenado.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['fibras musculares', 'cálculo', 'porcentaje'],
  },
  {
    id: 'C4-024',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un grupo hace una excursión de montaña con un descenso largo y pronunciado. Al día siguiente, y sobre todo al segundo día, todos refieren dolor intenso en los cuádriceps, pese a que la subida les pareció mucho más dura durante la marcha.',
    enunciado: '¿Qué explica ese dolor y por qué aparece tras la bajada y no tras la subida?',
    opciones: [
      'El trabajo excéntrico de frenar el cuerpo en el descenso provoca microdaño en la fibra, que duele con retraso',
      'El lactato acumulado durante la subida se deposita en el cuádriceps y produce dolor al día siguiente',
      'La subida agota el glucógeno del cuádriceps y ese vaciado es el que produce el dolor tardío',
      'La deshidratación de la jornada provoca calambres que se manifiestan en las horas posteriores',
    ],
    correcta: 0,
    explicacion:
      'Bajar exige frenar el peso del cuerpo, y frenar es trabajo excéntrico: el cuádriceps se alarga bajo tensión, sufre microdaño estructural y el dolor aparece a las 24–48 horas. El distractor más tentador es el del lactato, la explicación popular más extendida: el lactato se retira en menos de una hora y no puede causar un dolor que empieza al día siguiente. Dato para recordar: el dolor tardío es mecánico, y por eso la bajada duele más que la subida.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['contracción excéntrica', 'dolor tardío', 'daño muscular'],
  },
  {
    id: 'C4-025',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un entrenador enseña la sentadilla y descompone el gesto: el deportista baja controlando durante tres segundos, mantiene la posición abajo durante dos segundos y después sube.',
    enunciado: '¿Qué tipos de contracción del cuádriceps se suceden en ese gesto?',
    opciones: [
      'Excéntrica al bajar, isométrica al mantener y concéntrica al subir',
      'Concéntrica al bajar, isométrica al mantener y excéntrica al subir',
      'Isométrica al bajar, excéntrica al mantener y concéntrica al subir',
      'Excéntrica durante todo el recorrido, porque el peso siempre tira hacia abajo',
    ],
    correcta: 0,
    explicacion:
      'Al bajar el cuádriceps se alarga frenando la carga —excéntrica—, al mantener genera tensión sin cambiar de longitud —isométrica— y al subir se acorta venciendo el peso —concéntrica—. El distractor más tentador invierte las dos isotónicas, y es el error clásico: se asocia concéntrico con el momento en el que uno «se esfuerza más», que en una bajada controlada es precisamente la fase excéntrica. Dato para recordar: mira la longitud del músculo, no la sensación de esfuerzo.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['tipos de contracción', 'sentadilla', 'técnica'],
  },
  {
    id: 'C4-026',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Una joven deportista destaca en pruebas largas y siempre queda descolgada en los sprints finales. Una valoración estima que su musculatura de las piernas tiene un claro predominio de fibras tipo I.',
    enunciado: '¿Qué conclusión razonable puede extraer su entrenador?',
    opciones: [
      'Que su perfil favorece las pruebas de fondo, sin que eso impida entrenar la velocidad para mejorar lo que tenga',
      'Que debe abandonar cualquier trabajo de velocidad porque su perfil lo hace inútil por completo',
      'Que con dos años de trabajo de sprint convertirá sus fibras tipo I en fibras de tipo II',
      'Que el reparto de fibras no aporta ninguna información sobre en qué modalidad puede rendir más',
    ],
    correcta: 0,
    explicacion:
      'El reparto de fibras tiene un componente genético importante y orienta hacia dónde rendirá más, pero no es una sentencia: el trabajo de velocidad sigue mejorando la técnica, la coordinación intermuscular y el reclutamiento. El distractor más tentador es el de la conversión total, que confunde el ajuste real entre subtipos de tipo II con una transformación masiva de un tipo en otro. Dato para recordar: el entrenamiento afina lo que hay, no reescribe el mapa.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.9 — Sistema osteomuscular: contracción y fibras',
    etiquetas: ['fibras musculares', 'genética', 'orientación deportiva'],
  },
  {
    id: 'C4-027',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Un deportista quiere saber en qué punto del aparato digestivo pasan a la sangre los nutrientes de la comida previa a la competición. ¿Qué debe responderle su entrenador?',
    opciones: [
      'En el intestino delgado',
      'En el estómago, que es donde actúan los jugos gástricos sobre el alimento',
      'En el intestino grueso, junto con la absorción del agua que queda',
      'En el esófago, mientras el bolo alimenticio desciende por peristaltismo',
    ],
    correcta: 0,
    explicacion:
      'La absorción de la mayor parte de los nutrientes ocurre en el intestino delgado, gracias a las vellosidades que multiplican su superficie. El distractor más tentador es el estómago, porque es donde se percibe la digestión: el estómago descompone y regula la salida hacia el intestino, pero no absorbe nutrientes. Dato para recordar: por eso una comida rica en grasas retrasa el vaciado gástrico y hace que la energía tarde más en estar disponible.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.10 — Sistema digestivo',
    etiquetas: ['sistema digestivo', 'absorción', 'intestino delgado'],
  },
  {
    id: 'C4-028',
    modulo: 'c4-nervioso-digestivo-osteomuscular',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'En la facilitación neuromuscular propioceptiva se contrae el músculo antes de estirarlo. ¿Qué mecanismo aprovecha esa contracción previa?',
    opciones: [
      'El reflejo miotático inverso del órgano tendinoso de Golgi, que relaja el músculo tras una tensión elevada',
      'El reflejo miotático del huso muscular, que contrae el músculo cuando se estira con rapidez',
      'La activación de los corpúsculos de Pacini, que reducen la percepción de presión en la zona',
      'El aumento de temperatura del tejido, que por sí solo hace más extensible el músculo',
    ],
    correcta: 0,
    explicacion:
      'La contracción previa eleva la tensión en el tendón y dispara el reflejo miotático inverso del órgano de Golgi, que inhibe la contracción y deja el músculo momentáneamente más relajado: en esa ventana el estiramiento gana amplitud. El distractor más tentador es el reflejo miotático del huso, que hace justo lo contrario —contraer— y es el que hay que evitar estirando despacio. Dato para recordar: el Golgi es aliado del estiramiento y el huso es su obstáculo.',
    referencia: 'Cartilla 3, Tema 2, Subtema 2.8 — Sistema nervioso y propiocepción',
    etiquetas: ['FNP', 'órgano tendinoso de Golgi', 'flexibilidad'],
  },
];
