// content/banco/c6-biomecanica.ts
// C6 · Biomecánica. 28 ítems (bloque C, ADR-006).
//
// Reparto verificado contra verificarCuotas(cuotasDelBloque('C')):
//   Nivel      → 12 recuerdo (43 %) · 9 comprensión (32 %) · 7 aplicación (25 %)
//   Dificultad → 5 de nivel 1 · 17 de nivel 2 · 6 de nivel 3
//   Tipos      → 14 única · 4 cálculo · 3 múltiple · 3 caso · 2 emparejar
//                · 1 ordenar · 1 V/F
//
// ADR-014 — lo verificado que este módulo enseña:
//   · P = F × v, así que la potencia máxima cae con CARGAS MEDIAS, no con el
//     1RM: con la carga máxima la velocidad se desploma y el producto con ella.
//     Ya escrito en d3-fuerza y d5-velocidad; aquí se explica su origen físico.
//   · El centro de gravedad en posición anatómica está en torno al 55 % de la
//     estatura, a la altura de la segunda vértebra sacra, y puede quedar FUERA
//     del cuerpo cuando este cambia de forma.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 28 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'C6-001',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿De qué se ocupa la cinemática?',
    opciones: [
      'De describir el movimiento sin atender a las fuerzas que lo producen',
      'De estudiar las fuerzas que originan o modifican el movimiento del cuerpo',
      'De medir la energía que consume el deportista durante el gesto deportivo',
      'De analizar la composición corporal y su influencia sobre el rendimiento',
    ],
    correcta: 0,
    explicacion:
      'La cinemática describe: posición, desplazamiento, velocidad, aceleración y ángulos, sin preguntarse por qué se mueve lo que se mueve. El distractor más tentador es la cinética, que es precisamente la otra mitad de la moneda y estudia las fuerzas: las dos palabras se parecen tanto que el par se cruza constantemente. Dato para recordar: cinemática es el «qué pasa» y cinética es el «por qué pasa».',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['cinemática', 'definición', 'biomecánica'],
  },
  {
    id: 'C6-002',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿De qué se ocupa la cinética?',
    opciones: [
      'De las fuerzas que producen o modifican el movimiento',
      'De describir la trayectoria y la velocidad del gesto sin considerar sus causas',
      'De la clasificación de las articulaciones según sus grados de libertad',
      'De la velocidad de las reacciones químicas dentro de la fibra muscular',
    ],
    correcta: 0,
    explicacion:
      'La cinética estudia las causas del movimiento: fuerzas, momentos, presiones y todo lo que actúa sobre el cuerpo. El distractor más tentador es la descripción de trayectoria y velocidad, que es la definición de cinemática. El de las reacciones químicas juega con el otro sentido de la palabra, el de la química: en biomecánica, cinética es fuerza. Dato para recordar: si aparece la palabra fuerza, es cinética.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['cinética', 'definición', 'biomecánica'],
  },
  {
    id: 'C6-003',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué caracteriza a una palanca de primer género?',
    opciones: [
      'El punto de apoyo está entre la potencia y la resistencia',
      'La resistencia se sitúa entre el punto de apoyo y la potencia aplicada',
      'La potencia se aplica entre el punto de apoyo y la resistencia a vencer',
      'La potencia y la resistencia actúan en el mismo punto de la palanca',
    ],
    correcta: 0,
    explicacion:
      'En la palanca de primer género o interapoyo el apoyo queda en medio, como en una balanza o en el equilibrio de la cabeza sobre la articulación atlanto-occipital. Los dos distractores siguientes describen el segundo y el tercer género, que son las otras dos posiciones posibles de la misma terna. Dato para recordar: el nombre dice qué elemento queda en el centro — interapoyo, interresistencia e interpotencia.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['palancas', 'primer género', 'clasificación'],
  },
  {
    id: 'C6-004',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué gesto corporal es un ejemplo clásico de palanca de segundo género?',
    opciones: [
      'Ponerse de puntillas',
      'La flexión del codo con el bíceps braquial como músculo agonista',
      'La extensión del codo mediante la acción del tríceps sobre el olécranon',
      'El sostén de la cabeza sobre la articulación atlanto-occipital del cuello',
    ],
    correcta: 0,
    explicacion:
      'Al ponerse de puntillas, el apoyo está en los metatarsianos, la resistencia es el peso del cuerpo en el tobillo y la potencia la aplica el tríceps sural en el calcáneo: la resistencia queda en medio, que es la definición de segundo género. Los distractores son ejemplos reales de los otros dos géneros —tercero el bíceps, primero el tríceps y la cabeza—, y por eso se cruzan. Dato para recordar: el segundo género es raro en el cuerpo y este es su ejemplo canónico.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['palancas', 'segundo género', 'ejemplos'],
  },
  {
    id: 'C6-005',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es el género de palanca más abundante en el cuerpo humano?',
    opciones: [
      'El tercer género, con la potencia entre el apoyo y la resistencia',
      'El primer género, con el punto de apoyo situado entre los otros dos elementos',
      'El segundo género, con la resistencia entre el apoyo y la potencia aplicada',
      'Los tres se reparten por igual entre las articulaciones del aparato locomotor',
    ],
    correcta: 0,
    explicacion:
      'El tercer género domina el cuerpo humano porque los músculos se insertan muy cerca de la articulación: la potencia queda entre el apoyo y la resistencia. Eso sacrifica fuerza y gana velocidad y amplitud de movimiento, que es lo que interesa a un aparato pensado para moverse. El distractor más tentador es el primer género, que es el más intuitivo por la imagen de la balanza. Dato para recordar: el cuerpo cambió fuerza por velocidad.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['palancas', 'tercer género', 'clasificación'],
  },
  {
    id: 'C6-006',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Dónde se sitúa el centro de gravedad del cuerpo en posición anatómica?',
    opciones: [
      'En torno al 55 % de la estatura, a la altura de la segunda vértebra sacra',
      'En el centro geométrico del tórax, a la altura del apéndice xifoides del esternón',
      'En el punto medio exacto entre la coronilla y la planta de los pies del sujeto',
      'A la altura del ombligo en todas las personas, sea cual sea su morfología',
    ],
    correcta: 0,
    explicacion:
      'En posición anatómica el centro de gravedad queda alrededor del 55 % de la estatura, a la altura de la segunda vértebra sacra, algo más alto en hombres que en mujeres por la distinta distribución de la masa. El distractor más tentador es el punto medio exacto, que sería el 50 %: el cuerpo no reparte su masa de forma simétrica de arriba abajo, así que el centro queda por encima de la mitad. Dato para recordar: 55 %, no 50 %.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['centro de gravedad', 'posición anatómica', 'valores'],
  },
  {
    id: 'C6-007',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué es la base de sustentación?',
    opciones: [
      'La superficie delimitada por los puntos de apoyo del cuerpo y el espacio entre ellos',
      'La superficie de la planta del pie que contacta directamente con el suelo',
      'La proyección vertical del centro de gravedad sobre la superficie donde se apoya el cuerpo',
      'La distancia que separa el centro de gravedad del suelo en bipedestación',
    ],
    correcta: 0,
    explicacion:
      'La base de sustentación incluye los puntos de apoyo y todo el área comprendida entre ellos: con los pies separados, la base es el rectángulo entero y no solo las dos plantas. El distractor más tentador es el de la superficie de contacto, porque es lo que se ve: lo que estabiliza es el área total encerrada, y por eso separar los pies aumenta la estabilidad sin cambiar la suela que toca el suelo. Dato para recordar: cuenta el hueco, no solo el apoyo.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['base de sustentación', 'equilibrio', 'definición'],
  },
  {
    id: 'C6-008',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué diferencia una cadena cinemática abierta de una cerrada?',
    opciones: [
      'En la abierta el extremo distal se mueve libre; en la cerrada está fijo contra una resistencia',
      'En la abierta se mueve una sola articulación y en la cerrada participan varias a la vez',
      'En la abierta la contracción es concéntrica y en la cerrada es siempre excéntrica',
      'En la abierta se trabaja con el peso corporal y en la cerrada con una carga externa añadida en máquina',
    ],
    correcta: 0,
    explicacion:
      'Lo que define la cadena es qué pasa con el extremo distal: libre en la abierta —extensión de rodilla en máquina— y fijo en la cerrada —sentadilla, con el pie contra el suelo—. El distractor más tentador es el del número de articulaciones, porque efectivamente la cerrada suele involucrar varias: es una consecuencia habitual, no la definición. Dato para recordar: mira el extremo distal, no cuántas articulaciones se mueven.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['cadena cinemática', 'abierta', 'cerrada'],
  },
  {
    id: 'C6-009',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada gesto con el género de palanca que le corresponde.',
    izquierda: [
      'Sostener la cabeza sobre la articulación atlanto-occipital',
      'Elevarse sobre las puntas de los pies',
      'Flexionar el codo con el bíceps braquial',
      'Extender el codo con el tríceps braquial',
    ],
    derecha: [
      'Primer género: el apoyo queda entre la potencia y la resistencia',
      'Segundo género: la resistencia queda entre el apoyo y la potencia',
      'Tercer género: la potencia queda entre el apoyo y la resistencia',
      'Primer género, con el olécranon actuando como punto de apoyo posterior',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es el segundo con el tercero, porque los dos tienen el apoyo en un extremo y solo se distinguen en cuál de los otros dos elementos queda en medio. La pista está en el nombre: inter-apoyo, inter-resistencia e inter-potencia dicen literalmente qué va en el centro. Dato para recordar: en el cuerpo humano manda el tercer género, y el segundo apenas tiene ejemplos.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['palancas', 'clasificación', 'ejemplos'],
  },
  {
    id: 'C6-010',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada ley o magnitud de la mecánica con su enunciado.',
    izquierda: [
      'Primera ley de Newton',
      'Segunda ley de Newton',
      'Tercera ley de Newton',
      'Momento de fuerza',
    ],
    derecha: [
      'Un cuerpo mantiene su estado de reposo o movimiento salvo que actúe una fuerza',
      'La fuerza es igual a la masa por la aceleración que produce',
      'A toda acción le corresponde una reacción igual y de sentido contrario',
      'El producto de una fuerza por su brazo de palanca respecto al eje de giro',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Inercia, F = m × a y acción-reacción, en ese orden. La tercera es la que más rendimiento da en el deporte: el velocista avanza porque empuja el suelo hacia atrás y el suelo lo empuja a él hacia delante, y por eso la fuerza de reacción del suelo es la variable que se mide en las plataformas. Dato para recordar: sin la tercera ley no habría manera de explicar por qué correr sobre arena cansa más.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['leyes de Newton', 'clasificación', 'cinética'],
  },
  {
    id: 'C6-011',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las TRES condiciones que aumentan la estabilidad de un cuerpo.',
    opciones: [
      'Una base de sustentación más amplia',
      'Un centro de gravedad más bajo',
      'Mayor masa corporal del sujeto',
      'Un centro de gravedad situado lo más alto posible',
      'Una proyección del centro de gravedad cercana al borde de la base',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Base amplia, centro bajo y más masa: las tres estabilizan. Los dos distractores son las condiciones contrarias, y el de la proyección cerca del borde es el más tentador porque menciona un concepto correcto —la proyección tiene que caer dentro de la base—: cuanto más cerca del borde, menos margen queda antes de perder el equilibrio. Dato para recordar: por eso un luchador se agacha y separa los pies antes del contacto.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['equilibrio', 'estabilidad', 'centro de gravedad'],
  },
  {
    id: 'C6-012',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'La potencia mecánica máxima se alcanza trabajando con la carga del 1RM.',
    correcta: false,
    explicacion:
      'Falso. La potencia es el producto de la fuerza por la velocidad, y con la carga máxima la velocidad se desploma, así que el producto también: el pico de potencia aparece con cargas medias. Por eso el trabajo explosivo se prescribe por velocidad de ejecución y no por peso, y por eso levantar el 1RM es entrenamiento de fuerza máxima y no de potencia. Dato para recordar: mucha fuerza por poca velocidad da poca potencia, igual que poca fuerza por mucha velocidad.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['potencia', 'fuerza', 'velocidad'],
  },
  {
    id: 'C6-013',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué palanca ofrece siempre ventaja mecánica y por qué?',
    opciones: [
      'La de segundo género, porque el brazo de potencia es siempre mayor que el de resistencia',
      'La de tercer género, porque la potencia se aplica muy cerca del punto de apoyo',
      'La de primer género, porque el apoyo central reparte la carga entre los dos brazos',
      'Todas por igual, porque la ventaja depende de la carga y no de la disposición',
    ],
    correcta: 0,
    explicacion:
      'En el segundo género la resistencia queda entre el apoyo y la potencia, así que el brazo de potencia es forzosamente el mayor y la ventaja mecánica siempre supera la unidad: se vence más resistencia con menos fuerza. El distractor más tentador es el tercer género, que es el más abundante del cuerpo pero tiene ventaja mecánica menor que uno: cambia fuerza por velocidad. Dato para recordar: la ventaja mecánica es el cociente de los brazos.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['palancas', 'ventaja mecánica', 'segundo género'],
  },
  {
    id: 'C6-014',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Qué gana el cuerpo humano al tener la mayoría de sus palancas en tercer género, pese a perder ventaja mecánica?',
    opciones: [
      'Velocidad y amplitud de movimiento en el extremo distal del segmento',
      'Capacidad de sostener cargas máximas con un gasto energético mucho menor',
      'Mayor estabilidad articular frente a las fuerzas externas que recibe',
      'Un consumo de oxígeno más bajo durante los gestos repetitivos y largos',
    ],
    correcta: 0,
    explicacion:
      'Al insertarse el músculo muy cerca de la articulación, un acortamiento pequeño produce un desplazamiento grande y rápido del extremo del segmento: se paga con fuerza y se cobra en velocidad y recorrido. El distractor más tentador es el de sostener cargas máximas, que describe exactamente lo contrario de lo que consigue esta disposición. Dato para recordar: el cuerpo está diseñado para lanzar y correr, no para hacer de grúa.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['palancas', 'tercer género', 'velocidad'],
  },
  {
    id: 'C6-015',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Por qué la potencia mecánica máxima se alcanza con cargas medias?',
    opciones: [
      'Porque la potencia es el producto de fuerza por velocidad, y los dos factores se comportan de forma inversa',
      'Porque las cargas medias reclutan un número mayor de unidades motoras que las cargas máximas',
      'Porque con cargas medias el músculo trabaja en el rango de longitud donde produce más tensión',
      'Porque la carga media permite completar más repeticiones y acumular así más trabajo total',
    ],
    correcta: 0,
    explicacion:
      'Fuerza y velocidad van en direcciones opuestas: a más carga, menos velocidad. Su producto es máximo en la zona intermedia, no en los extremos. El distractor más tentador es el del reclutamiento, porque suena fisiológicamente serio, pero es falso: las cargas máximas reclutan más unidades motoras y aun así generan poca potencia porque el gesto es lentísimo. Dato para recordar: es aritmética, no fisiología — el máximo de un producto con factores inversos está en el medio.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['potencia', 'curva fuerza-velocidad', 'cargas'],
  },
  {
    id: 'C6-016',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué es el momento de una fuerza y de qué depende?',
    opciones: [
      'El efecto de giro de una fuerza, igual al producto de la fuerza por su brazo de palanca',
      'La cantidad total de fuerza aplicada sobre el segmento corporal, sin considerar en qué punto se aplica',
      'La velocidad a la que gira un segmento corporal alrededor de su eje articular',
      'El tiempo durante el cual se mantiene aplicada una fuerza sobre la articulación',
    ],
    correcta: 0,
    explicacion:
      'El momento o torque mide la capacidad de una fuerza para hacer girar un segmento, y depende tanto de la fuerza como de la distancia perpendicular al eje. El distractor más tentador es el que ignora el brazo, que es justamente el factor que explica por qué separar la carga del cuerpo la vuelve tan pesada: la misma mancuerna con el brazo extendido exige mucho más que pegada al torso. Dato para recordar: importa cuánto empujas y desde dónde.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['momento de fuerza', 'brazo de palanca', 'torque'],
  },
  {
    id: 'C6-017',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'En un salto de altura en estilo Fosbury, ¿qué permite que el saltador supere el listón?',
    opciones: [
      'Que al arquear el cuerpo el centro de gravedad se desplaza fuera de él y puede pasar por debajo del listón',
      'Que la velocidad de la carrera previa eleva el centro de gravedad muy por encima de su altura habitual',
      'Que la posición de espaldas reduce la masa efectiva del saltador durante la fase de vuelo',
      'Que al arquearse el centro de gravedad sube hasta situarse a la altura del pecho del saltador',
    ],
    correcta: 0,
    explicacion:
      'El centro de gravedad es un punto teórico donde se concentraría toda la masa, y cuando el cuerpo cambia de forma puede quedar fuera de él: arqueado sobre el listón, el centro de gravedad del saltador pasa por debajo de la barra aunque cada parte del cuerpo pase por encima. El distractor más tentador dice que sube, que es lo contrario del truco. Dato para recordar: se salta menos alto de lo que parece, y esa es toda la ventaja del estilo.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['centro de gravedad', 'salto', 'aplicación'],
  },
  {
    id: 'C6-018',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre el equilibrio.',
    opciones: [
      'Se pierde el equilibrio cuando la proyección del centro de gravedad sale de la base',
      'Bajar el centro de gravedad aumenta la estabilidad del cuerpo',
      'La base de sustentación incluye el área comprendida entre los puntos de apoyo',
      'El centro de gravedad se sitúa siempre dentro del cuerpo, sea cual sea la postura que se adopte',
      'Con los pies juntos la estabilidad es mayor que con los pies separados',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tres primeras describen bien el equilibrio: proyección dentro de la base, centro bajo y base como área encerrada. El distractor más tentador es el del centro de gravedad siempre dentro del cuerpo, porque en posición anatómica sí lo está: al cambiar de forma —un arco, una posición sentada— puede quedar fuera. Y los pies juntos reducen la base. Dato para recordar: la base es un área, no un par de puntos.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['equilibrio', 'base de sustentación', 'estabilidad'],
  },
  {
    id: 'C6-019',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene las siguientes posiciones de menor a mayor estabilidad.',
    elementos: [
      'De pie sobre una sola pierna, con la otra elevada',
      'De pie con los pies juntos',
      'De pie con los pies separados a la anchura de los hombros',
      'En posición de semiflexión, con los pies separados y el centro de gravedad bajo',
      'Tendido en decúbito supino sobre el suelo',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La estabilidad crece al ampliar la base de sustentación y bajar el centro de gravedad, y el tendido reúne las dos condiciones en grado máximo. El error más frecuente es colocar la semiflexión por encima del tendido porque es la postura que asocia con «estar firme» en el deporte: es la más estable de las posiciones de pie, no la más estable de todas. Dato para recordar: la posición más estable es también la menos útil para moverse.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['equilibrio', 'estabilidad', 'secuencia'],
  },
  {
    id: 'C6-020',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué caracteriza a un corredor eficiente desde el punto de vista biomecánico?',
    opciones: [
      'Poca oscilación vertical y buen aprovechamiento de la energía elástica en cada apoyo',
      'Una zancada lo más amplia posible, aunque el pie contacte muy por delante del cuerpo',
      'Una elevación pronunciada del centro de gravedad en cada paso de la carrera',
      'Un tiempo de contacto con el suelo lo más prolongado posible en cada apoyo',
    ],
    correcta: 0,
    explicacion:
      'La eficiencia en carrera consiste en gastar lo menos posible en subir y bajar el cuerpo y en devolver el máximo de energía elástica almacenada en tendones y fascias durante el apoyo. El distractor más tentador es la zancada amplia, que suena a potencia: si el pie cae muy por delante del centro de gravedad se genera una fuerza de frenado en cada paso. Dato para recordar: el corredor eficiente avanza, no sube ni frena.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.4 — Eficiencia en la carrera',
    etiquetas: ['eficiencia', 'carrera', 'economía'],
  },
  {
    id: 'C6-021',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre la técnica de carrera.',
    opciones: [
      'La velocidad es el producto de la frecuencia por la amplitud de zancada',
      'El ciclo de estiramiento-acortamiento devuelve energía elástica en cada apoyo',
      'Aumentar la amplitud de zancada siempre mejora la velocidad, sin excepción',
      'Correr sobre arena mejora la economía porque el suelo devuelve más energía',
      'El tiempo de contacto no guarda relación alguna con la eficiencia del corredor',
    ],
    correctas: [0, 1],
    explicacion:
      'La velocidad depende de frecuencia y amplitud, y el ciclo de estiramiento-acortamiento devuelve energía elástica que abarata cada apoyo. El distractor más tentador es el de la amplitud, porque el primer enunciado la nombra como factor: crecer en amplitud a costa de sobrepasar el centro de gravedad introduce frenado, así que la relación no es lineal. Y la arena absorbe energía en lugar de devolverla. Dato para recordar: amplitud y frecuencia se compensan entre sí.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.4 — Eficiencia en la carrera',
    etiquetas: ['carrera', 'zancada', 'ciclo estiramiento-acortamiento'],
  },
  {
    id: 'C6-022',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'El bíceps aplica una fuerza de 200 N con un brazo de palanca de 0,3 m respecto al eje del codo. Calcule el momento de fuerza generado.',
    respuesta: 60,
    tolerancia: 1,
    unidad: 'N·m',
    pasos: [
      'Momento de fuerza = fuerza × brazo de palanca',
      'Momento = 200 N × 0,3 m',
      'Momento = 60 N·m',
    ],
    explicacion:
      'El momento es el producto de la fuerza por la distancia perpendicular al eje, y se expresa en newton por metro. El error más frecuente es sumar en lugar de multiplicar, o meter el brazo en centímetros sin convertir, que daría 6000 y una unidad incoherente. Dato para recordar: el brazo pesa tanto como la fuerza — duplicar la distancia al eje duplica el momento sin tocar el peso, y por eso una mancuerna con el brazo extendido cuesta tanto más.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['momento de fuerza', 'cálculo', 'palancas'],
  },
  {
    id: 'C6-023',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'En una palanca, el brazo de potencia mide 12 cm y el brazo de resistencia mide 30 cm. Calcule la ventaja mecánica con dos decimales.',
    respuesta: 0.4,
    tolerancia: 0.03,
    unidad: 'sin unidad',
    pasos: [
      'Ventaja mecánica = brazo de potencia ÷ brazo de resistencia',
      'Ventaja mecánica = 12 cm ÷ 30 cm',
      'Ventaja mecánica = 0,40',
      'Al ser menor que 1, la palanca está en desventaja mecánica: gana velocidad y pierde fuerza',
    ],
    explicacion:
      'Una ventaja mecánica de 0,40 significa que hace falta aplicar dos veces y media la resistencia para vencerla, a cambio de mucha velocidad en el extremo: es el perfil típico de una palanca de tercer género, la más abundante del cuerpo. El error más frecuente es invertir el cociente y responder 2,5, que describiría una palanca ventajosa. Dato para recordar: potencia arriba, resistencia abajo, y por debajo de 1 el cuerpo cambia fuerza por velocidad.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.2 — Palancas del cuerpo humano',
    etiquetas: ['ventaja mecánica', 'cálculo', 'palancas'],
  },
  {
    id: 'C6-024',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un deportista mueve una carga aplicando una fuerza de 500 N a una velocidad media de 1,2 m/s. Calcule la potencia desarrollada.',
    respuesta: 600,
    tolerancia: 5,
    unidad: 'W',
    pasos: [
      'Potencia = fuerza × velocidad',
      'Potencia = 500 N × 1,2 m/s',
      'Potencia = 600 W',
    ],
    explicacion:
      'La potencia mecánica es el producto de fuerza por velocidad y se expresa en vatios. El interés del cálculo está en lo que revela: si el mismo deportista levanta 800 N pero solo a 0,4 m/s, la potencia cae a 320 W pese a mover más peso. Ese es el motivo de que el pico de potencia aparezca con cargas medias. Dato para recordar: para comparar dos series de trabajo explosivo hay que multiplicar, no mirar solo el peso de la barra.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['potencia', 'cálculo', 'fuerza-velocidad'],
  },
  {
    id: 'C6-025',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un deportista de 80 kg alcanza una aceleración de 2,5 m/s² durante la salida. Calcule la fuerza neta que ha generado.',
    respuesta: 200,
    tolerancia: 2,
    unidad: 'N',
    pasos: [
      'Segunda ley de Newton: F = m × a',
      'F = 80 kg × 2,5 m/s²',
      'F = 200 N',
    ],
    explicacion:
      'La segunda ley de Newton relaciona la fuerza neta con la masa y la aceleración conseguida: 200 N. El error más frecuente es confundir la fuerza neta con el peso del deportista, que sería 80 × 9,8 = 784 N y responde a otra pregunta —cuánto tira la gravedad de él, no cuánta fuerza generó para acelerar—. Dato para recordar: la misma fuerza acelera menos a un cuerpo más pesado, y por eso en la salida el peso corporal no es solo un lastre metabólico.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['leyes de Newton', 'cálculo', 'fuerza'],
  },
  {
    id: 'C6-026',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un luchador se prepara para recibir el ataque de su rival. Antes del contacto flexiona las rodillas, separa los pies más allá de la anchura de sus hombros y baja el tronco.',
    enunciado: '¿Qué está consiguiendo con esa posición?',
    opciones: [
      'Ampliar la base de sustentación y bajar el centro de gravedad, con lo que gana estabilidad',
      'Reducir su masa efectiva para que el impacto del rival le transmita menos energía',
      'Elevar el centro de gravedad para poder reaccionar más rápido ante el ataque',
      'Disminuir la base de sustentación para poder desplazarse con mayor agilidad',
    ],
    correcta: 0,
    explicacion:
      'Separar los pies amplía la base y flexionar baja el centro de gravedad: las dos condiciones que más estabilizan, aplicadas a la vez. El distractor más tentador es el de la agilidad, porque señala una contrapartida real —la posición más estable es también la que menos permite moverse—, pero describe justo lo contrario de lo que hace el luchador. Dato para recordar: estabilidad y movilidad se compran una a costa de la otra, y el luchador elige estabilidad al recibir.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.3 — Centro de gravedad y equilibrio',
    etiquetas: ['equilibrio', 'estabilidad', 'aplicación deportiva'],
  },
  {
    id: 'C6-027',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un entrenador quiere mejorar la potencia de salida de sus velocistas y programa sentadillas al 95 % del 1RM, tres series de dos repeticiones, argumentando que así se genera la mayor potencia posible.',
    enunciado: '¿Qué corresponde objetar a ese planteamiento?',
    opciones: [
      'Que a esa carga la velocidad de ejecución es mínima, así que el producto fuerza por velocidad es bajo',
      'Que el número de series y repeticiones es insuficiente para producir cualquier adaptación útil',
      'Que trabajar al 95 % del 1RM no produce ninguna mejora de fuerza en velocistas entrenados',
      'Que la sentadilla no es un ejercicio transferible a la salida de velocidad en ningún caso',
    ],
    correcta: 0,
    explicacion:
      'Al 95 % del 1RM la barra se mueve lentísimo, y como la potencia es fuerza por velocidad, el resultado es bajo pese a la carga enorme: ese trabajo desarrolla fuerza máxima, no potencia. El distractor más tentador niega cualquier mejora de fuerza, y es falso: el 95 % es excelente para fuerza máxima, que es una base necesaria; el error del entrenador es de etiqueta, no de utilidad. Dato para recordar: la potencia se busca con cargas medias y velocidad alta.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['potencia', 'prescripción', 'fuerza-velocidad'],
  },
  {
    id: 'C6-028',
    modulo: 'c6-biomecanica',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un deportista vuelve de una lesión de rodilla. El fisioterapeuta indica priorizar ejercicios en cadena cinemática cerrada durante las primeras semanas de readaptación.',
    enunciado: '¿Qué ejercicio corresponde a esa indicación?',
    opciones: [
      'La sentadilla, porque el pie permanece fijo en el suelo mientras se mueven varias articulaciones',
      'La extensión de rodilla en máquina, porque el movimiento se concentra en una sola articulación',
      'El curl femoral tumbado, porque el segmento distal se desplaza libremente en el aire',
      'El press de banca, porque se trabaja con carga externa sobre un banco estable',
    ],
    correcta: 0,
    explicacion:
      'En la sentadilla el pie queda fijo contra el suelo: es cadena cerrada, reparte la carga entre cadera, rodilla y tobillo y reproduce el patrón funcional de apoyo. Los dos primeros distractores son ejercicios de cadena abierta —extremo distal libre—, y el de la extensión de rodilla es el más tentador porque parece el ejercicio más específico de la articulación lesionada, cuando concentra en ella toda la carga. Dato para recordar: cerrada reparte, abierta concentra.',
    referencia: 'Cartilla 3, Tema 3, Subtema 3.1 — Cinética y cinemática',
    etiquetas: ['cadena cinemática', 'readaptación', 'aplicación'],
  },
];
