// content/banco/c7-nutricion-deportiva.ts
// C7 · Nutrición deportiva. 28 ítems (bloque C, ADR-006).
//
// Reparto verificado contra verificarCuotas(cuotasDelBloque('C')):
//   Nivel      → 12 recuerdo (43 %) · 9 comprensión (32 %) · 7 aplicación (25 %)
//   Dificultad → 5 de nivel 1 · 17 de nivel 2 · 6 de nivel 3
//   Tipos      → 14 única · 4 cálculo · 3 múltiple · 3 caso · 2 emparejar
//                · 1 ordenar · 1 V/F
//
// Cubre los 8 datos duros del módulo, DD-050 a DD-057. La cronología —antes,
// durante y después— es la columna vertebral del tema: lo que se pregunta no
// es qué comer sino CUÁNDO.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 28 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'C7-001',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué cantidad de agua se recomienda ingerir antes de comenzar una sesión?',
    opciones: [
      '250–500 ml',
      'Entre 1 y 2 litros, para asegurar una reserva hídrica amplia',
      'Nada, porque beber antes del esfuerzo provoca molestias digestivas',
      'Únicamente la cantidad que el deportista pida de forma espontánea por sed',
    ],
    correcta: 0,
    explicacion:
      'La pauta previa es de 250 a 500 ml de agua, suficiente para llegar bien hidratado sin sobrecargar el estómago. El distractor más tentador es el litro o dos, porque parece más prudente: un volumen así no se absorbe a tiempo, se queda en el estómago dando molestias y buena parte acaba en la vejiga. Dato para recordar: la hidratación se prepara en las horas previas, no en el vaso de antes de salir.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.1 — Alimentación antes del esfuerzo',
    etiquetas: ['hidratación', 'antes del esfuerzo', 'valores'],
  },
  {
    id: 'C7-002',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué se debe beber durante una sesión de menos de 60 minutos?',
    opciones: [
      'Agua',
      'Una bebida deportiva con hidratos de carbono y electrolitos añadidos',
      'Una bebida con proteína hidrolizada para frenar el catabolismo muscular',
      'Nada, para que el organismo aprenda a tolerar la deshidratación progresiva',
    ],
    correcta: 0,
    explicacion:
      'Por debajo de una hora el agua basta: ni las reservas de glucógeno ni las pérdidas de electrolitos llegan a comprometer el rendimiento. El distractor más tentador es la bebida deportiva, que es la respuesta correcta pero para sesiones de más de 60 minutos: los dos escenarios se estudian juntos y se cruzan. Dato para recordar: la frontera de los 60 minutos es la que decide entre agua y bebida deportiva.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['hidratación', 'durante el esfuerzo', 'agua'],
  },
  {
    id: 'C7-003',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué se recomienda beber durante una sesión de más de 60 minutos?',
    opciones: [
      'Una bebida deportiva con hidratos de carbono y electrolitos',
      'Agua sola, porque cualquier azúcar añadido retrasa el vaciado gástrico',
      'Una bebida rica en proteína para cubrir el desgaste muscular acumulado',
      'Una bebida hipertónica concentrada, para reponer sales de forma más rápida',
    ],
    correcta: 0,
    explicacion:
      'A partir de los 60 minutos conviene aportar hidratos y electrolitos: el glucógeno empieza a ser un factor limitante y con el sudor se pierden sales. El distractor más tentador es la bebida hipertónica, que suena a «más concentrada, más eficaz»: una concentración alta enlentece el vaciado gástrico y puede empeorar la deshidratación en vez de corregirla. Dato para recordar: por encima de la hora, agua sola ya no alcanza.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['hidratación', 'bebida deportiva', 'durante el esfuerzo'],
  },
  {
    id: 'C7-004',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Con cuánta antelación debe tomarse la comida rica en hidratos previa al esfuerzo?',
    opciones: [
      '2–4 horas antes',
      'Entre 30 y 60 minutos antes, para que la energía llegue lo más fresca posible',
      'Entre 8 y 10 horas antes, es decir, la noche anterior a la competición',
      'Justo al terminar el calentamiento, ya con el deportista activado',
    ],
    correcta: 0,
    explicacion:
      'La comida principal previa se sitúa entre 2 y 4 horas antes: tiempo suficiente para vaciar el estómago y tener la energía disponible sin llegar con digestión pesada. El distractor más tentador son los 30–60 minutos, que corresponde a un tentempié ligero y no a una comida completa: hacerla ahí garantiza molestias digestivas. Dato para recordar: cuanto más grande es la comida, más lejos de la hora de competir.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.1 — Alimentación antes del esfuerzo',
    etiquetas: ['antes del esfuerzo', 'hidratos de carbono', 'timing'],
  },
  {
    id: 'C7-005',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      '¿Qué tipo de hidratos y en qué momento conviene tomarlos para reponer el glucógeno tras el esfuerzo?',
    opciones: [
      'De alto índice glucémico, en los 30–60 minutos posteriores',
      'De bajo índice glucémico, en las 3 o 4 horas posteriores al entrenamiento',
      'De alto índice glucémico, pero esperando al menos 3 horas tras terminar',
      'Cualquier tipo de hidrato, siempre que se tome dentro de las 24 horas',
    ],
    correcta: 0,
    explicacion:
      'La reposición de glucógeno se acelera con hidratos de alto índice glucémico en los primeros 30 a 60 minutos, cuando el músculo está más receptivo a captar glucosa. El distractor más tentador invierte el índice glucémico: el bajo índice es lo que se busca ANTES del esfuerzo, para una liberación sostenida, y después interesa justo lo contrario. Dato para recordar: bajo índice antes, alto índice después.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['glucógeno', 'índice glucémico', 'recuperación'],
  },
  {
    id: 'C7-006',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué cantidad de proteína se recomienda tras el entrenamiento?',
    opciones: [
      '20–40 g de proteína de alta calidad',
      'Entre 80 y 100 g, para maximizar por completo la síntesis proteica muscular',
      'Entre 5 y 10 g, ya que el músculo no puede aprovechar cantidades mayores',
      'La proteína no debe consumirse después del esfuerzo, sino solo antes de él',
    ],
    correcta: 0,
    explicacion:
      'La horquilla útil está entre 20 y 40 g de proteína de alta calidad: por debajo el estímulo es insuficiente y por encima el excedente se oxida sin aportar más síntesis. El distractor más tentador son los 80–100 g, porque circula la idea de que más proteína es siempre más músculo: lo que se gana pasado ese umbral no va al músculo. Dato para recordar: la síntesis proteica tiene techo por toma, así que conviene repartir a lo largo del día.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['proteína', 'recuperación', 'valores'],
  },
  {
    id: 'C7-007',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuál es la proporción recomendada de hidratos y proteína en la recuperación?',
    opciones: [
      'CHO : proteína de 3:1 o 4:1',
      'CHO : proteína de 1:1, en cantidades exactamente iguales de ambos',
      'CHO : proteína de 1:3, con clara ventaja para el aporte proteico',
      'CHO : proteína de 10:1, prácticamente solo hidratos de carbono',
    ],
    correcta: 0,
    explicacion:
      'La proporción de recuperación es de 3 a 4 partes de hidratos por cada parte de proteína: los hidratos reponen glucógeno y la proteína repara, y juntos funcionan mejor que por separado. El distractor más tentador es el 1:1, porque suena equilibrado y porque en el imaginario del gimnasio la proteína manda: lo que más urge reponer tras el esfuerzo es el combustible. Dato para recordar: manda el hidrato, acompaña la proteína.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['recuperación', 'proporción', 'CHO:proteína'],
  },
  {
    id: 'C7-008',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿En qué situación se recomienda consumir proteína DURANTE el esfuerzo?',
    opciones: [
      'En pruebas de ultra-resistencia de más de 4 horas',
      'En cualquier sesión de fuerza que supere los cuarenta minutos de duración',
      'En sesiones de alta intensidad de entre 30 y 60 minutos de trabajo efectivo',
      'Nunca: la proteína durante el esfuerzo carece por completo de utilidad',
    ],
    correcta: 0,
    explicacion:
      'La ultra-resistencia de más de 4 horas es el único escenario en el que se recomienda aportar proteína durante el esfuerzo, porque el consumo prolongado empieza a comprometer la masa muscular. El distractor más tentador es la sesión de fuerza, donde la creencia popular sitúa la proteína como imprescindible en el momento: ahí lo que cuenta es el aporte de las horas posteriores. Dato para recordar: durante el esfuerzo mandan los hidratos, salvo en ultra.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['proteína', 'ultra-resistencia', 'durante el esfuerzo'],
  },
  {
    id: 'C7-009',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada momento con la pauta nutricional que le corresponde.',
    izquierda: [
      '2–4 horas antes',
      'Justo antes de empezar',
      'Durante una sesión de más de 60 min',
      'En los 30–60 min posteriores',
    ],
    derecha: [
      'Comida rica en hidratos de bajo índice glucémico',
      '250–500 ml de agua',
      'Bebida deportiva con hidratos y electrolitos',
      'Hidratos de alto índice glucémico y 20–40 g de proteína',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'La cronología completa es comida principal lejos, agua cerca, hidratos durante y reposición inmediata después. El par que más se falla es el primero con el último, porque en los dos hay hidratos: la diferencia está en el índice glucémico, bajo antes para liberar despacio y alto después para reponer rápido. Dato para recordar: en nutrición deportiva la pregunta casi nunca es qué, es cuándo.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.1 — Alimentación antes del esfuerzo',
    etiquetas: ['cronología', 'clasificación', 'timing'],
  },
  {
    id: 'C7-010',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada índice antropométrico con su cálculo.',
    izquierda: [
      'Índice de masa corporal',
      'Índice cintura-cadera',
      'Gasto energético total',
      'Porcentaje de pérdida de peso por sudoración',
    ],
    derecha: [
      'Peso en kg dividido entre la estatura en metros al cuadrado',
      'Perímetro de cintura dividido entre perímetro de cadera',
      'Metabolismo basal más efecto térmico de los alimentos más actividad física',
      'Diferencia de peso antes y después dividida entre el peso inicial, por cien',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se falla es el del IMC: se divide entre la estatura sin elevar al cuadrado, lo que da un número tres o cuatro veces mayor y sin sentido clínico. El índice cintura-cadera es un cociente de perímetros y no lleva unidades. Dato para recordar: el IMC no distingue músculo de grasa, así que en deportistas muy musculados clasifica mal — es un cribado poblacional, no un diagnóstico individual.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.4 — Antropometría aplicada',
    etiquetas: ['antropometría', 'IMC', 'clasificación'],
  },
  {
    id: 'C7-011',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre la bebida isotónica.',
    opciones: [
      'Tiene una concentración de solutos parecida a la del plasma sanguíneo',
      'Aporta hidratos de carbono y electrolitos junto con el agua',
      'Es la bebida indicada para cualquier sesión, dure lo que dure',
      'Su alta concentración de azúcares acelera el vaciado del estómago hacia el intestino',
      'Sustituye a la comida de recuperación posterior al entrenamiento',
    ],
    correctas: [0, 1],
    explicacion:
      'Isotónica significa concentración similar a la del plasma, y su función es aportar agua, hidratos y electrolitos a la vez. El distractor más tentador dice que sirve para cualquier sesión: por debajo de 60 minutos basta el agua, y añadir azúcar sin necesidad solo aporta calorías. Y una concentración alta enlentece el vaciado gástrico, no lo acelera. Dato para recordar: isotónica es una concentración, no una marca ni un sabor.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['bebida isotónica', 'hidratación', 'electrolitos'],
  },
  {
    id: 'C7-012',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      'En un esfuerzo prolongado en calor, la sed es un indicador suficiente para pautar la hidratación del deportista.',
    correcta: false,
    explicacion:
      'Falso. La sensación de sed aparece cuando ya hay un déficit hídrico instalado, así que beber solo cuando se tiene sed llega tarde en esfuerzos largos y en ambientes calurosos. Por eso se pauta un plan de ingesta por tiempo y se controla la pérdida pesando al deportista antes y después. La confusión viene de que en la vida cotidiana la sed sí basta. Dato para recordar: en competición la hidratación se programa, no se improvisa.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['hidratación', 'sed', 'deshidratación'],
  },
  {
    id: 'C7-013',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué mide el índice glucémico de un alimento?',
    opciones: [
      'La velocidad con la que eleva la glucosa en sangre respecto a un alimento de referencia',
      'La cantidad total de azúcares que contiene ese alimento por cada cien gramos',
      'El número de calorías que aporta el alimento en forma de hidratos de carbono',
      'El tiempo que tarda el alimento en abandonar por completo el estómago',
    ],
    correcta: 0,
    explicacion:
      'El índice glucémico mide velocidad, no cantidad: compara la rapidez con que un alimento eleva la glucemia frente a un patrón. El distractor más tentador es la cantidad de azúcares, porque los dos conceptos suelen ir juntos: hay alimentos con mucho azúcar y bajo índice glucémico, y ahí se ve que no son lo mismo. Dato para recordar: el índice glucémico responde a qué tan rápido, y la carga glucémica a cuánto en total.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.1 — Alimentación antes del esfuerzo',
    etiquetas: ['índice glucémico', 'definición', 'hidratos'],
  },
  {
    id: 'C7-014',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué se recomiendan hidratos de bajo índice glucémico antes del esfuerzo y de alto índice después?',
    opciones: [
      'Porque antes interesa una liberación sostenida de glucosa y después una reposición lo más rápida posible',
      'Porque los hidratos de bajo índice glucémico aportan bastantes más calorías por gramo',
      'Porque los de alto índice glucémico resultan indigestos si se toman en reposo',
      'Porque el organismo solo puede absorber hidratos de alto índice tras el ejercicio',
    ],
    correcta: 0,
    explicacion:
      'Antes de competir interesa que la glucosa entre despacio y dure; después interesa lo contrario, llenar el depósito cuanto antes aprovechando la ventana en que el músculo capta glucosa con más avidez. El distractor más tentador dice que solo se pueden absorber después, lo que confunde una ventaja de oportunidad con una imposibilidad fisiológica. Dato para recordar: bajo índice antes, alto índice después, y por el mismo motivo en los dos casos.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['índice glucémico', 'timing', 'glucógeno'],
  },
  {
    id: 'C7-015',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Qué justifica la ventana de recuperación de los 30–60 minutos posteriores?',
    opciones: [
      'Que el músculo capta glucosa con más facilidad justo tras el esfuerzo, lo que acelera la reposición del glucógeno',
      'Que pasada esa hora el organismo pierde de forma definitiva la capacidad de reponer glucógeno',
      'Que la digestión solo funciona correctamente durante esa hora tras terminar de entrenar',
      'Que la proteína ingerida más tarde de una hora no llega a absorberse en el intestino',
    ],
    correcta: 0,
    explicacion:
      'Tras el esfuerzo el músculo capta glucosa con más avidez, así que reponer pronto acelera la recarga: eso es lo que da valor a la ventana. Los tres distractores la convierten en un plazo absoluto, y es el error más frecuente del tema: pasada la hora se sigue reponiendo, solo que más despacio. Dato para recordar: la ventana importa mucho si compites otra vez en pocas horas, y muy poco si vuelves a entrenar al día siguiente.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['ventana de recuperación', 'glucógeno', 'recuperación'],
  },
  {
    id: 'C7-016',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué componentes suma el gasto energético total diario?',
    opciones: [
      'Metabolismo basal, efecto térmico de los alimentos y gasto por actividad física',
      'Únicamente las calorías que se queman durante las sesiones de entrenamiento',
      'Metabolismo basal y gasto por actividad física, sin ningún componente más',
      'Las calorías ingeridas en el día menos las que se eliminan por la orina y por las heces',
    ],
    correcta: 0,
    explicacion:
      'El gasto total suma tres partidas: el metabolismo basal, que es con diferencia la mayor; el efecto térmico de los alimentos, en torno al 10 %; y la actividad física, que es la única realmente modificable a corto plazo. El distractor más tentador omite el efecto térmico, que es el componente que más se olvida por ser el más pequeño. Dato para recordar: incluso en un deportista, el basal se lleva la mayor parte del gasto del día.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.4 — Antropometría aplicada',
    etiquetas: ['gasto energético total', 'metabolismo basal', 'componentes'],
  },
  {
    id: 'C7-017',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Por qué se evitan las comidas ricas en grasa y en fibra en las horas previas a competir?',
    opciones: [
      'Porque retrasan el vaciado gástrico y aumentan el riesgo de molestias digestivas durante el esfuerzo',
      'Porque la grasa y la fibra no aportan ninguna energía aprovechable al deportista',
      'Porque elevan la glucosa en sangre demasiado deprisa y provocan una hipoglucemia posterior',
      'Porque impiden por completo la absorción de los hidratos de carbono de esa misma comida',
    ],
    correcta: 0,
    explicacion:
      'Grasa y fibra enlentecen el vaciado del estómago: la comida sigue ahí cuando empieza el esfuerzo, y con la sangre desviada al músculo aparecen las molestias. El distractor más tentador es el de la subida rápida de glucosa, que describe justo lo contrario de lo que hacen estos nutrientes —bajan la respuesta glucémica, no la disparan—. Dato para recordar: la comida previa se elige por lo rápido que sale del estómago, no por lo nutritiva que sea.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.1 — Alimentación antes del esfuerzo',
    etiquetas: ['antes del esfuerzo', 'vaciado gástrico', 'fibra'],
  },
  {
    id: 'C7-018',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre la hidratación.',
    opciones: [
      'La sed aparece cuando ya existe un déficit hídrico instalado',
      'Pesar al deportista antes y después permite estimar la pérdida por sudor',
      'Por encima de 60 minutos conviene aportar electrolitos además de agua',
      'Beber grandes volúmenes de agua sola en esfuerzos muy largos carece de riesgo',
      'La deshidratación no afecta al rendimiento mientras no supere el 10 % del peso',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'La sed llega tarde, el pesaje estima la pérdida y por encima de la hora hacen falta electrolitos. El distractor más tentador es el de beber agua sola sin riesgo: en pruebas muy largas, reponer solo agua puede diluir el sodio en sangre y provocar hiponatremia, que es peligrosa. Y el rendimiento cae mucho antes del 10 %: con un 2 % ya se nota. Dato para recordar: ni poco ni de más, y con sales cuando el esfuerzo se alarga.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['hidratación', 'hiponatremia', 'deshidratación'],
  },
  {
    id: 'C7-019',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene cronológicamente las pautas nutricionales de un día de competición.',
    elementos: [
      'Comida rica en hidratos de bajo índice glucémico, 2–4 h antes',
      '250–500 ml de agua en los minutos previos a la salida',
      'Bebida con hidratos y electrolitos durante el esfuerzo, si supera los 60 min',
      'Hidratos de alto índice glucémico en los 30–60 min posteriores',
      'Comida completa de recuperación con proporción CHO:proteína de 3:1 o 4:1',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La cronología va de la comida principal a la reposición inmediata y termina con la comida completa de recuperación. El error más frecuente es adelantar la proteína al tramo previo, arrastrando la idea de gimnasio de que hay que tomarla siempre antes: antes de competir lo que interesa es combustible disponible y estómago vacío. Dato para recordar: hidratos antes y durante, hidratos con proteína después.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['cronología', 'competición', 'secuencia'],
  },
  {
    id: 'C7-020',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Qué diferencia a una bebida isotónica de una hipertónica y de una hipotónica?',
    opciones: [
      'La concentración de solutos respecto al plasma: igual, mayor o menor',
      'La cantidad de calorías totales que cada una de ellas aporta por envase',
      'La temperatura a la que se recomienda consumir cada una de las tres',
      'El tipo de azúcar empleado en su elaboración industrial y su procedencia',
    ],
    correcta: 0,
    explicacion:
      'Lo que las clasifica es la concentración de solutos comparada con la del plasma: la isotónica la iguala, la hipertónica la supera y la hipotónica queda por debajo. El distractor más tentador es el de las calorías, porque existe correlación —la hipertónica suele llevar más azúcar—, pero la definición no es calórica sino osmótica. Dato para recordar: la hipertónica enlentece el vaciado gástrico y por eso no sirve para rehidratar rápido.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['bebida isotónica', 'osmolaridad', 'clasificación'],
  },
  {
    id: 'C7-021',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre la proteína en el deportista.',
    opciones: [
      'La ingesta útil por toma está en torno a 20–40 g de proteína de alta calidad',
      'Repartir la proteína a lo largo del día aprovecha mejor la síntesis proteica',
      'Cuanta más proteína se ingiera en una toma, más músculo se sintetiza sin límite',
      'La proteína debe consumirse durante el esfuerzo en cualquier tipo de sesión',
      'El exceso de proteína se almacena tal cual en el músculo hasta que se necesite',
    ],
    correctas: [0, 1],
    explicacion:
      'Hay un techo por toma, en torno a 20–40 g, y por eso repartir a lo largo del día rinde más que concentrar. El distractor más tentador es el de que más siempre es más, que es la creencia dominante en el gimnasio: pasado el umbral, el excedente se oxida o se usa como energía. Y el organismo no tiene depósito de proteína: lo que hay son tejidos funcionales. Dato para recordar: no existe la despensa de aminoácidos.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['proteína', 'síntesis proteica', 'recuperación'],
  },
  {
    id: 'C7-022',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Un deportista pesa 78 kg y mide 1,80 m. Calcule su índice de masa corporal con dos decimales.',
    respuesta: 24.07,
    tolerancia: 0.2,
    unidad: 'kg/m²',
    pasos: [
      'IMC = peso (kg) ÷ estatura (m)²',
      'Estatura al cuadrado = 1,80 × 1,80 = 3,24',
      'IMC = 78 ÷ 3,24',
      'IMC = 24,07 kg/m²',
    ],
    explicacion:
      'El paso que decide el ítem es elevar la estatura al cuadrado: sin hacerlo el resultado sería 43,3, un valor que ninguna tabla de IMC contempla. Con 24,07 el deportista queda en normopeso. Dato para recordar: el IMC no distingue músculo de grasa, así que en deportistas muy musculados puede clasificar como sobrepeso a alguien con un porcentaje graso bajísimo. Es un cribado poblacional, no un diagnóstico individual.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.4 — Antropometría aplicada',
    etiquetas: ['IMC', 'cálculo', 'antropometría'],
  },
  {
    id: 'C7-023',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un deportista tiene un perímetro de cintura de 88 cm y de cadera de 102 cm. Calcule su índice cintura-cadera con dos decimales.',
    respuesta: 0.86,
    tolerancia: 0.03,
    unidad: 'sin unidad',
    pasos: [
      'Índice cintura-cadera = perímetro de cintura ÷ perímetro de cadera',
      'ICC = 88 cm ÷ 102 cm',
      'ICC = 0,8627',
      'ICC ≈ 0,86',
    ],
    explicacion:
      'El índice es un cociente de perímetros, así que no lleva unidades: los centímetros se cancelan. El error más frecuente es invertir el cociente y responder 1,16, un valor que describiría una cintura mayor que la cadera. Dato para recordar: el índice cintura-cadera informa sobre la distribución de la grasa, y esa distribución tiene más valor de salud que el peso total — el IMC no la ve en absoluto.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.4 — Antropometría aplicada',
    etiquetas: ['índice cintura-cadera', 'cálculo', 'antropometría'],
  },
  {
    id: 'C7-024',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Se prepara un batido de recuperación con 30 g de proteína, respetando una proporción CHO:proteína de 4:1. ¿Cuántos gramos de hidratos de carbono debe llevar?',
    respuesta: 120,
    tolerancia: 2,
    unidad: 'g',
    pasos: [
      'La proporción 4:1 indica 4 g de hidratos por cada gramo de proteína',
      'Hidratos = proteína × 4',
      'Hidratos = 30 g × 4',
      'Hidratos = 120 g',
    ],
    explicacion:
      'La proporción se aplica multiplicando la proteína por el primer término: 120 g de hidratos. El error más frecuente es invertirla y responder 7,5 g, lo que dejaría la recuperación sin apenas combustible. Con la proporción 3:1 el resultado sería 90 g, también válido según el criterio que se elija. Dato para recordar: en la recuperación manda el hidrato y la proteína acompaña, nunca al revés.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.3 — Recuperación tras el esfuerzo',
    etiquetas: ['recuperación', 'cálculo', 'CHO:proteína'],
  },
  {
    id: 'C7-025',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un deportista pesa 74,0 kg antes de entrenar y 72,8 kg al terminar. Si se recomienda reponer 1,5 litros por cada kilogramo perdido, ¿cuánto líquido debe ingerir?',
    respuesta: 1.8,
    tolerancia: 0.1,
    unidad: 'L',
    pasos: [
      'Pérdida de peso = 74,0 − 72,8 = 1,2 kg',
      'Reposición = pérdida × 1,5 L/kg',
      'Reposición = 1,2 × 1,5',
      'Reposición = 1,8 L',
    ],
    explicacion:
      'Se repone más volumen del perdido porque parte del líquido ingerido se elimina por la orina antes de rehidratar del todo: 1,8 litros para 1,2 kg de pérdida. El error más frecuente es reponer litro por kilo y quedarse en 1,2 L, con lo que el deportista arrancaría la sesión siguiente aún deshidratado. Dato para recordar: esa pérdida de 1,2 kg sobre 74 es un 1,6 % del peso, y el rendimiento ya cae a partir del 2 %.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['hidratación', 'cálculo', 'reposición'],
  },
  {
    id: 'C7-026',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Una corredora va a hacer una tirada larga de dos horas y media en un día caluroso. Pregunta a su entrenador qué debe llevar en el cinturón de hidratación para el recorrido.',
    enunciado: '¿Qué corresponde recomendarle?',
    opciones: [
      'Bebida deportiva con hidratos y electrolitos, porque el esfuerzo supera los 60 minutos',
      'Solo agua, porque cualquier bebida con azúcar produce molestias digestivas al correr',
      'Un batido con 30 g de proteína, para frenar la pérdida de masa muscular durante la tirada',
      'Nada de líquido, para acostumbrar al organismo a rendir en condiciones de deshidratación',
    ],
    correcta: 0,
    explicacion:
      'Dos horas y media superan con creces el umbral de los 60 minutos y el calor multiplica la pérdida de sales: toca bebida con hidratos y electrolitos. El distractor más tentador es el batido de proteína, porque la duración es larga: la proteína durante el esfuerzo se reserva a la ultra-resistencia de más de 4 horas, y aquí solo añadiría carga digestiva. Dato para recordar: por encima de 60 minutos, hidratos y sales; por encima de 4 horas, además proteína.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['hidratación', 'bebida deportiva', 'prescripción'],
  },
  {
    id: 'C7-027',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un equipo juega su partido a las 10 de la mañana. El entrenador quiere fijar la hora del desayuno y varios jugadores proponen desayunar fuerte a las 9:30 «para llegar con energía fresca».',
    enunciado: '¿Qué pauta corresponde establecer?',
    opciones: [
      'Desayunar entre las 6 y las 8, con hidratos de bajo índice glucémico, y dejar solo agua para la última media hora',
      'Desayunar a las 9:30 como proponen, ya que la energía debe ingerirse lo más cerca posible del partido',
      'No desayunar, para que el organismo movilice sus reservas de grasa desde el primer minuto',
      'Desayunar a las 9:30 pero solo proteína, que no interfiere con la digestión antes del esfuerzo',
    ],
    correcta: 0,
    explicacion:
      'La comida principal previa va de 2 a 4 horas antes, así que para las 10 el desayuno se sitúa entre las 6 y las 8, con hidratos de bajo índice glucémico; en la última media hora, solo agua. El distractor más tentador es la propuesta de los jugadores, que confunde tener la comida reciente con tener la energía disponible: a las 9:30 la digestión estaría en marcha justo cuando la sangre necesita irse al músculo. Dato para recordar: la energía se prepara con horas, no con minutos.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.1 — Alimentación antes del esfuerzo',
    etiquetas: ['antes del esfuerzo', 'timing', 'prescripción'],
  },
  {
    id: 'C7-028',
    modulo: 'c7-nutricion-deportiva',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un corredor de montaña prepara una prueba de 60 km que estima completar en unas seis horas. Su plan de avituallamiento incluye únicamente geles de hidratos y bebida isotónica.',
    enunciado: '¿Qué ajuste corresponde proponerle?',
    opciones: [
      'Añadir algún aporte de proteína durante la prueba, porque supera las 4 horas de esfuerzo continuo',
      'Retirar la bebida isotónica y sustituirla por agua sola durante todo el recorrido',
      'Mantener el plan tal como está, porque la proteína nunca se ingiere durante el esfuerzo',
      'Sustituir los geles por hidratos de bajo índice glucémico a lo largo de toda la prueba',
    ],
    correcta: 0,
    explicacion:
      'Seis horas entran de lleno en la ultra-resistencia, el único escenario en que se recomienda aportar proteína durante el esfuerzo para limitar el desgaste de masa muscular. El distractor más tentador es mantener el plan, porque aplica correctamente la regla general —durante el esfuerzo mandan los hidratos— sin ver que esta prueba es justamente su excepción. Dato para recordar: la frontera está en las 4 horas.',
    referencia: 'Cartilla 3, Tema 4, Subtema 4.2 — Alimentación e hidratación durante el esfuerzo',
    etiquetas: ['ultra-resistencia', 'proteína', 'prescripción'],
  },
];
