// content/banco/c8-psicologia-deporte.ts
// C8 · Psicología del deporte. 28 ítems (bloque C, ADR-006).
//
// Reparto verificado contra verificarCuotas(cuotasDelBloque('C')):
//   Nivel      → 12 recuerdo (43 %) · 9 comprensión (32 %) · 7 aplicación (25 %)
//   Dificultad → 3 de nivel 1 · 19 de nivel 2 · 6 de nivel 3
//   Tipos      → 17 única · 3 múltiple · 3 caso · 2 emparejar · 2 V/F
//                · 1 ordenar
//
// SIN ítems de tipo cálculo, y es deliberado: el módulo no tiene ninguna
// magnitud que calcular, y forzar un cálculo aquí produciría aritmética
// disfrazada de psicología. La cuota exige 4 tipos distintos y hay 6.
//
// El eje del módulo es la pareja teoría–autor, que es lo que más cae, y la
// distinción refuerzo negativo / castigo, que es lo que más se falla.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 28 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'C8-001',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿A qué autor se asocia el condicionamiento clásico?',
    opciones: [
      'Pavlov',
      'Skinner, por sus trabajos sobre las consecuencias de la conducta',
      'Bandura, por sus estudios sobre el aprendizaje por observación',
      'Vygotsky, por su concepto de zona de desarrollo próximo',
    ],
    correcta: 0,
    explicacion:
      'El condicionamiento clásico es de Pavlov: un estímulo neutro acaba provocando una respuesta por asociación repetida con otro que ya la provocaba. El distractor más tentador es Skinner, porque los dos son los grandes nombres del conductismo y sus condicionamientos se estudian seguidos: la diferencia es que Pavlov trabaja con asociación de estímulos y Skinner con consecuencias de la conducta. Dato para recordar: Pavlov asocia, Skinner premia y castiga.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['condicionamiento clásico', 'Pavlov', 'autores'],
  },
  {
    id: 'C8-002',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿A qué autor se asocia el condicionamiento operante?',
    opciones: [
      'Skinner',
      'Pavlov, por sus experimentos sobre respuestas condicionadas en animales',
      'Ausubel, por su propuesta sobre el aprendizaje significativo del alumno',
      'Piaget, por su descripción de las etapas del desarrollo cognitivo',
    ],
    correcta: 0,
    explicacion:
      'El condicionamiento operante es de Skinner: la conducta se modifica según sus consecuencias, que pueden reforzarla o debilitarla. El distractor más tentador es Pavlov, la otra mitad del conductismo, y el modo de no cruzarlos es fijarse en qué viene antes: en Pavlov el estímulo precede a la respuesta, y en Skinner la consecuencia viene después de la conducta. Dato para recordar: operante viene de operar sobre el entorno.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['condicionamiento operante', 'Skinner', 'autores'],
  },
  {
    id: 'C8-003',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿A qué autor corresponde el aprendizaje vicario o por observación?',
    opciones: [
      'Bandura',
      'Skinner, que explicó cómo las consecuencias modelan la conducta observada',
      'Thorndike, autor de la ley del efecto y del aprendizaje por ensayo y error',
      'Bruner, que defendió el aprendizaje por descubrimiento en el aula',
    ],
    correcta: 0,
    explicacion:
      'El aprendizaje vicario o social es de Bandura: se aprende observando a un modelo y las consecuencias que este recibe, sin necesidad de experimentarlas en carne propia. El distractor más tentador es Skinner, porque el aprendizaje vicario también habla de consecuencias: la diferencia es de quién son esas consecuencias, si propias u observadas en otro. Dato para recordar: para un entrenador, la demostración técnica es aprendizaje vicario puro.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['aprendizaje vicario', 'Bandura', 'autores'],
  },
  {
    id: 'C8-004',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Quién propuso el concepto de aprendizaje significativo?',
    opciones: [
      'Ausubel',
      'Piaget, en su teoría sobre la construcción del conocimiento por etapas',
      'Vygotsky, al describir el papel del entorno social en el aprendizaje',
      'Bandura, en el marco de su teoría del aprendizaje social por modelado',
    ],
    correcta: 0,
    explicacion:
      'El aprendizaje significativo es de Ausubel: lo nuevo se aprende de verdad cuando se ancla en lo que el aprendiz ya sabe. El distractor más tentador es Piaget, porque los dos son constructivistas y hablan de construir conocimiento: Piaget describe etapas de desarrollo y Ausubel se centra en cómo se integra el contenido nuevo. Dato para recordar: por eso un entrenador explica el saque nuevo apoyándose en el gesto que el deportista ya domina.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['aprendizaje significativo', 'Ausubel', 'autores'],
  },
  {
    id: 'C8-005',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Quién describió el desarrollo cognitivo como una sucesión de etapas?',
    opciones: [
      'Piaget',
      'Vygotsky, que subrayó la mediación social en el desarrollo del niño',
      'Ausubel, que estudió cómo se integran los conocimientos previos',
      'Pavlov, cuyos trabajos describieron respuestas condicionadas en el organismo',
    ],
    correcta: 0,
    explicacion:
      'Piaget describió el desarrollo cognitivo por etapas sucesivas, cada una con una forma característica de pensar. El distractor más tentador es Vygotsky, porque los dos estudiaron el desarrollo infantil y se citan siempre juntos: Piaget pone el peso en la maduración del individuo y Vygotsky en la mediación social. Dato para recordar: en el deporte de base esto se traduce en que la tarea tiene que ajustarse a la etapa, no al revés.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['Piaget', 'desarrollo cognitivo', 'autores'],
  },
  {
    id: 'C8-006',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿A quién corresponde el concepto de zona de desarrollo próximo?',
    opciones: [
      'Vygotsky',
      'Piaget, que definió las etapas por las que pasa el pensamiento infantil',
      'Bruner, defensor del aprendizaje por descubrimiento guiado en el aula',
      'Thorndike, que formuló la ley del efecto sobre la conducta aprendida',
    ],
    correcta: 0,
    explicacion:
      'La zona de desarrollo próximo es de Vygotsky: la distancia entre lo que el aprendiz hace solo y lo que puede hacer con ayuda de alguien más capaz. El distractor más tentador es Bruner, cuyo andamiaje es un desarrollo directo de esta idea y por eso se confunden. Dato para recordar: es el concepto que justifica que un entrenador proponga tareas ligeramente por encima de lo que el deportista domina, y que después retire la ayuda.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['zona de desarrollo próximo', 'Vygotsky', 'autores'],
  },
  {
    id: 'C8-007',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué es el refuerzo positivo?',
    opciones: [
      'Añadir un estímulo agradable tras una conducta para que se repita más',
      'Retirar un estímulo desagradable tras una conducta para que se repita más',
      'Aplicar un estímulo desagradable tras una conducta para que disminuya',
      'Retirar un estímulo agradable tras una conducta para que deje de aparecer',
    ],
    correcta: 0,
    explicacion:
      'El refuerzo positivo añade algo agradable tras la conducta para que aumente su frecuencia: un elogio concreto tras un buen gesto técnico. El distractor más tentador es el refuerzo negativo, que también aumenta la conducta pero retirando algo desagradable: los dos son refuerzos y por eso comparten efecto. Dato para recordar: positivo y negativo indican si se añade o se quita, no si es bueno o malo.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['refuerzo positivo', 'condicionamiento operante', 'definición'],
  },
  {
    id: 'C8-008',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué diferencia al refuerzo negativo del castigo?',
    opciones: [
      'El refuerzo negativo aumenta la conducta y el castigo la disminuye',
      'El refuerzo negativo disminuye la conducta y el castigo la aumenta',
      'Son dos nombres distintos para el mismo procedimiento conductual',
      'El refuerzo negativo se aplica a niños y el castigo a deportistas adultos',
    ],
    correcta: 0,
    explicacion:
      'Todo refuerzo aumenta la conducta, sea positivo o negativo; el castigo la disminuye. El refuerzo negativo la aumenta retirando algo desagradable —quitar una tarea pesada cuando el equipo cumple— y por eso funciona. El distractor más tentador es el que los iguala, y es el error más extendido del módulo: la palabra negativo se lee como sinónimo de castigo. Dato para recordar: refuerzo siempre suma conducta, castigo siempre la resta.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['refuerzo negativo', 'castigo', 'condicionamiento operante'],
  },
  {
    id: 'C8-009',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada teoría o concepto con su autor.',
    izquierda: [
      'Condicionamiento clásico',
      'Condicionamiento operante',
      'Aprendizaje vicario o social',
      'Zona de desarrollo próximo',
      'Aprendizaje significativo',
    ],
    derecha: ['Pavlov', 'Skinner', 'Bandura', 'Vygotsky', 'Ausubel'],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
    explicacion:
      'Los pares que más se cruzan son los dos condicionamientos, porque las palabras clásico y operante se confunden, y Vygotsky con Piaget, que no aparece aquí pero se cuela en cuanto se habla de desarrollo. La forma de fijarlos es por el verbo: Pavlov asocia, Skinner refuerza, Bandura observa, Vygotsky acompaña y Ausubel ancla. Dato para recordar: cada autor cabe en un verbo.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['teorías del aprendizaje', 'autores', 'clasificación'],
  },
  {
    id: 'C8-010',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada etapa del ciclo vital con lo que predomina en ella.',
    izquierda: ['Infancia', 'Adolescencia', 'Adultez', 'Vejez'],
    derecha: [
      'Juego y desarrollo de los patrones motores básicos',
      'Construcción de la identidad y comparación con los iguales',
      'Consolidación del rendimiento y compatibilidad con la vida laboral',
      'Mantenimiento de la autonomía y de la salud funcional',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada etapa pide un enfoque distinto, y el par que más se falla es el de la adolescencia: se le atribuye la búsqueda del rendimiento cuando lo que domina es la construcción de la identidad y la comparación social, que es justo el motivo por el que ahí se concentra el abandono deportivo. Dato para recordar: en la infancia se juega, en la adolescencia se pertenece, en la adultez se rinde y en la vejez se conserva.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.1 — Ciclo vital y deporte',
    etiquetas: ['ciclo vital', 'clasificación', 'etapas'],
  },
  {
    id: 'C8-011',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las TRES técnicas psicológicas aplicables en una sesión de entrenamiento.',
    opciones: [
      'Establecimiento de objetivos',
      'Visualización o imaginería del gesto técnico',
      'Autoinstrucciones y palabras clave durante la ejecución',
      'Aumento sistemático de la carga externa en cada microciclo',
      'Medición de la frecuencia cardíaca de reserva antes de cada serie',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Objetivos, visualización y autoinstrucciones son herramientas psicológicas de uso directo en la sesión. Los dos distractores son procedimientos reales del entrenamiento pero pertenecen a la metodología y a la fisiología, no a la psicología: el de la carga es el más tentador porque sí influye en la motivación cuando la progresión es visible. Dato para recordar: es técnica psicológica si actúa sobre lo que el deportista piensa o siente, no sobre lo que hace su cuerpo.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['técnicas psicológicas', 'sesión', 'clasificación'],
  },
  {
    id: 'C8-012',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'El refuerzo negativo y el castigo producen el mismo efecto sobre la conducta.',
    correcta: false,
    explicacion:
      'Falso. El refuerzo negativo AUMENTA la conducta retirando un estímulo desagradable, y el castigo la DISMINUYE. Que los dos lleven una connotación desagradable no los iguala: lo que define a un refuerzo es que la conducta se repita más, y lo que define a un castigo es que se repita menos. La confusión nace de leer negativo como malo. Dato para recordar: la palabra positivo o negativo dice si se añade o se quita algo; refuerzo o castigo dice hacia dónde va la conducta.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['refuerzo negativo', 'castigo', 'conducta'],
  },
  {
    id: 'C8-013',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué relación existe entre el nivel de activación y el rendimiento deportivo?',
    opciones: [
      'Es una U invertida: hay un nivel óptimo, y por debajo y por encima el rendimiento cae',
      'Es lineal creciente: cuanta más activación tenga el deportista, mejor rendirá siempre',
      'Es lineal decreciente: el mejor rendimiento aparece con la activación más baja posible',
      'No existe ninguna relación estable entre activación y rendimiento en el deporte',
    ],
    correcta: 0,
    explicacion:
      'La relación tiene forma de U invertida: existe un punto óptimo de activación, y tanto la apatía como el exceso de nervios deterioran el rendimiento. El distractor más tentador es la relación lineal creciente, porque encaja con la cultura del «cuanto más motivado, mejor»: un deportista sobreactivado pierde precisión, se acelera y toma peores decisiones. Dato para recordar: activar a alguien que ya está pasado de vueltas empeora el resultado.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['activación mental', 'rendimiento', 'U invertida'],
  },
  {
    id: 'C8-014',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿De qué depende cuál es el nivel óptimo de activación para una tarea?',
    opciones: [
      'De la complejidad y la precisión que exige la tarea: a más finura, menos activación',
      'De la duración total de la sesión de entrenamiento programada para ese día',
      'De la edad del deportista, con independencia del tipo de gesto que ejecute',
      'Es el mismo para todas las tareas, siempre que el deportista esté descansado',
    ],
    correcta: 0,
    explicacion:
      'Cuanto más fina y compleja es la tarea, más bajo es su punto óptimo de activación: un tiro con arco pide calma y un lanzamiento de peso admite mucha más excitación. El distractor más tentador es el que lo hace depender de la edad, porque las diferencias individuales sí existen: lo que manda es la naturaleza de la tarea. Dato para recordar: el grito de ánimo que ayuda a un levantador puede arruinarle la serie a un tirador.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['activación mental', 'complejidad de la tarea', 'rendimiento'],
  },
  {
    id: 'C8-015',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Qué diferencia la motivación intrínseca de la extrínseca?',
    opciones: [
      'La intrínseca nace del disfrute de la actividad y la extrínseca de recompensas externas',
      'La intrínseca la aporta el entrenador y la extrínseca la aporta la familia del deportista',
      'La intrínseca aparece en el adulto y la extrínseca es propia de la etapa infantil',
      'La intrínseca depende del resultado obtenido y la extrínseca del esfuerzo invertido',
    ],
    correcta: 0,
    explicacion:
      'La motivación intrínseca viene del propio disfrute de la práctica y la extrínseca de premios, trofeos o reconocimiento. El distractor más tentador reparte las dos entre entrenador y familia, y confunde la fuente con quién la administra: cualquiera puede ofrecer recompensas externas, pero nadie puede regalar el gusto por jugar. Dato para recordar: la intrínseca sostiene la práctica a largo plazo, y abusar de premios externos puede llegar a erosionarla.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['motivación', 'intrínseca', 'extrínseca'],
  },
  {
    id: 'C8-016',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué condiciones necesita el aprendizaje vicario para producirse?',
    opciones: [
      'Que el observador atienda al modelo, retenga lo visto, pueda reproducirlo y tenga motivación',
      'Que el observador ejecute el gesto muchas veces antes de haber visto el modelo',
      'Que el modelo sea siempre el entrenador y nunca un compañero del grupo',
      'Que el observador reciba un premio material inmediatamente tras cada intento',
    ],
    correcta: 0,
    explicacion:
      'Bandura describe cuatro condiciones: atención, retención, reproducción motriz y motivación. Sin cualquiera de ellas la observación no se convierte en aprendizaje. El distractor más tentador es el que exige que el modelo sea el entrenador, porque parece lo lógico en una sesión: un compañero de nivel parecido suele ser mejor modelo, precisamente porque el observador se ve capaz de reproducir lo que hace. Dato para recordar: se aprende mirando a quien uno cree que puede imitar.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['aprendizaje vicario', 'Bandura', 'modelado'],
  },
  {
    id: 'C8-017',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Por qué un refuerzo debe ser específico e inmediato para resultar eficaz?',
    opciones: [
      'Porque así el deportista identifica qué conducta concreta se está reforzando',
      'Porque un refuerzo tardío resulta más costoso de administrar para el entrenador',
      'Porque los refuerzos genéricos consumen demasiado tiempo dentro de la sesión',
      'Porque de lo contrario el refuerzo se transforma automáticamente en un castigo',
    ],
    correcta: 0,
    explicacion:
      'Un «muy bien» dicho diez minutos después no le dice al deportista qué hizo bien; un «buen apoyo del pie en ese último saque» sí. La especificidad y la inmediatez son las que unen el refuerzo a la conducta concreta que se quiere consolidar. El distractor más tentador dice que el refuerzo se convierte en castigo, lo que confunde ineficacia con efecto contrario: un refuerzo vago no castiga, simplemente no enseña. Dato para recordar: refuerza el gesto, no a la persona.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['refuerzo positivo', 'feedback', 'aprendizaje'],
  },
  {
    id: 'C8-018',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES características de un buen objetivo deportivo.',
    opciones: [
      'Es concreto y medible, no una intención general',
      'Es alcanzable pero exige un esfuerzo real al deportista',
      'Se refiere sobre todo al proceso y no solo al resultado final',
      'Depende únicamente de factores externos, como la clasificación del rival',
      'Se plantea a muy largo plazo, sin metas intermedias que lo acompañen',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Un buen objetivo es concreto, exigente pero alcanzable y centrado en el proceso, que es lo que el deportista sí controla. El distractor más tentador es el de los factores externos: los objetivos de resultado son legítimos y motivan, pero si dependen del rival el deportista puede hacerlo todo bien y aun así fracasar. Y sin metas intermedias el objetivo lejano deja de guiar la sesión de hoy. Dato para recordar: fija lo que depende de él.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['objetivos', 'motivación', 'proceso'],
  },
  {
    id: 'C8-019',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Ordene las técnicas psicológicas según el momento de la sesión en que se aplican, de principio a fin.',
    elementos: [
      'Recordar los objetivos de la sesión y activar mentalmente al grupo',
      'Visualizar el gesto técnico justo antes de ejecutarlo',
      'Emplear autoinstrucciones y palabras clave durante la parte principal',
      'Dar feedback específico sobre lo ejecutado al cerrar la parte principal',
      'Aplicar respiración y relajación en la vuelta a la calma',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La sesión abre activando y fijando objetivos, ejecuta con visualización y autoinstrucciones, cierra la parte principal con feedback y termina relajando. El error más frecuente es colocar la relajación al principio confundiéndola con el calentamiento mental: al inicio se busca subir la activación al punto óptimo, no bajarla. Dato para recordar: se activa al empezar y se desactiva al terminar, igual que con el cuerpo.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['sesión', 'técnicas psicológicas', 'secuencia'],
  },
  {
    id: 'C8-020',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿En qué consiste la visualización o imaginería?',
    opciones: [
      'En representar mentalmente el gesto con detalle antes de ejecutarlo',
      'En observar repetidamente vídeos de deportistas de élite ejecutando ese gesto',
      'En analizar por escrito los errores técnicos cometidos en la sesión anterior',
      'En ejecutar el gesto muy despacio para percibir mejor cada una de sus fases',
    ],
    correcta: 0,
    explicacion:
      'La visualización es una representación mental del gesto, lo más vívida y detallada posible, que activa parcialmente los mismos circuitos que la ejecución real. El distractor más tentador es el vídeo, porque también es visual: mirar a otro es modelado, y visualizar es verse a uno mismo haciéndolo. Dato para recordar: no sustituye al entrenamiento físico, pero permite ensayar cuando no se puede entrenar, por ejemplo durante una lesión.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['visualización', 'imaginería', 'técnicas psicológicas'],
  },
  {
    id: 'C8-021',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'vf',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'La adolescencia es la etapa del ciclo vital en la que se concentra el mayor abandono de la práctica deportiva.',
    correcta: true,
    explicacion:
      'Verdadero. En la adolescencia se juntan la construcción de la identidad, la comparación constante con los iguales, la presión por el resultado y la aparición de otros intereses, y el resultado es el pico de abandono deportivo. Para el entrenador es la etapa en la que más cuenta el clima del grupo y la sensación de pertenencia, y en la que menos rinde la presión por la marca. Dato para recordar: en la adolescencia se compite contra la comparación, no solo contra el rival.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.1 — Ciclo vital y deporte',
    etiquetas: ['adolescencia', 'abandono deportivo', 'ciclo vital'],
  },
  {
    id: 'C8-022',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador quiere aplicar una técnica psicológica en la parte inicial de la sesión. ¿Cuál corresponde a ese momento?',
    opciones: [
      'Recordar los objetivos del día y elevar la activación del grupo hasta su punto óptimo',
      'Aplicar respiración diafragmática lenta para bajar el nivel de activación general',
      'Analizar en detalle los errores cometidos durante toda la parte principal',
      'Realizar una evaluación escrita del clima motivacional del grupo completo',
    ],
    correcta: 0,
    explicacion:
      'La parte inicial es el momento de fijar objetivos y activar: el deportista tiene que llegar a la parte principal con la cabeza donde toca. El distractor más tentador es la respiración lenta, que es una técnica válida pero de la vuelta a la calma: aplicarla al inicio baja una activación que justo hay que subir. Dato para recordar: al empezar se activa y al terminar se desactiva, igual que con el cuerpo.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['sesión', 'activación mental', 'aplicación'],
  },
  {
    id: 'C8-023',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado: '¿Qué técnica psicológica corresponde a la vuelta a la calma?',
    opciones: [
      'Respiración, relajación y una breve reflexión sobre lo trabajado en la sesión',
      'Activación mental intensa mediante gritos y consignas colectivas del grupo',
      'Visualización del gesto técnico inmediatamente antes de cada ejecución',
      'Establecimiento de los objetivos que se perseguirán durante la sesión',
    ],
    correcta: 0,
    explicacion:
      'La vuelta a la calma es el momento de bajar la activación y cerrar la sesión con una reflexión breve sobre lo trabajado, que consolida el aprendizaje. Los tres distractores son técnicas correctas de otros momentos —activación e objetivos al inicio, visualización antes de ejecutar—, y el de la activación intensa es el más contradictorio: dejaría al deportista revolucionado al salir. Dato para recordar: la sesión también se cierra mentalmente, no solo estirando.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['vuelta a la calma', 'relajación', 'aplicación'],
  },
  {
    id: 'C8-024',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'multiple',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un tirador con arco llega a la competición muy acelerado, hablando rápido y sin poder quedarse quieto. Seleccione las DOS intervenciones adecuadas.',
    opciones: [
      'Guiarle una respiración lenta y profunda antes de la tanda',
      'Llevar su atención a una rutina precompetitiva conocida y repetible',
      'Subir la música y animarle a gritos para aprovechar esa energía',
      'Recordarle lo importante que es este resultado para la clasificación',
      'Pedirle que ejecute más rápido de lo habitual para no pensar tanto',
    ],
    correctas: [0, 1],
    explicacion:
      'El tiro con arco es una tarea de máxima precisión, así que su activación óptima es baja: toca desactivar con respiración y anclar la atención en una rutina conocida. El distractor más tentador es aprovechar la energía subiendo la música, que sería razonable con un levantador y aquí empeora la puntería. Y recordarle lo que está en juego sube todavía más la activación. Dato para recordar: a más finura, menos activación.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['activación mental', 'precisión', 'intervención'],
  },
  {
    id: 'C8-025',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un niño falla el lanzamiento pero por primera vez coloca bien los pies. ¿Cuál es el refuerzo más eficaz?',
    opciones: [
      'Señalar de inmediato que la colocación de los pies fue correcta',
      'Decirle «muy bien» al terminar toda la serie de lanzamientos',
      'No decir nada, porque el lanzamiento no acabó entrando en la canasta',
      'Explicarle con detalle todos los aspectos técnicos que aún debe corregir',
    ],
    correcta: 0,
    explicacion:
      'El refuerzo eficaz es específico e inmediato: nombrar la conducta concreta que se quiere consolidar, aunque el resultado final no llegara. El distractor más tentador es el «muy bien» al final de la serie, que es lo que hace la mayoría: llega tarde y no identifica qué estuvo bien, así que el niño no sabe qué repetir. Y callar porque no entró refuerza la idea de que solo cuenta el resultado. Dato para recordar: refuerza el proceso, que es lo que él controla.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['refuerzo positivo', 'feedback', 'aplicación'],
  },
  {
    id: 'C8-026',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un club premiaba con dinero cada gol marcado por sus juveniles. Al retirar los premios por falta de presupuesto, varios jugadores que antes disfrutaban entrenando empiezan a saltarse sesiones y dicen que «ya no vale la pena».',
    enunciado: '¿Qué explica ese cambio de conducta?',
    opciones: [
      'La recompensa externa desplazó a la motivación intrínseca, que era la que sostenía la práctica',
      'La motivación intrínseca de esos jugadores nunca llegó a existir en ningún momento',
      'El descenso del rendimiento físico es el que provocó la pérdida del interés por entrenar',
      'Los jugadores necesitan simplemente una recompensa económica de mayor cuantía',
    ],
    correcta: 0,
    explicacion:
      'Cuando una actividad que se disfrutaba pasa a hacerse por dinero, el motivo se traslada al premio y la motivación intrínseca se erosiona: al retirar la recompensa no queda nada sosteniendo la conducta. El distractor más tentador es subir la cuantía, que es la reacción intuitiva del club y agrava el problema al reforzar la dependencia del premio. Dato para recordar: los premios externos se usan con cuidado, sobre todo en formación.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['motivación intrínseca', 'recompensas', 'formación'],
  },
  {
    id: 'C8-027',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Una levantadora de pesas rinde muy por debajo de lo habitual en los entrenamientos matinales: se la ve apática, sin intensidad y comete errores de concentración. En cambio, en las sesiones de la tarde rinde con normalidad.',
    enunciado: '¿Qué intervención corresponde probar primero?',
    opciones: [
      'Elevar su activación antes de la sesión matinal con calentamiento intenso, música y consignas',
      'Aplicar técnicas de relajación y respiración lenta antes de la sesión de la mañana',
      'Reducir la carga de las sesiones matinales hasta que recupere la sensación de rendimiento',
      'Cambiar por completo su plan de entrenamiento y renunciar a entrenar por la mañana',
    ],
    correcta: 0,
    explicacion:
      'La apatía y los errores de concentración apuntan a una activación por debajo del punto óptimo, y la halterofilia admite además una activación alta por ser un gesto potente y poco fino: toca subirla. El distractor más tentador es la relajación, porque es la técnica que uno asocia a «hay un problema psicológico», y aquí empujaría en la dirección contraria. Dato para recordar: la U invertida tiene dos lados, y hay que mirar en cuál está el deportista.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.3 — Técnicas psicológicas en la sesión',
    etiquetas: ['activación mental', 'U invertida', 'intervención'],
  },
  {
    id: 'C8-028',
    modulo: 'c8-psicologia-deporte',
    bloque: 'C',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un entrenador de natación quiere enseñar un viraje nuevo a un grupo de principiantes. Duda entre demostrarlo él mismo, con su técnica de exnadador de competición, o pedir a un compañero del grupo que acaba de aprenderlo que lo muestre.',
    enunciado: '¿Qué opción favorece más el aprendizaje vicario y por qué?',
    opciones: [
      'El compañero, porque un modelo de nivel cercano hace que el observador se vea capaz de reproducirlo',
      'El entrenador, porque cuanto más perfecta sea la ejecución del modelo más se aprende',
      'Ninguna de las dos, porque el aprendizaje vicario no funciona en principiantes',
      'Las dos por igual, porque en el modelado solo cuenta el número de repeticiones vistas',
    ],
    correcta: 0,
    explicacion:
      'Bandura exige atención, retención, reproducción y motivación, y un modelo de nivel cercano refuerza justamente las dos últimas: el observador cree que puede hacerlo y se anima a intentarlo. El distractor más tentador es el del modelo perfecto, porque suena a sentido común: una ejecución inalcanzable puede desmotivar y deja al principiante sin puntos de referencia intermedios. Dato para recordar: se aprende mirando a quien uno cree que puede imitar.',
    referencia: 'Cartilla 3, Tema 5, Subtema 5.2 — Teorías del aprendizaje y sus autores',
    etiquetas: ['aprendizaje vicario', 'modelado', 'Bandura'],
  },
];
