// content/banco/d1-conceptualizacion.ts
// Bloque D · Módulo 1 — Conceptualización y metodología del entrenamiento.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 5 de nivel 1 · 13 de nivel 2 · 7 de nivel 3
//   tipos      → 14 única · 3 caso · 3 emparejar · 2 ordenar · 2 múltiple · 1 V/F
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D1-001',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se define el entrenamiento deportivo?',
    opciones: [
      'Un proceso pedagógico, planificado y sistemático que aplica cargas para provocar adaptaciones',
      'El conjunto de sesiones de acondicionamiento físico que precede a una competencia',
      'La aplicación de ejercicios de alta intensidad hasta alcanzar la fatiga del deportista',
      'El estudio de los métodos y medios con los que se dirige la preparación deportiva',
    ],
    explicacion:
      'La definición se sostiene en cuatro palabras: proceso, pedagógico, planificado y sistemático, todas dirigidas a producir adaptación. El distractor más tentador es el último, porque describe algo real: pero eso es la metodología del entrenamiento, que estudia el cómo, no el entrenamiento en sí, que es el proceso que ocurre en la cancha. Dato para recordar: si la definición habla de estudiar métodos, están definiendo metodología, no entrenamiento.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.1 — El entrenamiento deportivo',
    etiquetas: ['entrenamiento deportivo', 'definición', 'conceptualización'],
    correcta: 0,
  },
  {
    id: 'D1-002',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'Un entrenador enumera los componentes del entrenamiento así: física, técnica, táctica y psicológica. ¿Cuál le falta?',
    opciones: [
      'La preparación teórica',
      'La preparación coordinativa',
      'La preparación competitiva',
      'La preparación biomecánica',
    ],
    explicacion:
      'Los cinco componentes son preparación física, técnica, táctica, psicológica y teórica, y el que casi siempre se cae de la lista es el teórico: el conocimiento que el deportista tiene de su propio deporte, su reglamento y las normas antidopaje. El distractor más tentador es la preparación coordinativa, porque suena a contenido real: lo es, pero las capacidades coordinativas están dentro de la preparación física, no son un sexto componente. Dato para recordar: si la lista tiene cuatro, casi siempre falta el teórico.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.3 — Componentes del entrenamiento',
    etiquetas: ['componentes', 'preparación teórica', 'clasificación'],
    correcta: 0,
  },
  {
    id: 'D1-003',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿De qué fecha es la Ley 2210, que regula el ejercicio del entrenador deportivo en Colombia?',
    opciones: [
      '23 de mayo de 2022',
      '23 de mayo de 2021',
      '12 de octubre de 2022',
      '4 de febrero de 2023',
    ],
    explicacion:
      'La Ley 2210 fue sancionada el 23 de mayo de 2022 y es la norma que reconoce y regula el ejercicio del entrenador deportivo en el país. El distractor más tentador es la misma fecha con el año 2021, porque el número de la ley y el día quedan idénticos y solo cambia el año: es el error clásico de quien memoriza a medias. Dato para recordar: la ley lleva 2210 y es de 2022; el número y el año arrancan igual.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.5 — La Ley 2210 de 2022',
    etiquetas: ['Ley 2210', 'fecha', 'normativa'],
    correcta: 0,
  },
  {
    id: 'D1-004',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'El nivel de altos logros de la Ley 2210 se asigna al entrenador en función de los años que lleve dirigiendo equipos.',
    correcta: false,
    explicacion:
      'Falso. El nivel describe el tipo de deportista que el entrenador está habilitado para dirigir, no la antigüedad de quien lo dirige. Un entrenador con veinte años de oficio en una escuela de iniciación está en el nivel de formación, y eso no es un demérito: es la descripción del proceso que conduce. La confusión nace de leer los niveles como un escalafón laboral. Dato para recordar: el nivel retrata al deportista, no la hoja de vida del entrenador.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'Ley 2210', 'altos logros'],
  },
  {
    id: 'D1-005',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      '¿Cuánta experiencia mínima debe acreditar quien se presenta a la evaluación de idoneidad del entrenador deportivo?',
    opciones: ['12 meses', '6 meses', '24 meses', '36 meses'],
    explicacion:
      'El mínimo exigido es de doce meses de experiencia acreditada en el deporte correspondiente. El distractor más tentador es 24 meses, porque suena a un requisito "serio" y muchos aspirantes asumen que se piden dos años: no es así, con un año cumplido ya se puede presentar. Los seis meses corresponden a la mitad del requisito real. Dato para recordar: los tres requisitos son mayor de 18 años, 12 meses de experiencia y aprobar la evaluación en una categoría.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.5 — La Ley 2210 de 2022',
    etiquetas: ['Ley 2210', 'requisitos', 'idoneidad'],
    correcta: 0,
  },
  {
    id: 'D1-006',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Ordene las cinco fases del proceso metodológico del entrenamiento.',
    elementos: [
      'Planificación — se fijan objetivos, periodos y calendario',
      'Programación — se reparten contenidos en mesociclos, microciclos y sesiones',
      'Ejecución — se dirige la sesión en la cancha',
      'Control — se miden y registran los datos mientras el proceso corre',
      'Evaluación — se juzga el resultado contra el objetivo y se decide el ajuste',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'El orden es planificación, programación, ejecución, control y evaluación, y es fijo. El cruce más frecuente es invertir control y evaluación: se asume que primero se juzga y después se mide, cuando el juicio necesita el dato que solo el control aporta. El otro cruce habitual es poner la programación antes de la planificación, es decir, repartir contenidos antes de haber fijado el objetivo. Dato para recordar: primero decides el destino, luego trazas la ruta, luego caminas, luego mides y al final juzgas.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.4 — Fases del proceso metodológico',
    etiquetas: ['fases', 'proceso metodológico', 'secuencia'],
  },
  {
    id: 'D1-007',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada componente del entrenamiento con lo que desarrolla.',
    izquierda: [
      'Preparación física',
      'Preparación técnica',
      'Preparación táctica',
      'Preparación psicológica',
      'Preparación teórica',
    ],
    derecha: [
      'Las capacidades condicionales y coordinativas',
      'La ejecución correcta y eficiente del gesto deportivo',
      'La toma de decisiones durante la competencia',
      'La motivación, la concentración y el control de la activación',
      'El conocimiento del reglamento y de las normas antidopaje',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
    explicacion:
      'El par que más se falla es técnica con táctica: la técnica es el gesto, la táctica es la decisión de cuándo y para qué usarlo. Un jugador puede tener un pase impecable y elegir mal el momento de darlo, y eso es un problema táctico, no técnico. El otro cruce habitual asigna a la preparación psicológica lo que en realidad es teórico, como conocer el reglamento. Dato para recordar: técnica es el cómo del gesto, táctica es el cuándo y el para qué.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.3 — Componentes del entrenamiento',
    etiquetas: ['componentes', 'clasificación', 'técnica', 'táctica'],
  },
  {
    id: 'D1-008',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué estudia la metodología del entrenamiento?',
    opciones: [
      'Los métodos, medios y procedimientos con los que se dirige el proceso de entrenamiento',
      'Las adaptaciones fisiológicas que produce la carga en los sistemas del organismo',
      'La secuencia de competencias oficiales que define el calendario de la temporada',
      'Los requisitos legales que habilitan a una persona para ejercer como entrenador',
    ],
    explicacion:
      'La metodología del entrenamiento es el cuerpo de conocimiento que estudia los métodos, medios y procedimientos con los que se conduce el proceso, y que justifica por qué se eligen unos y no otros. El distractor más tentador es el de las adaptaciones fisiológicas: son el efecto que se busca, pero estudiarlas es fisiología del ejercicio, no metodología. Dato para recordar: el entrenamiento es el qué se hace y la metodología es el cómo se hace y por qué ese cómo.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.2 — Metodología del entrenamiento',
    etiquetas: ['metodología', 'definición', 'conceptualización'],
    correcta: 0,
  },
  {
    id: 'D1-009',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada concepto con su definición.',
    izquierda: [
      'Entrenamiento deportivo',
      'Metodología del entrenamiento',
      'Planificación',
      'Programación',
    ],
    derecha: [
      'Proceso pedagógico, planificado y sistemático dirigido a la adaptación',
      'Cuerpo de conocimiento sobre los métodos y medios que dirigen ese proceso',
      'Fase en la que se fijan objetivos, periodos y calendario',
      'Fase en la que se reparten contenidos y dosis en sesiones concretas',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los dos pares que se cruzan son entrenamiento con metodología y planificación con programación, y por la misma razón: en ambos casos uno es la decisión general y el otro la herramienta concreta. La metodología no es entrenar, es saber con qué se entrena; la programación no es decidir el objetivo, es bajarlo a sesiones. Dato para recordar: planificar es decidir el destino, programar es trazar la ruta hasta él.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.2 — Metodología del entrenamiento',
    etiquetas: ['metodología', 'planificación', 'programación', 'clasificación'],
  },
  {
    id: 'D1-010',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      'Seleccione los TRES requisitos que debe cumplir quien se presenta a la evaluación de idoneidad del entrenador deportivo.',
    opciones: [
      'Ser mayor de 18 años',
      'Acreditar como mínimo 12 meses de experiencia',
      'Aprobar la evaluación en una categoría deportiva',
      'Contar con título universitario en un área afín al deporte',
      'Haber competido como deportista de alto rendimiento',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Los tres requisitos son la mayoría de edad, doce meses de experiencia acreditada y aprobar la evaluación en la categoría en la que se trabaja. El distractor más tentador es el título universitario: quien lo tiene acredita su idoneidad por esa vía y no necesita presentar la evaluación, así que exigirlo aquí invierte la lógica de la norma. Haber competido tampoco se pide: se evalúa la capacidad de entrenar, no la trayectoria como deportista. Dato para recordar: 18 años, 12 meses y una categoría.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.5 — La Ley 2210 de 2022',
    etiquetas: ['Ley 2210', 'requisitos', 'idoneidad'],
  },
  {
    id: 'D1-011',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿A qué tipo de deportista corresponde el nivel de perfeccionamiento?',
    opciones: [
      'Al deportista intermedio, ya especializado en su disciplina',
      'Al deportista principiante que está en etapa de iniciación',
      'Al deportista avanzado que prepara picos de forma para un calendario',
      'Al deportista recreativo que practica sin intención competitiva',
    ],
    explicacion:
      'El nivel de perfeccionamiento acompaña al deportista intermedio, el que ya se especializó en su disciplina y compite con regularidad. El distractor más tentador es el deportista avanzado, porque la palabra "perfeccionamiento" sugiere el escalón más alto: pero ese escalón es altos logros. El principiante corresponde al nivel de formación. Dato para recordar: el orden es formación, perfeccionamiento y altos logros, y equivale a principiante, intermedio y avanzado.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'perfeccionamiento', 'Ley 2210'],
    correcta: 0,
  },
  {
    id: 'D1-012',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué distingue la fase de planificación de la fase de programación?',
    opciones: [
      'La planificación fija objetivos y periodos; la programación los baja a contenidos y dosis concretas',
      'La planificación se hace en papel y la programación se hace directamente en la cancha',
      'La planificación corresponde al club y la programación es responsabilidad del deportista',
      'La planificación se aplica a la temporada completa y la programación solo a la competencia',
    ],
    explicacion:
      'La planificación toma las decisiones grandes: qué se quiere lograr, en cuántos periodos y para qué fecha. La programación traduce eso a mesociclos, microciclos y sesiones, con contenidos y dosis. El distractor más tentador es el último, porque introduce una diferencia de alcance temporal que suena razonable: pero la programación también cubre la temporada completa, solo que con otro grado de detalle. Dato para recordar: planificar es decidir el destino y programar es trazar la ruta.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.4 — Fases del proceso metodológico',
    etiquetas: ['planificación', 'programación', 'fases'],
    correcta: 0,
  },
  {
    id: 'D1-013',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué diferencia hay entre la fase de control y la fase de evaluación?',
    opciones: [
      'El control recoge el dato mientras el proceso corre; la evaluación lo compara con el objetivo y decide',
      'El control se aplica al deportista y la evaluación se aplica al método de entrenamiento empleado',
      'El control es responsabilidad del entrenador y la evaluación corresponde al cuerpo médico y directivo del club',
      'El control usa pruebas físicas de campo y la evaluación usa exclusivamente resultados de competencia',
    ],
    explicacion:
      'Controlar es medir: pulso, tiempos, tonelaje, sensación del deportista, registrados mientras el ciclo transcurre. Evaluar es emitir un juicio de valor comparando esos datos contra el objetivo planteado y decidir si se ajusta el plan. El distractor más tentador es el que reparte las dos fases entre personas distintas, porque en muchos clubes eso pasa: pero es una división de tareas, no la diferencia conceptual. Dato para recordar: controlar es medir y evaluar es juzgar.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.4 — Fases del proceso metodológico',
    etiquetas: ['control', 'evaluación', 'fases'],
    correcta: 0,
  },
  {
    id: 'D1-014',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Dos entrenadores ponen el mismo ejercicio. Uno explica por qué eligió ese método y no otro; el otro no sabe justificarlo. ¿Qué separa a los dos?',
    opciones: [
      'El primero aplica un criterio metodológico y el segundo solo reproduce una actividad',
      'El primero trabaja el componente teórico del entrenamiento y el segundo el componente técnico',
      'El primero está en la fase de programación y el segundo en la fase de ejecución',
      'El primero atiende la carga interna del deportista y el segundo solo la carga externa',
    ],
    explicacion:
      'La metodología es lo que permite justificar la elección de un método frente a sus alternativas; sin ella el ejercicio existe pero no hay proceso detrás. El distractor más tentador es el del componente teórico, porque también habla de conocimiento: pero ese componente se refiere a lo que sabe el deportista sobre su deporte, no al criterio con que el entrenador toma decisiones. Dato para recordar: un entrenador sin metodología pone ejercicios; uno con metodología pone ejercicios que puede defender.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.2 — Metodología del entrenamiento',
    etiquetas: ['metodología', 'criterio', 'conceptualización'],
    correcta: 0,
  },
  {
    id: 'D1-015',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué la definición de entrenamiento deportivo insiste en que el proceso debe ser sistemático?',
    opciones: [
      'Porque el estímulo aislado no produce adaptación: hace falta repetición ordenada en el tiempo',
      'Porque solo así el entrenador puede documentar su trabajo ante las autoridades deportivas',
      'Porque la sistematicidad garantiza que todas las sesiones tengan la misma intensidad',
      'Porque un proceso sistemático elimina la necesidad de controlar la carga interna',
    ],
    explicacion:
      'La adaptación es una respuesta a estímulos repetidos con orden y con lógica: una sesión suelta genera fatiga, no adaptación. Por eso la sistematicidad está en la definición y no es un adorno. El distractor más tentador afirma que sistemático significa intensidad constante: es justo lo contrario, un proceso sistemático varía la carga de forma deliberada y ordenada. Dato para recordar: proceso, pedagógico, planificado y sistemático son las cuatro palabras que cargan la definición.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.1 — El entrenamiento deportivo',
    etiquetas: ['entrenamiento deportivo', 'sistematicidad', 'adaptación'],
    correcta: 0,
  },
  {
    id: 'D1-016',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre los niveles de la Ley 2210.',
    opciones: [
      'El nivel de formación acompaña al deportista principiante en etapa de iniciación',
      'El nivel de perfeccionamiento prioriza la especialización y la competencia regular',
      'El nivel de altos logros construye picos de forma para un calendario definido',
      'El nivel se asigna según los años de experiencia acumulados por el entrenador',
      'El orden correcto de los niveles es perfeccionamiento, formación y altos logros',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tres primeras describen correctamente a quién dirige cada nivel y qué prioriza. La cuarta invierte el sentido de la clasificación: el nivel retrata al deportista que se puede dirigir, no la antigüedad de quien lo dirige. La quinta altera la secuencia, que siempre es formación, perfeccionamiento y altos logros, en ese orden, igual que la progresión de la vida deportiva. Dato para recordar: principiante, intermedio y avanzado, en ese orden y sin saltos.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'Ley 2210', 'formación', 'altos logros'],
  },
  {
    id: 'D1-017',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador lleva veintidós años trabajando con una escuela de fútbol de barrio. Sus deportistas tienen entre 8 y 12 años, entrenan tres veces por semana y participan en un torneo local al año. Él quiere presentarse a la evaluación de idoneidad y no sabe en qué nivel inscribirse.',
    enunciado: '¿Qué nivel corresponde al proceso que dirige?',
    opciones: [
      'Formación, porque el nivel describe al deportista que acompaña y no su antigüedad como entrenador',
      'Altos logros, porque veintidós años de experiencia acreditada lo ubican en la categoría más alta',
      'Perfeccionamiento, porque sus deportistas ya compiten en un torneo oficial federado cada año',
      'Cualquiera de los tres, porque el nivel lo elige libremente el entrenador en el momento de inscribirse',
    ],
    explicacion:
      'El nivel se define por el tipo de deportista que se dirige, no por la trayectoria de quien lo dirige: niños en iniciación, con base multilateral y técnica elemental, corresponden al nivel de formación. El distractor más tentador es altos logros, porque veintidós años parecen justificar la categoría más alta: pero esa lectura convierte el nivel en un escalafón laboral, que es exactamente lo que no es. Dato para recordar: el nivel retrata al deportista, no la hoja de vida.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'formación', 'Ley 2210', 'idoneidad'],
    correcta: 0,
  },
  {
    id: 'D1-018',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Ordene los tres niveles de la Ley 2210 según la progresión de la vida deportiva, del inicio al rendimiento máximo.',
    elementos: [
      'Formación — base multilateral, técnica elemental y gusto por el deporte',
      'Perfeccionamiento — especialización, trabajo técnico-táctico y competencia regular',
      'Altos logros — individualización de la carga y picos de forma para un calendario',
    ],
    ordenCorrecto: [0, 1, 2],
    explicacion:
      'La secuencia sigue el recorrido del deportista: primero se construye base amplia, después se especializa y compite con regularidad, y solo al final se persigue el rendimiento máximo con carga individualizada. El error frecuente es adelantar el perfeccionamiento antes de la formación, porque en el lenguaje corriente "formarse" suena a algo que se hace después de aprender lo básico. Dato para recordar: formación, perfeccionamiento y altos logros equivalen a principiante, intermedio y avanzado.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'secuencia', 'Ley 2210'],
  },
  {
    id: 'D1-019',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Un deportista domina su gesto técnico pero desconoce el reglamento y las normas antidopaje. ¿Qué componente del entrenamiento está descuidado?',
    opciones: [
      'La preparación teórica',
      'La preparación táctica',
      'La preparación psicológica',
      'La preparación técnica',
    ],
    explicacion:
      'La preparación teórica es el conocimiento que el deportista tiene de su propio deporte: reglamento, principios de la disciplina y normas antidopaje. Es el componente que más se descuida porque parece relleno, y no lo es: quien no conoce el reglamento pierde puntos y quien no conoce las normas antidopaje se sanciona solo. El distractor más tentador es la táctica, porque también implica conocimiento: pero la táctica es decisión en juego, no información normativa. Dato para recordar: reglamento y antidopaje son componente teórico.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.3 — Componentes del entrenamiento',
    etiquetas: ['componentes', 'preparación teórica', 'antidopaje'],
    correcta: 0,
  },
  {
    id: 'D1-020',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador anota semana a semana el tonelaje levantado y la frecuencia cardíaca de cada deportista, sin sacar todavía ninguna conclusión. ¿En qué fase del proceso está?',
    opciones: ['Control', 'Evaluación', 'Programación', 'Ejecución'],
    explicacion:
      'Recoger y registrar datos mientras el ciclo transcurre, sin emitir juicio, es exactamente la fase de control. El distractor más tentador es evaluación, porque uno asocia "medir" con "calificar": pero la evaluación empieza cuando esos datos se comparan contra el objetivo y se decide un ajuste, y aquí eso todavía no ocurrió. La programación repartiría contenidos y la ejecución dirigiría la sesión. Dato para recordar: controlar es medir, evaluar es juzgar; el juicio llega después del dato.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.4 — Fases del proceso metodológico',
    etiquetas: ['control', 'fases', 'proceso metodológico'],
    correcta: 0,
  },
  {
    id: 'D1-021',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Una entrenadora de 25 años lleva siete meses dirigiendo el equipo de voleibol de un colegio. No tiene título profesional en un área afín al deporte y quiere acreditarse como entrenadora deportiva este año.',
    enunciado: '¿Qué le impide presentarse ahora mismo a la evaluación de idoneidad?',
    opciones: [
      'Todavía no acredita los 12 meses de experiencia que exige la norma',
      'No cumple la edad mínima exigida para presentarse a la evaluación',
      'Sin título profesional en un área afín no puede acreditarse por ninguna vía',
      'El voleibol de colegio no cuenta como categoría deportiva para la evaluación',
    ],
    explicacion:
      'La entrenadora cumple la edad, pero le faltan cinco meses para llegar al mínimo de doce de experiencia acreditada; ese es el único requisito pendiente. El distractor más tentador es el del título profesional, porque invierte la lógica de la norma: el título es una vía alterna para quien lo tiene, no un requisito para quien se presenta a la evaluación. Precisamente la evaluación existe para quien no tiene título. Dato para recordar: 18 años, 12 meses y una categoría.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.5 — La Ley 2210 de 2022',
    etiquetas: ['Ley 2210', 'requisitos', 'idoneidad', 'experiencia'],
    correcta: 0,
  },
  {
    id: 'D1-022',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un grupo de atletas de 16 años lleva cuatro temporadas en el club. Ya eligieron su prueba, compiten en el calendario departamental cada mes y su entrenador quiere ordenar el trabajo del próximo semestre según el nivel que les corresponde.',
    enunciado: '¿Qué debe priorizar el trabajo de ese semestre?',
    opciones: [
      'La especialización en la prueba elegida y el trabajo técnico-táctico con competencia regular',
      'La base multilateral y la variedad de gestos, dejando la prueba elegida para más adelante',
      'La individualización total de la carga y la construcción de un pico de forma único al año',
      'La reducción de la competencia para concentrar todo el semestre en preparación física general',
    ],
    explicacion:
      'Atletas que ya eligieron prueba y compiten con regularidad están en el nivel de perfeccionamiento, cuya prioridad es la especialización y el trabajo técnico-táctico sostenido por un calendario de competencia. El distractor más tentador es el de individualizar y construir un pico único: eso corresponde a altos logros, y aplicarlo aquí adelanta una etapa que este grupo todavía no necesita. La base multilateral ya fue el trabajo de las temporadas anteriores. Dato para recordar: especializar es perfeccionamiento; afinar el pico es altos logros.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'perfeccionamiento', 'especialización'],
    correcta: 0,
  },
  {
    id: 'D1-023',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un jugador ejecuta bien todos los gestos en entrenamiento, pero en partido se bloquea y pierde la concentración cuando el marcador va en contra. ¿Qué componente hay que reforzar?',
    opciones: [
      'La preparación psicológica',
      'La preparación técnica',
      'La preparación física',
      'La preparación teórica',
    ],
    explicacion:
      'El gesto está resuelto en entrenamiento, así que el problema no es técnico: lo que falla es el manejo de la activación y de la concentración bajo presión de resultado, y eso es preparación psicológica. El distractor más tentador es la técnica, porque el error se ve en la ejecución: pero un gesto que sale bien en un contexto y mal en otro señala el contexto, no el gesto. Dato para recordar: si el gesto está aprendido y se cae solo bajo presión, el frente es psicológico.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.3 — Componentes del entrenamiento',
    etiquetas: ['componentes', 'preparación psicológica', 'competencia'],
    correcta: 0,
  },
  {
    id: 'D1-024',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado: 'Relacione cada acción del entrenador con la fase del proceso a la que pertenece.',
    izquierda: [
      'Define que el pico de forma debe caer en el campeonato de octubre',
      'Reparte los contenidos de las próximas cuatro semanas en sesiones',
      'Registra el pulso y el tonelaje de cada deportista al terminar la sesión',
      'Compara los tiempos de junio con el objetivo del ciclo y cambia el método',
    ],
    derecha: ['Planificación', 'Programación', 'Control', 'Evaluación'],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada acción lleva un verbo que delata su fase: definir el objetivo y la fecha es planificar, repartir contenidos en sesiones es programar, registrar datos es controlar y comparar contra el objetivo para ajustar es evaluar. El cruce más frecuente es asignar a evaluación la acción de registrar datos, porque medir se siente como calificar: pero la evaluación necesita que el dato ya exista. Dato para recordar: fijar, repartir, registrar y comparar son los cuatro verbos que separan las fases.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.4 — Fases del proceso metodológico',
    etiquetas: ['fases', 'proceso metodológico', 'aplicación'],
  },
  {
    id: 'D1-025',
    modulo: 'd1-conceptualizacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un entrenador recibe un grupo nuevo de niños de 9 años que nunca han practicado un deporte reglado. ¿Qué debe orientar su trabajo del primer año?',
    opciones: [
      'Una base motriz amplia y variada, con técnica elemental y adherencia al deporte',
      'La especialización temprana en una posición para ganar ventaja competitiva',
      'La individualización de la carga según los resultados de los tests iniciales',
      'La preparación de un pico de forma para el torneo municipal de fin de año',
    ],
    explicacion:
      'Niños que arrancan están en el nivel de formación, cuya prioridad es la base motriz amplia, la técnica elemental y que sigan queriendo entrenar el año siguiente. El distractor más tentador es la especialización temprana, porque promete resultados rápidos: los da al principio y estrecha el repertorio motriz justo cuando más barato sale ampliarlo. Individualizar la carga y construir picos son tareas de altos logros. Dato para recordar: en formación se siembra base, no resultado.',
    referencia: 'Cartilla 4, Tema 1, Subtema 1.6 — Niveles de formación del entrenador',
    etiquetas: ['niveles', 'formación', 'iniciación', 'multilateralidad'],
    correcta: 0,
  },
];
