// content/banco/d2-carga.ts
// Bloque D · Módulo 2 — La carga y sus componentes.
//
// 25 ítems. Reparto exigido por verificarCuotas con n = 25:
//   nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   dificultad → 5 de nivel 1 · 14 de nivel 2 · 6 de nivel 3
//   tipos      → 12 única · 4 cálculo · 3 caso · 2 múltiple · 2 emparejar · 1 ordenar · 1 V/F
//
// Los cuatro ítems de cálculo cubren lo más preguntable del módulo: densidad
// a partir de trabajo y descanso, volumen como tonelaje y carga de sesión.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D2-001',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué es la carga de entrenamiento?',
    opciones: [
      'El estímulo de trabajo que se aplica al deportista para provocar una adaptación',
      'El peso total que el deportista desplaza durante una sesión de fuerza',
      'La fatiga acumulada al final de un microciclo de entrenamiento',
      'El conjunto de ejercicios que componen la parte principal de la sesión',
    ],
    explicacion:
      'La carga es el estímulo que se aplica buscando adaptación: no es la lista de ejercicios ni el resultado de hacerlos, es la exigencia que suponen. El distractor más tentador es el peso total desplazado, porque en el gimnasio "carga" significa justamente eso: pero ese tonelaje es solo el volumen, es decir, uno de los cinco componentes de la carga. Dato para recordar: la carga no es lo que hizo el deportista, es lo que le exigió hacerlo.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.1 — Concepto de carga',
    etiquetas: ['carga', 'definición', 'adaptación'],
    correcta: 0,
  },
  {
    id: 'D2-002',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuáles son los cinco componentes de la carga de entrenamiento?',
    opciones: [
      'Volumen, intensidad, densidad, frecuencia y duración',
      'Volumen, intensidad, densidad, recuperación y adaptación',
      'Volumen, intensidad, potencia, frecuencia y duración',
      'Volumen, intensidad, densidad, frecuencia y especificidad',
    ],
    explicacion:
      'Los cinco componentes son volumen, intensidad, densidad, frecuencia y duración. El distractor más tentador cambia duración por adaptación y recuperación: las dos son consecuencias de aplicar la carga, no componentes con los que se dosifica. La especificidad tampoco cabe aquí, porque es un principio del entrenamiento, no una variable de dosificación. Dato para recordar: volumen e intensidad dan la magnitud de la carga; densidad, frecuencia y duración deciden cómo se reparte en el tiempo.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.2 — Componentes de la carga',
    etiquetas: ['componentes', 'carga', 'clasificación'],
    correcta: 0,
  },
  {
    id: 'D2-003',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se calcula la densidad de una serie de entrenamiento?',
    opciones: [
      'Tiempo de trabajo dividido entre el tiempo total, es decir trabajo más descanso',
      'Tiempo de trabajo dividido entre el tiempo de descanso de la serie',
      'Tiempo de descanso dividido entre el tiempo de trabajo de la serie',
      'Tiempo total de la sesión dividido entre el número de series y repeticiones realizadas',
    ],
    explicacion:
      'La densidad es la fracción del tiempo que se pasó trabajando: tiempo de trabajo sobre tiempo total, y el total incluye el trabajo además del descanso. El distractor más tentador divide el trabajo entre el descanso, que es la relación trabajo-descanso y no la densidad: con 30 s y 60 s daría 0,5 en vez de 0,33. Dato para recordar: el denominador siempre suma el trabajo; si te da más de 1, dividiste mal.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'fórmula', 'componentes'],
    correcta: 0,
  },
  {
    id: 'D2-004',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'La densidad de una serie se obtiene dividiendo el tiempo de trabajo entre el tiempo de descanso.',
    correcta: false,
    explicacion:
      'Falso. El denominador de la densidad es el tiempo total, que suma trabajo y descanso, no el descanso solo. Una serie de 30 s de trabajo con 60 s de descanso tiene densidad 30 ÷ 90 = 0,33, no 30 ÷ 60 = 0,5. La confusión viene de la notación de relación trabajo-descanso, que sí compara los dos tiempos entre sí, pero es otra cosa. Dato para recordar: la densidad es una fracción del total y por eso nunca puede pasar de 1.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'fórmula', 'error frecuente'],
  },
  {
    id: 'D2-005',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué es la carga externa?',
    opciones: [
      'El trabajo prescrito y ejecutado, medido fuera del organismo en kilos, kilómetros o series',
      'La respuesta que el organismo del deportista da al trabajo realizado',
      'El estrés que aportan factores ajenos al entrenamiento, como el estudio o el trabajo',
      'La carga que se aplica en condiciones ambientales adversas, fuera de las instalaciones',
    ],
    explicacion:
      'La carga externa es lo que el entrenador prescribe y puede medir sin tocar al deportista: kilos, kilómetros, series, repeticiones, velocidad. El distractor más tentador es el del estrés ajeno al entrenamiento, porque la palabra "externa" invita a pensar en lo que pasa fuera de la cancha: pero externa aquí significa fuera del organismo, no fuera del plan. Dato para recordar: la carga externa es lo que escribes en la planilla; la interna es lo que el cuerpo pagó por hacerlo.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.5 — Carga interna y carga externa',
    etiquetas: ['carga externa', 'definición', 'control'],
    correcta: 0,
  },
  {
    id: 'D2-006',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál de estos indicadores expresa carga interna?',
    opciones: [
      'El esfuerzo percibido que reporta el deportista al terminar',
      'El número de series y repeticiones programadas para la sesión',
      'La velocidad media de desplazamiento durante la sesión',
      'El tonelaje total levantado a lo largo del entrenamiento',
    ],
    explicacion:
      'El esfuerzo percibido es una respuesta del organismo al trabajo, así que expresa carga interna, igual que la frecuencia cardíaca o el lactato. Los otros tres son cantidades del trabajo prescrito y ejecutado, es decir, carga externa. El distractor más tentador es la velocidad media, porque parece reflejar el rendimiento del deportista: pero se mide fuera del organismo y no dice nada de lo que le costó. Dato para recordar: si se puede medir sin preguntar ni conectar nada al deportista, es carga externa.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.5 — Carga interna y carga externa',
    etiquetas: ['carga interna', 'RPE', 'control'],
    correcta: 0,
  },
  {
    id: 'D2-007',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada componente de la carga con la unidad en que se expresa.',
    izquierda: ['Volumen', 'Intensidad', 'Densidad', 'Frecuencia', 'Duración'],
    derecha: [
      'Kilómetros, kilos o series por repeticiones',
      'Porcentaje del 1RM o de la frecuencia cardíaca máxima',
      'Fracción entre el tiempo de trabajo y el tiempo total',
      'Número de sesiones por semana',
      'Minutos que se extiende la sesión o la serie',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
    explicacion:
      'El cruce más frecuente es volumen con duración, porque los dos se pueden expresar en minutos: la diferencia está en que el volumen mide la cantidad total de trabajo acumulado y la duración mide cuánto se extiende el estímulo. El otro cruce habitual es frecuencia con densidad, porque las dos hablan de repartir en el tiempo: frecuencia son sesiones por semana, densidad es la proporción de trabajo dentro de una sesión. Dato para recordar: frecuencia mira el calendario, densidad mira el cronómetro.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.2 — Componentes de la carga',
    etiquetas: ['componentes', 'unidades', 'clasificación'],
  },
  {
    id: 'D2-008',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es el rango de valores de la escala original de Borg para el esfuerzo percibido?',
    opciones: ['De 6 a 20', 'De 0 a 10', 'De 1 a 15', 'De 0 a 100'],
    explicacion:
      'La escala original de Borg va de 6 a 20, y arranca en 6 porque se diseñó para que el valor multiplicado por diez se aproximara a la frecuencia cardíaca de un adulto joven sano: 6 corresponde al reposo y 20 al esfuerzo máximo. El distractor más tentador es el 0 a 10, que también existe pero es la escala CR-10, una versión posterior más simple de explicar. Dato para recordar: la original va de 6 a 20 y la CR-10 de 0 a 10; la que se usa para carga de sesión es la CR-10.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.6 — Escala de Borg',
    etiquetas: ['Borg', 'RPE', 'carga interna'],
    correcta: 0,
  },
  {
    id: 'D2-009',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione los TRES indicadores que corresponden a carga interna.',
    opciones: [
      'La frecuencia cardíaca durante la sesión',
      'La concentración de lactato en sangre',
      'El esfuerzo percibido reportado por el deportista',
      'Los kilos levantados en cada serie',
      'Los kilómetros recorridos durante la sesión',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Frecuencia cardíaca, lactato y esfuerzo percibido son respuestas del organismo al trabajo, así que expresan carga interna. Kilos y kilómetros son cantidades del trabajo ejecutado, medibles sin consultar al deportista, y por tanto carga externa. El distractor más tentador es el lactato para quien lo asocia solo al laboratorio y no lo reconoce como indicador de campo: lo es, y de los más directos. Dato para recordar: si el dato sale del cuerpo, es interna; si sale de la planilla, es externa.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.5 — Carga interna y carga externa',
    etiquetas: ['carga interna', 'carga externa', 'indicadores'],
  },
  {
    id: 'D2-010',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué establece la relación inversa entre volumen e intensidad?',
    opciones: [
      'Que a mayor intensidad el volumen tolerable baja, y a mayor volumen la intensidad sostenible baja',
      'Que volumen e intensidad deben mantenerse siempre en la misma proporción dentro del ciclo de trabajo',
      'Que el volumen se incrementa en la misma medida en que se incrementa la intensidad',
      'Que la intensidad solo puede subir cuando el volumen ya alcanzó su valor máximo planificado',
    ],
    explicacion:
      'La relación inversa dice que los dos grandes componentes se compensan: subir uno obliga a bajar el otro, porque la capacidad total de trabajo tiene un techo fisiológico. El distractor más tentador es el que exige subir el volumen al máximo antes de tocar la intensidad, porque suena a progresión ordenada: pero convierte una relación de compensación en una secuencia obligatoria que no existe. Dato para recordar: nadie levanta el 95 % de su 1RM veinte series ni corre un maratón a ritmo de 400 metros.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.3 — Volumen e intensidad',
    etiquetas: ['volumen', 'intensidad', 'relación inversa'],
    correcta: 0,
  },
  {
    id: 'D2-011',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada concepto de la carga con su definición.',
    izquierda: ['Carga externa', 'Carga interna', 'Volumen', 'Intensidad'],
    derecha: [
      'El trabajo prescrito y ejecutado, medido fuera del organismo',
      'La respuesta que el organismo da a ese trabajo',
      'La cantidad total de trabajo realizado',
      'El grado de exigencia de ese trabajo',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'El par que más se cruza es carga externa con volumen, porque los dos se miden en kilos y kilómetros: la diferencia es de categoría, no de unidad. El volumen es un componente de la dosificación; la carga externa es la naturaleza de todo lo que se mide fuera del organismo, y el volumen es solo una de sus expresiones. Dato para recordar: externa e interna describen de dónde sale el dato; volumen e intensidad describen cuánto y cuán fuerte.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.5 — Carga interna y carga externa',
    etiquetas: ['carga externa', 'carga interna', 'volumen', 'intensidad'],
  },
  {
    id: 'D2-012',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Dos deportistas hacen exactamente la misma sesión y uno termina mucho más fatigado que el otro. ¿Cómo se explica?',
    opciones: [
      'La carga externa fue idéntica, pero la carga interna depende del estado de cada organismo',
      'La carga interna fue idéntica y lo que cambió fue el volumen realizado por cada uno',
      'Uno de los dos ejecutó mal el gesto técnico y por eso gastó más energía de la prevista',
      'La sesión estuvo mal programada, porque una misma carga debería fatigar por igual',
    ],
    explicacion:
      'La carga externa es la misma para todos —diez repeticiones a 60 kg son diez repeticiones a 60 kg—, pero la carga interna depende del sueño, el estado de salud, el nivel de entrenamiento, el calor y la altitud. El distractor más tentador es el del error técnico, porque también explicaría un gasto mayor: puede ocurrir, pero no hace falta para explicar la diferencia, que aparece incluso con ejecución idéntica. Dato para recordar: la carga externa se planifica, la carga interna se controla.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.5 — Carga interna y carga externa',
    etiquetas: ['carga interna', 'carga externa', 'individualización'],
    correcta: 0,
  },
  {
    id: 'D2-013',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un entrenador mantiene el peso y las repeticiones de siempre, pero recorta el descanso entre series a la mitad. ¿Qué componente de la carga modificó?',
    opciones: [
      'La densidad, que sube porque el trabajo ocupa una fracción mayor del tiempo total',
      'El volumen, que sube porque la sesión concentra más trabajo por unidad de tiempo',
      'La intensidad, que sube porque el deportista debe levantar el peso más fatigado',
      'La frecuencia, que sube porque las series se suceden con mayor rapidez',
    ],
    explicacion:
      'Recortar el descanso sin tocar peso ni repeticiones cambia la densidad: el mismo trabajo ocupa ahora una fracción mayor del tiempo total. El distractor más tentador es la intensidad, porque la sesión se siente más dura: pero la intensidad es el grado de exigencia del trabajo en sí, y el peso levantado no cambió. El volumen tampoco, porque las series y repeticiones son las mismas. Dato para recordar: la densidad es la palanca que sube la carga sin tocar nada más.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'descanso', 'componentes'],
    correcta: 0,
  },
  {
    id: 'D2-014',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'La equivalencia entre el esfuerzo percibido de la escala original de Borg y la frecuencia cardíaca es solo aproximada. ¿Por qué?',
    opciones: [
      'Porque se calibró en adultos jóvenes sanos y falla con la edad, la medicación o el calor',
      'Porque la escala original mide de 0 a 10 y hay que convertirla antes de multiplicar',
      'Porque el esfuerzo percibido corresponde a carga externa y la frecuencia cardíaca a carga interna',
      'Porque la frecuencia cardíaca solo se estabiliza después de los primeros veinte minutos',
    ],
    explicacion:
      'La regla de multiplicar el valor por diez se calibró sobre adultos jóvenes sanos, y se desvía en personas mayores, en quien toma betabloqueantes y en condiciones de calor o deshidratación, donde el pulso se dispara sin que la percepción suba igual. El distractor más tentador confunde las dos escalas: la original va de 6 a 20 y es justamente la que admite la multiplicación; la de 0 a 10 es la CR-10. Dato para recordar: la equivalencia orienta, no prescribe.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.6 — Escala de Borg',
    etiquetas: ['Borg', 'RPE', 'frecuencia cardíaca', 'carga interna'],
    correcta: 0,
  },
  {
    id: 'D2-015',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre el volumen y la intensidad.',
    opciones: [
      'Juntos definen la magnitud de la carga de entrenamiento',
      'A mayor intensidad, el volumen que se puede tolerar es menor',
      'El trabajo de fuerza máxima combina intensidad alta con volumen bajo',
      'Subir volumen e intensidad a la vez multiplica la adaptación conseguida',
      'La intensidad se expresa en kilómetros recorridos o kilos totales levantados',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tres primeras describen bien la pareja: son los dos grandes componentes, se compensan entre sí y la fuerza máxima es el ejemplo canónico de intensidad alta con volumen bajo. La cuarta es el error de programación más común en campo: subir ambos a la vez no multiplica la adaptación, acumula fatiga sin estímulo claro. La quinta cambia las unidades de sitio, porque kilómetros y kilos totales son volumen. Dato para recordar: si sube uno, baja el otro.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.3 — Volumen e intensidad',
    etiquetas: ['volumen', 'intensidad', 'magnitud', 'relación inversa'],
  },
  {
    id: 'D2-016',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene las siguientes series de menor a mayor densidad.',
    elementos: [
      'Relación 1 : 3 — 30 s de trabajo y 90 s de descanso',
      'Relación 1 : 2 — 30 s de trabajo y 60 s de descanso',
      'Relación 1 : 1 — 30 s de trabajo y 30 s de descanso',
      'Relación 2 : 1 — 60 s de trabajo y 30 s de descanso',
    ],
    ordenCorrecto: [0, 1, 2, 3],
    explicacion:
      'Las densidades son 0,25, 0,33, 0,50 y 0,67: cuanto más descanso por unidad de trabajo, menor densidad. El error más frecuente aparece en la relación 1 : 3, donde muchos calculan un tercio en vez de un cuarto porque olvidan sumar el tiempo de trabajo al denominador. La regla que lo evita es directa: en una relación 1 : n la densidad vale 1 dividido entre 1 más n. Dato para recordar: más descanso significa menos densidad, siempre.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'relación trabajo-descanso', 'secuencia'],
  },
  {
    id: 'D2-017',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador de atletismo decide que su grupo va a mejorar más rápido y sube al mismo tiempo el kilometraje semanal de 40 a 60 km y el ritmo de todas las series. A las cinco semanas los atletas llegan fatigados a cada sesión, no completan las series de calidad y sus marcas empeoran.',
    enunciado: '¿Qué error de dosificación cometió?',
    opciones: [
      'Subió volumen e intensidad a la vez, ignorando la relación inversa entre los dos',
      'Aumentó la densidad de las sesiones sin modificar el descanso entre repeticiones',
      'Confundió la carga interna con la carga externa al programar el kilometraje',
      'Mantuvo constante la frecuencia semanal en lugar de añadir sesiones nuevas',
    ],
    explicacion:
      'Volumen e intensidad se compensan: subirlos juntos supera el techo de trabajo que el organismo puede asimilar y el resultado es fatiga acumulada sin adaptación. El distractor más tentador es el de la densidad, porque el cuadro final se parece al de una sesión demasiado apretada: pero el entrenador no tocó los descansos, tocó los dos grandes componentes. Dato para recordar: cuando subas uno de los dos, baja el otro; ese es el ajuste que faltó.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.3 — Volumen e intensidad',
    etiquetas: ['relación inversa', 'volumen', 'intensidad', 'fatiga'],
    correcta: 0,
  },
  {
    id: 'D2-018',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué componentes de la carga determinan su magnitud?',
    opciones: [
      'El volumen y la intensidad',
      'La densidad y la frecuencia',
      'La duración y la frecuencia',
      'La intensidad y la densidad',
    ],
    explicacion:
      'La magnitud de la carga la definen el volumen y la intensidad: cuánto trabajo y con qué grado de exigencia. Los otros tres componentes deciden cómo se reparte esa magnitud en el tiempo, no cuánta es. El distractor más tentador empareja intensidad con densidad, porque las dos hacen que la sesión se sienta dura: pero la densidad organiza el tiempo dentro de la sesión, no añade magnitud. Dato para recordar: volumen e intensidad dan la magnitud; densidad, frecuencia y duración la distribuyen.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.2 — Componentes de la carga',
    etiquetas: ['magnitud', 'volumen', 'intensidad', 'componentes'],
    correcta: 0,
  },
  {
    id: 'D2-019',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Un entrenador escribe en su planilla una relación trabajo-descanso de 1 : 3 y anota que la densidad es del 33 %. ¿Dónde está el error?',
    opciones: [
      'La densidad es del 25 %: el denominador suma el trabajo, así que son 4 partes y no 3',
      'La densidad es del 33 %: la relación 1 : 3 significa un tercio de trabajo y está bien anotada',
      'La densidad es del 75 %: hay que dividir el descanso entre el tiempo total de la serie',
      'La densidad no puede calcularse a partir de una relación sin conocer los segundos exactos',
    ],
    explicacion:
      'En una relación 1 : 3 hay una parte de trabajo y tres de descanso, es decir cuatro partes en total: la densidad es 1 ÷ 4 = 0,25, o sea 25 %. El distractor más tentador es justamente el 33 %, que sale de dividir 1 entre 3 y es el error que comete casi todo el que va rápido. La regla general lo resuelve: en una relación 1 : n la densidad vale 1 ÷ (1 + n). Dato para recordar: la relación compara los tiempos entre sí; la densidad los compara contra el total.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'relación trabajo-descanso', 'error frecuente'],
    correcta: 0,
  },
  {
    id: 'D2-020',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Una serie consiste en 30 segundos de trabajo seguidos de 60 segundos de descanso. Calcule la densidad y exprese el resultado en porcentaje.',
    respuesta: 33.3,
    tolerancia: 0.7,
    unidad: '%',
    pasos: [
      'Tiempo total = tiempo de trabajo + tiempo de descanso = 30 + 60 = 90 s',
      'Densidad = tiempo de trabajo ÷ tiempo total = 30 ÷ 90 = 0,333',
      'Expresado en porcentaje: 0,333 × 100 = 33,3 %',
    ],
    explicacion:
      'El único paso que hay que cuidar es el denominador: son 90 segundos, no 60. Quien divide 30 entre el descanso obtiene 0,5 y responde 50 %, que es el error más repetido de todo el módulo. La densidad es la fracción del tiempo que se pasó trabajando, y por eso nunca puede superar el 100 %. Dato para recordar: 30 s de trabajo con 60 s de descanso dan 33 %, y bajar ese descanso a 30 s lo sube a 50 %.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'cálculo', 'trabajo-descanso'],
  },
  {
    id: 'D2-021',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un circuito se organiza con 45 segundos de trabajo en cada estación y 15 segundos de transición para pasar a la siguiente. Calcule la densidad del circuito en porcentaje.',
    respuesta: 75,
    tolerancia: 1,
    unidad: '%',
    pasos: [
      'Tiempo total por estación = 45 s de trabajo + 15 s de transición = 60 s',
      'Densidad = 45 ÷ 60 = 0,75',
      'Expresado en porcentaje: 0,75 × 100 = 75 %',
    ],
    explicacion:
      'Una densidad del 75 % es muy alta: el deportista pasa tres cuartas partes del circuito trabajando, y eso convierte la sesión en un estímulo metabólico exigente aunque cada estación se ejecute a intensidad moderada. El error habitual es leer la transición como si no contara y responder 100 %, o dividir 45 entre 15 y obtener un valor imposible mayor que 1. Dato para recordar: en los circuitos la densidad alta es la que hace el trabajo, no el peso.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'cálculo', 'circuito'],
  },
  {
    id: 'D2-022',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un deportista realiza 4 series de 8 repeticiones con 60 kg en sentadilla. Calcule el volumen de trabajo expresado como tonelaje total desplazado.',
    respuesta: 1920,
    tolerancia: 20,
    unidad: 'kg',
    pasos: [
      'Repeticiones totales = 4 series × 8 repeticiones = 32 repeticiones',
      'Tonelaje = repeticiones totales × peso desplazado = 32 × 60 kg',
      'Tonelaje = 1920 kg',
    ],
    explicacion:
      'El tonelaje es la forma más usada de expresar volumen en el trabajo de fuerza: series por repeticiones por peso. El error frecuente es multiplicar solo series por peso y responder 240 kg, olvidando las repeticiones, que son las que acumulan el trabajo real. Conviene notar que este número no dice nada sobre la intensidad: 1920 kg se pueden acumular con 60 kg o con 20 kg y más repeticiones. Dato para recordar: el tonelaje mide cuánto, no cuán fuerte.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.3 — Volumen e intensidad',
    etiquetas: ['volumen', 'tonelaje', 'cálculo', 'fuerza'],
  },
  {
    id: 'D2-023',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Al terminar una sesión de 75 minutos, un deportista califica su esfuerzo con un 7 en la escala de 0 a 10. Calcule la carga de esa sesión en unidades arbitrarias.',
    respuesta: 525,
    tolerancia: 5,
    unidad: 'UA',
    pasos: [
      'Carga de sesión = RPE en escala 0–10 × duración en minutos',
      'Carga = 7 × 75 min',
      'Carga = 525 unidades arbitrarias',
    ],
    explicacion:
      'La carga de sesión multiplica el esfuerzo percibido por los minutos, y es la forma más barata de cuantificar carga interna sin comprar un solo aparato. El error habitual es usar el valor de la escala original de Borg, de 6 a 20, en lugar de la de 0 a 10: con un 15 el resultado sería 1125 y dejaría de ser comparable con el resto del registro. Dato para recordar: para carga de sesión se usa la escala de 0 a 10, siempre la misma.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.6 — Escala de Borg',
    etiquetas: ['carga de sesión', 'RPE', 'cálculo', 'carga interna'],
  },
  {
    id: 'D2-024',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Una entrenadora programa hipertrofia para un grupo de jugadores. Prescribe 4 series de 10 repeticiones al 75 % del 1RM, pero deja 4 minutos de descanso entre series porque le sobra tiempo de gimnasio.',
    enunciado: '¿Qué ajuste corresponde hacer para que la sesión responda al objetivo?',
    opciones: [
      'Recortar el descanso a un rango de 30 s a 1 min 30 s para subir la densidad',
      'Subir el peso por encima del 85 % del 1RM manteniendo el descanso de 4 minutos',
      'Aumentar a 8 series de 10 repeticiones sin modificar el descanso entre series',
      'Bajar a 6 repeticiones por serie para ajustar el volumen al descanso programado',
    ],
    explicacion:
      'El peso y las repeticiones ya son los del rango de hipertrofia; lo que está fuera de sitio es el descanso, porque cuatro minutos corresponden al trabajo de fuerza máxima. Recortarlo sube la densidad y devuelve la sesión al estímulo buscado. El distractor más tentador es subir el peso por encima del 85 %, porque parece "entrenar más": eso cambia el objetivo a fuerza máxima en vez de corregir la sesión. Dato para recordar: en hipertrofia el descanso va de 30 s a 1 min 30 s.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.4 — Densidad',
    etiquetas: ['densidad', 'hipertrofia', 'descanso', 'prescripción'],
    correcta: 0,
  },
  {
    id: 'D2-025',
    modulo: 'd2-carga',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un equipo entrena con la misma planilla desde hace tres semanas. Dos jugadores reportan un esfuerzo percibido de 5 sobre 10 y otro reporta 9 en las mismas sesiones. El tercero duerme cinco horas por noche porque trabaja de madrugada y llega directo al entrenamiento.',
    enunciado: '¿Qué lectura corresponde hacer y qué decisión se deriva?',
    opciones: [
      'La carga externa es igual para los tres, pero la interna del tercero es mucho mayor: hay que individualizarle la carga',
      'La planilla está mal calculada, porque una misma carga externa debe producir la misma carga interna',
      'El tercero está exagerando su reporte, así que conviene sustituir el esfuerzo percibido por el tonelaje',
      'La diferencia se corrige subiendo la carga externa de los dos primeros hasta igualar los reportes',
    ],
    explicacion:
      'Una misma carga externa produce cargas internas distintas según el estado de cada deportista, y dormir cinco horas es exactamente el tipo de factor que dispara la respuesta interna sin que cambie una sola línea de la planilla. Por eso la externa se planifica y la interna se controla e individualiza. El distractor más tentador propone descartar el reporte por poco fiable: el esfuerzo percibido es subjetivo por diseño, y ahí está su valor. Dato para recordar: el reporte discordante es información, no ruido.',
    referencia: 'Cartilla 4, Tema 2, Subtema 2.5 — Carga interna y carga externa',
    etiquetas: ['carga interna', 'carga externa', 'individualización', 'RPE'],
    correcta: 0,
  },
];
