// content/banco/d3-fuerza.ts
// D3 · Capacidad física: fuerza. 25 ítems.
//
// Reparto verificado contra verificarCuotas (bloque D, mínimo 25):
//   Nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   Dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   Tipos      → 13 única · 3 caso · 3 cálculo · 2 múltiple · 2 emparejar
//                · 1 ordenar · 1 V/F
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D3-001',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se define la fuerza como capacidad física?',
    opciones: [
      'La capacidad de generar tensión muscular para vencer o contrarrestar una resistencia externa',
      'La capacidad de ejecutar un gesto en el menor tiempo posible desde la señal de salida',
      'La capacidad de sostener un esfuerzo prolongado retrasando la aparición de la fatiga',
      'La capacidad de alcanzar la mayor amplitud posible en el recorrido de una articulación',
    ],
    correcta: 0,
    explicacion:
      'La fuerza es la capacidad de generar tensión muscular contra una resistencia externa. La palabra que ordena todo el módulo es tensión, no desplazamiento: por eso una contracción isométrica, en la que nada se mueve, es trabajo de fuerza pleno. El distractor más tentador es el de sostener el esfuerzo retrasando la fatiga, que es la definición de resistencia: se cuela porque la fuerza resistencia comparte apellido con ella, pero lo que se sostiene ahí es una tensión, no un ritmo. Dato para recordar: fuerza es tensión, resistencia es tiempo, velocidad es tiempo mínimo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.1 — Definición y clasificación de la fuerza',
    etiquetas: ['fuerza', 'definición', 'capacidades físicas'],
  },
  {
    id: 'D3-002',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Con qué porcentaje del 1RM se trabaja la fuerza máxima?',
    opciones: [
      'Más del 85 % del 1RM',
      'Entre el 70 y el 85 % del 1RM',
      'Entre el 50 y el 70 % del 1RM',
      'Por debajo del 50 % del 1RM',
    ],
    correcta: 0,
    explicacion:
      'La fuerza máxima se entrena por encima del 85 % del 1RM, con menos de 6 repeticiones y descansos de 2 a 5 minutos. El distractor más tentador es el 70–85 %, que es la franja de hipertrofia: los dos rangos se tocan en el 85 % y mucha gente los junta en un único "trabajo pesado", cuando producen adaptaciones distintas —nerviosa arriba, estructural abajo—. Por debajo del 70 % ya se entra en resistencia muscular. Dato para recordar: la frontera de los 85 % separa la ganancia de fuerza de la ganancia de tamaño.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['fuerza máxima', '1RM', 'intensidad'],
  },
  {
    id: 'D3-003',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuántas repeticiones por serie corresponden al trabajo de hipertrofia?',
    opciones: [
      'Entre 6 y 12 repeticiones',
      'Menos de 6 repeticiones',
      'Entre 15 y 20 repeticiones',
      'Más de 25 repeticiones',
    ],
    correcta: 0,
    explicacion:
      'La hipertrofia se trabaja entre 6 y 12 repeticiones, que es lo que dura una serie de 20 a 40 segundos con cargas del 70 al 85 % del 1RM. El distractor más tentador es "menos de 6", que corresponde a fuerza máxima: se confunde porque en el gimnasio se asocia hipertrofia con levantar mucho, y lo que hace crecer al músculo no es la carga más alta sino el tiempo de tensión con carga alta. De 15 repeticiones en adelante el trabajo ya es de resistencia muscular. Dato para recordar: 6 y 12 son las fronteras de la hipertrofia por arriba y por abajo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['hipertrofia', 'repeticiones', '1RM'],
  },
  {
    id: 'D3-004',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'La fuerza resistencia se entrena con cargas superiores al 85 % del 1RM y descansos de 2 a 5 minutos entre series.',
    correcta: false,
    explicacion:
      'Falso. Esos valores son los de la fuerza máxima. La fuerza resistencia va por el lado contrario de la tabla: cargas por debajo del 70 % del 1RM, 15 repeticiones o más, series de 45 segundos en adelante y descansos de hasta 30 segundos. La confusión nace de leer las columnas de la tabla como datos sueltos en lugar de como una fila coherente: si la carga es máxima, las repeticiones tienen que ser pocas y el descanso largo, por pura fisiología. Dato para recordar: descanso largo y carga alta van juntos; descanso corto y carga baja también.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['fuerza resistencia', 'descanso', '1RM'],
  },
  {
    id: 'D3-005',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuánto descanso se prescribe entre series de fuerza máxima?',
    opciones: [
      'De 2 a 5 minutos',
      'De 30 segundos a 1 minuto y medio',
      'Hasta 30 segundos',
      'De 10 a 15 segundos',
    ],
    correcta: 0,
    explicacion:
      'La fuerza máxima exige de 2 a 5 minutos entre series porque lo que se agota con cargas de más del 85 % es la fosfocreatina y el sistema nervioso, y la fosfocreatina tarda minutos en reponerse. El distractor más tentador es el de 30 segundos a minuto y medio, que es el descanso de hipertrofia: ahí el descanso corto es parte del estímulo porque mantiene el ambiente metabólico, mientras que en fuerza máxima ese mismo descanso arruina la serie siguiente. Dato para recordar: en fuerza máxima el descanso no es pérdida de tiempo, es parte de la carga.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['fuerza máxima', 'descanso', 'fosfocreatina'],
  },
  {
    id: 'D3-006',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada objetivo de entrenamiento con su prescripción de carga y descanso.',
    izquierda: ['Fuerza máxima', 'Hipertrofia', 'Resistencia muscular', 'Fuerza explosiva'],
    derecha: [
      'Más del 85 % del 1RM, menos de 6 repeticiones, 2 a 5 min de descanso',
      '70–85 % del 1RM, 6 a 12 repeticiones, 30 s a 1 min 30 s de descanso',
      'Por debajo del 70 % del 1RM, 15 repeticiones o más, hasta 30 s de descanso',
      'Cargas medias movidas a la máxima velocidad posible, con descanso completo',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada objetivo tiene una fila completa y coherente: carga, repeticiones y descanso se mueven juntos. El cruce que más se falla es fuerza máxima con hipertrofia, porque los dos suenan a "pesado"; los separa que la fuerza máxima busca adaptación nerviosa con series muy cortas y descanso largo, y la hipertrofia busca tiempo de tensión con descanso corto. El otro error frecuente es asignar a la fuerza explosiva una carga ligera fija, cuando lo que la define es la velocidad de ejecución. Dato para recordar: si la carga sube, las repeticiones bajan y el descanso se alarga.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['clasificación', '1RM', 'descanso', 'prescripción'],
  },
  {
    id: 'D3-007',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      '¿Qué vía energética sostiene una serie de fuerza máxima de 4 repeticiones al 90 % del 1RM?',
    opciones: [
      'La vía anaeróbica aláctica',
      'La vía anaeróbica láctica',
      'La vía aeróbica con oxidación de glucógeno',
      'La vía aeróbica con oxidación de ácidos grasos',
    ],
    correcta: 0,
    explicacion:
      'Una serie de 4 repeticiones al 90 % dura menos de 15 segundos, y ese rango lo cubre el sistema anaeróbico aláctico: ATP libre y fosfocreatina, sin producción de lactato. El distractor más tentador es la vía láctica, que sostiene las series de 20 a 40 segundos propias de la hipertrofia: la diferencia no está en lo pesada que se sienta la serie sino en cuánto dura. Las dos vías aeróbicas quedan fuera por completo en esfuerzos de segundos. Dato para recordar: menos de 15 s aláctico, 20–40 s láctico, 45 s o más aeróbico.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['vía aláctica', 'fuerza máxima', 'duración de la serie'],
  },
  {
    id: 'D3-008',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      'Seleccione las DOS adaptaciones que produce principalmente el método de intensidades máximas.',
    opciones: [
      'Mayor reclutamiento de unidades motoras',
      'Mejor sincronización y mayor frecuencia de descarga de las motoneuronas',
      'Aumento marcado de la sección transversal del músculo',
      'Aumento de la densidad capilar del músculo entrenado',
      'Aumento de las reservas de glucógeno muscular',
    ],
    correctas: [0, 1],
    explicacion:
      'El método de intensidades máximas mejora la fuerza por vía nerviosa: recluta más unidades motoras, las sincroniza mejor y eleva la frecuencia de descarga. El distractor más tentador es el aumento de la sección transversal, porque se da por hecho que levantar más pesado engorda más el músculo; la hipertrofia necesita volumen de trabajo, y este método hace muy pocas repeticiones totales. La densidad capilar y las reservas de glucógeno son adaptaciones de trabajo aeróbico, no de fuerza máxima. Dato para recordar: con este método se gana fuerza sin ganar mucho tamaño.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['intensidades máximas', 'adaptación nerviosa', 'unidades motoras'],
  },
  {
    id: 'D3-009',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué representa el 1RM de un deportista en un ejercicio determinado?',
    opciones: [
      'La carga máxima que puede movilizar una sola vez con técnica correcta',
      'La carga con la que puede completar exactamente diez repeticiones seguidas',
      'La carga máxima que puede sostener de forma isométrica durante un minuto',
      'La suma de las cargas movilizadas en la sesión más dura de la semana',
    ],
    correcta: 0,
    explicacion:
      'El 1RM es la carga máxima movilizada una única vez con técnica correcta en un ejercicio concreto, y es la referencia sobre la que se calculan todos los porcentajes de prescripción. El distractor más tentador es la carga de diez repeticiones, que existe y se llama 10RM: sirve para estimar el 1RM, pero no es el 1RM. La versión isométrica describe otra cosa distinta, la fuerza máxima estática. Dato para recordar: el 1RM es por ejercicio, así que el de sentadilla no dice nada del de press de banca.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.4 — Tests de valoración de la fuerza',
    etiquetas: ['1RM', 'test', 'evaluación'],
  },
  {
    id: 'D3-010',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿En qué consiste el ciclo de estiramiento-acortamiento que aprovecha la pliometría?',
    opciones: [
      'El músculo se estira inmediatamente antes de acortarse y suma energía elástica y reflejo miotático',
      'El músculo se contrae de forma isométrica y después cede lentamente ante la carga',
      'El músculo alterna contracciones concéntricas y descansos completos dentro de la misma serie',
      'El músculo se acorta a velocidad constante contra una resistencia que no varía',
    ],
    correcta: 0,
    explicacion:
      'El ciclo de estiramiento-acortamiento consiste en estirar el músculo justo antes de acortarlo: el componente elástico devuelve energía y el reflejo miotático añade activación, de modo que la fase concéntrica sale reforzada. El distractor más tentador describe una contracción isométrica seguida de una excéntrica, que son fases reales del trabajo de fuerza pero en el orden inverso al que produce el efecto. Dato para recordar: el CEA es lo que hace que el salto con contramovimiento supere al salto sin él.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['pliometría', 'CEA', 'fuerza reactiva'],
  },
  {
    id: 'D3-011',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada test con la manifestación de fuerza que valora.',
    izquierda: [
      'Test de 1RM',
      'Salto vertical con contramovimiento',
      'Lanzamiento de balón medicinal',
      'Dinamometría manual',
    ],
    derecha: [
      'Fuerza máxima dinámica del ejercicio evaluado',
      'Fuerza explosiva del tren inferior',
      'Fuerza explosiva del tren superior',
      'Fuerza máxima isométrica de prensión',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada test tiene su manifestación y su segmento: el 1RM mide fuerza máxima dinámica, los saltos miden explosiva de piernas, el lanzamiento mide explosiva de brazos y tronco, y el dinamómetro mide fuerza isométrica de prensión. El error más frecuente es asignar la dinamometría a la fuerza máxima general del deportista, cuando solo informa de la mano evaluada y en régimen estático. El otro cruce típico es dar el salto vertical por medida de fuerza máxima: mide potencia, que es fuerza por velocidad. Dato para recordar: pregunta siempre qué segmento y en qué régimen mide el test.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.4 — Tests de valoración de la fuerza',
    etiquetas: ['tests', 'evaluación', 'fuerza explosiva', 'dinamometría'],
  },
  {
    id: 'D3-012',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el trabajo de hipertrofia usa descansos cortos, de 30 segundos a minuto y medio?',
    opciones: [
      'Porque el descanso corto mantiene el ambiente metabólico de la serie, y ese ambiente es parte del estímulo',
      'Porque con descansos largos el músculo se enfría y aumenta el riesgo de lesión articular',
      'Porque permite completar más series en el mismo tiempo y así elevar el volumen total de la sesión, que es el motor del crecimiento',
      'Porque la fosfocreatina se repone por completo en menos de un minuto tras una serie submáxima',
    ],
    correcta: 0,
    explicacion:
      'En hipertrofia el descanso corto es deliberado: sostiene el ambiente metabólico que la serie de 20 a 40 segundos ha creado, y ese ambiente forma parte del estímulo que empuja el crecimiento. El distractor más tentador es el del ahorro de tiempo, porque es cierto que se entrena más rápido: pero eso es una consecuencia práctica, no la razón fisiológica, y confundirlas lleva a recortar también los descansos de fuerza máxima. La última opción además es falsa: la fosfocreatina necesita varios minutos. Dato para recordar: en hipertrofia el descanso corto entrena; en fuerza máxima el descanso corto arruina.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['hipertrofia', 'descanso', 'vía láctica'],
  },
  {
    id: 'D3-013',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué distingue a la fuerza explosiva de la fuerza máxima?',
    opciones: [
      'La explosiva busca la mayor tensión en el menor tiempo posible; la máxima busca la mayor tensión sin importar el tiempo',
      'La explosiva se entrena solo con el peso corporal y gestos de salto; la máxima siempre con carga externa por encima del 85 % del 1RM',
      'La explosiva es propia de los deportes de equipo y de las pruebas de velocidad; la máxima solo tiene sentido en halterofilia y powerlifting',
      'La explosiva trabaja el músculo en régimen excéntrico, frenando la carga, y la máxima en régimen concéntrico, venciéndola',
    ],
    correcta: 0,
    explicacion:
      'Lo que separa a las dos es el tiempo. La fuerza máxima pregunta cuánta tensión puedes generar, sin límite de duración; la explosiva pregunta cuánta tensión puedes generar en las décimas de segundo que dura un salto o un lanzamiento. El distractor más tentador es el del peso corporal, porque muchos ejercicios explosivos se hacen sin carga: pero la explosiva se puede entrenar con carga media, y lo que la define es la intención de mover rápido, no lo ligero del implemento. Dato para recordar: la explosiva la define la velocidad de la ejecución, no el peso que se usa.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['fuerza explosiva', 'fuerza máxima', 'potencia'],
  },
  {
    id: 'D3-014',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'La potencia es el producto de la fuerza por la velocidad. ¿Por qué entonces la potencia máxima no se alcanza levantando el 1RM?',
    opciones: [
      'Porque con la carga máxima la velocidad se desploma, y el producto de los dos factores cae con ella',
      'Porque el 1RM se ejecuta en régimen isométrico y en ese régimen no hay potencia mecánica',
      'Porque la potencia solo se puede medir en gestos sin carga externa, como el salto vertical',
      'Porque con la carga máxima el músculo trabaja con fibras lentas, que generan menos potencia',
    ],
    correcta: 0,
    explicacion:
      'Fuerza y velocidad se mueven en sentido contrario: con cargas altas hay mucha fuerza y poquísima velocidad, con cargas ligeras al revés. Como la potencia es el producto de ambas, su máximo no cae en ninguno de los dos extremos sino con cargas intermedias. El distractor más tentador es el de las fibras lentas, que invierte el hecho real: con cargas máximas se reclutan precisamente las fibras rápidas. Dato para recordar: para entrenar potencia se usan cargas medias movidas a la máxima velocidad intencional, no la carga más pesada que se aguante.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['potencia', 'curva fuerza-velocidad', 'fuerza explosiva'],
  },
  {
    id: 'D3-015',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Un entrenador mantiene la carga al 80 % del 1RM y las 10 repeticiones, pero recorta el descanso de 90 a 30 segundos. ¿Qué consecuencia tiene ese único cambio?',
    opciones: [
      'Sube la exigencia metabólica de la sesión y la carga se acerca al terreno de la resistencia muscular',
      'Aumenta la ganancia de fuerza máxima porque el músculo trabaja con más fatiga acumulada',
      'No cambia nada relevante, porque el estímulo lo definen la carga y las repeticiones, y las dos siguen escritas igual en la planilla',
      'Reduce la exigencia total de la sesión porque disminuye el tiempo bajo tensión',
    ],
    correcta: 0,
    explicacion:
      'El descanso es un componente de la carga, no un hueco entre series: recortarlo a un tercio impide que el músculo restituya y empuja la sesión hacia el trabajo metabólico propio de la resistencia muscular, con las repeticiones cayendo serie tras serie. El distractor más tentador es el de "no cambia nada", porque en el papel la carga y las repeticiones siguen escritas iguales: lo que cambia es la calidad real de las series siguientes. Dato para recordar: si solo puedes tocar una variable, el descanso es la que más cambia la sesión sin cambiar el papel.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['descanso', 'densidad', 'hipertrofia', 'resistencia muscular'],
  },
  {
    id: 'D3-016',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene las fases del protocolo de un test de 1RM, de la primera a la última.',
    elementos: [
      'Calentamiento general y movilidad de las articulaciones implicadas',
      'Serie de aproximación ligera de 8 a 10 repeticiones',
      'Segunda aproximación de 3 a 5 repeticiones con carga moderada',
      'Primer intento máximo con la carga estimada',
      'Incrementos sucesivos con 3 a 5 min de descanso hasta el intento fallido',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'El protocolo va de menos a más: calentamiento, dos aproximaciones que preparan el sistema nervioso sin fatigar, y solo después los intentos máximos con descansos largos entre ellos. El error más común es saltarse las aproximaciones y atacar el máximo en frío, lo que baja el resultado y sube el riesgo. El error contrario es hacer demasiadas series previas: si el 1RM aparece en el séptimo u octavo intento, la fatiga acumulada ya lo convirtió en otro test. Dato para recordar: el 1RM debe resolverse en 3 a 5 intentos máximos.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.4 — Tests de valoración de la fuerza',
    etiquetas: ['1RM', 'protocolo', 'test', 'secuencia'],
  },
  {
    id: 'D3-017',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre la estimación indirecta del 1RM.',
    opciones: [
      'La serie de estimación debe llevarse al máximo número de repeticiones posible',
      'La estimación pierde precisión a medida que aumenta el número de repeticiones realizadas',
      'El valor obtenido es una estimación y varía según el ejercicio evaluado',
      'Cuantas más repeticiones se completen, más exacto es el 1RM estimado',
      'Todas las fórmulas devuelven el mismo valor para un mismo par de peso y repeticiones',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'La estimación indirecta exige llevar la serie al máximo de repeticiones posibles, pierde precisión conforme suben las repeticiones y devuelve un valor propio de cada ejercicio. El distractor más tentador es el cuarto, que invierte la relación real: parece lógico que más datos den más precisión, pero las fórmulas se ajustaron para series cortas y por encima de unas diez repeticiones el error crece. El quinto es falso: con 60 kg a 12 repeticiones, Epley estima 84 kg y Brzycki 86,4 kg. Dato para recordar: la serie de estimación se hace corta y al máximo esfuerzo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.4 — Tests de valoración de la fuerza',
    etiquetas: ['1RM estimado', 'Epley', 'Brzycki', 'fiabilidad'],
  },
  {
    id: 'D3-018',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador entrega la planilla de la sesión de fuerza: 3 series de 12 repeticiones al 90 % del 1RM, con 45 segundos de descanso entre series. El objetivo escrito en la cabecera de la planilla es "hipertrofia".',
    enunciado: '¿Qué está mal en esa prescripción?',
    opciones: [
      'La carga es incompatible con 12 repeticiones: al 90 % del 1RM no se completan más de 4 o 5',
      'El número de series es insuficiente para producir hipertrofia con esa carga',
      'El descanso de 45 segundos es demasiado corto para cualquier objetivo de fuerza',
      'La hipertrofia no se puede buscar con series de 12 repeticiones, sino de 6 como máximo',
    ],
    correcta: 0,
    explicacion:
      'Las columnas de la tabla son la misma realidad dicha de varias maneras: al 90 % del 1RM el deportista completa 4 o 5 repeticiones, no 12. Pedir 12 a esa carga no es exigente, es imposible, y la sesión terminará ejecutándose con menos peso del escrito. El distractor más tentador es el del descanso, porque 45 segundos sí es corto para una carga del 90 %: pero es un descanso normal para hipertrofia, así que no es el error de fondo. Las 12 repeticiones tampoco son el problema: son correctas para hipertrofia, lo que sobra es el porcentaje. Dato para recordar: al 90 % corresponden 4 o 5 repeticiones.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['prescripción', 'hipertrofia', '1RM', 'coherencia'],
  },
  {
    id: 'D3-019',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el método de intensidades máximas da mucha ganancia de fuerza con poco aumento del tamaño muscular?',
    opciones: [
      'Porque mejora sobre todo el control nervioso del músculo y acumula muy poco volumen total de trabajo',
      'Porque las cargas altas activan sobre todo las fibras lentas, que tienen poco potencial de crecimiento y apenas aumentan su sección',
      'Porque el descanso largo entre series impide que llegue sangre suficiente al músculo trabajado',
      'Porque la fuerza máxima depende del tendón y no de la sección transversal del músculo',
    ],
    correcta: 0,
    explicacion:
      'La ganancia de este método es principalmente nerviosa —más unidades motoras reclutadas, mejor sincronización, mayor frecuencia de descarga— y el volumen total de repeticiones es tan bajo que no alcanza a producir un estímulo estructural grande. El distractor más tentador es el de las fibras lentas, que dice exactamente lo contrario de lo que ocurre: las cargas altas reclutan las fibras rápidas, que son las de mayor potencial de crecimiento. Dato para recordar: se puede ser mucho más fuerte sin verse más grande, y ese es justo el objetivo en deportes con categorías de peso.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['intensidades máximas', 'adaptación nerviosa', 'hipertrofia'],
  },
  {
    id: 'D3-020',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Un deportista tiene un 1RM de 120 kg en sentadilla. El plan indica trabajo de hipertrofia al 75 % del 1RM. ¿Qué carga debe poner en la barra?',
    respuesta: 90,
    tolerancia: 1,
    unidad: 'kg',
    pasos: [
      'Carga de trabajo = 1RM × porcentaje prescrito',
      'Carga = 120 kg × 0,75',
      'Carga = 90 kg',
      'Comprobación: 75 % cae dentro del rango de hipertrofia (70–85 %), coherente con 6 a 12 repeticiones',
    ],
    explicacion:
      'La carga de trabajo sale de multiplicar el 1RM por el porcentaje prescrito: 120 × 0,75 = 90 kg. El error más frecuente es calcular el porcentaje sobre la carga de la sesión anterior en lugar de sobre el 1RM, lo que va desviando la intensidad real semana a semana hasta que la planilla ya no describe lo que ocurre en la sala. Conviene además verificar la coherencia: el 75 % está dentro de la franja de hipertrofia, así que las 6 a 12 repeticiones del plan encajan. Dato para recordar: todo porcentaje de fuerza se calcula sobre el 1RM vigente, y por eso el 1RM se vuelve a medir cada cierto tiempo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['1RM', 'porcentaje', 'hipertrofia', 'prescripción'],
  },
  {
    id: 'D3-021',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Una deportista completa 8 repeticiones máximas con 80 kg en press de banca. Estime su 1RM con la fórmula de Epley: 1RM = peso × (1 + repeticiones / 30).',
    respuesta: 101.3,
    tolerancia: 1,
    unidad: 'kg',
    pasos: [
      'Epley: 1RM = peso × (1 + repeticiones / 30)',
      'repeticiones / 30 = 8 / 30 = 0,267',
      '1 + 0,267 = 1,267',
      '1RM = 80 × 1,267 = 101,3 kg',
    ],
    explicacion:
      'Epley añade al peso movido una fracción proporcional a las repeticiones completadas: con 8 repeticiones el factor es 1,267 y el 1RM estimado queda en 101,3 kg. El error más frecuente es dividir entre 30 el peso en lugar de las repeticiones, lo que da un número sin sentido físico. El segundo error es aplicar la fórmula a una serie que no se llevó al máximo: si la deportista podía hacer 11 y paró en 8, la estimación sale corta. Dato para recordar: la fórmula solo vale si la serie terminó porque no había una repetición más.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.4 — Tests de valoración de la fuerza',
    etiquetas: ['Epley', '1RM estimado', 'cálculo', 'test'],
  },
  {
    id: 'D3-022',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un deportista completa 12 repeticiones máximas con 60 kg en remo. Estime su 1RM con la fórmula de Brzycki: 1RM = peso / (1,0278 − 0,0278 × repeticiones).',
    respuesta: 86.4,
    tolerancia: 1.5,
    unidad: 'kg',
    pasos: [
      'Brzycki: 1RM = peso / (1,0278 − 0,0278 × repeticiones)',
      '0,0278 × 12 = 0,3336',
      'Denominador = 1,0278 − 0,3336 = 0,6942',
      '1RM = 60 / 0,6942 = 86,4 kg',
    ],
    explicacion:
      'En Brzycki el peso se divide por un denominador que se va achicando conforme suben las repeticiones: con 12 el denominador queda en 0,6942 y el 1RM estimado en 86,4 kg. El error más frecuente es multiplicar en lugar de dividir, o restar mal el 0,3336 y quedarse con un denominador mayor que 1, que devolvería un 1RM menor que el peso movido: imposible. Con estas mismas 12 repeticiones, Epley estimaría 84 kg: las dos fórmulas coinciden hasta unas 10 repeticiones y se separan a partir de ahí. Dato para recordar: por encima de 10 repeticiones la estimación deja de ser fiable.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.4 — Tests de valoración de la fuerza',
    etiquetas: ['Brzycki', '1RM estimado', 'cálculo', 'fiabilidad'],
  },
  {
    id: 'D3-023',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un jugador de rugby de 22 años entra en pretemporada con seis semanas por delante. Su entrenador quiere que gane masa muscular en el tren superior antes de empezar el trabajo específico. El jugador tiene dos años de experiencia con pesas y una técnica correcta en los ejercicios básicos.',
    enunciado: '¿Qué prescripción corresponde al objetivo?',
    opciones: [
      '4 series de 10 repeticiones al 75 % del 1RM con 60 segundos de descanso',
      '5 series de 3 repeticiones al 92 % del 1RM con 4 minutos de descanso',
      '3 series de 20 repeticiones al 55 % del 1RM con 25 segundos de descanso',
      '6 series de 2 repeticiones al 60 % del 1RM a máxima velocidad con 3 minutos de descanso',
    ],
    correcta: 0,
    explicacion:
      'Ganar masa muscular es hipertrofia, y la fila completa de la hipertrofia es 70–85 % del 1RM, 6 a 12 repeticiones y descansos de 30 segundos a minuto y medio: la primera opción encaja en las tres columnas. El distractor más tentador es el de 5 × 3 al 92 %, porque es el trabajo que se ve más duro y todo el mundo asocia lo duro con crecer; produce fuerza por vía nerviosa con muy poco volumen total, que es justo lo contrario del objetivo. La tercera opción es resistencia muscular y la cuarta es trabajo de potencia. Dato para recordar: para hipertrofia manda el volumen con carga media-alta, no la carga máxima.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['hipertrofia', 'prescripción', 'pretemporada'],
  },
  {
    id: 'D3-024',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Una velocista de 100 m llega al periodo competitivo con buen nivel de fuerza máxima: su sentadilla ronda dos veces su peso corporal. Sin embargo, sus tiempos de los primeros 30 metros no mejoran y en el vídeo se ve que aplica la fuerza tarde en cada apoyo. El entrenador decide reorientar el trabajo de sala.',
    enunciado: '¿Qué prescripción corresponde al problema detectado?',
    opciones: [
      'Cargas medias movidas a la máxima velocidad intencional y trabajo pliométrico, con descanso completo entre series',
      'Series de 3 repeticiones al 95 % del 1RM con 4 minutos de descanso, para seguir elevando el techo de fuerza máxima disponible',
      'Series de 15 a 20 repeticiones al 60 % para mejorar la resistencia de las piernas en la salida',
      'Trabajo isométrico sostenido en el ángulo de máxima flexión de la rodilla, tres veces por semana',
    ],
    correcta: 0,
    explicacion:
      'El problema no es cuánta fuerza tiene sino en cuánto tiempo la aplica, y eso es fuerza explosiva: cargas medias movidas a la máxima velocidad intencional, más pliometría para aprovechar el ciclo de estiramiento-acortamiento, con descanso completo para que cada repetición salga rápida de verdad. El distractor más tentador es seguir subiendo la fuerza máxima al 95 %, porque es lo que la deportista ya hace bien: elevar más un techo que no está limitando no cambia el tiempo de aplicación. La tercera opción confunde el problema con fatiga y la cuarta trabaja un solo ángulo, sin velocidad. Dato para recordar: cuando la fuerza está pero llega tarde, lo que falta es potencia.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.3 — Métodos de entrenamiento de la fuerza',
    etiquetas: ['fuerza explosiva', 'pliometría', 'potencia', 'prescripción'],
  },
  {
    id: 'D3-025',
    modulo: 'd3-fuerza',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador quiere mejorar la resistencia muscular del tren inferior de un grupo de aficionados. ¿Qué combinación de carga, repeticiones y descanso corresponde a ese objetivo?',
    opciones: [
      'Por debajo del 70 % del 1RM, 15 repeticiones o más y hasta 30 segundos de descanso',
      'Entre el 70 y el 85 % del 1RM, 6 a 12 repeticiones y minuto y medio de descanso',
      'Más del 85 % del 1RM, 5 repeticiones y 3 minutos de descanso',
      'Alrededor del 60 % del 1RM, 4 repeticiones a máxima velocidad y 3 minutos de descanso',
    ],
    correcta: 0,
    explicacion:
      'La resistencia muscular se entrena con cargas por debajo del 70 % del 1RM, 15 repeticiones o más y descansos de hasta 30 segundos, de modo que la serie supere los 45 segundos y el trabajo pase a sostenerse por vía aeróbica. El distractor más tentador es la segunda opción, la de hipertrofia, porque también usa repeticiones altas comparadas con la fuerza máxima: la separan el descanso, que allí es tres veces más largo, y la carga, que sube por encima del 70 %. La cuarta describe trabajo de potencia. Dato para recordar: en resistencia muscular el descanso corto es condición, no detalle.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.1.2 — Manifestaciones de la fuerza',
    etiquetas: ['resistencia muscular', 'prescripción', '1RM', 'descanso'],
  },
];
