// content/banco/d4-resistencia.ts
// D4 · Capacidad física: resistencia. 25 ítems.
//
// Reparto verificado contra verificarCuotas (bloque D, mínimo 25):
//   Nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   Dificultad → 6 de nivel 1 · 13 de nivel 2 · 6 de nivel 3
//   Tipos      → 13 única · 3 caso · 3 cálculo · 2 múltiple · 2 emparejar
//                · 1 ordenar · 1 V/F
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D4-001',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cómo se define la resistencia como capacidad física?',
    opciones: [
      'La capacidad de sostener un esfuerzo, retrasar y soportar la fatiga y recuperarse rápido al terminar',
      'La capacidad de generar la mayor tensión muscular posible frente a una resistencia externa',
      'La capacidad de repetir un gesto técnico sin que se deteriore su precisión',
      'La capacidad de alcanzar la máxima velocidad de desplazamiento en el menor tiempo posible',
    ],
    correcta: 0,
    explicacion:
      'La resistencia tiene cuatro partes: sostener el esfuerzo, retrasar la fatiga, soportarla cuando llega y recuperarse rápido. La cuarta se olvida y es la que separa a un deportista que aguanta una sesión de otro que además llega entero a la del día siguiente. El distractor más tentador es el de la tensión muscular, que define la fuerza: se cuela porque la fuerza resistencia comparte apellido con esta capacidad, pero ahí lo que se repite es una tensión y aquí lo que se sostiene es un ritmo. Dato para recordar: recuperarse forma parte de la definición, no es un añadido.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.1 — Definición y clasificación de la resistencia',
    etiquetas: ['resistencia', 'definición', 'capacidades físicas'],
  },
  {
    id: 'D4-002',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué duración corresponde a la resistencia de duración corta?',
    opciones: ['De 35 segundos a 2 minutos', 'De 2 a 10 minutos', 'De 10 a 35 minutos', 'De 5 a 15 segundos'],
    correcta: 0,
    explicacion:
      'La resistencia de duración corta cubre de 35 segundos a 2 minutos, con predominio anaeróbico láctico y un aporte aeróbico que crece a medida que pasa el tiempo. El distractor más tentador es el de 2 a 10 minutos, que es la resistencia de duración media: se confunden porque las dos se sienten como esfuerzos "cortos y duros", pero en la media el peso aeróbico ya es mayoritario. Los 5 a 15 segundos quedan fuera: eso es trabajo del sistema fosfágeno, no resistencia. Dato para recordar: por debajo de 35 segundos ya no se habla de resistencia.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.2 — Tipos de resistencia',
    etiquetas: ['duración corta', 'clasificación', 'vía láctica'],
  },
  {
    id: 'D4-003',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué caracteriza al método de repeticiones frente al resto de métodos fraccionados?',
    opciones: [
      'La pausa entre repeticiones es completa: se espera la recuperación antes de la siguiente',
      'La pausa entre repeticiones es incompleta y se reanuda con el pulso todavía alto',
      'No existe pausa: la recuperación se hace corriendo a ritmo suave',
      'La pausa se realiza siempre en movimiento y nunca detenido',
    ],
    correcta: 0,
    explicacion:
      'El método de repeticiones se define por la pausa completa: se espera a estar recuperado para que la siguiente repetición se pueda hacer a la misma velocidad alta que la primera, porque lo que se entrena es el ritmo de competición. El distractor más tentador es la pausa incompleta, que es exactamente la definición del interválico: son los dos métodos fraccionados y la única diferencia estructural entre ellos es esa. La tercera opción describe un método continuo. Dato para recordar: recuperación total es repeticiones; recuperación incompleta es interválico.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['método de repeticiones', 'pausa', 'fraccionados'],
  },
  {
    id: 'D4-004',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'En el método interválico la recuperación entre series es completa: se espera a que la frecuencia cardíaca vuelva a valores de reposo antes de arrancar la siguiente.',
    correcta: false,
    explicacion:
      'Falso. El interválico se define justamente por lo contrario: la pausa es incompleta, se llama pausa útil y la siguiente serie arranca con el pulso todavía alto, típicamente en la franja de 120 a 140 lpm. Esperar la recuperación total convierte la sesión en método de repeticiones, que persigue otro objetivo. La confusión viene de que en el lenguaje de campo se llama "series" a todo lo que lleve pausa, sin distinguir de qué pausa se trata. Dato para recordar: en el interválico la adaptación ocurre durante la pausa, así que reventarla anula el estímulo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['interválico', 'pausa útil', 'fraccionados'],
  },
  {
    id: 'D4-005',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿En qué consiste el test de Cooper?',
    opciones: [
      'Recorrer la mayor distancia posible en 12 minutos',
      'Recorrer 1000 metros en el menor tiempo posible',
      'Correr de ida y vuelta entre dos líneas separadas 20 metros siguiendo una señal sonora',
      'Sostener una carrera continua durante 30 minutos a frecuencia cardíaca constante',
    ],
    correcta: 0,
    explicacion:
      'El test de Cooper consiste en recorrer la mayor distancia posible en 12 minutos, y con esa distancia se estima el VO₂máx. Es indirecto, se aplica a un grupo entero a la vez y solo necesita pista y cronómetro, que es la razón de su popularidad en campo. El distractor más tentador es la carrera de ida y vuelta con señal sonora, que es la Course Navette: los dos estiman el VO₂máx en campo, pero en Cooper el deportista se dosifica solo y en la Navette el ritmo se lo impone el audio. Dato para recordar: Cooper mide distancia con el tiempo fijo en 12 minutos.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['test de Cooper', 'VO₂máx', 'evaluación'],
  },
  {
    id: 'D4-006',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada tipo de resistencia con su rango de duración.',
    izquierda: [
      'Resistencia de duración corta',
      'Resistencia de duración media',
      'Resistencia de larga duración I',
      'Resistencia de larga duración III',
    ],
    derecha: ['De 35 s a 2 min', 'De 2 a 10 min', 'De 10 a 35 min', 'De 90 min a 6 h'],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'La escala va encadenada: corta de 35 s a 2 min, media de 2 a 10 min, y a partir de los 10 minutos empiezan las cuatro largas, de las que la I llega a 35 min y la III cubre de 90 min a 6 h. El error más frecuente es hacer arrancar la corta en el segundo cero, cuando por debajo de 35 segundos el esfuerzo ya no se clasifica como resistencia. El otro cruce típico es mezclar larga I con larga II, que se separan en el minuto 35. Dato para recordar: los cortes son 35 s, 2 min, 10 min, 35 min, 90 min y 6 h.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.2 — Tipos de resistencia',
    etiquetas: ['clasificación', 'duración', 'larga duración'],
  },
  {
    id: 'D4-007',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      '¿A qué velocidad arranca la Course Navette y cuánto sube en cada palier?',
    opciones: [
      'Arranca a 8,5 km/h y sube 0,5 km/h por palier',
      'Arranca a 10 km/h y sube 1 km/h por palier',
      'Arranca a 8,5 km/h y sube 1 km/h por palier',
      'Arranca a 6 km/h y sube 0,5 km/h por palier',
    ],
    correcta: 0,
    explicacion:
      'La Course Navette arranca a 8,5 km/h y sube 0,5 km/h en cada palier de un minuto, entre dos líneas separadas 20 metros. El distractor más tentador es el que mantiene los 8,5 km/h iniciales pero sube de kilómetro en kilómetro: acierta el arranque y se equivoca en el incremento, que es justo el dato que permite reconstruir la velocidad de cualquier palier. Con incrementos de 1 km/h el test se acabaría en la mitad de paliers. Dato para recordar: velocidad del palier = 8,5 + 0,5 × (palier − 1).',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['Course Navette', 'protocolo', 'palier'],
  },
  {
    id: 'D4-008',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione los DOS métodos que pertenecen a la familia de los métodos continuos.',
    opciones: [
      'Método continuo extensivo',
      'Método variable o fartlek',
      'Método interválico extensivo',
      'Método de repeticiones',
      'Método de competición',
    ],
    correctas: [0, 1],
    explicacion:
      'Los métodos continuos son los que no tienen pausa: el continuo extensivo, el continuo intensivo y el variable o fartlek. El distractor más tentador es el interválico extensivo, porque comparte el apellido "extensivo" con un método continuo y eso invita a agruparlos; lo que define la familia no es la intensidad sino la ausencia o presencia de pausa. El método de repeticiones y el de competición tampoco son continuos. Dato para recordar: el fartlek es continuo aunque cambie de ritmo, porque la recuperación se hace corriendo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['métodos continuos', 'fartlek', 'clasificación'],
  },
  {
    id: 'D4-009',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuándo se considera que una resistencia es local?',
    opciones: [
      'Cuando interviene menos de un sexto o un séptimo de la masa muscular total',
      'Cuando el esfuerzo dura menos de dos minutos en total',
      'Cuando se realiza sin desplazamiento del deportista por el terreno',
      'Cuando el trabajo se sostiene por debajo del umbral aeróbico',
    ],
    correcta: 0,
    explicacion:
      'La resistencia es local cuando participa menos de un sexto o un séptimo de la masa muscular total, que en la práctica equivale a la musculatura de un solo miembro. Por encima de esa fracción se habla de resistencia general, y ahí el límite del rendimiento deja de estar en el músculo aislado y pasa al sistema cardiorrespiratorio. El distractor más tentador es el de la duración, porque mezcla dos criterios de clasificación distintos: la duración separa corta, media y largas, no local de general. Dato para recordar: local y general se deciden por masa muscular, no por reloj.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.1 — Definición y clasificación de la resistencia',
    etiquetas: ['resistencia local', 'resistencia general', 'clasificación'],
  },
  {
    id: 'D4-010',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué es la pausa útil en un entrenamiento interválico?',
    opciones: [
      'Una recuperación incompleta que se corta cuando el pulso baja a la franja de 120 a 140 lpm',
      'Una recuperación total que devuelve la frecuencia cardíaca a los valores de reposo',
      'Una pausa de duración fija de tres minutos entre todas las series de la sesión',
      'El tiempo que el deportista dedica a estirar entre una serie y la siguiente',
    ],
    correcta: 0,
    explicacion:
      'La pausa útil es una recuperación deliberadamente incompleta: se reanuda cuando el pulso ha bajado a la franja de 120 a 140 lpm o se ha recuperado alrededor de un tercio, no cuando el deportista se siente fresco. El distractor más tentador es la recuperación total, que es la del método de repeticiones y suena a lo correcto porque estar recuperado parece siempre mejor. La pausa útil tampoco es un tiempo fijo: se decide por el estado del deportista. Dato para recordar: se llama útil porque el estímulo se produce durante ella.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['pausa útil', 'interválico', 'recuperación'],
  },
  {
    id: 'D4-011',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada test de resistencia con su protocolo.',
    izquierda: ['Test de Cooper', 'Course Navette', 'Test de 1000 metros', 'Test Yo-Yo'],
    derecha: [
      'Recorrer la mayor distancia posible en 12 minutos',
      'Ida y vuelta entre líneas a 20 m siguiendo una señal sonora que acelera',
      'Cubrir una distancia fija en el menor tiempo posible',
      'Navette con una pausa de recuperación de 10 segundos entre tramos',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cooper fija el tiempo y mide distancia; el test de 1000 m fija la distancia y mide tiempo; la Navette y el Yo-Yo son progresivos y máximos, y los separa la pausa de 10 segundos del Yo-Yo. El cruce que más se falla es Navette con Yo-Yo, porque los dos usan señal sonora y cambios de dirección: la pausa del Yo-Yo lo acerca al perfil intermitente de los deportes de equipo. El otro error es intercambiar Cooper con el test de 1000 m sin fijarse en qué variable queda fija. Dato para recordar: en Cooper lo fijo son los 12 minutos.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['tests', 'Cooper', 'Course Navette', 'Yo-Yo'],
  },
  {
    id: 'D4-012',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el método continuo extensivo se prescribe a intensidad baja, por debajo del umbral aeróbico?',
    opciones: [
      'Porque a esa intensidad el esfuerzo se puede sostener mucho tiempo y se acumula el volumen que construye la base aeróbica',
      'Porque por encima del umbral aeróbico el organismo deja de utilizar oxígeno como fuente de energía',
      'Porque a intensidades mayores el corazón no alcanza a aumentar su volumen sistólico',
      'Porque es la única intensidad en la que se puede mantener constante la frecuencia de zancada',
    ],
    correcta: 0,
    explicacion:
      'El continuo extensivo busca volumen, y el volumen solo se acumula a una intensidad que se pueda sostener durante mucho tiempo sin fatiga desproporcionada: por eso vive por debajo del umbral aeróbico. El distractor más tentador afirma que por encima del umbral se deja de usar oxígeno, lo cual es falso: el metabolismo aeróbico sigue siendo mayoritario bastante más arriba, lo que cambia es que empieza a acumularse lactato. Dato para recordar: en el continuo extensivo lo que se entrena es la cantidad, no la calidad del ritmo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['continuo extensivo', 'umbral aeróbico', 'volumen'],
  },
  {
    id: 'D4-013',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué diferencia al interválico extensivo del interválico intensivo?',
    opciones: [
      'El extensivo usa series más largas a intensidad media; el intensivo, series más cortas a intensidad alta',
      'El extensivo emplea pausa completa y el intensivo pausa incompleta',
      'El extensivo se realiza siempre en terreno llano y el intensivo en cuestas',
      'El extensivo trabaja resistencia local y el intensivo resistencia general',
    ],
    correcta: 0,
    explicacion:
      'Los dos son interválicos, así que los dos llevan pausa incompleta: lo que los separa es la combinación de duración e intensidad de las series. El extensivo alarga las series a intensidad media y persigue adaptaciones cardíacas centrales; el intensivo acorta las series y sube la intensidad para trabajar potencia aeróbica y tolerancia al lactato. El distractor más tentador es el de las pausas, porque esa sí es la diferencia entre interválico y repeticiones, pero no entre las dos variantes del interválico. Dato para recordar: extensivo e intensivo hablan de la serie; la pausa ya está decidida por la familia.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['interválico extensivo', 'interválico intensivo', 'métodos'],
  },
  {
    id: 'D4-014',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Por qué se dice que en el método interválico buena parte del estímulo cardíaco se produce durante la pausa y no durante la serie?',
    opciones: [
      'Porque al cortar el esfuerzo la frecuencia cardíaca cae antes que el retorno venoso, el ventrículo se llena mejor y el volumen sistólico alcanza su pico',
      'Porque durante la pausa el músculo libera el lactato acumulado y eso obliga al corazón a acelerarse',
      'Porque en la pausa se recupera la fosfocreatina y esa reposición exige un gasto cardíaco mayor que la serie',
      'Porque la frecuencia cardíaca solo se puede medir con fiabilidad cuando el deportista está detenido',
    ],
    correcta: 0,
    explicacion:
      'Al terminar la serie la frecuencia cardíaca baja rápido mientras el retorno venoso sigue elevado unos segundos: el ventrículo dispone de más tiempo y más sangre para llenarse, y el volumen sistólico llega ahí a su valor más alto de toda la sesión. Ese es el estímulo que persigue el interválico, y por eso la pausa se llama útil. El distractor más tentador es el del lactato, porque describe algo que sí ocurre en la pausa, pero la eliminación de lactato no es el mecanismo que agranda la respuesta cardíaca. Dato para recordar: si esperas a estar fresco, tiras el estímulo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['pausa útil', 'volumen sistólico', 'interválico'],
  },
  {
    id: 'D4-015',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Dos deportistas con el mismo VO₂máx real hacen el test de Cooper y uno obtiene 300 metros menos. ¿Cuál es la explicación más probable?',
    opciones: [
      'Salió demasiado rápido y se hundió antes del final, así que recorrió menos metros de los que su fisiología permitía',
      'El test de Cooper mide directamente el consumo de oxígeno, de modo que uno de los dos valores está mal medido',
      'El VO₂máx no influye en el resultado del test de Cooper, que depende únicamente de la fuerza de las piernas',
      'La fórmula de Cooper se aplica solo a distancias superiores a 3000 metros y por debajo pierde validez',
    ],
    correcta: 0,
    explicacion:
      'Cooper es un test indirecto y de ritmo libre: supone que el evaluado se dosifica bien y se vacía de verdad. Quien sale por encima de sus posibilidades se hunde en la segunda mitad y firma una distancia por debajo de su capacidad real, así que la estrategia de ritmo forma parte de la prueba y debe explicarse antes de aplicarla. El distractor más tentador es el que afirma que Cooper mide el consumo directamente: si así fuera, dos VO₂máx iguales darían resultados iguales, pero la fórmula solo estima a partir de metros recorridos. Dato para recordar: Cooper estima, no mide.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['test de Cooper', 'estimación', 'ritmo', 'validez'],
  },
  {
    id: 'D4-016',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene los tipos de resistencia por duración, de la más corta a la más larga.',
    elementos: [
      'Resistencia de duración corta — de 35 s a 2 min',
      'Resistencia de duración media — de 2 a 10 min',
      'Resistencia de larga duración I — de 10 a 35 min',
      'Resistencia de larga duración II — de 35 a 90 min',
      'Resistencia de larga duración III — de 90 min a 6 h',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La escala encadena los cortes sin huecos: 35 s, 2 min, 10 min, 35 min, 90 min. El error más frecuente es colocar la de duración media antes que la corta, porque "media" suena a punto de partida; el orden lo marca el reloj, no el nombre. El otro error es olvidar que la larga duración se subdivide en cuatro tramos y tratarla como una sola categoría, con lo que se pierden los cortes de 35 y 90 minutos, que son los que el examen pregunta. Dato para recordar: a más duración, más peso de las grasas como sustrato.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.2 — Tipos de resistencia',
    etiquetas: ['clasificación', 'duración', 'secuencia'],
  },
  {
    id: 'D4-017',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Seleccione las TRES afirmaciones correctas sobre los métodos continuos y los fraccionados.',
    opciones: [
      'Lo que separa a las dos familias es la presencia o ausencia de pausa dentro de la sesión',
      'El fartlek es continuo porque la recuperación de los tramos rápidos se hace en movimiento',
      'El interválico y el método de repeticiones se distinguen por el tipo de pausa que emplean',
      'Los métodos continuos se realizan siempre a una intensidad constante de principio a fin',
      'Los métodos fraccionados solo se pueden aplicar a deportistas de alto rendimiento',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tres primeras son correctas: la pausa define la familia, el fartlek sigue siendo continuo porque nunca se detiene, e interválico y repeticiones se separan por pausa incompleta frente a pausa completa. El distractor más tentador es el cuarto, porque el continuo extensivo sí es de ritmo estable: pero el fartlek y el continuo variable cambian de intensidad y siguen siendo continuos, así que la constancia no es requisito de la familia. El quinto es falso: los fraccionados se adaptan a cualquier nivel ajustando series y pausas. Dato para recordar: la pregunta que ordena todo es si hay pausa o no.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['métodos continuos', 'fraccionados', 'fartlek', 'clasificación'],
  },
  {
    id: 'D4-018',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador programa 8 repeticiones de 400 metros a ritmo fuerte y anota en la planilla "interválico intensivo". En la pista, deja que los atletas caminen hasta que su pulso baja a 70 lpm antes de arrancar cada repetición, porque quiere que todas salgan al mismo ritmo.',
    enunciado: '¿Qué está ocurriendo realmente en esa sesión?',
    opciones: [
      'Está aplicando el método de repeticiones: con recuperación completa la sesión deja de ser interválica',
      'Está aplicando un interválico extensivo, porque las series de 400 metros son demasiado largas para el intensivo',
      'Está aplicando un método continuo variable, porque los atletas se mantienen caminando entre series',
      'Está aplicando correctamente el interválico intensivo, ya que la intensidad de las series es alta',
    ],
    correcta: 0,
    explicacion:
      'La etiqueta de la planilla no manda: lo que define el método es la pausa, y esperar a 70 lpm es recuperación completa, así que la sesión es método de repeticiones. No está mal entrenar así —es lo indicado para trabajar ritmo de competición—, pero el estímulo cardíaco de la pausa útil se perdió. El distractor más tentador es el interválico extensivo, porque suena a que el problema está en la distancia de las series: la distancia influye en la variante, no en la familia. Dato para recordar: si esperas la recuperación total, ya no estás haciendo interválico.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['interválico', 'repeticiones', 'pausa', 'prescripción'],
  },
  {
    id: 'D4-019',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'El fartlek alterna tramos rápidos y tramos lentos. ¿Por qué se clasifica igualmente como método continuo?',
    opciones: [
      'Porque no hay pausa: la recuperación de los tramos rápidos se hace corriendo suave, sin detenerse',
      'Porque la intensidad media de la sesión coincide con la del método continuo extensivo',
      'Porque los cambios de ritmo los decide el terreno y no el entrenador',
      'Porque su duración total siempre supera los 35 minutos de la larga duración II',
    ],
    correcta: 0,
    explicacion:
      'La familia la decide la pausa, no la constancia del ritmo. En el fartlek el deportista baja el ritmo pero sigue en movimiento, así que no hay pausa y el método es continuo. El distractor más tentador es el de la intensidad media, porque suena a una explicación técnica: dos sesiones pueden tener la misma media y ser métodos distintos, ya que la media no informa de cómo se repartió el esfuerzo. Que los cambios los marque el terreno es una variante del fartlek, no su criterio de clasificación. Dato para recordar: recuperar corriendo es continuo; recuperar parado es fraccionado.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['fartlek', 'métodos continuos', 'clasificación'],
  },
  {
    id: 'D4-020',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Un deportista recorre 2600 metros en el test de Cooper. Estime su VO₂máx con la fórmula del test: VO₂máx = (distancia en metros − 504,9) / 44,73.',
    respuesta: 46.8,
    tolerancia: 0.5,
    unidad: 'ml/kg/min',
    pasos: [
      'Fórmula de Cooper: VO₂máx = (distancia en metros − 504,9) / 44,73',
      'Numerador = 2600 − 504,9 = 2095,1',
      'VO₂máx = 2095,1 / 44,73',
      'VO₂máx = 46,8 ml/kg/min',
    ],
    explicacion:
      'Se resta la constante y se divide por el divisor, en ese orden: 2600 menos 504,9 da 2095,1, y dividido entre 44,73 devuelve 46,8 ml/kg/min. El error más frecuente es dividir primero la distancia y restar después, lo que da un valor absurdamente bajo. El segundo error es meter la distancia en kilómetros: la fórmula está calibrada en metros, así que introducir 2,6 devuelve un número negativo, que es la señal de que las unidades están mal. Dato para recordar: en Cooper la distancia entra siempre en metros.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['test de Cooper', 'VO₂máx', 'cálculo'],
  },
  {
    id: 'D4-021',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un futbolista adulto completa el palier 7 de la Course Navette. Estime su VO₂máx aplicando la ecuación para adultos VO₂máx = 5,857 × V − 19,458, donde V es la velocidad del palier alcanzado en km/h.',
    respuesta: 47.9,
    tolerancia: 0.5,
    unidad: 'ml/kg/min',
    pasos: [
      'Velocidad del palier = 8,5 + 0,5 × (palier − 1)',
      'V = 8,5 + 0,5 × 6 = 8,5 + 3 = 11,5 km/h',
      'VO₂máx = 5,857 × 11,5 − 19,458 = 67,36 − 19,458',
      'VO₂máx = 47,9 ml/kg/min',
    ],
    explicacion:
      'El cálculo tiene dos pasos y el primero es el que se falla: hay que convertir el palier en velocidad antes de tocar la ecuación, y el incremento se aplica al palier menos uno, porque el palier 1 ya es la velocidad de arranque. Quien multiplica 0,5 por 7 obtiene 12 km/h y arrastra el error hasta el final. El otro descuido es olvidar la resta de 19,458 y entregar la velocidad multiplicada como si fuera el consumo. Dato para recordar: palier 1 son 8,5 km/h, y cada palier siguiente suma medio kilómetro por hora.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['Course Navette', 'palier', 'VO₂máx', 'cálculo'],
  },
  {
    id: 'D4-022',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Una corredora recorre 2800 metros en el test de Cooper. Estime su VO₂máx y exprese el resultado en MET, sabiendo que 1 MET equivale a 3,5 ml/kg/min.',
    respuesta: 14.7,
    tolerancia: 0.3,
    unidad: 'MET',
    pasos: [
      'Cooper: VO₂máx = (2800 − 504,9) / 44,73 = 2295,1 / 44,73',
      'VO₂máx = 51,3 ml/kg/min',
      'Conversión a MET: MET = VO₂máx / 3,5',
      'MET = 51,3 / 3,5 = 14,7 MET',
    ],
    explicacion:
      'Son dos conversiones encadenadas: primero la fórmula de Cooper devuelve 51,3 ml/kg/min y después se divide entre 3,5 para pasar a MET, con lo que quedan 14,7. El error más frecuente es multiplicar por 3,5 en lugar de dividir, lo que daría 179 MET, un valor imposible que debería encender la alarma: pocas personas superan los 20 MET. El otro error es dividir la distancia entre 3,5 antes de aplicar Cooper, mezclando las dos operaciones. Dato para recordar: 1 MET son 3,5 ml/kg/min, y se divide para pasar de consumo a MET.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['test de Cooper', 'MET', 'VO₂máx', 'cálculo'],
  },
  {
    id: 'D4-023',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un equipo de fútbol aficionado arranca la pretemporada después de dos meses de parón total. Quedan cinco semanas para el primer partido y el entrenador quiere construir la base aeróbica del grupo antes de meter trabajo de alta intensidad. Varios jugadores llegan con sobrepeso y ninguno ha corrido en ocho semanas.',
    enunciado: '¿Qué método corresponde a las primeras semanas de ese plan?',
    opciones: [
      'Método continuo extensivo: carrera prolongada a intensidad baja, sin pausas',
      'Método interválico intensivo: series cortas cerca del VO₂máx con pausa útil',
      'Método de repeticiones: series a ritmo de competición con recuperación completa',
      'Método de competición: partidos de entrenamiento a máxima exigencia dos veces por semana',
    ],
    correcta: 0,
    explicacion:
      'Con un grupo desentrenado y el objetivo declarado de construir base, corresponde el continuo extensivo: intensidad baja, sin pausas y mucho tiempo acumulado, que es lo que asienta las adaptaciones aeróbicas y prepara el aparato locomotor para el trabajo duro posterior. El distractor más tentador es el interválico intensivo, porque en el fútbol el esfuerzo real es intermitente y parece lógico entrenar como se compite: aplicado sobre jugadores sin base y con sobrepeso, multiplica el riesgo de lesión y no se puede sostener cinco semanas. Dato para recordar: primero volumen, después intensidad.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['continuo extensivo', 'pretemporada', 'prescripción'],
  },
  {
    id: 'D4-024',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un corredor de 10 000 metros lleva tres meses acumulando volumen en carrera continua suave y su base aeróbica está sólida. Faltan ocho semanas para su competición objetivo y su entrenador detecta que pierde el ritmo en los últimos 2000 metros, cuando la carrera se rompe y hay que responder a los cambios.',
    enunciado: '¿Qué método incorporar en este momento de la temporada?',
    opciones: [
      'Interválico intensivo: series cortas a intensidad alta con pausa incompleta',
      'Continuo extensivo: aumentar todavía más el volumen semanal a ritmo suave',
      'Resistencia local de tren inferior con series de 20 repeticiones en gimnasio',
      'Método de competición semanal: correr 10 000 metros a tope cada domingo',
    ],
    correcta: 0,
    explicacion:
      'La base ya está construida y lo que falla es responder a cambios de ritmo cerca del final: eso pide potencia aeróbica y tolerancia al lactato, que es exactamente lo que produce el interválico intensivo con pausa incompleta. El distractor más tentador es seguir subiendo el volumen suave, porque es lo que le ha funcionado hasta ahora: repetir el estímulo que ya está asimilado no resuelve un déficit distinto, y a ocho semanas de la competición gasta un tiempo que no sobra. Competir cada domingo mide, no entrena. Dato para recordar: el método se elige por el déficit detectado, no por lo que ya funciona.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.3 — Métodos de entrenamiento de la resistencia',
    etiquetas: ['interválico intensivo', 'periodización', 'prescripción'],
  },
  {
    id: 'D4-025',
    modulo: 'd4-resistencia',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador quiere valorar la resistencia aeróbica de treinta escolares en una sola sesión de clase, con una cancha y un cronómetro como único material. ¿Qué prueba corresponde?',
    opciones: [
      'El test de Cooper, que se aplica a todo el grupo a la vez y solo necesita medir la distancia en 12 minutos',
      'Un test de 1RM en prensa de piernas para estimar la capacidad de trabajo del tren inferior',
      'Una prueba de esfuerzo en tapiz rodante con analizador de gases para medir el VO₂máx directo',
      'Un test de salto vertical con contramovimiento repetido tres veces por alumno',
    ],
    correcta: 0,
    explicacion:
      'El test de Cooper resuelve el caso: es colectivo, dura 12 minutos, se hace con una pista marcada y un cronómetro, y estima el VO₂máx de los treinta escolares en la misma sesión. El distractor más tentador es la prueba con analizador de gases, porque es la medición más exacta que existe: exige laboratorio, un evaluado cada vez y un coste incompatible con una clase de treinta. El 1RM y el salto vertical miden fuerza, no resistencia. Dato para recordar: el mejor test no es el más preciso, es el más preciso entre los que se pueden aplicar de verdad.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.2.4 — Tests de valoración de la resistencia',
    etiquetas: ['test de Cooper', 'evaluación', 'aplicabilidad'],
  },
];
