// content/banco/d5-velocidad.ts
// D5 · Capacidad física: velocidad. 25 ítems.
//
// Reparto verificado contra verificarCuotas(CUOTAS) con n = 25:
//   Nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   Dificultad → 6 de nivel 1 · 12 de nivel 2 · 7 de nivel 3
//   Tipos      → 13 única · 3 caso · 3 cálculo · 2 múltiple · 2 emparejar
//                · 1 ordenar · 1 V/F  (7 tipos distintos)
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D5-001',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿En qué dos factores se descompone la velocidad de desplazamiento?',
    opciones: [
      'Frecuencia y amplitud del movimiento',
      'Fuerza aplicada y tiempo de contacto con el suelo',
      'Potencia muscular y coordinación intermuscular',
      'Longitud del segmento y ángulo de despegue',
    ],
    correcta: 0,
    explicacion:
      'La velocidad de un desplazamiento cíclico es el producto de la frecuencia (ciclos por segundo) por la amplitud (distancia avanzada en cada ciclo): con esos dos números queda descrita por completo. El distractor más tentador es fuerza aplicada y tiempo de contacto, porque son los factores que explican de dónde sale la amplitud, pero son la causa mecánica, no la descomposición de la velocidad. Dato para recordar: velocidad = frecuencia × amplitud, y los dos factores se pelean entre sí.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3 — Velocidad',
    etiquetas: ['velocidad', 'frecuencia', 'amplitud', 'definición'],
  },
  {
    id: 'D5-002',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué mide la velocidad de reacción?',
    opciones: [
      'El tiempo entre la aparición del estímulo y el inicio del movimiento',
      'El tiempo total que tarda el deportista en completar el gesto técnico',
      'La distancia recorrida en los primeros metros tras la señal de salida',
      'La cantidad de estímulos que el deportista distingue por unidad de tiempo',
    ],
    correcta: 0,
    explicacion:
      'La velocidad de reacción se cierra en el instante en que el movimiento empieza: lo que ocurra después ya no cuenta. El distractor más tentador es el tiempo total hasta completar el gesto, porque eso es lo que un cronómetro de campo suele registrar; pero ese valor es el tiempo de respuesta, que suma reacción más movimiento. Dato para recordar: tiempo de respuesta = tiempo de reacción + tiempo de movimiento.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.1 — Clasificación de la velocidad',
    etiquetas: ['velocidad de reacción', 'tiempo de reacción', 'clasificación'],
  },
  {
    id: 'D5-003',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'Un remate de voleibol ejecutado en el menor tiempo posible corresponde a la velocidad…',
    opciones: [
      'Gestual, también llamada acíclica o segmentaria',
      'De desplazamiento, también llamada cíclica',
      'De reacción compleja o discriminativa',
      'Resistencia a la velocidad de tipo láctico',
    ],
    correcta: 0,
    explicacion:
      'La velocidad gestual es la de un gesto técnico único, ejecutado una vez y con un segmento: remate, golpeo, lanzamiento. Por eso se le llama acíclica. El distractor más tentador es la velocidad de desplazamiento, porque el rematador salta y se mueve; pero lo que se cronometra es el gesto del brazo, no un desplazamiento repetido. Dato para recordar: si el enunciado dice acíclica o segmentaria, está hablando de la velocidad gestual.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.1 — Clasificación de la velocidad',
    etiquetas: ['velocidad gestual', 'acíclica', 'clasificación'],
  },
  {
    id: 'D5-004',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'El trabajo de velocidad máxima debe programarse al final de la sesión, cuando el deportista ya acumula fatiga de las tareas anteriores.',
    correcta: false,
    explicacion:
      'Falso. La velocidad máxima se entrena en estado de frescura, al principio de la sesión y justo después del calentamiento, porque solo así el deportista alcanza de verdad su velocidad tope. La confusión viene de que otras capacidades sí se benefician de trabajar con fatiga previa, como la resistencia a la velocidad. Dato para recordar: correr rápido cansado no entrena velocidad, entrena a moverse despacio, y lo que se repite es lo que se aprende.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['velocidad máxima', 'fatiga', 'estructura de la sesión'],
  },
  {
    id: 'D5-005',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué vía energética sostiene una repetición de velocidad máxima de 5 segundos?',
    opciones: [
      'El sistema anaeróbico aláctico, con ATP y fosfocreatina',
      'El sistema anaeróbico láctico, con glucólisis y producción de lactato',
      'El sistema aeróbico, con oxidación del glucógeno muscular',
      'El sistema aeróbico, con oxidación de los ácidos grasos libres',
    ],
    correcta: 0,
    explicacion:
      'Cinco segundos a intensidad máxima se pagan con el ATP que ya está en la fibra más la fosfocreatina que lo regenera: es el sistema anaeróbico aláctico, el único capaz de entregar energía a esa velocidad. El distractor más tentador es el láctico, porque el sprint deja al deportista sin aire y se asocia con lactato; pero la glucólisis tarda en encenderse y su protagonismo empieza más allá de los 8–10 segundos de esfuerzo. Dato para recordar: por debajo de 6 s manda el aláctico, y de ahí sale toda la prescripción de descansos.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['aláctico', 'fosfocreatina', 'vía energética'],
  },
  {
    id: 'D5-006',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada tipo de velocidad con la situación que le corresponde.',
    izquierda: [
      'Velocidad de reacción',
      'Velocidad de desplazamiento',
      'Velocidad gestual',
      'Resistencia a la velocidad',
    ],
    derecha: [
      'El portero se lanza al oír el impacto del disparo',
      'El extremo recorre 40 m para llegar al contragolpe',
      'El boxeador ejecuta un directo lo más rápido posible',
      'El jugador repite ocho sprints en los últimos diez minutos',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada tipo se identifica por lo que se cronometra: el intervalo hasta que arranca el movimiento, la distancia recorrida, el gesto único o la capacidad de repetir sin caer. La confusión más frecuente es meter el sprint repetido dentro de la velocidad de desplazamiento: los dos son carreras, pero lo que se evalúa en el segundo caso es cuánto se degrada la marca de la primera repetición a la última. Dato para recordar: la resistencia a la velocidad es la única del grupo que se mide por la caída del rendimiento, no por la marca.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.1 — Clasificación de la velocidad',
    etiquetas: ['tipos de velocidad', 'clasificación', 'ejemplos'],
  },
  {
    id: 'D5-007',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué define a la resistencia a la velocidad?',
    opciones: [
      'Sostener la velocidad máxima o casi máxima el mayor tiempo posible frente a la fatiga',
      'Alcanzar la velocidad máxima en la menor distancia y el menor tiempo posibles desde una salida parada',
      'Repetir un gesto técnico con la máxima frecuencia durante una serie larga',
      'Mantener un ritmo de carrera constante durante un esfuerzo de fondo prolongado',
    ],
    correcta: 0,
    explicacion:
      'La resistencia a la velocidad es la capacidad de que la velocidad no se caiga: el deportista ya sabe correr rápido, lo que se entrena es cuánto aguanta a ese ritmo. El distractor más tentador es alcanzar la velocidad máxima en la menor distancia, que describe la aceleración, una cualidad distinta y con otro entrenamiento. La cuarta opción describe resistencia a secas, sin componente de velocidad. Dato para recordar: es el único trabajo de velocidad con descanso incompleto y con la fatiga buscada a propósito.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.1 — Clasificación de la velocidad',
    etiquetas: ['resistencia a la velocidad', 'fatiga', 'clasificación'],
  },
  {
    id: 'D5-008',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado:
      'Seleccione las DOS características que corresponden a una sesión de velocidad máxima.',
    opciones: [
      'Repeticiones de menos de seis segundos',
      'Recuperación completa entre repeticiones, con relación trabajo:descanso de 1:12 a 1:20',
      'Volumen total elevado, de quince a veinte repeticiones, para acumular un estímulo suficiente',
      'Descanso incompleto, de treinta a cuarenta y cinco segundos, para provocar acumulación de lactato',
      'Ubicación al final de la sesión, después del trabajo de fuerza y antes de la vuelta a la calma',
    ],
    correctas: [0, 1],
    explicacion:
      'Las dos características correctas salen de la misma raíz: el depósito de fosfocreatina se agota en segundos y tarda minutos en reponerse, así que las repeticiones son cortas y las pausas, largas. Los tres distractores describen exactamente lo contrario y todos son creencias de campo reales: que más volumen es más estímulo, que hay que terminar reventado y que la velocidad se mete al final "para no gastar la sesión". Dato para recordar: una sesión de velocidad bien hecha tiene poco volumen y dura menos de lo que la gente espera.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['velocidad máxima', 'recuperación', 'prescripción'],
  },
  {
    id: 'D5-009',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué evalúa el test de 30 metros lanzados?',
    opciones: [
      'La velocidad máxima de desplazamiento',
      'La capacidad de aceleración desde parado',
      'La resistencia a la velocidad en esfuerzos repetidos',
      'La velocidad de reacción ante un estímulo sonoro',
    ],
    correcta: 0,
    explicacion:
      'En el test de 30 m lanzados el deportista dispone de una carrera previa de impulso y solo se cronometran los 30 m siguientes, ya a pleno ritmo: por eso mide velocidad punta y no otra cosa. El distractor más tentador es la aceleración, que es justamente lo que mide el test de 30 m desde parado, su hermano de nombre casi idéntico. Dato para recordar: si quieres saber a cuánto corre alguien, tienes que dejarlo llegar lanzado.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.3 — Tests de velocidad',
    etiquetas: ['30 m lanzados', 'test', 'velocidad máxima'],
  },
  {
    id: 'D5-010',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué diferencia a la reacción simple de la reacción compleja o discriminativa?',
    opciones: [
      'En la simple hay un solo estímulo previsto y una sola respuesta; en la compleja hay que elegir entre varias',
      'En la simple el estímulo es sonoro, como el disparo de salida, y en la compleja siempre visual, como el movimiento del rival',
      'En la simple responde un solo segmento corporal y en la compleja participa todo el cuerpo en un desplazamiento',
      'En la simple el deportista parte de reposo y en la compleja parte en movimiento',
    ],
    correcta: 0,
    explicacion:
      'Lo que distingue a las dos es la carga de decisión: con un estímulo y una respuesta previstos el sistema nervioso solo ejecuta, mientras que con varias opciones posibles tiene que reconocer, descartar y elegir, y eso alarga el tiempo. El distractor más tentador es el del tipo de estímulo, porque las salidas de atletismo son sonoras y los deportes de oposición son visuales; pero es una coincidencia frecuente, no la definición. Dato para recordar: lo que se alarga en la reacción compleja es la etapa de elaboración central.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.1 — Clasificación de la velocidad',
    etiquetas: ['reacción simple', 'reacción compleja', 'clasificación'],
  },
  {
    id: 'D5-011',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada test con la cualidad que evalúa.',
    izquierda: [
      'Test de 30 m lanzados',
      'Test de 20 m con salida parada',
      'Test de golpeo de placas (tapping)',
      'RAST: 6 × 35 m con 10 s de recuperación',
    ],
    derecha: [
      'Velocidad máxima de desplazamiento',
      'Capacidad de aceleración',
      'Velocidad gestual del miembro superior',
      'Resistencia a la velocidad',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los dos tests de carrera se distinguen por la salida: con impulso previo se mide la velocidad punta y desde parado se mide cuánto tarda el deportista en ponerse en marcha. El par que más se falla es el RAST, que muchos asignan a la velocidad máxima porque son sprints: lo que evalúa es cuánto se degrada la marca entre la primera repetición y la sexta, con solo 10 s de pausa. Dato para recordar: el descanso del protocolo delata qué mide el test.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.3 — Tests de velocidad',
    etiquetas: ['tests', 'RAST', 'tapping', 'clasificación'],
  },
  {
    id: 'D5-012',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el entrenamiento de velocidad máxima exige recuperaciones tan largas entre repeticiones?',
    opciones: [
      'Porque la fosfocreatina se agota en segundos y necesita minutos para reponerse hasta un nivel que permita repetir a tope',
      'Porque el lactato producido en cada repetición tarda varios minutos en retirarse de la sangre y su acumulación frenaría la repetición siguiente',
      'Porque el sistema aeróbico necesita ese tiempo para volver a cubrir la demanda energética del músculo',
      'Porque el descanso largo permite bajar la frecuencia cardíaca hasta valores de reposo antes de repetir',
    ],
    correcta: 0,
    explicacion:
      'La pausa larga no es para descansar en general: es para que el depósito de fosfocreatina vuelva a llenarse, porque sin él la repetición siguiente se corre más lento y ya no entrena velocidad. El distractor más tentador es el lactato, y falla por la base: una repetición de menos de seis segundos apenas produce lactato, precisamente porque la glucólisis no llega a tomar el mando. Dato para recordar: relación trabajo:descanso de 1:12 a 1:20, es decir uno o dos minutos de pausa por cada seis segundos de sprint.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['recuperación', 'fosfocreatina', 'aláctico', 'prescripción'],
  },
  {
    id: 'D5-013',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Qué es la barrera de velocidad?',
    opciones: [
      'El estancamiento que aparece al automatizar un estereotipo dinámico por repetir siempre el mismo gesto a la misma velocidad',
      'El límite fisiológico de velocidad que impone la proporción de fibras rápidas de cada deportista',
      'La caída de velocidad que se produce en los últimos metros de una carrera por agotamiento de la fosfocreatina',
      'La resistencia del aire, que crece con el cuadrado de la velocidad y frena al deportista a partir de cierto ritmo',
    ],
    correcta: 0,
    explicacion:
      'La barrera de velocidad es un problema de aprendizaje, no de fisiología: el sistema nervioso fija el ritmo repetido como patrón y deja de buscar uno más rápido, así que el rendimiento se estanca aunque el entrenamiento continúe. El distractor más tentador es el límite por tipo de fibra, porque también explica un techo; pero ese techo es estable desde el principio y no aparece de pronto tras meses de trabajo. Dato para recordar: se rompe variando el ejercicio, con sobrevelocidad y dejando de repetir el gesto un tiempo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['barrera de velocidad', 'estereotipo dinámico', 'estancamiento'],
  },
  {
    id: 'D5-014',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene las etapas del tiempo de reacción, desde el estímulo hasta la respuesta.',
    elementos: [
      'El receptor percibe el estímulo',
      'La señal viaja por la vía aferente hasta el sistema nervioso central',
      'El sistema nervioso central elabora la respuesta',
      'La orden viaja por la vía eferente hasta el músculo',
      'El músculo se activa y produce tensión',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La secuencia es siempre percibir, subir, decidir, bajar y contraer: primero la información llega al centro y solo después sale la orden hacia la periferia. El error más frecuente es invertir las dos transmisiones, colocando la vía eferente antes de la elaboración, como si el músculo se enterara antes que el cerebro. Dato para recordar: la etapa que más varía entre una reacción simple y una compleja, y la única que se entrena de verdad, es la elaboración central.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.1 — Clasificación de la velocidad',
    etiquetas: ['tiempo de reacción', 'etapas', 'secuencia'],
  },
  {
    id: 'D5-015',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Un velocista alarga deliberadamente su zancada y su marca en 60 m empeora. ¿Qué explica el resultado?',
    opciones: [
      'La ganancia de amplitud se pagó con una pérdida mayor de frecuencia, y el producto de ambos factores bajó',
      'La zancada más larga aumentó el gasto energético y agotó antes las reservas de fosfocreatina',
      'Al alargar la zancada disminuyó la fuerza aplicada en cada apoyo y con ella la potencia total',
      'El cambio de patrón activó la barrera de velocidad y consolidó un estereotipo dinámico más lento',
    ],
    correcta: 0,
    explicacion:
      'La velocidad es el producto de frecuencia por amplitud, así que subir un factor solo mejora la marca si el otro no cae más de lo que el primero sube: una zancada más larga exige más tiempo de vuelo y baja la cadencia. El distractor más tentador es el de la barrera de velocidad, porque también describe un empeoramiento; pero la barrera surge de repetir siempre lo mismo, no de cambiar el patrón, que es lo contrario. Dato para recordar: se entrena el factor que está por debajo del potencial del deportista, sin destruir el otro.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3 — Velocidad',
    etiquetas: ['frecuencia', 'amplitud', 'zancada', 'rendimiento'],
  },
  {
    id: 'D5-016',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Los métodos de velocidad asistida, como la carrera en cuesta abajo suave o el remolque, ¿sobre qué factor actúan y por qué?',
    opciones: [
      'Sobre la frecuencia, porque obligan a girar las piernas más rápido de lo que el deportista consigue por sí solo',
      'Sobre la amplitud, porque la ayuda externa reduce el frenado en cada apoyo y permite dar zancadas más largas de las habituales',
      'Sobre la fuerza aplicada en cada apoyo, porque el deportista debe frenar la ayuda en cada contacto',
      'Sobre la resistencia a la velocidad, porque permiten sostener el ritmo máximo durante más metros',
    ],
    correcta: 0,
    explicacion:
      'La asistencia externa hace parte del trabajo de traslación, y eso deja al sistema nervioso ante una cadencia que no alcanza solo: lo que se entrena es la capacidad de coordinarse a esa frecuencia. El distractor más tentador es la amplitud, porque cuesta abajo la zancada sí se ve más larga; pero para amplitud se usa el método contrario, la velocidad resistida con trineo o cuesta arriba, que aumenta la fuerza aplicada. Dato para recordar: asistida trabaja frecuencia, resistida trabaja amplitud.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['sobrevelocidad', 'velocidad asistida', 'frecuencia', 'métodos'],
  },
  {
    id: 'D5-017',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Un entrenador cronometra con una app el intervalo entre la señal luminosa y el momento en que el jugador toca el cono. ¿Qué está midiendo en realidad?',
    opciones: [
      'El tiempo de respuesta, que suma el tiempo de reacción y el tiempo de movimiento',
      'El tiempo de reacción puro, porque el cronómetro arranca con el estímulo',
      'La velocidad gestual del miembro superior, medida en condiciones de campo',
      'La velocidad de reacción compleja, porque hay un estímulo y un desplazamiento',
    ],
    correcta: 0,
    explicacion:
      'El tiempo de reacción termina en el instante en que el movimiento arranca, y aislar ese instante exige instrumentación fina, como electromiografía o plataformas. Todo lo que se mide hasta que el jugador toca el cono incluye además el gesto completo, así que es tiempo de respuesta. El distractor más tentador es el tiempo de reacción puro, apoyado en que el cronómetro sí arranca con el estímulo: el problema no es dónde empieza la medición, es dónde termina. Dato para recordar: tiempo de respuesta = tiempo de reacción + tiempo de movimiento.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.3 — Tests de velocidad',
    etiquetas: ['tiempo de respuesta', 'tiempo de reacción', 'medición'],
  },
  {
    id: 'D5-018',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un velocista de 60 m lleva catorce meses con la misma sesión: ocho repeticiones de 60 m a máxima velocidad, con recuperación completa, dos veces por semana. Los primeros meses bajó tres décimas su marca. Desde entonces repite el mismo tiempo en cada control, y en los entrenamientos cronometra siempre lo mismo, décima arriba décima abajo.',
    enunciado: '¿Qué explica mejor el estancamiento?',
    opciones: [
      'Una barrera de velocidad: repetir siempre el mismo gesto a la misma velocidad ha consolidado un estereotipo dinámico',
      'Una recuperación insuficiente entre repeticiones, que impide alcanzar la velocidad real en las últimas series',
      'Un exceso de volumen semanal, que ha llevado al deportista a un estado de fatiga crónica',
      'Una carencia de trabajo aeróbico de base, que limita la recuperación entre sesiones',
    ],
    correcta: 0,
    explicacion:
      'El cuadro es el de manual: mismo ejercicio, misma distancia, misma velocidad durante más de un año, mejora inicial y luego techo. El sistema nervioso automatizó ese ritmo y dejó de buscar uno más rápido. El distractor más tentador es la recuperación insuficiente, porque explicaría bien un estancamiento; pero el enunciado dice que la recuperación es completa, y además el deportista cronometra lo mismo también en los controles frescos. Dato para recordar: se rompe variando distancias y condiciones, metiendo sobrevelocidad y dejando de repetir el gesto un tiempo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['barrera de velocidad', 'estancamiento', 'planificación'],
  },
  {
    id: 'D5-019',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre la velocidad.',
    opciones: [
      'La etapa del tiempo de reacción que más se puede entrenar es la elaboración de la respuesta en el sistema nervioso central',
      'La resistencia a la velocidad es el único trabajo de velocidad que se realiza con recuperación incompleta',
      'La frecuencia de movimiento y la velocidad de reacción tienen su periodo más favorable entre los 7 y los 12 años',
      'La velocidad de desplazamiento máxima madura antes que la frecuencia porque depende menos de la fuerza',
      'En el trabajo de velocidad resistida conviene que la carga frene al deportista al menos un 30 % de su velocidad normal',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tres primeras son ciertas y las tres tocan puntos distintos: la etapa entrenable de la reacción, el único trabajo que busca fatiga y la fase sensible ligada a la maduración nerviosa. La cuarta invierte el orden real: la frecuencia y la reacción maduran antes justamente porque dependen del sistema nervioso, mientras que la velocidad máxima de desplazamiento necesita fuerza y llega con la pubertad. La quinta pasa de largo el límite práctico: si la carga frena más de un 10 % aproximado, el patrón de carrera cambia y se pierde la transferencia. Dato para recordar: a un niño se le entrena la velocidad jugando, no con series cronometradas.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3 — Velocidad',
    etiquetas: ['fases sensibles', 'velocidad resistida', 'reacción', 'prescripción'],
  },
  {
    id: 'D5-020',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Un jugador cubre el test de 30 metros lanzados en 3,20 segundos. Calcule su velocidad máxima en metros por segundo.',
    respuesta: 9.375,
    tolerancia: 0.05,
    unidad: 'm/s',
    pasos: [
      'La velocidad es la distancia dividida entre el tiempo',
      'v = 30 m ÷ 3,20 s',
      'v = 9,375 m/s',
      'Si se pide en km/h: 9,375 × 3,6 = 33,75 km/h',
    ],
    explicacion:
      'La velocidad de un tramo es siempre distancia entre tiempo, y en el test de 30 m lanzados esa razón da directamente la velocidad punta porque el deportista ya llegaba a pleno ritmo. El error más frecuente es sumar al cálculo los metros de impulso previo: esos 30 m de carrera de aproximación no se cronometran y no entran en la cuenta. Dato para recordar: para pasar de m/s a km/h se multiplica por 3,6; para volver, se divide entre 3,6.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.3 — Tests de velocidad',
    etiquetas: ['30 m lanzados', 'cálculo', 'velocidad máxima'],
  },
  {
    id: 'D5-021',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Una velocista da 4,5 zancadas por segundo con una amplitud media de 2,10 metros por zancada. Calcule su velocidad de desplazamiento en kilómetros por hora.',
    respuesta: 34.02,
    tolerancia: 0.3,
    unidad: 'km/h',
    pasos: [
      'Velocidad = frecuencia × amplitud',
      'v = 4,5 zancadas/s × 2,10 m = 9,45 m/s',
      'Conversión a km/h: se multiplica por 3,6',
      'v = 9,45 × 3,6 = 34,02 km/h',
    ],
    explicacion:
      'Multiplicar los ciclos por segundo por los metros de cada ciclo da metros por segundo de forma directa, sin ningún factor intermedio. El error más frecuente es olvidar la conversión final y entregar 9,45 como si fuera la respuesta en km/h, un valor que correspondería a un trote muy suave y que debería saltar a la vista como imposible para una velocista. Dato para recordar: si el resultado en km/h no queda entre 30 y 40 para un sprint de alto nivel, revisa la conversión.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3 — Velocidad',
    etiquetas: ['frecuencia', 'amplitud', 'cálculo', 'conversión de unidades'],
  },
  {
    id: 'D5-022',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Programa seis repeticiones de 50 metros a máxima velocidad. Cada repetición dura 6 segundos y prescribe una relación trabajo:descanso de 1:20. Calcule cuántos segundos debe durar la pausa entre repeticiones.',
    respuesta: 120,
    tolerancia: 5,
    unidad: 's',
    pasos: [
      'La relación trabajo:descanso 1:20 significa 20 partes de pausa por cada parte de trabajo',
      'Tiempo de trabajo por repetición = 6 s',
      'Pausa = 6 s × 20',
      'Pausa = 120 s, es decir 2 minutos entre repeticiones',
    ],
    explicacion:
      'La relación se aplica sobre la duración de una sola repetición, no sobre el tiempo total de la serie: seis segundos por veinte dan dos minutos de pausa, que es lo que la fosfocreatina necesita para reponerse a un nivel que permita repetir a tope. El error más frecuente es aplicar el 1:20 sobre los 36 segundos de trabajo acumulado de las seis repeticiones, lo que daría doce minutos de pausa y convertiría la sesión en algo impracticable. Dato para recordar: la relación trabajo:descanso siempre se lee repetición a repetición.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['relación trabajo:descanso', 'cálculo', 'aláctico', 'prescripción'],
  },
  {
    id: 'D5-023',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Trabaja con un portero de fútbol sala de 19 años. En los partidos llega tarde a los remates desde media distancia: la lectura del disparo es correcta y su salto es potente, pero arranca tarde. En los tests corre bien los 20 m y salta por encima de la media del equipo.',
    enunciado: '¿Qué contenido corresponde priorizar en su plan?',
    opciones: [
      'Reacción ante estímulos variados y salidas desde posiciones distintas',
      'Series de 40 m con recuperación completa para elevar su velocidad máxima',
      'Sprints repetidos con descanso incompleto para mejorar su resistencia a la velocidad',
      'Trabajo de fuerza explosiva de tren inferior para aumentar la potencia del salto',
    ],
    correcta: 0,
    explicacion:
      'El problema descrito es el intervalo entre el estímulo y el arranque, con la lectura y el salto ya resueltos: eso es velocidad de reacción, y en un portero es reacción compleja, con varios estímulos posibles y elección de respuesta. El distractor más tentador es la fuerza explosiva, porque el gesto termina en un salto; pero el enunciado dice que el salto ya es potente y que lo que falla es el momento de empezar. Dato para recordar: el portero no tiene un problema de conducción nerviosa, tiene un problema de decisión, y eso se entrena con estímulos variados.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['velocidad de reacción', 'prescripción', 'fútbol sala'],
  },
  {
    id: 'D5-024',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Una sesión de un club de atletismo se ordena así: calentamiento de 15 minutos, circuito de fuerza de 40 minutos, diez repeticiones de 60 m a máxima velocidad con 45 segundos de pausa, y vuelta a la calma. Los atletas cronometran en la sexta repetición casi un segundo más que en la primera.',
    enunciado: '¿Qué dos correcciones ordenan la sesión?',
    opciones: [
      'Pasar las repeticiones de velocidad delante del circuito de fuerza y ampliar la pausa a dos o tres minutos',
      'Mantener el orden de la sesión y reducir las repeticiones de diez a seis para limitar la fatiga acumulada al final',
      'Mantener el orden y bajar la distancia de 60 a 30 metros para que la fatiga afecte menos',
      'Cambiar las repeticiones a máxima velocidad por series submáximas al 85 % con la misma pausa',
    ],
    correcta: 0,
    explicacion:
      'Los dos fallos son de colocación y de pausa: el trabajo de velocidad debe ir en fresco, justo después del calentamiento, y necesita recuperación completa, que con repeticiones de unos seis segundos significa dos o tres minutos y no cuarenta y cinco. Corregidos ambos, la caída de un segundo desaparece. El distractor más tentador es reducir el volumen manteniendo el orden: alivia la fatiga final pero deja las repeticiones detrás de cuarenta minutos de fuerza, así que la primera ya sale lenta. Dato para recordar: si la marca se cae repetición a repetición, no estás entrenando velocidad.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.2 — Métodos de entrenamiento de la velocidad',
    etiquetas: ['estructura de la sesión', 'recuperación', 'velocidad máxima', 'prescripción'],
  },
  {
    id: 'D5-025',
    modulo: 'd5-velocidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Quiere saber cuánto se le cae el ritmo a un jugador de baloncesto cuando repite esfuerzos máximos con poca pausa. ¿Qué test elige?',
    opciones: [
      'RAST: seis repeticiones de 35 m con 10 segundos de recuperación entre ellas',
      'Test de 30 m lanzados, con carrera de impulso previa y cronometraje de los 30 m siguientes',
      'Test de 10 × 5 m, con ida y vuelta entre dos líneas separadas cinco metros',
      'Test de golpeo de placas, alternando 25 ciclos entre dos discos con una mano',
    ],
    correcta: 0,
    explicacion:
      'Lo que se quiere medir es la degradación del rendimiento entre la primera repetición y la última, y para eso hace falta un protocolo con varias repeticiones máximas y pausas cortas: exactamente lo que hace el RAST con sus diez segundos de recuperación. El distractor más tentador es el 10 × 5 m, porque también son tramos repetidos; pero ese test evalúa velocidad con cambios de dirección en un esfuerzo continuo, no la caída entre repeticiones. Dato para recordar: el descanso del protocolo delata qué mide el test.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.3.3 — Tests de velocidad',
    etiquetas: ['RAST', 'resistencia a la velocidad', 'tests', 'evaluación'],
  },
];
