// content/banco/d6-flexibilidad.ts
// D6 · Capacidad física: flexibilidad. 25 ítems.
//
// Reparto verificado contra verificarCuotas(CUOTAS) con n = 25:
//   Nivel      → 11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   Dificultad → 6 de nivel 1 · 12 de nivel 2 · 7 de nivel 3
//   Tipos      → 13 única · 3 caso · 3 cálculo · 2 múltiple · 2 emparejar
//                · 1 ordenar · 1 V/F  (7 tipos distintos)
//
// El eje de los distractores es la confusión real del módulo: movilidad
// articular, elasticidad muscular y flexibilidad usadas como sinónimos.
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D6-001',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿De qué dos componentes resulta la flexibilidad?',
    opciones: [
      'De la movilidad articular y de la elasticidad muscular',
      'De la elasticidad muscular y de la fuerza del músculo agonista',
      'De la movilidad articular y de la coordinación intermuscular',
      'De la longitud de las palancas óseas y del tono muscular en reposo',
    ],
    correcta: 0,
    explicacion:
      'La flexibilidad es el resultado de sumar lo que permite la articulación y lo que permite el músculo: sin cualquiera de los dos no hay amplitud de movimiento real. El distractor más tentador mete la fuerza del agonista, que sí interviene pero en otra cosa: es lo que determina cuánta de esa flexibilidad el deportista puede usar por sí mismo, es decir, el reparto entre activa y pasiva. Dato para recordar: flexibilidad = movilidad articular + elasticidad muscular.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4 — Flexibilidad',
    etiquetas: ['flexibilidad', 'movilidad articular', 'elasticidad', 'definición'],
  },
  {
    id: 'D6-002',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué describe la movilidad articular?',
    opciones: [
      'El recorrido que permite una articulación según sus superficies óseas, su cápsula y sus ligamentos',
      'La capacidad del músculo de alargarse por encima de su longitud de reposo',
      'La amplitud total de movimiento que el deportista alcanza en un gesto completo',
      'La velocidad con la que una articulación recupera su posición tras un movimiento amplio',
    ],
    correcta: 0,
    explicacion:
      'La movilidad es una propiedad de la articulación misma: un hombro permite mucho más recorrido que una rodilla, y eso no lo cambia ningún músculo. El distractor más tentador es la amplitud total del gesto, porque en la práctica es lo que se ve; pero esa amplitud ya es flexibilidad, el resultado de sumar movilidad y elasticidad. Dato para recordar: si el límite está en la cápsula o el hueso, estirar el músculo no lo va a resolver.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['movilidad articular', 'articulación', 'definición'],
  },
  {
    id: 'D6-003',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué es la elasticidad muscular?',
    opciones: [
      'La capacidad del músculo de deformarse y recuperar su forma y longitud originales al cesar la fuerza',
      'La capacidad del músculo de alargarse hasta el límite que permite la articulación',
      'La capacidad del músculo de sostener una posición forzada durante un tiempo prolongado',
      'La capacidad del músculo de contraerse con rapidez tras un estiramiento previo',
    ],
    correcta: 0,
    explicacion:
      'La palabra clave de la definición es recuperar: elástico es lo que vuelve a su forma, como la goma, no lo que se deja estirar, como la plastilina. El distractor más tentador es alargarse hasta el límite articular, que describe la extensibilidad, una cualidad distinta con la que la elasticidad se confunde a diario. La cuarta opción describe el ciclo de estiramiento-acortamiento, que es trabajo de fuerza. Dato para recordar: alargarse es extensibilidad, volver es elasticidad.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['elasticidad muscular', 'extensibilidad', 'definición'],
  },
  {
    id: 'D6-004',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'La elasticidad muscular es la capacidad del músculo de alargarse por encima de su longitud de reposo.',
    correcta: false,
    explicacion:
      'Falso. Esa es la definición de extensibilidad. La elasticidad es lo contrario del recorrido de ida: es la capacidad de recuperar la forma y la longitud originales cuando la fuerza deja de actuar. La confusión es constante porque las dos cualidades se manifiestan en el mismo gesto de estirar, una en la ida y otra en la vuelta. Dato para recordar: un material puede ser muy extensible y nada elástico, como la plastilina, que se estira y se queda estirada.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['elasticidad muscular', 'extensibilidad', 'conceptos'],
  },
  {
    id: 'D6-005',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué relación existe entre la flexibilidad activa y la pasiva de un mismo deportista?',
    opciones: [
      'La pasiva siempre es mayor que la activa, y su diferencia se llama déficit de flexibilidad',
      'La activa siempre es mayor que la pasiva, porque la contracción del agonista añade recorrido',
      'Son equivalentes en deportistas entrenados y solo difieren en personas sedentarias',
      'La relación depende de la articulación: en las de tipo bisagra la activa supera a la pasiva',
    ],
    correcta: 0,
    explicacion:
      'Una fuerza externa siempre puede llevar la articulación más lejos que la propia contracción del deportista, así que la pasiva marca el techo y la activa queda por debajo. El distractor más tentador invierte la relación apoyándose en algo cierto —que el agonista aporta recorrido— pero ese aporte es lo que define la activa, no algo que se sume encima de la pasiva. Dato para recordar: déficit de flexibilidad = pasiva − activa, y es rango disponible que el deportista no puede usar solo.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['flexibilidad activa', 'flexibilidad pasiva', 'déficit'],
  },
  {
    id: 'D6-006',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada concepto con su definición.',
    izquierda: [
      'Movilidad articular',
      'Elasticidad muscular',
      'Extensibilidad muscular',
      'Flexibilidad',
    ],
    derecha: [
      'Recorrido que permite la articulación por su estructura ósea, capsular y ligamentosa',
      'Capacidad de recuperar la forma original al cesar la fuerza que deformó el músculo',
      'Capacidad del músculo de alargarse por encima de su longitud de reposo',
      'Amplitud de movimiento resultante de sumar los factores articulares y los musculares',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los cuatro conceptos se ordenan por dónde vive cada uno: el primero en la articulación, el segundo y el tercero en el músculo y el cuarto es el resultado global. El par que más se falla es elasticidad con extensibilidad, porque los dos se manifiestan en el mismo gesto: la extensibilidad es la ida, cuánto se alarga; la elasticidad es la vuelta, si recupera la forma. Dato para recordar: la flexibilidad no es un concepto más de la lista, es la suma de los otros.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['conceptos', 'movilidad articular', 'elasticidad', 'clasificación'],
  },
  {
    id: 'D6-007',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿En qué consiste el método de facilitación neuromuscular propioceptiva mantener-relajar?',
    opciones: [
      'Estirar de forma pasiva, contraer isométricamente el músculo estirado, relajar y volver a estirar más amplio',
      'Estirar de forma pasiva y sostener la posición final el mayor tiempo posible sin ninguna contracción',
      'Alternar rebotes cortos con pausas de relajación para vencer progresivamente la resistencia del músculo',
      'Contraer el músculo antagonista mientras un compañero empuja el segmento hacia el final del recorrido',
    ],
    correcta: 0,
    explicacion:
      'El mantener-relajar mete una contracción isométrica del propio músculo que se está estirando dentro del estiramiento, y aprovecha la fase posterior para ganar recorrido. El distractor más tentador es el de la contracción del antagonista, porque describe la variante contraer-relajar-contraer el antagonista, que añade ese paso al final: es una variante del método, no el método base. Dato para recordar: el orden es estirar, contraer el músculo estirado, relajar y estirar más.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['FNP', 'mantener-relajar', 'métodos'],
  },
  {
    id: 'D6-008',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Seleccione las DOS condiciones en las que la flexibilidad de una persona es mayor.',
    opciones: [
      'Con la musculatura caliente tras un calentamiento completo',
      'En una medición realizada por la tarde',
      'En una medición realizada nada más levantarse',
      'Tras varias semanas de reposo por una lesión en otra zona',
      'Con temperatura ambiente baja y sin calentamiento previo',
    ],
    correctas: [0, 1],
    explicacion:
      'El calor aumenta la extensibilidad de los tejidos y por eso el calentamiento previo mejora cualquier medición; y a lo largo del día la flexibilidad crece, así que una toma vespertina da valores más altos que la de primera hora. Los tres distractores son las condiciones opuestas: madrugada, frío y sedentarismo. El del reposo por lesión es el más tentador porque suena a descanso reparador, y en realidad el rango que no se usa se pierde. Dato para recordar: para comparar dos mediciones hay que igualar hora y calentamiento.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4 — Flexibilidad',
    etiquetas: ['factores', 'temperatura', 'evaluación'],
  },
  {
    id: 'D6-009',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué evalúa principalmente el test de sit and reach?',
    opciones: [
      'La extensibilidad de los músculos isquiosurales',
      'La movilidad articular de la cadera en los tres planos',
      'La elasticidad de la musculatura extensora de la cadera',
      'La amplitud de flexión de la columna cervical y dorsal',
    ],
    correcta: 0,
    explicacion:
      'El sit and reach, con las piernas extendidas y el tronco flexionado hacia adelante, tiene su factor limitante casi siempre en la parte posterior del muslo: mide sobre todo isquiosurales, y de forma bastante más discutible la zona lumbar. El distractor más tentador es la movilidad de cadera en los tres planos, porque la cadera efectivamente se flexiona en el test; pero un test único y en un solo plano no puede describir el recorrido articular completo. Dato para recordar: para saber grados y articulación concreta se usa goniometría, no el sit and reach.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.3 — Tests de flexibilidad',
    etiquetas: ['sit and reach', 'isquiosurales', 'tests'],
  },
  {
    id: 'D6-010',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué mide la goniometría y en qué unidad expresa el resultado?',
    opciones: [
      'La amplitud de movimiento de una articulación concreta, expresada en grados',
      'La distancia que alcanza un segmento corporal respecto a una referencia, en centímetros',
      'La resistencia que opone el músculo al ser estirado, en unidades de fuerza',
      'El tiempo que la articulación tarda en recorrer todo su rango, en segundos',
    ],
    correcta: 0,
    explicacion:
      'El goniómetro es un instrumento de dos brazos que se alinea con los segmentos a cada lado de la articulación y lee el ángulo: por eso el resultado siempre son grados y siempre corresponde a una articulación concreta y a un movimiento concreto. El distractor más tentador es el de los centímetros, que es la unidad de los tests de campo como el sit and reach, con los que la goniometría se agrupa en la misma lista. Dato para recordar: eje en el centro de rotación, brazo fijo en el segmento que no se mueve, brazo móvil en el que sí.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.3 — Tests de flexibilidad',
    etiquetas: ['goniometría', 'grados', 'tests'],
  },
  {
    id: 'D6-011',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada procedimiento de estiramiento con su descripción.',
    izquierda: ['Estático', 'Dinámico', 'Balístico', 'FNP'],
    derecha: [
      'Llegar al final del rango y mantener la posición sin moverse',
      'Movimientos activos y controlados hasta el límite, sin rebote',
      'Rebotes que aprovechan el impulso y la inercia del segmento',
      'Alternar estiramiento con contracciones del propio músculo',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Los cuatro se distinguen por lo que hace el deportista mientras estira: nada, moverse controlado, rebotar o contraer. El par que más se falla es dinámico con balístico, porque en los dos hay movimiento; la diferencia es el rebote, es decir si el segmento llega al límite frenado y controlado o lanzado por la inercia. Dato para recordar: dinámico va en el calentamiento, balístico solo con deportistas formados y con cautela.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['procedimientos', 'estático', 'dinámico', 'balístico', 'FNP'],
  },
  {
    id: 'D6-012',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Por qué el rebote del estiramiento balístico juega en contra del objetivo buscado?',
    opciones: [
      'Porque el estiramiento rápido activa el reflejo miotático y el músculo se contrae justo cuando se pretende alargarlo',
      'Porque el movimiento repetido eleva la temperatura del músculo y con ella su resistencia a la deformación',
      'Porque la inercia del segmento impide alcanzar el final del recorrido articular disponible',
      'Porque las contracciones sucesivas agotan la fosfocreatina y limitan la duración de la sesión',
    ],
    correcta: 0,
    explicacion:
      'El huso muscular responde a la velocidad del alargamiento, no a su magnitud: cuanto más rápido el estiramiento, más fuerte la orden refleja de contraer para defender al músculo. Rebotar es empujar y frenar a la vez. El distractor más tentador es el de la temperatura, que confunde el sentido del efecto: el calor aumenta la extensibilidad, no la reduce. Dato para recordar: el reflejo miotático se dispara por velocidad, así que estirar despacio es lo que lo evita.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['balístico', 'reflejo miotático', 'huso muscular'],
  },
  {
    id: 'D6-013',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Un jugador alcanza 95° de flexión de cadera con ayuda de un compañero y solo 70° por sí mismo. ¿Qué significa esa diferencia y cómo se reduce?',
    opciones: [
      'Es un déficit de flexibilidad de 25°: tiene rango disponible que no puede usar solo, y se reduce con fuerza en rangos amplios',
      'Es un déficit de flexibilidad de 25°: le falta extensibilidad muscular, y se reduce estirando más tiempo cada sesión',
      'Es un error de medición: la flexibilidad activa y la pasiva deberían coincidir en un deportista sano',
      'Es una limitación de movilidad articular de 25°: la cápsula bloquea el recorrido y se reduce con movilizaciones',
    ],
    correcta: 0,
    explicacion:
      'El compañero demuestra que el rango existe, así que el músculo se deja llevar hasta 95°; lo que falta es fuerza del agonista para llegar solo, y eso se entrena con trabajo de fuerza en posiciones de recorrido amplio, no con más estiramiento. El distractor más tentador atribuye el déficit a falta de extensibilidad y prescribe estirar: si el problema fuera ese, la medición pasiva también se habría quedado corta. Dato para recordar: rango que solo aparece con ayuda es rango que en competición no existe.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['déficit de flexibilidad', 'flexibilidad activa', 'prescripción'],
  },
  {
    id: 'D6-014',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene los pasos del método FNP mantener-relajar tal como se ejecutan.',
    elementos: [
      'Estiramiento pasivo hasta el primer límite cómodo, unos 10 s',
      'Contracción isométrica submáxima del músculo estirado, unos 6 s',
      'Fase de relajación de 2 a 3 s',
      'Nuevo estiramiento pasivo, más amplio, de 10 a 30 s',
    ],
    ordenCorrecto: [0, 1, 2, 3],
    explicacion:
      'La secuencia tiene una lógica: primero se lleva el músculo a tensión, después se le pide una contracción isométrica desde esa posición, luego se le da un margen breve para relajarse y solo entonces se aprovecha para ganar recorrido. El error más frecuente es empezar por la contracción, sin estiramiento previo: sin tensión de partida la contracción no produce el efecto que se busca. Dato para recordar: la contracción es submáxima y de unos 6 s, no un esfuerzo máximo prolongado.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['FNP', 'mantener-relajar', 'secuencia', 'protocolo'],
  },
  {
    id: 'D6-015',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Por qué el estiramiento estático prolongado no es la mejor opción en el calentamiento de una sesión de potencia?',
    opciones: [
      'Porque mantenido más de 60 s por grupo muscular reduce de forma aguda la fuerza y la altura de salto',
      'Porque aumenta tanto el rango de movimiento que el gesto técnico pierde precisión durante la sesión',
      'Porque enfría la musculatura al mantener al deportista quieto y anula el efecto del calentamiento previo',
      'Porque el mantenimiento prolongado activa el reflejo miotático y deja el músculo en tensión permanente',
    ],
    correcta: 0,
    explicacion:
      'El estiramiento estático prolongado inmediatamente antes de un esfuerzo explosivo deja una pérdida aguda de fuerza y de altura de salto, y por eso el calentamiento se construye con estiramientos dinámicos y el trabajo estático de desarrollo se lleva a la vuelta a la calma o a una sesión aparte. El distractor más tentador es el del reflejo miotático, que existe pero se dispara por la velocidad del estiramiento, así que apunta al balístico y no al estático mantenido. Dato para recordar: por debajo de 60 s por grupo muscular el efecto es trivial.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['estiramiento estático', 'calentamiento', 'potencia', 'rendimiento'],
  },
  {
    id: 'D6-016',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: '¿Qué distingue al reflejo miotático del reflejo miotático inverso?',
    opciones: [
      'El miotático parte del huso muscular ante el estiramiento rápido y contrae; el inverso parte del órgano tendinoso de Golgi ante la tensión mantenida y relaja',
      'El miotático parte del órgano tendinoso de Golgi ante la tensión mantenida y relaja; el inverso parte del huso muscular ante el estiramiento rápido y contrae',
      'El miotático actúa sobre el propio músculo estirado y el inverso actúa sobre su antagonista, al que relaja para dejar avanzar el movimiento',
      'El miotático aparece solo durante el estiramiento pasivo y el inverso solo cuando la contracción es voluntaria y sostenida',
    ],
    correcta: 0,
    explicacion:
      'Son dos receptores distintos con dos respuestas opuestas: el huso muscular vigila el alargamiento y su velocidad, y su respuesta es contraer; el órgano tendinoso de Golgi vigila la tensión, y ante una tensión alta y mantenida su respuesta es relajar, lo que se llama inhibición autógena. El distractor más tentador intercambia los dos receptores, que es el error clásico. La tercera opción describe la inhibición recíproca, un mecanismo distinto de los dos. Dato para recordar: huso detecta estiramiento y contrae; Golgi detecta tensión y relaja.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['reflejo miotático', 'órgano tendinoso de Golgi', 'inhibición autógena'],
  },
  {
    id: 'D6-017',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'El mismo deportista registra −5 cm en el sit and reach de un club y 18 cm en el de otro, el mismo día y sin haber entrenado entre las dos tomas. ¿Cómo se explica?',
    opciones: [
      'Los dos cajones tienen el cero en sitios distintos: en uno coincide con la planta del pie y en el otro la planta está marcada en 23 cm',
      'El primer club midió en frío, nada más llegar, y el segundo tras un calentamiento completo: el calor aumenta la extensibilidad y explica toda la diferencia',
      'El primer club usó la versión con las rodillas flexionadas y el segundo la versión clásica con las piernas completamente extendidas',
      'Uno de los dos registros está mal tomado, porque un valor negativo es imposible en el sit and reach y obliga a repetir la medición',
    ],
    correcta: 0,
    explicacion:
      'La diferencia de 23 cm entre las dos anotaciones es exactamente el desplazamiento de escala del cajón calibrado: en la versión clásica el cero está en la planta del pie y no llegar a las puntas da negativos, mientras que en la calibrada la planta marca 23 cm y todos los valores salen positivos. El distractor más tentador es el calentamiento, que sí modifica el resultado, pero en unos pocos centímetros y nunca en la magnitud de un cambio de escala. Dato para recordar: antes de anotar nada, mira dónde tiene el cero el cajón.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.3 — Tests de flexibilidad',
    etiquetas: ['sit and reach', 'protocolo', 'evaluación', 'escala'],
  },
  {
    id: 'D6-018',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Dos jugadores de su equipo fallan el mismo test de flexión de cadera. Al primero, la pierna se le frena con una sensación de tirón en la parte posterior del muslo, que cede si se insiste con suavidad. Al segundo, la pierna se detiene en seco con un tope duro en la ingle, sin tirón muscular y sin ceder nada por más que se insista.',
    enunciado: '¿Qué diferencia hay entre los dos casos?',
    opciones: [
      'El primero tiene una limitación muscular y el segundo una limitación articular, así que estirar solo le sirve al primero',
      'Los dos tienen una limitación de elasticidad muscular, pero el segundo la tiene en un grado más avanzado y por eso su tope se siente más duro',
      'El primero tiene una limitación articular de la cadera y el segundo una limitación de elasticidad muscular por sobrecarga de entrenamiento',
      'Los dos tienen el mismo problema de flexibilidad y ambos responderán igual a un programa de estiramientos sostenido en el tiempo',
    ],
    correcta: 0,
    explicacion:
      'La sensación final del movimiento es lo que separa los dos casos: un freno elástico que tira y cede apunta al músculo, y un tope duro que no cede apunta a la estructura articular, hueso contra hueso o cápsula tensa. Como la flexibilidad es la suma de movilidad y elasticidad, el mismo resultado en el test puede venir de dos orígenes distintos. El distractor más tentador es tratarlos como el mismo problema en distinto grado, que es lo que se hace en la práctica cuando solo se mira el número del test. Dato para recordar: al segundo, estirar no le va a resolver nada.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['movilidad articular', 'elasticidad', 'diagnóstico', 'prescripción'],
  },
  {
    id: 'D6-019',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 3,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre la flexibilidad.',
    opciones: [
      'Es la única capacidad física que empieza a involucionar ya en la infancia si no se trabaja',
      'En el trabajo con niños el objetivo es mantener la flexibilidad que ya traen, no desarrollarla',
      'La explicación clásica del efecto del FNP son la inhibición autógena y la inhibición recíproca',
      'Los estiramientos previos a la sesión han demostrado prevenir las lesiones musculares',
      'El estiramiento balístico es el procedimiento recomendado para el calentamiento de principiantes',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Las tres primeras son correctas y las tres se sostienen entre sí: como la flexibilidad se pierde desde temprano, con niños se trabaja para conservarla, y el FNP se explica clásicamente por los dos mecanismos de inhibición. La cuarta es la creencia de campo más extendida del módulo: lo que reduce lesiones son los programas de calentamiento con trabajo de fuerza, sobre todo excéntrica, no el estiramiento. La quinta invierte la recomendación: en el calentamiento van dinámicos, y el balístico se reserva para deportistas formados. Dato para recordar: el estiramiento cumple con el rango de movimiento; no le pidas objetivos que no son suyos.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4 — Flexibilidad',
    etiquetas: ['FNP', 'edad', 'lesiones', 'calentamiento'],
  },
  {
    id: 'D6-020',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 1,
    enunciado:
      'Aplica el sit and reach con un cajón calibrado en el que la planta del pie está marcada en 23 cm. El deportista llega con las yemas 8 cm más allá de la punta de los pies. ¿Qué valor debe registrar?',
    respuesta: 31,
    tolerancia: 0.5,
    unidad: 'cm',
    pasos: [
      'En el cajón calibrado, la planta del pie corresponde a la marca de 23 cm',
      'El deportista supera esa referencia en 8 cm',
      'Valor registrado = 23 cm + 8 cm',
      'Valor registrado = 31 cm',
    ],
    explicacion:
      'El valor que se anota es la lectura de la regla del cajón, no la distancia respecto a los pies: con la planta en 23 cm, superar las puntas en 8 cm se registra como 31 cm. El error más frecuente es anotar los 8 cm directamente, que es la lectura correcta pero de otro cajón, el clásico con el cero en la planta del pie. Dato para recordar: los dos cajones son válidos y sus resultados no se pueden comparar entre sí sin corregir los 23 cm de diferencia de escala.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.3 — Tests de flexibilidad',
    etiquetas: ['sit and reach', 'cálculo', 'protocolo'],
  },
  {
    id: 'D6-021',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Mide con goniómetro la flexión de codo de un lanzador. En extensión completa el instrumento marca 12° y al final de la flexión marca 138°. Calcule la amplitud de movimiento de esa articulación.',
    respuesta: 126,
    tolerancia: 1,
    unidad: 'grados',
    pasos: [
      'La amplitud de movimiento es la diferencia entre el ángulo final y el inicial',
      'ADM = ángulo final − ángulo inicial',
      'ADM = 138° − 12°',
      'ADM = 126°',
    ],
    explicacion:
      'La goniometría entrega dos lecturas y lo que interesa es el recorrido entre ellas, no la posición final: por eso siempre hay una resta. El error más frecuente es anotar los 138° como amplitud, ignorando que el codo partía de 12° y no de la posición anatómica de 0°, lo que infla el resultado en esos mismos 12° que el deportista nunca recorrió. Dato para recordar: ADM = ángulo final − ángulo inicial, y el ángulo final por sí solo no es el recorrido.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.3 — Tests de flexibilidad',
    etiquetas: ['goniometría', 'cálculo', 'amplitud de movimiento'],
  },
  {
    id: 'D6-022',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Una gimnasta alcanza 92° de flexión de cadera con ayuda externa y 69° por su propia contracción. ¿Qué porcentaje de su rango pasivo no es capaz de utilizar por sí misma?',
    respuesta: 25,
    tolerancia: 1,
    unidad: '%',
    pasos: [
      'Déficit de flexibilidad = flexibilidad pasiva − flexibilidad activa',
      'Déficit = 92° − 69° = 23°',
      'Porcentaje = (déficit ÷ flexibilidad pasiva) × 100',
      'Porcentaje = (23 ÷ 92) × 100 = 25 %',
    ],
    explicacion:
      'Son dos pasos y el enunciado pide el segundo: primero el déficit en grados y después qué fracción representa del rango pasivo, que es el total disponible. El error más frecuente es dividir el déficit entre la flexibilidad activa, 23 entre 69, lo que da 33 % y responde a otra pregunta: cuánto más rango tendría si pudiera usarlo todo. Dato para recordar: el denominador es el rango pasivo, porque es el techo real de la articulación.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.1 — Movilidad, elasticidad y flexibilidad',
    etiquetas: ['déficit de flexibilidad', 'cálculo', 'flexibilidad activa', 'porcentaje'],
  },
  {
    id: 'D6-023',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Dirige el calentamiento de un equipo de voleibol antes de una sesión de saltos y remates. El plan que le entregaron incluye ocho minutos de estiramientos estáticos mantenidos, con dos repeticiones de 45 segundos por grupo muscular, justo antes de entrar a la pista.',
    enunciado: '¿Qué ajuste corresponde hacer al calentamiento?',
    opciones: [
      'Sustituir los estiramientos estáticos por movilidad y estiramientos dinámicos, y llevar el trabajo estático a la vuelta a la calma',
      'Mantener los estiramientos estáticos en el calentamiento pero reducir cada repetición de 45 a 30 segundos, dejando dos por grupo muscular',
      'Sustituir los estiramientos estáticos por estiramientos balísticos con rebotes cortos y progresivos hasta el final del recorrido',
      'Eliminar por completo el trabajo de flexibilidad de la semana, porque compite con el entrenamiento de salto y le resta altura',
    ],
    correcta: 0,
    explicacion:
      'Noventa segundos acumulados por grupo muscular en estático, justo antes de una sesión de saltos, dejan una pérdida aguda de fuerza y de altura de salto; lo que corresponde en el calentamiento son estiramientos dinámicos, y el trabajo estático de desarrollo se conserva pero se mueve a la vuelta a la calma. El distractor más tentador es bajar a 30 s por repetición: mejora la cosa pero sigue acumulando 60 s por grupo, y no aporta lo que un calentamiento sí necesita, que es activación. Dato para recordar: no se elimina la flexibilidad del plan, se cambia de momento.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['calentamiento', 'estiramiento dinámico', 'potencia', 'prescripción'],
  },
  {
    id: 'D6-024',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un auxiliar aplica FNP a un atleta con isquiosurales cortos. Lo lleva de golpe al final del recorrido sin estiramiento previo, le pide una contracción máxima sostenida durante 20 segundos y, al terminar, suelta la pierna sin volver a estirar. El atleta refiere molestia y no gana rango.',
    enunciado: '¿Cómo debe corregirse la aplicación?',
    opciones: [
      'Estirar pasivamente unos 10 s, pedir una contracción isométrica submáxima de unos 6 s y aprovechar la relajación para un nuevo estiramiento de 10 a 30 s',
      'Mantener la contracción máxima de 20 s pero precederla de un estiramiento pasivo de unos 10 s, y soltar la pierna al terminar, sin un estiramiento final',
      'Sustituir la contracción isométrica por rebotes cortos y suaves en el final del recorrido, manteniendo igual el resto de la secuencia',
      'Repetir la misma secuencia tres veces por sesión, sin cambiar ningún tiempo, para que el efecto acumulado compense la falta de ganancia',
    ],
    correcta: 0,
    explicacion:
      'Los tres fallos de la aplicación son de protocolo: falta el estiramiento previo que pone el músculo en tensión, la contracción es máxima y demasiado larga cuando basta con unos 6 s submáximos, y sobre todo falta el estiramiento final, que es donde se gana el rango. El distractor más tentador conserva la contracción de 20 s y añade solo el estiramiento previo: corrige un fallo de tres y deja fuera el paso que produce la ganancia. Dato para recordar: el rango se gana en el estiramiento posterior a la contracción, no en la contracción.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['FNP', 'protocolo', 'mantener-relajar', 'prescripción'],
  },
  {
    id: 'D6-025',
    modulo: 'd6-flexibilidad',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Va a programar trabajo de flexibilidad estática para mejorar el rango de los isquiosurales de un grupo de adultos. ¿Qué prescripción corresponde?',
    opciones: [
      'De 10 a 30 s por repetición, con 2 a 4 repeticiones hasta acumular unos 60 s por grupo muscular, al menos 2 o 3 días por semana',
      'De 3 a 5 s por repetición, con 10 repeticiones seguidas hasta acumular unos 40 s por grupo muscular, todos los días de la semana',
      'Una sola repetición de 3 minutos continuos por grupo muscular, sin fraccionar en varias series, dos días por semana',
      'De 45 a 60 s por repetición, con 6 repeticiones hasta acumular unos 5 min por grupo muscular, en cada sesión de entrenamiento',
    ],
    correcta: 0,
    explicacion:
      'La referencia práctica es acumular alrededor de 60 s por grupo muscular repartidos en repeticiones de 10 a 30 s, con una frecuencia mínima de dos o tres días semanales. El distractor más tentador es el de 3 a 5 s con muchas repeticiones, porque es lo que se ve en la mayoría de vueltas a la calma; el problema es que por debajo de 10 s el estímulo no alcanza a producir el efecto. Dato para recordar: pasar de 30 s en una sola repetición no aporta nada extra, así que se reparte en varias.',
    referencia: 'Cartilla 4, Tema 3, Subtema 3.4.2 — Procedimientos de entrenamiento',
    etiquetas: ['estiramiento estático', 'prescripción', 'dosificación'],
  },
];
