// content/banco/d7-modelos-planificacion.ts
// Bloque D · Paso 15. 25 ítems.
//
// Reparto verificado contra verificarCuotas(items, CUOTAS):
//   Nivel        11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   Dificultad   6 de nivel 1 · 12 de nivel 2 · 7 de nivel 3
//   Tipos        13 única · 3 caso · 2 cálculo · 2 múltiple · 2 emparejar
//                · 2 ordenar · 1 V/F  (7 tipos distintos)
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D7-001',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿En qué tres períodos divide el modelo tradicional el macrociclo?',
    opciones: [
      'Preparatorio, competitivo y transitorio',
      'Acumulación, transformación y realización',
      'General, especial y de mantenimiento',
      'Introductorio, de choque y de descarga',
    ],
    correcta: 0,
    explicacion:
      'El macrociclo del modelo tradicional se divide en período preparatorio, período competitivo y período transitorio, siempre en ese orden. El distractor más tentador es acumulación, transformación y realización: esos son los tres mesociclos del ATR, que pertenece a los modelos contemporáneos y funciona con bloques de semanas, no con períodos de meses. Dato para recordar: si oyes "preparatorio, competitivo y transitorio", estás en el modelo tradicional.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['modelo tradicional', 'períodos', 'macrociclo'],
  },
  {
    id: 'D7-002',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿A qué autor se atribuye la formulación del modelo tradicional de planificación?',
    opciones: ['Matveiev', 'Verkhoshansky', 'Issurin', 'Arosiev'],
    correcta: 0,
    explicacion:
      'Matveiev formuló en los años sesenta la periodización clásica, que es lo que hoy se llama modelo tradicional. El distractor más tentador es Verkhoshansky, porque también es un autor soviético clásico del entrenamiento; pero su aporte es justamente el contrario, el de las cargas concentradas que rompen con la propuesta de Matveiev. Issurin es del ATR y Arosiev del péndulo. Dato para recordar: Matveiev es el punto de partida y todos los demás nacen de discutirlo.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['Matveiev', 'modelo tradicional', 'autores'],
  },
  {
    id: 'D7-003',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      '¿Cómo evolucionan el volumen y la intensidad a lo largo del macrociclo del modelo tradicional?',
    opciones: [
      'El volumen arranca alto y baja; la intensidad arranca baja y sube',
      'El volumen arranca bajo y sube; la intensidad arranca alta y baja',
      'Los dos arrancan altos y bajan juntos hacia la competencia',
      'Los dos se mantienen constantes y solo cambia el contenido específico',
    ],
    correcta: 0,
    explicacion:
      'La relación es inversa: se empieza con mucho volumen y poca intensidad para construir base, y se termina con poco volumen y mucha intensidad para afinar la forma. El distractor más tentador es la opción invertida, porque quien recuerda "la relación es inversa" pero no en qué sentido acierta la mitad del enunciado y falla la dirección. Dato para recordar: primero se acumula cantidad, después se afila la calidad.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['volumen', 'intensidad', 'modelo tradicional', 'relación inversa'],
  },
  {
    id: 'D7-004',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'El modelo tradicional desarrolla las capacidades de forma consecutiva, concentrando una sola orientación de carga en cada bloque.',
    correcta: false,
    explicacion:
      'Falso. El modelo tradicional desarrolla varias capacidades de forma simultánea: en la misma semana hay fuerza, resistencia y velocidad, cada una con una porción del tiempo. Concentrar una sola orientación por bloque es la propuesta de las cargas concentradas de Verkhoshansky y del ATR, es decir, de los modelos contemporáneos. La confusión nace de que los dos modelos usan la palabra bloque para cosas distintas. Dato para recordar: tradicional es simultáneo, contemporáneo es consecutivo.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1 — Modelos de planificación',
    etiquetas: ['modelo tradicional', 'cargas simultáneas', 'cargas concentradas'],
  },
  {
    id: 'D7-005',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿En qué consiste el trabajo con cargas concentradas?',
    opciones: [
      'Concentrar en un mismo bloque la carga de una sola orientación, en vez de repartirla entre varias capacidades',
      'Concentrar todo el volumen de la temporada en el período preparatorio y competir sin entrenar',
      'Concentrar las sesiones duras en los tres días previos a cada competencia del calendario',
      'Concentrar el trabajo de todas las capacidades en una única sesión diaria muy larga',
    ],
    correcta: 0,
    explicacion:
      'Las cargas concentradas agrupan en un bloque el estímulo de una sola orientación, porque el deportista de alto nivel ya no responde a la carga diluida entre muchas capacidades. El distractor más tentador es el de concentrar las sesiones duras antes de competir: eso describe una estrategia de afinamiento, no un modelo de distribución de la carga, y además llegaría a la competencia con el deportista fatigado. Dato para recordar: se concentra la orientación, no el calendario ni la duración de la sesión.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['cargas concentradas', 'Verkhoshansky', 'modelo contemporáneo'],
  },
  {
    id: 'D7-006',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'En el modelo ATR, ¿qué se trabaja durante el mesociclo de acumulación?',
    opciones: [
      'Capacidades básicas, con volumen alto e intensidad baja',
      'El gesto específico de la modalidad, con la intensidad ya elevada',
      'La velocidad y el afinamiento, con el pico de forma como objetivo',
      'La recuperación tras la competencia, con actividad ligera y variada',
    ],
    correcta: 0,
    explicacion:
      'La acumulación es la primera letra del ATR y trabaja las capacidades básicas con volumen alto e intensidad baja: es la fase que llena el depósito. El distractor más tentador es el trabajo específico con intensidad elevada, que corresponde a la transformación, la segunda letra; quien recuerda las tres palabras pero no su orden funcional las cruza aquí. La tercera opción describe la realización y la cuarta un mesociclo de recuperación. Dato para recordar: acumulación, transformación y realización van de lo general a lo competitivo.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['ATR', 'acumulación', 'Issurin', 'mesociclo'],
  },
  {
    id: 'D7-007',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada modelo de planificación con el autor al que se atribuye.',
    izquierda: [
      'Modelo tradicional',
      'Cargas concentradas',
      'ATR',
      'Péndulo',
      'Microciclo estructurado',
    ],
    derecha: ['Matveiev', 'Verkhoshansky', 'Issurin y Kaverin', 'Arosiev', 'Seirul·lo'],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
    explicacion:
      'Cada modelo tiene un autor identificable y el examen los pregunta emparejados. El par que más se falla es cargas concentradas con ATR: Verkhoshansky propuso concentrar la carga de una orientación y años después Issurin y Kaverin ordenaron esa idea en los tres mesociclos del ATR, así que están emparentados pero no son lo mismo ni son del mismo autor. El otro cruce frecuente es asignar el péndulo al deporte de equipo, cuando ahí lo que manda es el microciclo estructurado de Seirul·lo. Dato para recordar: Matveiev abre la lista y todos los demás responden a él.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1 — Modelos de planificación',
    etiquetas: ['autores', 'modelos', 'clasificación'],
  },
  {
    id: 'D7-008',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada modelo con el rasgo que lo define.',
    izquierda: ['Tradicional', 'Cargas concentradas', 'Péndulo', 'Alta intensidad'],
    derecha: [
      'Un solo pico de forma, tres períodos y cargas simultáneas',
      'Una sola orientación por bloque, con caída del rendimiento durante la concentración',
      'Alternancia de ciclos de preparación general y especial a lo largo de la temporada',
      'Carga elevada durante todo el año, sin diferencias marcadas entre períodos',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Cada modelo se reconoce por un rasgo que ninguno de los otros comparte. El par que más se falla es el de alta intensidad con cargas concentradas: los dos suenan a "entrenar duro", pero el de alta intensidad mantiene la carga elevada de forma continua y sin períodos marcados, mientras que las cargas concentradas alternan una fase de acumulación con otra de asimilación en la que la carga baja. Dato para recordar: al tradicional lo define el pico único; a las cargas concentradas, la caída deliberada del rendimiento.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1 — Modelos de planificación',
    etiquetas: ['modelos', 'rasgos definitorios', 'clasificación'],
  },
  {
    id: 'D7-009',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Qué es el pico de rendimiento?',
    opciones: [
      'El momento en que coinciden la mejor condición física, técnica y psicológica del deportista',
      'La carga más alta que el deportista soporta en una única sesión de entrenamiento',
      'El valor máximo de frecuencia cardíaca registrado durante una competencia',
      'El instante del período preparatorio en que el volumen alcanza su valor más alto',
    ],
    correcta: 0,
    explicacion:
      'El pico de rendimiento es un estado del deportista, no un dato de una sesión: es cuando la condición física, la técnica y el estado psicológico coinciden en su mejor punto. El distractor más tentador es la carga más alta de una sesión, porque en el lenguaje de gimnasio "pico" suele significar el máximo de un día; en planificación se refiere al estado de forma, que se construye durante meses y se sostiene unas pocas semanas. Dato para recordar: planificar es colocar el pico encima de la fecha correcta.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1 — Modelos de planificación',
    etiquetas: ['pico de rendimiento', 'forma deportiva'],
  },
  {
    id: 'D7-010',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es la función del período transitorio en el modelo tradicional?',
    opciones: [
      'Recuperar con actividad ligera y variada, sin perder toda la base construida',
      'Aumentar progresivamente la intensidad para llegar afinado a la competencia',
      'Acumular el mayor volumen de la temporada con trabajo general',
      'Competir en las pruebas menores que sirven de control del proceso',
    ],
    correcta: 0,
    explicacion:
      'El período transitorio cierra el macrociclo y sirve para recuperar de verdad, con actividad ligera y variada que evita perder toda la base construida durante el año. El distractor más tentador es acumular el mayor volumen con trabajo general: eso es el período preparatorio, y se confunde porque en los dos casos el trabajo es poco específico. La diferencia está en la carga, que en el transitorio es baja. Dato para recordar: transitorio no significa preparar la transición al siguiente ciclo entrenando, significa descansar activamente.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['período transitorio', 'modelo tradicional', 'recuperación'],
  },
  {
    id: 'D7-011',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: 'En los modelos contemporáneos, ¿a qué se refiere el rasgo de flexibilidad?',
    opciones: [
      'A que el plan se ajusta sobre la marcha según la respuesta del deportista y los cambios del calendario',
      'A que se incluye trabajo de amplitud de movimiento en todas las sesiones del ciclo',
      'A que el deportista elige libremente los contenidos de cada sesión de entrenamiento',
      'A que la carga se reparte por igual entre todas las capacidades físicas del deportista',
    ],
    correcta: 0,
    explicacion:
      'La flexibilidad de un modelo de planificación es la capacidad del plan de modificarse mientras se ejecuta, según cómo responde el deportista y cómo se mueve el calendario de competencias. El distractor más tentador es el trabajo de amplitud de movimiento, porque en el lenguaje de campo flexibilidad es una capacidad física; aquí la palabra nombra una propiedad del plan, no un contenido de entrenamiento. Dato para recordar: los tres rasgos del modelo contemporáneo son flexibilidad, multifuncionalidad e individualización.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['flexibilidad', 'modelo contemporáneo'],
  },
  {
    id: 'D7-012',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      '¿Por qué el modelo tradicional se queda corto ante un calendario con muchas competencias importantes repartidas por el año?',
    opciones: [
      'Porque está construido para producir un solo pico de forma, y el resto del año el deportista está por debajo de su mejor nivel',
      'Porque no contempla el período competitivo dentro de la estructura del macrociclo',
      'Porque su carga es demasiado alta para sostenerla más de tres o cuatro meses seguidos',
      'Porque prescinde del trabajo general y llega sin base a las competencias de mitad de año',
    ],
    correcta: 0,
    explicacion:
      'El modelo tradicional ordena toda la temporada hacia un único pico: fuera de esa ventana el deportista está construyendo o está de bajada, lo cual es un problema si hay objetivos importantes en marzo, en julio y en noviembre. El distractor más tentador es el de la carga demasiado alta, porque suena razonable que el problema sea la exigencia; en realidad el tradicional trabaja con carga diluida y su límite es de ubicación temporal, no de magnitud. Dato para recordar: el problema del tradicional no es cuánto se entrena, es cuándo se llega.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['modelo tradicional', 'calendario', 'pico de rendimiento'],
  },
  {
    id: 'D7-013',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Durante un bloque de cargas concentradas el rendimiento del deportista baja respecto al que tenía antes de empezar. ¿Cómo se interpreta esa caída?',
    opciones: [
      'Es esperada: forma parte del efecto retardado, y la mejora aparece después, cuando la carga baja y el organismo asimila',
      'Es señal de que la carga se calculó por encima de lo tolerable y hay que interrumpir el bloque',
      'Es consecuencia de haber trabajado varias capacidades a la vez y haber diluido el estímulo',
      'Es normal solo en deportistas principiantes, que aún no toleran cargas de una sola orientación',
    ],
    correcta: 0,
    explicacion:
      'La caída del rendimiento durante la concentración es la firma del efecto retardado: el organismo está sobrecargado y la ganancia se manifiesta más tarde, en la fase en que la carga baja. El distractor más tentador es interrumpir el bloque por exceso de carga, porque el síntoma observable es idéntico al de una sobrecarga mal calculada; la diferencia es que aquí la caída estaba prevista y la medición de resultados se hace al final de la fase de realización, no dentro de la acumulación. Dato para recordar: si cortas la concentración a mitad, te quedas sin la caída y también sin la subida.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['efecto retardado', 'cargas concentradas', 'Verkhoshansky'],
  },
  {
    id: 'D7-014',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES características que corresponden al modelo tradicional.',
    opciones: [
      'Busca un único pico de forma en el macrociclo',
      'Divide el macrociclo en período preparatorio, competitivo y transitorio',
      'Desarrolla varias capacidades de forma simultánea, de lo general a lo específico',
      'Concentra la carga de una sola orientación en cada bloque de trabajo',
      'Reparte la temporada en tres o cuatro macrociclos con su propio pico cada uno',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Pico único, tres períodos y desarrollo simultáneo de lo general a lo específico son tres de las cuatro marcas del modelo tradicional; la cuarta es la relación inversa entre volumen e intensidad. Los dos distractores describen el modelo contemporáneo: la concentración de una orientación por bloque y el reparto del año en varios macrociclos con su pico. El más tentador es el primero de los dos, porque el tradicional también organiza el trabajo en etapas y se confunde etapa con bloque concentrado. Dato para recordar: tradicional es un pico y cargas simultáneas.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['modelo tradicional', 'características', 'modelo contemporáneo'],
  },
  {
    id: 'D7-015',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Qué diferencia el desarrollo simultáneo de las capacidades del desarrollo consecutivo?',
    opciones: [
      'El simultáneo trabaja varias capacidades en la misma semana con una porción del tiempo cada una; el consecutivo dedica casi todo el tiempo a una sola durante varias semanas',
      'El simultáneo alterna capacidades dentro de la misma sesión; el consecutivo las trabaja en sesiones distintas del mismo día',
      'El simultáneo se aplica solo en el período preparatorio; el consecutivo, solo en el período competitivo',
      'El simultáneo utiliza cargas altas y el consecutivo cargas bajas repetidas muchas veces',
    ],
    correcta: 0,
    explicacion:
      'La diferencia está en cómo se reparte el tiempo entre capacidades: simultáneo significa varias a la vez con estímulo diluido, y consecutivo significa una sola concentrada durante semanas, confiando en el efecto residual de lo trabajado antes. El distractor más tentador es el que sitúa la diferencia dentro de la sesión o del día: ahí lo que cambia es la organización de una jornada, no el modelo de distribución de la carga a lo largo del ciclo. Dato para recordar: la escala de la comparación son semanas, no sesiones.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1 — Modelos de planificación',
    etiquetas: ['cargas simultáneas', 'cargas consecutivas', 'efecto residual'],
  },
  {
    id: 'D7-016',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado:
      'Ordene las etapas y períodos de un macrociclo tradicional, desde el inicio de la temporada hasta el final.',
    elementos: [
      'Etapa de preparación general: volumen alto y trabajo poco específico',
      'Etapa de preparación especial: aparece el trabajo propio de la modalidad',
      'Etapa precompetitiva: baja el volumen y se pule la forma',
      'Período competitivo: se sostiene el rendimiento sobre el calendario',
      'Período transitorio: recuperación con actividad ligera y variada',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La secuencia va de lo general a lo específico y termina descansando: preparación general, preparación especial, precompetitiva, competitivo y transitorio. El error más frecuente es colocar el transitorio al principio, razonando que primero se descansa y luego se arranca; el transitorio cierra el macrociclo anterior, no abre el siguiente, y por eso su carga es baja en lugar de creciente. El otro error es invertir preparación general y especial, que es justamente la progresión que el modelo defiende. Dato para recordar: las dos primeras etapas son las dos mitades del período preparatorio.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['períodos', 'etapas', 'modelo tradicional', 'secuencia'],
  },
  {
    id: 'D7-017',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Por qué el trabajo por bloques concentrados necesita apoyarse en el efecto residual del entrenamiento?',
    opciones: [
      'Porque mientras se concentra una orientación las demás capacidades no se entrenan, y solo el residuo de lo ya trabajado evita que se pierdan',
      'Porque el residuo de fatiga acumulada es lo que provoca la mejora en la fase siguiente del bloque',
      'Porque los restos metabólicos del bloque anterior estimulan la adaptación del bloque siguiente',
      'Porque el efecto residual permite alargar cada bloque hasta que la capacidad deje de mejorar',
    ],
    correcta: 0,
    explicacion:
      'Concentrar la carga en una orientación implica dejar de entrenar el resto durante semanas, y eso solo es viable porque una capacidad bien entrenada se mantiene un tiempo sin estímulo: ese remanente es el efecto residual. El distractor más tentador confunde residual con residuo de fatiga, que es otra cosa y pertenece al efecto retardado: la fatiga acumulada explica por qué el rendimiento cae durante el bloque, no por qué las demás capacidades sobreviven. Dato para recordar: efecto residual es lo que queda de lo entrenado; efecto retardado es cuándo aparece la mejora.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['efecto residual', 'efecto retardado', 'bloques', 'multifuncionalidad'],
  },
  {
    id: 'D7-018',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador consigue el plan anual de un fondista internacional y se lo aplica tal cual a un juvenil de dieciséis años que lleva dos temporadas corriendo. A las seis semanas el juvenil llega roto a los entrenamientos, ha bajado su marca y ha faltado a dos sesiones por molestias en el tendón de Aquiles.',
    enunciado: '¿Cuál es el error de planificación que mejor explica lo que pasó?',
    opciones: [
      'Aplicó un modelo diseñado para un deportista con años de base y con otro calendario, sin individualizar nada',
      'Aplicó un modelo tradicional cuando el juvenil necesitaba un modelo contemporáneo por bloques',
      'Repartió la carga entre demasiadas capacidades a la vez y diluyó el estímulo del juvenil',
      'Colocó el período transitorio al inicio de la temporada en lugar de al final del macrociclo',
    ],
    correcta: 0,
    explicacion:
      'El plan del internacional supone una base construida durante años y un calendario que el juvenil no tiene; sin individualización, la carga que en uno produce adaptación en el otro produce fatiga y lesión. El distractor más tentador es el de haber elegido tradicional en vez de contemporáneo, porque parece un error de modelo; en realidad el juvenil es justo el perfil al que le conviene un enfoque tradicional, con base general amplia. Dato para recordar: el modelo se elige por el deportista y el calendario, nunca copiando el plan de otro.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['individualización', 'modelo contemporáneo', 'juvenil', 'elección de modelo'],
  },
  {
    id: 'D7-019',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione los TRES rasgos que caracterizan a los modelos contemporáneos.',
    opciones: [
      'Flexibilidad: el plan se ajusta sobre la marcha según la respuesta y el calendario',
      'Multifuncionalidad: cada bloque persigue varios efectos y se aprovecha el efecto residual',
      'Individualización: el plan se adapta al nivel y a la respuesta de ese deportista concreto',
      'Estandarización: el plan se aplica igual a todo el grupo para poder compararlo',
      'Linealidad: la carga crece de forma constante desde el primer día hasta la competencia',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'Flexibilidad, multifuncionalidad e individualización son los tres rasgos con los que se define el modelo contemporáneo, y conviene sabérselos con esos nombres exactos. Los dos distractores son sus contrarios: la estandarización es lo opuesto a individualizar, y la linealidad es lo opuesto a un plan que se ajusta y que alterna concentración con asimilación. El más tentador es la linealidad, porque suena a progresión bien hecha; una progresión lineal sin descargas es justamente lo que el modelo evita. Dato para recordar: los tres rasgos son propiedades del plan, no contenidos de entrenamiento.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['modelo contemporáneo', 'flexibilidad', 'multifuncionalidad', 'individualización'],
  },
  {
    id: 'D7-020',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Llega al club un atleta de veinte años que nunca ha entrenado de forma sistemática. Quiere competir en los campeonatos departamentales, que se celebran una vez al año, en octubre. Estamos en enero y no hay ninguna otra competencia relevante en el calendario.',
    enunciado: '¿Qué modelo de planificación corresponde para esta primera temporada?',
    opciones: [
      'Tradicional: un macrociclo largo, base general amplia y un único pico colocado en octubre',
      'Por bloques concentrados: cuatro bloques de una sola orientación cada uno para acelerar la adaptación',
      'Cíclico con microciclo estructurado: una semana tipo que se repite de enero a octubre',
      'De alta intensidad: carga elevada durante todo el año sin diferencias marcadas entre períodos',
    ],
    correcta: 0,
    explicacion:
      'Un deportista sin base y con una sola competencia objetivo al año es el caso exacto para el que se diseñó el modelo tradicional: hay tiempo de sobra para construir de lo general a lo específico y solo hace falta un pico. El distractor más tentador es el trabajo por bloques concentrados, porque promete adaptación más rápida; concentrar una orientación exige una base previa que este atleta no tiene, y con él produciría fatiga en lugar de mejora. Dato para recordar: sin base construida, tradicional; con base y calendario denso, contemporáneo.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['elección de modelo', 'principiante', 'modelo tradicional'],
  },
  {
    id: 'D7-021',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un preparador físico entra a un equipo de fútbol profesional. La liga tiene treinta y ocho fechas repartidas en nueve meses, con partido casi todos los fines de semana y algunas semanas con doble compromiso. El técnico exige que el equipo rinda en cada partido.',
    enunciado: '¿Qué enfoque de planificación corresponde a este calendario?',
    opciones: [
      'Un enfoque cíclico con microciclo estructurado: una semana tipo que se repite tomando el partido como referencia fija',
      'Un macrociclo tradicional con un único pico colocado en la fecha treinta y ocho de la liga',
      'Bloques concentrados de seis semanas por orientación, aceptando la caída de rendimiento dentro de cada bloque',
      'Un período preparatorio de cuatro meses antes de empezar a competir en la liga',
    ],
    correcta: 0,
    explicacion:
      'Cuando hay que rendir cada semana durante nueve meses no existe un pico que colocar: la solución es repetir un ciclo corto que tome el partido como referencia y ajuste el contenido, que es justamente el microciclo estructurado. El distractor más tentador es el de los bloques concentrados, porque es el modelo moderno por excelencia; su caída deliberada de rendimiento dentro del bloque es inaceptable en un equipo al que se le exigen puntos cada fin de semana. Dato para recordar: competencia semanal sostenida pide modelo cíclico, no pico.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.3 — Modelos cíclicos',
    etiquetas: ['microciclo estructurado', 'deporte de equipo', 'Seirul·lo', 'elección de modelo'],
  },
  {
    id: 'D7-022',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Una entrenadora planifica con bloques ATR de 4 semanas de acumulación, 3 de transformación y 2 de realización. Dispone de 36 semanas de temporada. ¿Cuántos bloques ATR completos puede programar?',
    respuesta: 4,
    tolerancia: 0.5,
    unidad: 'bloques',
    pasos: [
      'Duración de un bloque ATR = acumulación + transformación + realización',
      'Duración = 4 + 3 + 2 = 9 semanas',
      'Bloques completos = semanas disponibles ÷ duración del bloque',
      'Bloques = 36 ÷ 9 = 4 bloques ATR',
    ],
    explicacion:
      'Cada bloque ATR es la suma de sus tres mesociclos, así que primero hay que sumar 4 + 3 + 2 = 9 semanas y solo después dividir el total de la temporada. El error más frecuente es dividir 36 entre 3 y responder 12, confundiendo el número de mesociclos con el de bloques: 12 es la cantidad de mesociclos, no de bloques completos. Como cada bloque termina en una realización, esas 4 respuestas son también los 4 picos de forma de la temporada. Dato para recordar: un bloque ATR son tres mesociclos, no uno.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['ATR', 'cálculo', 'macrociclo', 'picos'],
  },
  {
    id: 'D7-023',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un macrociclo tradicional de 40 semanas reparte el tiempo así: 60 % al período preparatorio, 30 % al competitivo y 10 % al transitorio. ¿Cuántas semanas más dura el período preparatorio que el competitivo?',
    respuesta: 12,
    tolerancia: 0.5,
    unidad: 'semanas',
    pasos: [
      'Período preparatorio = 40 × 0,60 = 24 semanas',
      'Período competitivo = 40 × 0,30 = 12 semanas',
      'Diferencia = 24 − 12',
      'Diferencia = 12 semanas',
    ],
    explicacion:
      'La pregunta pide una diferencia, no una duración: hay que calcular los dos períodos y restarlos, 24 menos 12 igual a 12 semanas. El error más frecuente es responder 24, que es la duración del preparatorio y no la diferencia, porque el 60 % es el porcentaje que salta a la vista. El otro error es restar los porcentajes y responder 30, olvidando convertirlos a semanas. Como comprobación, los tres períodos deben sumar el total: 24 + 12 + 4 = 40. Dato para recordar: en el modelo tradicional el preparatorio siempre es el período más largo.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.1 — Modelo tradicional',
    etiquetas: ['períodos', 'cálculo', 'macrociclo', 'modelo tradicional'],
  },
  {
    id: 'D7-024',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Una nadadora de nivel nacional tiene tres competencias objetivo en el año: marzo, julio y noviembre. ¿Cómo debe estructurarse su temporada?',
    opciones: [
      'En tres macrociclos, cada uno con su propio período competitivo y su pico de forma',
      'En un macrociclo anual con el pico colocado en la competencia de julio, la del medio',
      'En un macrociclo anual con el período competitivo extendido de marzo a noviembre',
      'En un macrociclo anual con tres períodos transitorios, uno después de cada competencia',
    ],
    correcta: 0,
    explicacion:
      'Tres objetivos separados por meses exigen tres picos, y un pico requiere su propio ciclo completo: la temporada se parte en tres macrociclos más cortos, cada uno con su preparación y su competitivo. El distractor más tentador es extender el período competitivo de marzo a noviembre, porque parece resolver el problema sin partir el año; un período competitivo de nueve meses no sostiene el rendimiento, solo lo deja caer sin volver a construirlo. Dato para recordar: un pico por macrociclo; si necesitas tres picos, necesitas tres macrociclos.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['macrociclo', 'picos', 'modelo contemporáneo', 'calendario'],
  },
  {
    id: 'D7-025',
    modulo: 'd7-modelos-planificacion',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Un mediofondista trabaja con bloques ATR. Ordene las fases de su bloque, de la primera a la última.',
    elementos: [
      'Acumulación: capacidades básicas con volumen alto e intensidad baja',
      'Transformación: trabajo específico de la modalidad, sube la intensidad',
      'Realización: afinamiento, velocidad y competencia objetivo',
      'Microciclo de descarga antes de arrancar el bloque siguiente',
    ],
    ordenCorrecto: [0, 1, 2, 3],
    explicacion:
      'El bloque ATR va de lo general a lo competitivo —acumulación, transformación, realización— y se cierra con una descarga breve que permite empezar el siguiente sin arrastrar fatiga. El error más frecuente es colocar la realización antes que la transformación, porque las dos suenan a trabajo intenso; la transformación convierte la base acumulada en rendimiento específico y la realización solo afina lo que ya está construido. El otro error es meter la descarga al principio, cuando su función es cerrar. Dato para recordar: acumular, transformar, realizar y descargar, en ese orden.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.1.2 — Modelos contemporáneos',
    etiquetas: ['ATR', 'secuencia', 'bloques', 'descarga'],
  },
];
