// content/banco/d8-estructuras.ts
// Bloque D · Paso 15. 25 ítems.
//
// Reparto verificado contra verificarCuotas(items, CUOTAS):
//   Nivel        11 recuerdo (44 %) · 8 comprensión (32 %) · 6 aplicación (24 %)
//   Dificultad   7 de nivel 1 · 12 de nivel 2 · 6 de nivel 3
//   Tipos        13 única · 3 caso · 2 cálculo · 2 múltiple · 2 emparejar
//                · 2 ordenar · 1 V/F  (7 tipos distintos)
//
// Los ítems son datos literales: nunca se generan con map(), plantillas ni
// funciones auxiliares. 25 objetos a mano son legibles, revisables y diffeables.
import type { Item } from '@/lib/tipos';

export const ITEMS: Item[] = [
  {
    id: 'D8-001',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuál es la estructura de mayor duración de la planificación y qué agrupa?',
    opciones: [
      'El macrociclo, que agrupa mesociclos',
      'El mesociclo, que agrupa macrociclos',
      'El microciclo, que agrupa mesociclos',
      'La sesión, que agrupa microciclos',
    ],
    correcta: 0,
    explicacion:
      'El macrociclo es la estructura mayor de la planificación y contiene mesociclos, que a su vez contienen microciclos, que a su vez contienen sesiones. El distractor más tentador es el que invierte macrociclo y mesociclo, porque los dos prefijos se confunden al leer rápido: macro es grande y meso es intermedio. Dato para recordar: el orden de mayor a menor es macrociclo, mesociclo, microciclo y sesión.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2 — Estructuras de la planificación',
    etiquetas: ['macrociclo', 'estructuras', 'jerarquía'],
  },
  {
    id: 'D8-002',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuál es la duración habitual de un microciclo?',
    opciones: [
      '7 días, dentro de un rango de 3 a 10',
      '4 semanas, dentro de un rango de 2 a 6',
      '3 meses, dentro de un rango de 3 a 12',
      '2 días, dentro de un rango de 1 a 4',
    ],
    correcta: 0,
    explicacion:
      'El microciclo dura habitualmente 7 días, aunque el rango legítimo va de 3 a 10 según su función. El distractor más tentador es el de 4 semanas dentro de un rango de 2 a 6: esa es la duración del mesociclo, y micro y meso se cruzan constantemente porque ambos nombres suenan a estructura intermedia. Dato para recordar: el microciclo se cuenta en días y el mesociclo en semanas.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.3 — Microestructura',
    etiquetas: ['microciclo', 'duración', 'estructuras'],
  },
  {
    id: 'D8-003',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuál es la duración habitual de un mesociclo?',
    opciones: [
      '4 semanas, dentro de un rango de 2 a 6',
      '7 días, dentro de un rango de 3 a 10',
      '6 meses, dentro de un rango de 3 a 12',
      '12 semanas, dentro de un rango de 8 a 16',
    ],
    correcta: 0,
    explicacion:
      'El mesociclo dura habitualmente 4 semanas, es decir alrededor de un mes, con un rango que va de 2 a 6 semanas según la orientación del bloque. El distractor más tentador son los 7 días, que corresponden al microciclo: quien recuerda que el mesociclo agrupa microciclos pero no cuántos, tiende a colapsar los dos niveles. Dato para recordar: un mesociclo típico son cuatro microciclos de una semana.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.2 — Mesoestructura',
    etiquetas: ['mesociclo', 'duración', 'estructuras'],
  },
  {
    id: 'D8-004',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿Cuáles son las tres partes de una sesión de entrenamiento, en orden?',
    opciones: [
      'Parte inicial o calentamiento, parte principal y parte final o vuelta a la calma',
      'Parte general, parte específica y parte de competencia',
      'Activación, trabajo de fuerza y trabajo de resistencia',
      'Preparatoria, competitiva y transitoria',
    ],
    correcta: 0,
    explicacion:
      'Toda sesión se ordena en parte inicial o calentamiento, parte principal o fundamental y parte final o vuelta a la calma. El distractor más tentador es preparatoria, competitiva y transitoria: esos son los tres períodos del macrociclo, no las partes de una sesión, y se confunden porque los dos tríos describen un arranque, un centro y un cierre. Dato para recordar: períodos son del macrociclo; partes son de la sesión.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['sesión', 'partes', 'calentamiento', 'vuelta a la calma'],
  },
  {
    id: 'D8-005',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué se define en el nivel del macrociclo y no en ningún otro?',
    opciones: [
      'Cuál es la competencia principal, en qué fecha cae y cómo se reparte el tiempo en períodos',
      'Qué día de la semana es duro y qué día es suave para el deportista',
      'La orientación de la carga de las próximas cuatro semanas de trabajo',
      'El orden concreto de los ejercicios dentro de la parte principal',
    ],
    correcta: 0,
    explicacion:
      'El macrociclo es el nivel donde se fija la competencia objetivo, su fecha y el reparto del tiempo en períodos: todo lo demás se ordena hacia atrás desde ahí. El distractor más tentador es la orientación de la carga de cuatro semanas, porque también suena a decisión de fondo; esa decisión es del mesociclo. La alternancia de días es del microciclo y el orden de ejercicios es de la sesión. Dato para recordar: cada nivel resuelve una pregunta distinta y el error caro es contestar en el nivel equivocado.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.1 — Macroestructura',
    etiquetas: ['macrociclo', 'nivel de decisión', 'competencia principal'],
  },
  {
    id: 'D8-006',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Cuál es la función de la vuelta a la calma al cerrar una sesión?',
    opciones: [
      'Devolver progresivamente el organismo a valores de reposo y favorecer la retirada de metabolitos',
      'Prevenir la aparición del dolor muscular tardío de los días siguientes',
      'Aprovechar la fatiga acumulada para añadir un último estímulo de fuerza',
      'Elevar la temperatura muscular antes de que el deportista se retire a la ducha',
    ],
    correcta: 0,
    explicacion:
      'La vuelta a la calma baja de forma progresiva la frecuencia cardíaca y la ventilación, favorece la retirada de metabolitos y evita que la sangre quede acumulada en las piernas al parar de golpe. El distractor más tentador es la prevención de las agujetas, porque es lo que todo el mundo repite en el campo: el dolor tardío viene del daño microscópico de la fibra, sobre todo del trabajo excéntrico, y aparece igual con o sin vuelta a la calma. Dato para recordar: acelera el retorno a valores basales, no evita el dolor.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['vuelta a la calma', 'sesión', 'recuperación'],
  },
  {
    id: 'D8-007',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'vf',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado:
      'Un microciclo debe durar obligatoriamente siete días, porque esa es la duración del ciclo de adaptación del organismo.',
    correcta: false,
    explicacion:
      'Falso. El microciclo suele durar siete días porque el calendario social y competitivo es semanal, no porque el organismo tenga un ciclo de adaptación de siete días. El rango legítimo va de 3 a 10 días: un microciclo de choque de cinco días o uno de aproximación de diez son igual de válidos. La confusión nace de ver siempre planes escritos en semanas y asumir que la semana es una unidad fisiológica. Dato para recordar: 7 días es el valor habitual, no una obligación.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.3 — Microestructura',
    etiquetas: ['microciclo', 'duración', 'estructuras'],
  },
  {
    id: 'D8-008',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada estructura de la planificación con su duración habitual.',
    izquierda: ['Macrociclo', 'Mesociclo', 'Microciclo', 'Sesión'],
    derecha: [
      'De 3 a 12 meses',
      'De 2 a 6 semanas, lo normal 4',
      'De 3 a 10 días, lo normal 7',
      'De 60 a 120 minutos',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
    ],
    explicacion:
      'Las cuatro estructuras se distinguen por su escala de tiempo: meses, semanas, días y minutos. El par que más se falla es mesociclo con microciclo, porque los dos prefijos suenan parecidos y los dos se escriben en calendarios semanales; la clave es que el mesociclo se cuenta en semanas y el microciclo en días. Conviene fijar además que un mesociclo típico contiene cuatro microciclos. Dato para recordar: la escala baja de meses a semanas, de semanas a días y de días a minutos.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2 — Estructuras de la planificación',
    etiquetas: ['estructuras', 'duración', 'clasificación'],
  },
  {
    id: 'D8-009',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'emparejar',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: 'Relacione cada tipo de mesociclo con su función.',
    izquierda: ['Entrante', 'Básico', 'De control', 'Precompetitivo', 'De recuperación'],
    derecha: [
      'Reincorporar tras el descanso, con carga moderada y mucha variedad',
      'Producir la adaptación de fondo: es el motor del plan',
      'Comprobar con tests o competencias menores si el proceso va bien',
      'Pulir la forma: baja el volumen y sube el trabajo específico',
      'Restablecer tras un bloque duro o tras la competencia principal',
    ],
    pares: [
      [0, 0],
      [1, 1],
      [2, 2],
      [3, 3],
      [4, 4],
    ],
    explicacion:
      'Cada tipo de mesociclo cumple una función que no cumple ningún otro, y el examen los pregunta emparejados. El par que más se falla es entrante con de recuperación: los dos llevan carga baja, pero el entrante arranca un ciclo y va subiendo, mientras que el de recuperación cierra un bloque y va bajando. El otro cruce frecuente es precompetitivo con competitivo: el primero pule antes de competir, el segundo sostiene el rendimiento mientras se compite. Dato para recordar: el mesociclo básico es donde de verdad se adapta el organismo.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.2 — Mesoestructura',
    etiquetas: ['mesociclo', 'tipos', 'clasificación'],
  },
  {
    id: 'D8-010',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 2,
    enunciado: '¿Qué tipo de microciclo corresponde a la semana previa a una competencia?',
    opciones: [
      'De aproximación, con descarga para llegar fresco',
      'De choque, con la carga más alta del mesociclo',
      'De ajuste, con carga gradual para reincorporarse',
      'De recuperación, con actividad ligera y sin objetivos',
    ],
    correcta: 0,
    explicacion:
      'El microciclo de aproximación es el que precede a la competencia: baja la carga para que el deportista llegue descansado sin perder la sensación de ritmo. El distractor más tentador es el de choque, porque existe la idea de "apretar" justo antes de competir; un microciclo de choque en esa semana deja al deportista fatigado en el peor momento posible. El de ajuste sirve para entrar en un ciclo y el de recuperación para cerrar uno. Dato para recordar: antes de competir se descarga, no se aprieta.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.3 — Microestructura',
    etiquetas: ['microciclo', 'tipos', 'aproximación', 'competencia'],
  },
  {
    id: 'D8-011',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'recuerdo',
    dificultad: 1,
    enunciado: '¿En qué dos partes se divide el calentamiento, y en qué orden?',
    opciones: [
      'General primero y específica después',
      'Específica primero y general después',
      'Estática primero y dinámica después',
      'De fuerza primero y de movilidad después',
    ],
    correcta: 0,
    explicacion:
      'El calentamiento va de la parte general, con movimiento global que eleva la temperatura y la frecuencia cardíaca, a la parte específica, con gestos parecidos a los de la parte principal. El distractor más tentador es el orden invertido, porque quien recuerda las dos palabras pero no la lógica las coloca al azar; la parte específica exige un músculo ya caliente, así que no puede ir primero. Dato para recordar: es la misma progresión de todo el entrenamiento, de lo general a lo específico.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['calentamiento', 'sesión', 'parte general', 'parte específica'],
  },
  {
    id: 'D8-012',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: '¿Por qué el microciclo tiende a durar siete días en la mayoría de los planes?',
    opciones: [
      'Porque el calendario social y competitivo es semanal, y el plan se acopla a él',
      'Porque el organismo completa su ciclo de supercompensación exactamente en siete días',
      'Porque siete días es el tiempo mínimo para que aparezca cualquier adaptación fisiológica',
      'Porque las federaciones exigen que los planes se presenten en unidades de una semana',
    ],
    correcta: 0,
    explicacion:
      'La semana es una unidad social, no fisiológica: el deportista trabaja, estudia y compite en ciclos de siete días, y el plan se acopla a esa realidad. El distractor más tentador es el de la supercompensación, porque suena a fundamento fisiológico serio; los tiempos de recuperación varían según la capacidad y la magnitud de la carga, y no coinciden en siete días para todas. Dato para recordar: el microciclo va de 3 a 10 días y el 7 es una comodidad de calendario.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.3 — Microestructura',
    etiquetas: ['microciclo', 'duración', 'supercompensación'],
  },
  {
    id: 'D8-013',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 1,
    enunciado: 'Ordene las estructuras de la planificación, de la de mayor duración a la de menor.',
    elementos: [
      'Ciclo plurianual: de dos a cuatro años',
      'Macrociclo: de tres a doce meses',
      'Mesociclo: de dos a seis semanas',
      'Microciclo: de tres a diez días',
      'Sesión de entrenamiento: de sesenta a ciento veinte minutos',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La jerarquía baja de años a meses, de meses a semanas, de semanas a días y de días a minutos: ciclo plurianual, macrociclo, mesociclo, microciclo y sesión. El error más frecuente es cruzar mesociclo y microciclo, porque los dos prefijos suenan parecidos: meso es intermedio y micro es el más pequeño de los ciclos. El otro error es olvidar el ciclo plurianual, que existe por encima del macrociclo y es donde se piensa una carrera olímpica. Dato para recordar: cada estructura contiene a la siguiente.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2 — Estructuras de la planificación',
    etiquetas: ['estructuras', 'jerarquía', 'secuencia'],
  },
  {
    id: 'D8-014',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'ordenar',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Ordene los momentos de una sesión de entrenamiento, del primero al último.',
    elementos: [
      'Información inicial: se explica el objetivo y la organización de la sesión',
      'Calentamiento general: movimiento global que eleva la temperatura y la frecuencia cardíaca',
      'Calentamiento específico: gestos parecidos a los que vienen después',
      'Parte principal: se trabaja el objetivo real de la sesión',
      'Vuelta a la calma: retorno progresivo a valores de reposo',
    ],
    ordenCorrecto: [0, 1, 2, 3, 4],
    explicacion:
      'La sesión abre informando del objetivo, calienta primero de forma general y luego específica, desarrolla la parte principal y cierra con la vuelta a la calma. El error más frecuente es invertir las dos mitades del calentamiento, porque se asume que hay que ir directo al gesto de la modalidad; el trabajo específico necesita un músculo ya caliente. El otro error es colocar la información inicial al final, confundiéndola con la retroalimentación posterior. Dato para recordar: de lo general a lo específico también dentro del calentamiento.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['sesión', 'partes', 'calentamiento', 'secuencia'],
  },
  {
    id: 'D8-015',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      '¿Por qué el trabajo de técnica y de velocidad se coloca al principio de la parte principal y no al final?',
    opciones: [
      'Porque exigen un sistema nervioso fresco, y con fatiga el gesto se aprende mal y sube el riesgo de lesión',
      'Porque son los contenidos que más calorías consumen y conviene hacerlos con las reservas llenas',
      'Porque el músculo necesita estar frío para ejecutar movimientos rápidos con precisión',
      'Porque el trabajo de resistencia previo agotaría por completo los depósitos de fosfocreatina',
    ],
    correcta: 0,
    explicacion:
      'La técnica y la velocidad dependen de la calidad de la señal nerviosa y de la precisión del gesto: con el deportista fatigado el patrón se ejecuta mal, se consolida mal y el riesgo de lesión sube. El distractor más tentador es el del gasto calórico, porque suena a razón energética plausible; el criterio no es cuánta energía se gasta, sino en qué estado está el sistema nervioso. Dato para recordar: dentro de la parte principal el orden es técnica y velocidad, luego fuerza y por último resistencia.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['sesión', 'parte principal', 'orden de contenidos', 'técnica'],
  },
  {
    id: 'D8-016',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las TRES afirmaciones correctas sobre la vuelta a la calma.',
    opciones: [
      'Devuelve progresivamente la frecuencia cardíaca y la ventilación a valores de reposo',
      'Favorece la retirada de metabolitos acumulados durante la parte principal',
      'Evita que la sangre quede acumulada en las piernas al detener el esfuerzo de golpe',
      'Impide la aparición del dolor muscular tardío en los días siguientes',
      'Produce ganancias de fuerza si se prolonga más allá de veinte minutos',
    ],
    correctas: [0, 1, 2],
    explicacion:
      'La vuelta a la calma tiene tres efectos comprobados: baja de forma progresiva la frecuencia cardíaca y la ventilación, ayuda a retirar metabolitos y evita el estancamiento de sangre en los miembros inferiores al parar bruscamente. El distractor más tentador es la prevención del dolor tardío, porque es la creencia más repetida en el campo: ese dolor viene del daño microscópico de la fibra, sobre todo del trabajo excéntrico, y aparece igual con o sin vuelta a la calma. Dato para recordar: acelera el retorno a valores basales, no evita las agujetas.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['vuelta a la calma', 'sesión', 'agujetas', 'recuperación'],
  },
  {
    id: 'D8-017',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'comprension',
    dificultad: 3,
    enunciado:
      'Más allá de su duración, ¿qué distingue al mesociclo del microciclo como nivel de planificación?',
    opciones: [
      'El mesociclo decide la orientación de la carga del bloque; el microciclo decide la alternancia entre días duros y suaves',
      'El mesociclo decide los ejercicios concretos; el microciclo decide la competencia objetivo de la temporada',
      'El mesociclo se aplica solo en el período preparatorio; el microciclo, solo en el período competitivo',
      'El mesociclo contiene macrociclos; el microciclo contiene mesociclos de menor tamaño',
    ],
    correcta: 0,
    explicacion:
      'Cada nivel resuelve una pregunta distinta: en el mesociclo se decide de qué va el bloque, por ejemplo cuatro semanas orientadas a fuerza máxima, y en el microciclo se decide cómo se reparten las sesiones dentro de esos días, qué día es duro y qué día es suave. El distractor más tentador es el que atribuye al mesociclo la elección de ejercicios, porque parece la decisión inmediatamente inferior; los ejercicios concretos son de la sesión. Dato para recordar: el error caro es contestar en el nivel equivocado.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.2 — Mesoestructura',
    etiquetas: ['mesociclo', 'microciclo', 'nivel de decisión'],
  },
  {
    id: 'D8-018',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'multiple',
    nivel: 'comprension',
    dificultad: 2,
    enunciado: 'Seleccione las DOS afirmaciones correctas sobre el mesociclo.',
    opciones: [
      'Es una agrupación de microciclos con una orientación de carga común',
      'El mesociclo básico se subdivide en desarrollador y estabilizador',
      'Su duración habitual es de siete días, con un rango de tres a diez',
      'Es la estructura donde se fija la fecha de la competencia principal',
      'Es la unidad más pequeña con sentido de entrenamiento del plan',
    ],
    correctas: [0, 1],
    explicacion:
      'El mesociclo agrupa microciclos bajo una misma orientación de carga, y el tipo básico —el que produce la adaptación de fondo— se subdivide en desarrollador, que sube la carga, y estabilizador, que la mantiene para consolidar. El distractor más tentador es el de la duración de siete días, que corresponde al microciclo. La cuarta opción es una decisión del macrociclo y la quinta describe la sesión. Dato para recordar: mesociclo son semanas y su pregunta es de qué va el bloque.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.2 — Mesoestructura',
    etiquetas: ['mesociclo', 'desarrollador', 'estabilizador', 'estructuras'],
  },
  {
    id: 'D8-019',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'comprension',
    dificultad: 3,
    viñeta:
      'Un entrenador programa un microciclo con cinco sesiones de alta exigencia de lunes a viernes, convencido de que así acumula más estímulo. Al tercer microciclo igual, sus deportistas rinden menos que al empezar el mesociclo y varios reportan sueño malo y piernas pesadas.',
    enunciado: '¿Qué error de microestructura explica lo que está pasando?',
    opciones: [
      'No hay alternancia entre carga y recuperación dentro del microciclo, y la adaptación ocurre en la recuperación',
      'El microciclo dura cinco días en lugar de los siete que exige el organismo para adaptarse',
      'Las sesiones duras deberían repartirse en dos microciclos de mayor duración cada uno',
      'Falta un mesociclo de control que mida con tests el estado de los deportistas',
    ],
    correcta: 0,
    explicacion:
      'El microciclo es justamente el nivel donde se decide qué día es duro y qué día es suave, y sin esa alternancia el estímulo se acumula sin que el organismo llegue a asimilarlo: la adaptación ocurre durante la recuperación, no durante la carga. El distractor más tentador es el de la duración, porque cinco días parece "corto"; el rango de 3 a 10 días es legítimo y el problema no es cuántos días tiene el microciclo sino cómo se reparten dentro. Dato para recordar: dos sesiones duras seguidas no son doble estímulo, son media adaptación.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.3 — Microestructura',
    etiquetas: ['microciclo', 'alternancia', 'recuperación', 'sobrecarga'],
  },
  {
    id: 'D8-020',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador dispone de un macrociclo de 28 semanas y trabaja con mesociclos de 4 semanas cada uno. ¿Cuántos mesociclos completos puede programar?',
    respuesta: 7,
    tolerancia: 0.5,
    unidad: 'mesociclos',
    pasos: [
      'Número de mesociclos = semanas del macrociclo ÷ semanas de cada mesociclo',
      'Número de mesociclos = 28 ÷ 4',
      'Número de mesociclos = 7',
      'Comprobación: 7 × 4 = 28 semanas, el macrociclo completo',
    ],
    explicacion:
      'Basta dividir las semanas del macrociclo entre la duración del mesociclo: 28 entre 4 da 7 mesociclos exactos. El error más frecuente es responder 28, confundiendo semanas con mesociclos, o responder 4 dividiendo al revés; conviene comprobar siempre multiplicando de vuelta, porque 7 por 4 devuelve las 28 semanas de partida. Como cada mesociclo lleva cuatro microciclos de siete días, el macrociclo suma también 28 microciclos. Dato para recordar: mesociclo típico igual a cuatro semanas.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.2 — Mesoestructura',
    etiquetas: ['mesociclo', 'cálculo', 'macrociclo', 'estructuras'],
  },
  {
    id: 'D8-021',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'calculo',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Una sesión dura 90 minutos: 15 minutos de calentamiento y 10 minutos de vuelta a la calma. ¿Qué porcentaje del tiempo total ocupa la parte principal?',
    respuesta: 72.2,
    tolerancia: 1,
    unidad: '%',
    pasos: [
      'Tiempo de la parte principal = total − calentamiento − vuelta a la calma',
      'Parte principal = 90 − 15 − 10 = 65 minutos',
      'Porcentaje = (parte principal ÷ tiempo total) × 100',
      'Porcentaje = (65 ÷ 90) × 100 = 72,2 %',
    ],
    explicacion:
      'Hay que restar del total las dos partes conocidas antes de dividir: 90 menos 15 menos 10 deja 65 minutos de parte principal, que sobre 90 son el 72,2 %. El error más frecuente es restar solo el calentamiento y calcular 75 sobre 90, que da 83,3 %, porque la vuelta a la calma se olvida por ser la parte más corta. Este reparto es el habitual: la parte principal se lleva entre dos tercios y tres cuartos de la sesión. Dato para recordar: calentamiento 10–20 min y vuelta a la calma 5–10 min.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['sesión', 'cálculo', 'parte principal', 'porcentaje'],
  },
  {
    id: 'D8-022',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 2,
    viñeta:
      'Un entrenador arma una sesión de 90 minutos para su equipo juvenil: calentamiento, cuarenta minutos de carrera continua, después el trabajo de fuerza explosiva con saltos y por último quince minutos de técnica de pase antes de la vuelta a la calma.',
    enunciado: '¿Cómo debe reordenar la parte principal de esa sesión?',
    opciones: [
      'Técnica de pase primero, después la fuerza explosiva y la carrera continua al final',
      'Fuerza explosiva primero, después la carrera continua y la técnica de pase al final',
      'Carrera continua primero, después la técnica de pase y la fuerza explosiva al final',
      'Dejar el orden como está y alargar el calentamiento para compensar la fatiga',
    ],
    correcta: 0,
    explicacion:
      'Dentro de la parte principal el orden es técnica y velocidad, luego fuerza y por último resistencia, porque los dos primeros contenidos exigen un sistema nervioso fresco. Tal como estaba la sesión, los juveniles hacían saltos y técnica de pase después de cuarenta minutos de carrera, es decir con el gesto ya degradado. El distractor más tentador coloca la fuerza explosiva primero: es mejor que el original, pero deja la técnica al final, que es el contenido más sensible a la fatiga. Dato para recordar: lo que se aprende va antes que lo que solo se soporta.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['sesión', 'parte principal', 'orden de contenidos', 'fuerza explosiva'],
  },
  {
    id: 'D8-023',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 2,
    enunciado:
      'Un entrenador decide que el campeonato nacional de octubre será el objetivo de la temporada y reparte el año en períodos. ¿En qué nivel de estructura está tomando esa decisión?',
    opciones: ['En el macrociclo', 'En el mesociclo', 'En el microciclo', 'En la sesión'],
    correcta: 0,
    explicacion:
      'Fijar la competencia objetivo y repartir el año en períodos son decisiones del macrociclo: es el nivel que abarca meses y desde el que se ordena hacia atrás todo lo demás. El distractor más tentador es el mesociclo, porque también se piensa en bloques largos; en el mesociclo se decide la orientación de la carga de unas pocas semanas, no la fecha objetivo de la temporada. Dato para recordar: macrociclo fija la fecha, mesociclo la orientación, microciclo la alternancia y la sesión los contenidos.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.1 — Macroestructura',
    etiquetas: ['macrociclo', 'nivel de decisión', 'competencia principal'],
  },
  {
    id: 'D8-024',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'unica',
    nivel: 'aplicacion',
    dificultad: 3,
    enunciado:
      'Tras cuatro semanas subiendo la carga, una entrenadora quiere consolidar lo ganado sin seguir aumentando la exigencia. ¿Qué mesociclo corresponde programar a continuación?',
    opciones: [
      'Un mesociclo básico estabilizador, que mantiene la carga para consolidar la adaptación',
      'Un mesociclo básico desarrollador, que sigue subiendo la carga hasta el techo del deportista',
      'Un mesociclo precompetitivo, que baja el volumen y sube el trabajo específico',
      'Un mesociclo entrante, que reincorpora con carga moderada y mucha variedad',
    ],
    correcta: 0,
    explicacion:
      'El mesociclo básico tiene dos versiones y aquí corresponde la estabilizadora: mantiene la carga en el nivel alcanzado para que la adaptación se consolide, en lugar de seguir empujando. El distractor más tentador es el desarrollador, porque es el otro básico y la diferencia entre ambos es de una palabra; desarrollador es justo lo que la entrenadora ha estado haciendo esas cuatro semanas y lo que ha decidido no repetir. El precompetitivo pule antes de competir y el entrante abre un ciclo. Dato para recordar: básico desarrollador sube, básico estabilizador mantiene.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.2 — Mesoestructura',
    etiquetas: ['mesociclo', 'estabilizador', 'desarrollador', 'carga'],
  },
  {
    id: 'D8-025',
    modulo: 'd8-estructuras',
    bloque: 'D',
    tipo: 'caso',
    nivel: 'aplicacion',
    dificultad: 3,
    viñeta:
      'Un grupo de corredores termina una serie de mil metros a ritmo fuerte, se detiene en seco y se sienta en el pasto a estirar durante diez minutos. Dos de ellos se marean al ponerse de pie y se quejan de piernas pesadas el resto de la tarde.',
    enunciado: '¿Qué corresponde ajustar en el cierre de esa sesión?',
    opciones: [
      'Añadir cinco a diez minutos de trote suave antes de estirar, para el retorno progresivo a valores de reposo',
      'Suprimir los estiramientos, porque son la causa directa del mareo al ponerse de pie',
      'Alargar los estiramientos hasta veinte minutos para prevenir el dolor muscular tardío',
      'Cerrar con una serie corta a ritmo alto para reactivar la circulación de las piernas',
    ],
    correcta: 0,
    explicacion:
      'Parar en seco tras un esfuerzo fuerte deja la sangre acumulada en las piernas y provoca el mareo al incorporarse: la vuelta a la calma con trote suave de cinco a diez minutos devuelve progresivamente la frecuencia cardíaca y la ventilación a valores de reposo y favorece la retirada de metabolitos. El distractor más tentador es alargar los estiramientos para prevenir el dolor tardío, porque es la creencia más extendida del campo; ese dolor viene del daño de la fibra y no se evita estirando más. Dato para recordar: la vuelta a la calma es actividad progresivamente más suave, no quedarse quieto.',
    referencia: 'Cartilla 4, Tema 4, Subtema 4.2.4 — Sesión de entrenamiento',
    etiquetas: ['vuelta a la calma', 'sesión', 'agujetas', 'recuperación'],
  },
];
